drop table if exists acgc_table;
create table acgc_table ("Table" varchar(63));
insert into acgc_table values ('carpet'), ('fish'), ('fossil'), ('furniture'), ('gyroid'), ('insect'), ('shirt'), ('song'), ('stationery'), ('tool'), ('wallpaper');
drop table if exists acww_table;
create table acww_table ("Table" varchar(63));
insert into acww_table values ('accessory'), ('carpet'), ('fish'), ('fossil'), ('furniture'), ('gyroid'), ('insect'), ('shirt'), ('song'), ('stationery'), ('tool'), ('wallpaper');
drop table if exists accf_table;
create table accf_table ("Table" varchar(63));
insert into accf_table values ('accessory'), ('carpet'), ('fish'), ('fossil'), ('furniture'), ('gyroid'), ('insect'), ('painting'), ('shirt'), ('song'), ('stationery'), ('tool'), ('wallpaper');
drop table if exists acnl_table;
create table acnl_table ("Table" varchar(63));
insert into acnl_table values ('accessory'), ('art'), ('bottom'), ('carpet'), ('dlc'), ('dress'), ('feet'), ('fish'), ('fossil'), ('fossil_model'), ('furniture'), ('gyroid'), ('hat'), ('insect'), ('music_box'), ('seafood'), ('shirt'), ('song'), ('stationery'), ('tool'), ('villager_picture'), ('wallpaper'), ('wet_suit');