drop table if exists acnl_accessory;
create table acnl_accessory ("Index" int primary key, Selected int, Name varchar(50), Status varchar(50), "From" varchar(50), Color1 varchar(31), Color2 varchar(31))
insert into acnl_accessory values(1, 0, '3D Glasses', 'normal', 'Accessory Corner', 'red', 'blue')
insert into acnl_accessory values(2, 0, 'Aviator Shades', 'unorderable', 'GracieGrace (Summer)', 'brown', 'brown')
insert into acnl_accessory values(3, 0, 'Bad Bro''s Stache', 'unorderable', 'Fortune Cookie', 'red', 'black')
insert into acnl_accessory values(4, 0, 'Ballroom Mask', 'unorderable', 'GracieGrace (Winter)', 'white', 'white')
insert into acnl_accessory values(5, 0, 'Bandage', 'normal', 'Accessory Corner', 'brown', 'brown')
insert into acnl_accessory values(6, 0, 'Beak', 'normal', 'Accessory Corner', 'yellow', 'yellow')
insert into acnl_accessory values(7, 0, 'Big Bro''s Mustache', 'unorderable', 'Fortune Cookie', 'brown', 'brown')
insert into acnl_accessory values(8, 0, 'Blue Frames', 'normal', 'Accessory Corner', 'blue', 'blue')
insert into acnl_accessory values(9, 0, 'Brown Glasses', 'normal', 'Accessory Corner', 'brown', 'brown')
insert into acnl_accessory values(10, 0, 'Cucumber Pack', 'normal', 'Accessory Corner', 'green', 'green')
insert into acnl_accessory values(11, 0, 'Curly Mustache', 'normal', 'Accessory Corner', 'black', 'black')
insert into acnl_accessory values(12, 0, 'Cyber Shades', 'normal', 'Accessory Corner', 'gray', 'black')
insert into acnl_accessory values(13, 0, 'Doctor''s Mask', 'normal', 'Accessory Corner', 'white', 'white')
insert into acnl_accessory values(14, 0, 'Doctor''s Mirror', 'normal', 'Accessory Corner', 'white', 'white')
insert into acnl_accessory values(15, 0, 'Eye Mask', 'normal', 'Accessory Corner', 'green', 'green')
insert into acnl_accessory values(16, 0, 'Eye Patch', 'normal', 'Accessory Corner', 'black', 'black')
insert into acnl_accessory values(17, 0, 'Facial Mask', 'normal', 'Accessory Corner', 'white', 'white')
insert into acnl_accessory values(18, 0, 'Funky Glasses', 'normal', 'Accessory Corner', 'purple', 'purple')
insert into acnl_accessory values(19, 0, 'Funny Glasses', 'normal', 'Accessory Corner', 'brown', 'black')
insert into acnl_accessory values(20, 0, 'Gas Mask', 'normal', 'Accessory Corner', 'gray', 'gray')
insert into acnl_accessory values(21, 0, 'Goggles', 'normal', 'Accessory Corner', 'aqua', 'aqua')
insert into acnl_accessory values(22, 0, 'Gracie Glasses', 'unorderable', 'GracieGrace (Summer)', 'blue', 'colorful')
insert into acnl_accessory values(23, 0, 'Green Glasses', 'normal', 'Accessory Corner', 'green', 'green')
insert into acnl_accessory values(24, 0, 'Heart Shades', 'unorderable', 'GracieGrace (Spring)', 'pink', 'black')
insert into acnl_accessory values(25, 0, 'HMD', 'normal', 'Accessory Corner', 'gray', 'gray')
insert into acnl_accessory values(26, 0, 'Hockey Mask', 'normal', 'Accessory Corner', 'white', 'white')
insert into acnl_accessory values(27, 0, 'Huge Shades', 'normal', 'Accessory Corner', 'red', 'black')
insert into acnl_accessory values(28, 0, 'Jester''s Mask', 'normal', 'Accessory Corner', 'white', 'black')
insert into acnl_accessory values(29, 0, 'King''s Beard', 'normal', 'Accessory Corner', 'white', 'white')
insert into acnl_accessory values(30, 0, 'Ladder Shades', 'unorderable', 'Summer Solstice', 'red', 'red')
insert into acnl_accessory values(31, 0, 'Leaf', 'normal', 'Accessory Corner', 'green', 'green')
insert into acnl_accessory values(32, 0, 'Lemon Pack', 'normal', 'Accessory Corner', 'yellow', 'yellow')
insert into acnl_accessory values(33, 0, 'Masquerade Mask', 'normal', 'Accessory Corner', 'orange', 'pink')
insert into acnl_accessory values(34, 0, 'Mint Glasses', 'normal', 'Accessory Corner', 'aqua', 'aqua')
insert into acnl_accessory values(35, 0, 'Monocle', 'normal', 'Accessory Corner', 'aqua', 'gray')
insert into acnl_accessory values(36, 0, 'Oval Shades', 'normal', 'Accessory Corner', 'white', 'black')
insert into acnl_accessory values(37, 0, 'Pacifier', 'normal', 'Accessory Corner', 'pink', 'pink')
insert into acnl_accessory values(38, 0, 'Pilot Shades', 'normal', 'Accessory Corner', 'white', 'black')
insert into acnl_accessory values(39, 0, 'Pink Glasses', 'normal', 'Accessory Corner', 'pink', 'pink')
insert into acnl_accessory values(40, 0, 'Post-Op Patch', 'normal', 'Accessory Corner', 'white', 'white')
insert into acnl_accessory values(41, 0, 'Purple Glasses', 'normal', 'Accessory Corner', 'purple', 'purple')
insert into acnl_accessory values(42, 0, 'Red Glasses', 'normal', 'Accessory Corner', 'red', 'red')
insert into acnl_accessory values(43, 0, 'Red Nose', 'normal', 'Accessory Corner', 'red', 'red')
insert into acnl_accessory values(44, 0, 'Rimmed Glasses', 'normal', 'Accessory Corner', 'aqua', 'black')
insert into acnl_accessory values(45, 0, 'Round Glasses', 'normal', 'Accessory Corner', 'aqua', 'black')
insert into acnl_accessory values(46, 0, 'Santa Beard', 'normal', 'Limited (December 1 to 24)', 'white', 'white')
insert into acnl_accessory values(47, 0, 'Silver Frames', 'normal', 'Accessory Corner', 'white', 'white')
insert into acnl_accessory values(48, 0, 'Snorkel Mask', 'unorderable', 'Island', 'aqua', 'black')
insert into acnl_accessory values(49, 0, 'Sporty Shades', 'normal', 'Accessory Corner', 'green', 'black')
insert into acnl_accessory values(50, 0, 'Stache & Glasses', 'normal', 'Accessory Corner', 'red', 'black')
insert into acnl_accessory values(51, 0, 'Star Shades', 'unorderable', 'GracieGrace (Autumn)', 'yellow', 'black')
insert into acnl_accessory values(52, 0, 'Steampunk Glasses', 'normal', 'Accessory Corner', 'brown', 'brown')
insert into acnl_accessory values(53, 0, 'Superhero Mask', 'normal', 'Accessory Corner', 'black', 'black')
insert into acnl_accessory values(54, 0, 'Thick Glasses', 'normal', 'Accessory Corner', 'black', 'black')
insert into acnl_accessory values(55, 0, 'Tiny Shades', 'normal', 'Accessory Corner', 'black', 'black')
insert into acnl_accessory values(56, 0, 'Tortoise Specs', 'unorderable', 'GracieGrace (Winter)', 'brown', 'brown')
insert into acnl_accessory values(57, 0, 'Triangle Shades', 'normal', 'Accessory Corner', 'black', 'black')
insert into acnl_accessory values(58, 0, 'Yellow Glasses', 'normal', 'Accessory Corner', 'yellow', 'yellow')