drop table if exists acnl_bottom;
create table acnl_bottom ("Index" int primary key, Selected int, Name varchar(50), Status varchar(50), "From" varchar(50), Color1 varchar(31), Color2 varchar(31))
insert into acnl_bottom values(1, 0, 'Acid-Washed Pants', 'unorderable', 'GracieGrace', 'blue', 'gray')
insert into acnl_bottom values(2, 0, 'Aloha Shorts', 'unorderable', 'Island', 'brown', 'white')
insert into acnl_bottom values(3, 0, 'Arctic-Camo Pants', 'normal', 'Ables', 'gray', 'gray')
insert into acnl_bottom values(4, 0, 'Armor Pants', 'normal', 'Ables', 'gray', 'gray')
insert into acnl_bottom values(5, 0, 'Baseball Pants', 'normal', 'Ables', 'blue', 'white')
insert into acnl_bottom values(6, 0, 'Basketball Shorts', 'normal', 'Ables', 'yellow', 'black')
insert into acnl_bottom values(7, 0, 'Bear-Costume Pants', 'normal', 'Ables', 'brown', 'brown')
insert into acnl_bottom values(8, 0, 'Black Formal Pants', 'normal', 'Ables', 'black', 'black')
insert into acnl_bottom values(9, 0, 'Black Formal Skirt', 'normal', 'Ables', 'black', 'black')
insert into acnl_bottom values(10, 0, 'Black Track Pants', 'normal', 'Ables', 'black', 'black')
insert into acnl_bottom values(11, 0, 'Black-Denim Pants', 'normal', 'Ables', 'black', 'black')
insert into acnl_bottom values(12, 0, 'Black-Denim Skirt', 'normal', 'Ables', 'black', 'black')
insert into acnl_bottom values(13, 0, 'Blue Boxing Shorts', 'normal', 'Ables', 'blue', 'gray')
insert into acnl_bottom values(14, 0, 'Blue Gym Shorts', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(15, 0, 'Blue PJ Bottoms', 'normal', 'Ables', 'aqua', 'aqua')
insert into acnl_bottom values(16, 0, 'Blue Polka Shorts', 'normal', 'Ables', 'blue', 'aqua')
insert into acnl_bottom values(17, 0, 'Blue Warm-Up Pants', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(18, 0, 'Blue-Grid Skirt', 'normal', 'Ables', 'aqua', 'beige')
insert into acnl_bottom values(19, 0, 'Blue-Stripe Pants', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(20, 0, 'Blue-Zap Pants', 'normal', 'Ables', 'blue', 'white')
insert into acnl_bottom values(21, 0, 'Bone Pants', 'normal', 'Ables', 'white', 'black')
insert into acnl_bottom values(22, 0, 'Brown Argyle Skirt', 'unorderable', 'GracieGrace', 'brown', 'black')
insert into acnl_bottom values(23, 0, 'Brown Formal Pants', 'normal', 'Ables', 'brown', 'brown')
insert into acnl_bottom values(24, 0, 'Brown Plaid Shorts', 'unorderable', 'GracieGrace', 'brown', 'brown')
insert into acnl_bottom values(25, 0, 'Cargo Pants', 'normal', 'Ables', 'green', 'green')
insert into acnl_bottom values(26, 0, 'Caveman Shorts', 'normal', 'Ables', 'yellow', 'brown')
insert into acnl_bottom values(27, 0, 'Checkerboard Skirt', 'normal', 'Ables', 'red', 'black')
insert into acnl_bottom values(28, 0, 'Chino Pants', 'normal', 'Ables', 'beige', 'beige')
insert into acnl_bottom values(29, 0, 'Corseted Skirt', 'normal', 'Ables', 'aqua', 'black')
insert into acnl_bottom values(30, 0, 'Cow Pants', 'unorderable', 'GracieGrace', 'white', 'black')
insert into acnl_bottom values(31, 0, 'Cuffed Pants', 'normal', 'Ables', 'aqua', 'brown')
insert into acnl_bottom values(32, 0, 'Dapper Skirt', 'normal', 'Ables', 'yellow', 'green')
insert into acnl_bottom values(33, 0, 'Dark Polka Skirt', 'normal', 'Ables', 'colorful', 'black')
insert into acnl_bottom values(34, 0, 'Denim Skirt', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(35, 0, 'Desert-Camo Pants', 'normal', 'Ables', 'beige', 'brown')
insert into acnl_bottom values(36, 0, 'Dogtooth Pants', 'normal', 'Ables', 'gray', 'black')
insert into acnl_bottom values(37, 0, 'Dragon Leggings', 'normal', 'Ables', 'orange', 'black')
insert into acnl_bottom values(38, 0, 'Dry-Denim Pants', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(39, 0, 'Dry-Denim Skirt', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(40, 0, 'Emerald Polka Skirt', 'normal', 'Ables', 'green', 'blue')
insert into acnl_bottom values(41, 0, 'Explorer Pants', 'normal', 'Ables', 'beige', 'beige')
insert into acnl_bottom values(42, 0, 'Festivale Pants', 'normal', 'Ables', 'colorful', 'colorful')
insert into acnl_bottom values(43, 0, 'Firefighter Pants', 'normal', 'Ables', 'yellow', 'black')
insert into acnl_bottom values(44, 0, 'Flame Pants', 'normal', 'Ables', 'red', 'black')
insert into acnl_bottom values(45, 0, 'Frog-Costume Pants', 'normal', 'Ables', 'green', 'green')
insert into acnl_bottom values(46, 0, 'Funky-Dot Skirt', 'normal', 'Ables', 'pink', 'purple')
insert into acnl_bottom values(47, 0, 'Genie Pants', 'normal', 'Ables', 'red', 'white')
insert into acnl_bottom values(48, 0, 'Giraffe Pants', 'unorderable', 'GracieGrace', 'yellow', 'brown')
insert into acnl_bottom values(49, 0, 'Gold-Armor Pants', 'normal', 'Ables', 'yellow', 'yellow')
insert into acnl_bottom values(50, 0, 'Grass Skirt', 'normal', 'Ables', 'red', 'brown')
insert into acnl_bottom values(51, 0, 'Gray Formal Pants', 'normal', 'Ables', 'gray', 'gray')
insert into acnl_bottom values(52, 0, 'Gray Formal Skirt', 'normal', 'Ables', 'gray', 'gray')
insert into acnl_bottom values(53, 0, 'Gray Sweatpants', 'normal', 'Ables', 'gray', 'gray')
insert into acnl_bottom values(54, 0, 'Gray Tartan Skirt', 'normal', 'Ables', 'gray', 'white')
insert into acnl_bottom values(55, 0, 'Gray-Stripe Pants', 'normal', 'Ables', 'gray', 'gray')
insert into acnl_bottom values(56, 0, 'Green Gym Shorts', 'normal', 'Ables', 'green', 'green')
insert into acnl_bottom values(57, 0, 'Green Plaid Shorts', 'normal', 'Ables', 'green', 'green')
insert into acnl_bottom values(58, 0, 'Green Tartan Pants', 'normal', 'Ables', 'green', 'black')
insert into acnl_bottom values(59, 0, 'Green Warm-Up Pants', 'normal', 'Ables', 'green', 'green')
insert into acnl_bottom values(60, 0, 'Green-Zap Pants', 'normal', 'Ables', 'green', 'white')
insert into acnl_bottom values(61, 0, 'Hero''s Pants', 'unorderable', 'Fortune Cookie', 'white', 'white')
insert into acnl_bottom values(62, 0, 'Hot Spring Skirt', 'normal', 'Ables', 'pink', 'beige')
insert into acnl_bottom values(63, 0, 'Imperial Pants', 'normal', 'Ables', 'red', 'red')
insert into acnl_bottom values(64, 0, 'Jester Pants', 'normal', 'Ables', 'yellow', 'purple')
insert into acnl_bottom values(65, 0, 'Jinbei Shorts', 'normal', 'Ables', 'blue', 'gray')
insert into acnl_bottom values(66, 0, 'Jungle-Camo Pants', 'normal', 'Ables', 'green', 'brown')
insert into acnl_bottom values(67, 0, 'Jungle-Camo Shorts', 'normal', 'Ables', 'green', 'brown')
insert into acnl_bottom values(68, 0, 'Kappa-Costume Pants', 'unorderable', 'Island', 'green', 'green')
insert into acnl_bottom values(69, 0, 'Kilt', 'normal', 'Ables', 'purple', 'purple')
insert into acnl_bottom values(70, 0, 'Kung-Fu Pants', 'normal', 'Ables', 'black', 'black')
insert into acnl_bottom values(71, 0, 'Leopard Pants', 'normal', 'Ables', 'yellow', 'brown')
insert into acnl_bottom values(72, 0, 'Leopard Skirt', 'normal', 'Ables', 'yellow', 'brown')
insert into acnl_bottom values(73, 0, 'Lite Polka Skirt', 'normal', 'Ables', 'colorful', 'white')
insert into acnl_bottom values(74, 0, 'Matador''s Pants', 'unorderable', 'GracieGrace', 'orange', 'black')
insert into acnl_bottom values(75, 0, 'Military Pants', 'normal', 'Ables', 'green', 'green')
insert into acnl_bottom values(76, 0, 'Mint Gingham Skirt', 'normal', 'Ables', 'green', 'brown')
insert into acnl_bottom values(77, 0, 'Mummy Pants', 'normal', 'Ables', 'white', 'white')
insert into acnl_bottom values(78, 0, 'Natty Skirt', 'normal', 'Ables', 'blue', 'pink')
insert into acnl_bottom values(79, 0, 'Navy Formal Pants', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(80, 0, 'Navy Formal Skirt', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(81, 0, 'New Spring Skirt', 'normal', 'Ables', 'pink', 'purple')
insert into acnl_bottom values(82, 0, 'Ninja Pants', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(83, 0, 'Orange Pants', 'normal', 'Ables', 'orange', 'orange')
insert into acnl_bottom values(84, 0, 'Pastel-Check Skirt', 'normal', 'Ables', 'colorful', 'colorful')
insert into acnl_bottom values(85, 0, 'Patched-Knee Pants', 'unorderable', 'GracieGrace', 'red', 'black')
insert into acnl_bottom values(86, 0, 'Pep-Squad Skirt', 'normal', 'Ables', 'white', 'white')
insert into acnl_bottom values(87, 0, 'Picnic Skirt', 'normal', 'Ables', 'pink', 'purple')
insert into acnl_bottom values(88, 0, 'Pink Argyle Skirt', 'unorderable', 'GracieGrace', 'pink', 'brown')
insert into acnl_bottom values(89, 0, 'Pink PJ Bottoms', 'normal', 'Ables', 'pink', 'pink')
insert into acnl_bottom values(90, 0, 'Pink Sweatpants', 'normal', 'Ables', 'pink', 'pink')
insert into acnl_bottom values(91, 0, 'Pleather Pants', 'unorderable', 'GracieGrace', 'black', 'black')
insert into acnl_bottom values(92, 0, 'Racing Pants', 'normal', 'Ables', 'red', 'white')
insert into acnl_bottom values(93, 0, 'Rainbow Plaid Shorts', 'unorderable', 'GracieGrace', 'colorful', 'colorful')
insert into acnl_bottom values(94, 0, 'Red Boxing Shorts', 'normal', 'Ables', 'red', 'gray')
insert into acnl_bottom values(95, 0, 'Red Gym Shorts', 'normal', 'Ables', 'red', 'red')
insert into acnl_bottom values(96, 0, 'Red Plaid Skirt', 'normal', 'Ables', 'red', 'orange')
insert into acnl_bottom values(97, 0, 'Red Polka Skirt', 'normal', 'Ables', 'red', 'red')
insert into acnl_bottom values(98, 0, 'Red Tartan Pants', 'normal', 'Ables', 'red', 'orange')
insert into acnl_bottom values(99, 0, 'Red Warm-Up Pants', 'normal', 'Ables', 'red', 'red')
insert into acnl_bottom values(100, 0, 'Red-Grid Skirt', 'normal', 'Ables', 'beige', 'brown')
insert into acnl_bottom values(101, 0, 'Red-Stripe Pants', 'normal', 'Ables', 'red', 'white')
insert into acnl_bottom values(102, 0, 'Red-Zap Pants', 'normal', 'Ables', 'red', 'white')
insert into acnl_bottom values(103, 0, 'Relay Shorts', 'normal', 'Ables', 'purple', 'purple')
insert into acnl_bottom values(104, 0, 'Royal Shorts', 'normal', 'Ables', 'yellow', 'red')
insert into acnl_bottom values(105, 0, 'Running Pants', 'normal', 'Ables', 'white', 'black')
insert into acnl_bottom values(106, 0, 'Sailor Skirt', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(107, 0, 'Samurai Pants', 'normal', 'Ables', 'blue', 'black')
insert into acnl_bottom values(108, 0, 'Santa Pants', 'normal', 'Ables', 'red', 'white')
insert into acnl_bottom values(109, 0, 'Scale-Armor Pants', 'normal', 'Ables', 'blue', 'aqua')
insert into acnl_bottom values(110, 0, 'Soccer Shorts', 'normal', 'Ables', 'blue', 'blue')
insert into acnl_bottom values(111, 0, 'Space Pants', 'normal', 'Ables', 'white', 'white')
insert into acnl_bottom values(112, 0, 'Tan Dogtooth Pants', 'normal', 'Ables', 'brown', 'brown')
insert into acnl_bottom values(113, 0, 'Tiger Pants', 'unorderable', 'GracieGrace', 'yellow', 'black')
insert into acnl_bottom values(114, 0, 'Two-Tone Pants', 'unorderable', 'GracieGrace', 'red', 'beige')
insert into acnl_bottom values(115, 0, 'Varia Suit Pants', 'unorderable', 'Fortune Cookie', 'orange', 'orange')
insert into acnl_bottom values(116, 0, 'Western Pants', 'normal', 'Ables', 'brown', 'brown')
insert into acnl_bottom values(117, 0, 'White Formal Pants', 'unorderable', 'GracieGrace', 'white', 'white')
insert into acnl_bottom values(118, 0, 'White-Lace Skirt', 'unorderable', 'GracieGrace', 'white', 'white')
insert into acnl_bottom values(119, 0, 'Worn-Out Jeans', 'unorderable', 'GracieGrace', 'blue', 'blue')
insert into acnl_bottom values(120, 0, 'Wrestler Pants', 'normal', 'Ables', 'red', 'aqua')
insert into acnl_bottom values(121, 0, 'Zebra Pants', 'unorderable', 'GracieGrace', 'white', 'black')
insert into acnl_bottom values(122, 0, 'Patched Pants', 'unorderable', 'Halloween', 'gray', 'gray')