drop table if exists acnl_music_box;
create table acnl_music_box ("Index" int primary key, Selected int, Name varchar(50), "From" varchar(31));
insert into acnl_music_box values(1, 0, 'Agent K.K.', 'Cyrus');
insert into acnl_music_box values(2, 0, 'Aloha K.K.', 'Cyrus');
insert into acnl_music_box values(3, 0, 'Bubblegum K.K.', 'Cyrus');
insert into acnl_music_box values(4, 0, 'Cafe K.K.', 'Cyrus');
insert into acnl_music_box values(5, 0, 'Comrade K.K.', 'Cyrus');
insert into acnl_music_box values(6, 0, 'DJ K.K.', 'Cyrus');
insert into acnl_music_box values(7, 0, 'Forest Life', 'Cyrus');
insert into acnl_music_box values(8, 0, 'Go K.K. Rider', 'Cyrus');
insert into acnl_music_box values(9, 0, 'Hypno K.K.', 'Cyrus');
insert into acnl_music_box values(10, 0, 'I Love You', 'Cyrus');
insert into acnl_music_box values(11, 0, 'Imperial K.K.', 'Cyrus');
insert into acnl_music_box values(12, 0, 'K.K. Adventure', 'Cyrus');
insert into acnl_music_box values(13, 0, 'K.K. Aria', 'Cyrus');
insert into acnl_music_box values(14, 0, 'K.K. Ballad', 'Cyrus');
insert into acnl_music_box values(15, 0, 'K.K. Bazaar', 'Cyrus');
insert into acnl_music_box values(16, 0, 'K.K. Birthday', 'Cyrus');
insert into acnl_music_box values(17, 0, 'K.K. Blues', 'Cyrus');
insert into acnl_music_box values(18, 0, 'K.K. Bossa', 'Cyrus');
insert into acnl_music_box values(19, 0, 'K.K. Calypso', 'Cyrus');
insert into acnl_music_box values(20, 0, 'K.K. Casbah', 'Cyrus');
insert into acnl_music_box values(21, 0, 'K.K. Chorale', 'Cyrus');
insert into acnl_music_box values(22, 0, 'K.K. Condor', 'Cyrus');
insert into acnl_music_box values(23, 0, 'K.K. Country', 'Cyrus');
insert into acnl_music_box values(24, 0, 'K.K. Cruisin''', 'Cyrus');
insert into acnl_music_box values(25, 0, 'K.K. D&B', 'Cyrus');
insert into acnl_music_box values(26, 0, 'K.K. Dirge', 'Cyrus');
insert into acnl_music_box values(27, 0, 'K.K. Disco', 'Cyrus');
insert into acnl_music_box values(28, 0, 'K.K. Dixie', 'Cyrus');
insert into acnl_music_box values(29, 0, 'K.K. Etude', 'Cyrus');
insert into acnl_music_box values(30, 0, 'K.K. Faire', 'Cyrus');
insert into acnl_music_box values(31, 0, 'K.K. Flamenco', 'Cyrus');
insert into acnl_music_box values(32, 0, 'K.K. Folk', 'Cyrus');
insert into acnl_music_box values(33, 0, 'K.K. Fusion', 'Cyrus');
insert into acnl_music_box values(34, 0, 'K.K. Groove', 'Cyrus');
insert into acnl_music_box values(35, 0, 'K.K. Gumbo', 'Cyrus');
insert into acnl_music_box values(36, 0, 'K.K. House', 'Cyrus');
insert into acnl_music_box values(37, 0, 'K.K. Island', 'Cyrus');
insert into acnl_music_box values(38, 0, 'K.K. Jazz', 'Cyrus');
insert into acnl_music_box values(39, 0, 'K.K. Jongara', 'Cyrus');
insert into acnl_music_box values(40, 0, 'K.K. Lament', 'Cyrus');
insert into acnl_music_box values(41, 0, 'K.K. Love Song', 'Cyrus');
insert into acnl_music_box values(42, 0, 'K.K. Lullaby', 'Cyrus');
insert into acnl_music_box values(43, 0, 'K.K. Mambo', 'Cyrus');
insert into acnl_music_box values(44, 0, 'K.K. Marathon', 'Cyrus');
insert into acnl_music_box values(45, 0, 'K.K. March', 'Cyrus');
insert into acnl_music_box values(46, 0, 'K.K. Metal', 'Cyrus');
insert into acnl_music_box values(47, 0, 'K.K. Milonga', 'Cyrus');
insert into acnl_music_box values(48, 0, 'K.K. Moody', 'Cyrus');
insert into acnl_music_box values(49, 0, 'K.K. Oasis', 'Cyrus');
insert into acnl_music_box values(50, 0, 'K.K. Parade', 'Cyrus');
insert into acnl_music_box values(51, 0, 'K.K. Ragtime', 'Cyrus');
insert into acnl_music_box values(52, 0, 'K.K. Rally', 'Cyrus');
insert into acnl_music_box values(53, 0, 'K.K. Reggae', 'Cyrus');
insert into acnl_music_box values(54, 0, 'K.K. Rock', 'Cyrus');
insert into acnl_music_box values(55, 0, 'K.K. Rockabilly', 'Cyrus');
insert into acnl_music_box values(56, 0, 'K.K. Safari', 'Cyrus');
insert into acnl_music_box values(57, 0, 'K.K. Salsa', 'Cyrus');
insert into acnl_music_box values(58, 0, 'K.K. Samba', 'Cyrus');
insert into acnl_music_box values(59, 0, 'K.K. Ska', 'Cyrus');
insert into acnl_music_box values(60, 0, 'K.K. Sonata', 'Cyrus');
insert into acnl_music_box values(61, 0, 'K.K. Song', 'Cyrus');
insert into acnl_music_box values(62, 0, 'K.K. Soul', 'Cyrus');
insert into acnl_music_box values(63, 0, 'K.K. Steppe', 'Cyrus');
insert into acnl_music_box values(64, 0, 'K.K. Stroll', 'Cyrus');
insert into acnl_music_box values(65, 0, 'K.K. Swing', 'Cyrus');
insert into acnl_music_box values(66, 0, 'K.K. Synth', 'Cyrus');
insert into acnl_music_box values(67, 0, 'K.K. Tango', 'Cyrus');
insert into acnl_music_box values(68, 0, 'K.K. Technopop', 'Cyrus');
insert into acnl_music_box values(69, 0, 'K.K. Waltz', 'Cyrus');
insert into acnl_music_box values(70, 0, 'K.K. Western', 'Cyrus');
insert into acnl_music_box values(71, 0, 'King K.K.', 'Cyrus');
insert into acnl_music_box values(72, 0, 'Lucky K.K.', 'Cyrus');
insert into acnl_music_box values(73, 0, 'Marine Song 2001', 'Cyrus');
insert into acnl_music_box values(74, 0, 'Mountain Song', 'Cyrus');
insert into acnl_music_box values(75, 0, 'Mr. K.K.', 'Cyrus');
insert into acnl_music_box values(76, 0, 'My Place', 'Cyrus');
insert into acnl_music_box values(77, 0, 'Neapolitan', 'Cyrus');
insert into acnl_music_box values(78, 0, 'Only Me', 'Cyrus');
insert into acnl_music_box values(79, 0, 'Pondering', 'Cyrus');
insert into acnl_music_box values(80, 0, 'Rockin'' K.K.', 'Cyrus');
insert into acnl_music_box values(81, 0, 'Senor K.K.', 'Cyrus');
insert into acnl_music_box values(82, 0, 'Soulful K.K.', 'Cyrus');
insert into acnl_music_box values(83, 0, 'Space K.K.', 'Cyrus');
insert into acnl_music_box values(84, 0, 'Spring Blossoms', 'Cyrus');
insert into acnl_music_box values(85, 0, 'Stale Cupcakes', 'Cyrus');
insert into acnl_music_box values(86, 0, 'Steep Hill', 'Cyrus');
insert into acnl_music_box values(87, 0, 'Surfin'' K.K.', 'Cyrus');
insert into acnl_music_box values(88, 0, 'The K. Funk', 'Cyrus');
insert into acnl_music_box values(89, 0, 'To the Edge', 'Cyrus');
insert into acnl_music_box values(90, 0, 'Two Days Ago', 'Cyrus');
insert into acnl_music_box values(91, 0, 'Wandering', 'Cyrus');