drop table if exists acnl_wallpaper;
create table acnl_wallpaper ("Index" int primary key, Selected int, Name varchar(50), Status varchar(50), "From" varchar(50));
insert into acnl_wallpaper values(1, 0, 'Alpine Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(2, 0, 'Ancient Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(3, 0, 'Arched Window', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(4, 0, 'Astro Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(5, 0, 'Autumn Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(6, 0, 'Backgammon Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(7, 0, 'Backyard Fence', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(8, 0, 'Balloon Wall', 'unorderable', 'Balloon');
insert into acnl_wallpaper values(9, 0, 'Bamboo Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(10, 0, 'Basement Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(11, 0, 'Bathhouse Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(12, 0, 'Blue Tarp', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(13, 0, 'Blue Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(14, 0, 'Blue-Trim Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(15, 0, 'Butterfly Wall', 'normal', 'Nat');
insert into acnl_wallpaper values(16, 0, 'Cabana Wall', 'unorderable', 'Island');
insert into acnl_wallpaper values(17, 0, 'Cabin Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(18, 0, 'Card Wall', 'unorderable', 'GracieGrace (Sales)');
insert into acnl_wallpaper values(19, 0, 'Chain-Link Fence', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(20, 0, 'Cheese Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(21, 0, 'Chic Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(22, 0, 'Citrus Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(23, 0, 'Cityscape Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(24, 0, 'Classic Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(25, 0, 'Classroom Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(26, 0, 'Common Wall', 'normal', 'House/Timmy&Tommy''s');
insert into acnl_wallpaper values(27, 0, 'Concrete Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(28, 0, 'Creepy Wall', 'unorderable', 'Halloween');
insert into acnl_wallpaper values(29, 0, 'Desert Vista', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(30, 0, 'Dig-Site Wall', 'normal', 'Museum Shop');
insert into acnl_wallpaper values(31, 0, 'Dirt-Clod Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(32, 0, 'Dotted Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(33, 0, 'Egg Wall', 'unorderable', 'Bunny Day');
insert into acnl_wallpaper values(34, 0, 'Exhibit-Room Wall', 'unorderable', 'Exhibit Room');
insert into acnl_wallpaper values(35, 0, 'Exotic Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(36, 0, 'Exquisite Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(37, 0, 'Floral Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(38, 0, 'Flower Pop Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(39, 0, 'Forest Wall', 'unorderable', 'Mushroom');
insert into acnl_wallpaper values(40, 0, 'Garden Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(41, 0, 'Gold Screen Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(42, 0, 'Golden Wall', 'unorderable', 'Cyrus');
insert into acnl_wallpaper values(43, 0, 'Gorgeous Wall', 'unorderable', 'GracieGrace (Winter)');
insert into acnl_wallpaper values(44, 0, 'Gracie Wallpaper', 'unorderable', 'GracieGrace (Summer)');
insert into acnl_wallpaper values(45, 0, 'Green Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(46, 0, 'Groovy Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(47, 0, 'Harvest Wall', 'normal', 'Limited (November 1 to Fourth Thursday)');
insert into acnl_wallpaper values(48, 0, 'Ice Wall', 'unorderable', 'Snowmam');
insert into acnl_wallpaper values(49, 0, 'Illusion Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(50, 0, 'Imperial Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(51, 0, 'Industrial Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(52, 0, 'Ivy Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(53, 0, 'Jingle Wall', 'normal', 'Limited (December 1 to 23)');
insert into acnl_wallpaper values(54, 0, 'Jungle Wall', 'normal', 'Museum Shop');
insert into acnl_wallpaper values(55, 0, 'Kiddie Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(56, 0, 'Kitchen Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(57, 0, 'Kitschy Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(58, 0, 'Lab Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(59, 0, 'Lattice Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(60, 0, 'Library Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(61, 0, 'Lovely Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(62, 0, 'Lunar Horizon', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(63, 0, 'Manor Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(64, 0, 'Marine Pop Wall', 'unorderable', 'Chip');
insert into acnl_wallpaper values(65, 0, 'Maze Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(66, 0, 'Meadow Vista', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(67, 0, 'Mermaid Wall', 'unorderable', 'Island');
insert into acnl_wallpaper values(68, 0, 'Mod Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(69, 0, 'Modern Screen', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(70, 0, 'Modern Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(71, 0, 'Modern Wood Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(72, 0, 'Mortar Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(73, 0, 'Mosaic Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(74, 0, 'Museum Wall', 'normal', 'Museum Shop');
insert into acnl_wallpaper values(75, 0, 'Mushroom Mural', 'unorderable', 'Fortune Cookie');
insert into acnl_wallpaper values(76, 0, 'Music-Room Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(77, 0, 'Neutral Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(78, 0, 'Office Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(79, 0, 'Old Brick Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(80, 0, 'Ornate Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(81, 0, 'Paintball Wall', 'normal', 'Museum Shop');
insert into acnl_wallpaper values(82, 0, 'Palace Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(83, 0, 'Parlor Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(84, 0, 'Party Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(85, 0, 'Pastel-Dot Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(86, 0, 'Pave Wall', 'unorderable', 'Festivale');
insert into acnl_wallpaper values(87, 0, 'Paw-Print Wall', 'normal', 'Isabelle/Timmy&Tommy''s');
insert into acnl_wallpaper values(88, 0, 'Plaster Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(89, 0, 'Playroom Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(90, 0, 'Plaza Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(91, 0, 'Princess Wall', 'unorderable', 'GracieGrace (Spring)');
insert into acnl_wallpaper values(92, 0, 'Ramshackle Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(93, 0, 'Ranch Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(94, 0, 'Red Tile Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(95, 0, 'Regal Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(96, 0, 'Ringside Seating', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(97, 0, 'Robo-Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(98, 0, 'Rococo Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(99, 0, 'Rose Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(100, 0, 'Sci-Fi Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(101, 0, 'Sea View', 'unorderable', 'Pascal');
insert into acnl_wallpaper values(102, 0, 'Shanty Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(103, 0, 'Shoji Screen', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(104, 0, 'Ski-Slope Wall', 'unorderable', 'Snowman');
insert into acnl_wallpaper values(105, 0, 'Sky Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(106, 0, 'Skyscraper Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(107, 0, 'Sleek Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(108, 0, 'Sloppy Wall', 'unorderable', 'Re-Tail/Police Station');
insert into acnl_wallpaper values(109, 0, 'Snowman Wall', 'unorderable', 'Snowboy');
insert into acnl_wallpaper values(110, 0, 'Spooky Wall', 'normal', 'Limited (October 1 to 31)');
insert into acnl_wallpaper values(111, 0, 'Sporty Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(112, 0, 'Stately Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(113, 0, 'Stone Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(114, 0, 'Stripe Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(115, 0, 'Summit Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(116, 0, 'Sweets Wall', 'unorderable', 'GracieGrace (Autumn)');
insert into acnl_wallpaper values(117, 0, 'Tearoom Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(118, 0, 'Tent Wall', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(119, 0, 'Tree-Lined Wall', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(120, 0, 'Tropical Vista', 'unorderable', 'Island');
insert into acnl_wallpaper values(121, 0, 'Underwater Wall', 'normal', 'Museum Shop');
insert into acnl_wallpaper values(122, 0, 'Western Vista', 'unorderable', 'Saharah');
insert into acnl_wallpaper values(123, 0, 'Wood Paneling', 'normal', 'Timmy&Tommy''s');
insert into acnl_wallpaper values(124, 0, 'Old Wallpaper', 'unorderable', 'Halloween');
