drop table if exists acnl_wet_suit;
create table acnl_wet_suit ("Index" int primary key, Selected int, Name varchar(255), "From" varchar(63), Color1 varchar(31), Color2 varchar(31));
insert into acnl_wet_suit values(1, 0, 'Black Wet Suit', 'Island', 'yellow', 'black');
insert into acnl_wet_suit values(2, 0, 'Blue Wet Suit', 'Club Tortimer', 'blue', 'blue');
insert into acnl_wet_suit values(3, 0, 'Green Wet Suit', 'Island', 'green', 'black');
insert into acnl_wet_suit values(4, 0, 'Orange Wet Suit', 'Island', 'orange', 'black');
insert into acnl_wet_suit values(5, 0, 'Pink Wet Suit', 'Island', 'pink', 'pink');
insert into acnl_wet_suit values(6, 0, 'Red Wet Suit', 'Club Tortimer', 'red', 'black');
insert into acnl_wet_suit values(7, 0, 'Rental Wet Suit', 'Lloid/Tour', 'aqua', 'aqua');
insert into acnl_wet_suit values(8, 0, 'Striped Wet Suit', 'Club Tortimer', 'red', 'white');
insert into acnl_wet_suit values(9, 0, 'White Wet Suit', 'Club Tortimer', 'white', 'white');
