drop table if exists acnh_fossil;
create table acnh_fossil ("Index" int primary key, Selected int, Name varchar(255), Price varchar(31), "From" varchar(31));
insert into acnh_fossil values(1, 0, 'acanthostega', '2000', 'Dig spot');
insert into acnh_fossil values(2, 0, 'amber', '1200', 'Dig spot');
insert into acnh_fossil values(3, 0, 'ammonite', '1100', 'Dig spot');
insert into acnh_fossil values(4, 0, 'ankylo skull', '3500', 'Dig spot');
insert into acnh_fossil values(5, 0, 'ankylo tail', '2500', 'Dig spot');
insert into acnh_fossil values(6, 0, 'ankylo torso', '3000', 'Dig spot');
insert into acnh_fossil values(7, 0, 'anomalocaris', '2000', 'Dig spot');
insert into acnh_fossil values(8, 0, 'archaeopteryx', '1300', 'Dig spot');
insert into acnh_fossil values(9, 0, 'archelon skull', '4000', 'Dig spot');
insert into acnh_fossil values(10, 0, 'archelon tail', '3500', 'Dig spot');
insert into acnh_fossil values(11, 0, 'australopith', '1100', 'Dig spot');
insert into acnh_fossil values(12, 0, 'brachio chest', '5500', 'Dig spot');
insert into acnh_fossil values(13, 0, 'brachio pelvis', '5000', 'Dig spot');
insert into acnh_fossil values(14, 0, 'brachio skull', '6000', 'Dig spot');
insert into acnh_fossil values(15, 0, 'brachio tail', '5500', 'Dig spot');
insert into acnh_fossil values(16, 0, 'coprolite', '1100', 'Dig spot');
insert into acnh_fossil values(17, 0, 'deinony tail', '2500', 'Dig spot');
insert into acnh_fossil values(18, 0, 'deinony torso', '3000', 'Dig spot');
insert into acnh_fossil values(19, 0, 'dimetrodon skull', '5500', 'Dig spot');
insert into acnh_fossil values(20, 0, 'dimetrodon torso', '5000', 'Dig spot');
insert into acnh_fossil values(21, 0, 'dinosaur track', '1000', 'Dig spot');
insert into acnh_fossil values(22, 0, 'diplo chest', '4000', 'Dig spot');
insert into acnh_fossil values(23, 0, 'diplo neck', '4500', 'Dig spot');
insert into acnh_fossil values(24, 0, 'diplo pelvis', '4500', 'Dig spot');
insert into acnh_fossil values(25, 0, 'diplo skull', '5000', 'Dig spot');
insert into acnh_fossil values(26, 0, 'diplo tail', '5000', 'Dig spot');
insert into acnh_fossil values(27, 0, 'diplo tail tip', '4000', 'Dig spot');
insert into acnh_fossil values(28, 0, 'dunkleosteus', '3500', 'Dig spot');
insert into acnh_fossil values(29, 0, 'eusthenopteron', '2000', 'Dig spot');
insert into acnh_fossil values(30, 0, 'iguanodon skull', '4000', 'Dig spot');
insert into acnh_fossil values(31, 0, 'iguanodon tail', '3000', 'Dig spot');
insert into acnh_fossil values(32, 0, 'iguanodon torso', '3500', 'Dig spot');
insert into acnh_fossil values(33, 0, 'juramaia', '1500', 'Dig spot');
insert into acnh_fossil values(34, 0, 'left megalo side', '4000', 'Dig spot');
insert into acnh_fossil values(35, 0, 'left ptera wing', '4500', 'Dig spot');
insert into acnh_fossil values(36, 0, 'left quetzal wing', '5000', 'Dig spot');
insert into acnh_fossil values(37, 0, 'mammoth skull', '3000', 'Dig spot');
insert into acnh_fossil values(38, 0, 'mammoth torso', '2500', 'Dig spot');
insert into acnh_fossil values(39, 0, 'megacero skull', '4500', 'Dig spot');
insert into acnh_fossil values(40, 0, 'megacero tail', '3000', 'Dig spot');
insert into acnh_fossil values(41, 0, 'megacero torso', '3500', 'Dig spot');
insert into acnh_fossil values(42, 0, 'myllokunmingia', '1500', 'Dig spot');
insert into acnh_fossil values(43, 0, 'ophthalmo skull', '2500', 'Dig spot');
insert into acnh_fossil values(44, 0, 'ophthalmo torso', '2000', 'Dig spot');
insert into acnh_fossil values(45, 0, 'pachysaurus skull', '4000', 'Dig spot');
insert into acnh_fossil values(46, 0, 'pachysaurus tail', '3500', 'Dig spot');
insert into acnh_fossil values(47, 0, 'parasaur skull', '3500', 'Dig spot');
insert into acnh_fossil values(48, 0, 'parasaur tail', '2500', 'Dig spot');
insert into acnh_fossil values(49, 0, 'parasaur torso', '3000', 'Dig spot');
insert into acnh_fossil values(50, 0, 'plesio body', '4500', 'Dig spot');
insert into acnh_fossil values(51, 0, 'plesio skull', '4000', 'Dig spot');
insert into acnh_fossil values(52, 0, 'plesio tail', '4500', 'Dig spot');
insert into acnh_fossil values(53, 0, 'ptera body', '4000', 'Dig spot');
insert into acnh_fossil values(54, 0, 'quetzal torso', '4500', 'Dig spot');
insert into acnh_fossil values(55, 0, 'right megalo side', '5500', 'Dig spot');
insert into acnh_fossil values(56, 0, 'right ptera wing', '4500', 'Dig spot');
insert into acnh_fossil values(57, 0, 'right quetzal wing', '5000', 'Dig spot');
insert into acnh_fossil values(58, 0, 'sabertooth skull', '2500', 'Dig spot');
insert into acnh_fossil values(59, 0, 'sabertooth tail', '2000', 'Dig spot');
insert into acnh_fossil values(60, 0, 'shark-tooth pattern', '1000', 'Dig spot');
insert into acnh_fossil values(61, 0, 'spino skull', '4000', 'Dig spot');
insert into acnh_fossil values(62, 0, 'spino tail', '2500', 'Dig spot');
insert into acnh_fossil values(63, 0, 'spino torso', '3000', 'Dig spot');
insert into acnh_fossil values(64, 0, 'stego skull', '5000', 'Dig spot');
insert into acnh_fossil values(65, 0, 'stego tail', '4000', 'Dig spot');
insert into acnh_fossil values(66, 0, 'stego torso', '4500', 'Dig spot');
insert into acnh_fossil values(67, 0, 'T. rex skull', '6000', 'Dig spot');
insert into acnh_fossil values(68, 0, 'T. rex tail', '5000', 'Dig spot');
insert into acnh_fossil values(69, 0, 'T. rex torso', '5500', 'Dig spot');
insert into acnh_fossil values(70, 0, 'tricera skull', '5500', 'Dig spot');
insert into acnh_fossil values(71, 0, 'tricera tail', '4500', 'Dig spot');
insert into acnh_fossil values(72, 0, 'tricera torso', '5000', 'Dig spot');
insert into acnh_fossil values(73, 0, 'trilobite', '1300', 'Dig spot');
