drop table if exists acnh_headwear;
create table acnh_headwear ("Index" int primary key, Selected int, Name varchar(63), Status varchar(31), Price varchar(31), "From" varchar(63), Style varchar(31));
insert into acnh_headwear values(1, 0, 'acorn knit cap (Mustard)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(2, 0, 'acorn knit cap (Avocado)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(3, 0, 'acorn knit cap (Berry red)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(4, 0, 'acorn knit cap (Navy blue)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(5, 0, 'acorn knit cap (Cream)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(6, 0, 'acorn knit cap (Chestnut)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(7, 0, 'alpinist hat (Blue)', 'unorderable', '500', 'Gulliver', 'Simple');
insert into acnh_headwear values(8, 0, 'alpinist hat (Red)', 'unorderable', '500', 'Gulliver', 'Simple');
insert into acnh_headwear values(9, 0, 'alpinist hat (Green)', 'unorderable', '500', 'Gulliver', 'Simple');
insert into acnh_headwear values(10, 0, 'ancient administrator hat (Black)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(11, 0, 'apple hat', 'unorderable', '1000', 'Crafting', 'Cute');
insert into acnh_headwear values(12, 0, 'Aran-knit cap (Red)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(13, 0, 'Aran-knit cap (Blue)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(14, 0, 'Aran-knit cap (Green)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(15, 0, 'Aran-knit cap (White)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(16, 0, 'baby''s hat (Baby purple)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(17, 0, 'baby''s hat (Baby yellow)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(18, 0, 'baby''s hat (Baby green)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(19, 0, 'baby''s hat (Baby pink)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(20, 0, 'baby''s hat (Baby gray)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(21, 0, 'baby''s hat (Baby blue)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(22, 0, 'baby''s hat (Baby orange)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(23, 0, 'baby''s hat (Baby mint)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(24, 0, 'balloon hat (Green)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(25, 0, 'balloon hat (Rainbow)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(26, 0, 'balloon hat (Orange)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(27, 0, 'balloon hat (Blue)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(28, 0, 'bamboo hat', 'unorderable', '200', 'Crafting', 'Simple');
insert into acnh_headwear values(29, 0, 'barrette (Pink)', 'orderable', '490', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(30, 0, 'baseball cap (Navy blue)', 'orderable', '840', 'Able Sisters', 'Active');
insert into acnh_headwear values(31, 0, 'baseball cap (Green)', 'orderable', '840', 'Able Sisters', 'Active');
insert into acnh_headwear values(32, 0, 'baseball cap (Orange)', 'orderable', '840', 'Able Sisters', 'Active');
insert into acnh_headwear values(33, 0, 'baseball cap (Red)', 'orderable', '840', 'Able Sisters', 'Active');
insert into acnh_headwear values(34, 0, 'baseball cap (Yellow)', 'orderable', '840', 'Able Sisters', 'Active');
insert into acnh_headwear values(35, 0, 'batter''s helmet (Navy blue)', 'orderable', '1040', 'Able Sisters', 'Active');
insert into acnh_headwear values(36, 0, 'batter''s helmet (Green)', 'orderable', '1040', 'Able Sisters', 'Active');
insert into acnh_headwear values(37, 0, 'batter''s helmet (Orange)', 'orderable', '1040', 'Able Sisters', 'Active');
insert into acnh_headwear values(38, 0, 'batter''s helmet (Yellow)', 'orderable', '1040', 'Able Sisters', 'Active');
insert into acnh_headwear values(39, 0, 'batter''s helmet (Red)', 'orderable', '1040', 'Able Sisters', 'Active');
insert into acnh_headwear values(40, 0, 'bear cap (Brown)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(41, 0, 'bear cap (Black)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(42, 0, 'bear cap (Pink)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(43, 0, 'bear cap (Blue)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(44, 0, 'beret (Berry red)', 'orderable', '880', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(45, 0, 'beret (Blue)', 'orderable', '880', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(46, 0, 'beret (Green)', 'orderable', '880', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(47, 0, 'beret (Mustard)', 'orderable', '880', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(48, 0, 'beret (Gray)', 'orderable', '880', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(49, 0, 'beret (White)', 'orderable', '880', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(50, 0, 'bicycle helmet (Red)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(51, 0, 'bicycle helmet (Lime)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(52, 0, 'bicycle helmet (Green)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(53, 0, 'bicycle helmet (Orange)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(54, 0, 'bicycle helmet (Purple)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(55, 0, 'bicycle helmet (Pink)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(56, 0, 'bicycle helmet (Navy blue)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(57, 0, 'bicycle helmet (Blue)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(58, 0, 'birthday hat (Blue)', 'unorderable', '600', 'Birthday', 'Gorgeous');
insert into acnh_headwear values(59, 0, 'birthday hat (Yellow)', 'unorderable', '600', 'Birthday', 'Gorgeous');
insert into acnh_headwear values(60, 0, 'birthday hat (Pink)', 'unorderable', '600', 'Birthday', 'Gorgeous');
insert into acnh_headwear values(61, 0, 'blue rose crown', 'unorderable', '12000', 'Crafting', 'Cute');
insert into acnh_headwear values(62, 0, 'bowler hat with ribbon (Beige)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(63, 0, 'bowler hat with ribbon (Green)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(64, 0, 'bowler hat with ribbon (Red)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(65, 0, 'bowler hat with ribbon (Pink)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(66, 0, 'bowler hat with ribbon (Blue)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(67, 0, 'bun wig (Pink)', 'orderable', '1440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(68, 0, 'bun wig (White)', 'orderable', '1440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(69, 0, 'bun wig (Purple)', 'orderable', '1440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(70, 0, 'bun wig (Green)', 'orderable', '1440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(71, 0, 'bun wig (Orange)', 'orderable', '1440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(72, 0, 'bun wig (Blue)', 'orderable', '1440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(73, 0, 'bun wig (Mustard)', 'orderable', '1440', 'Able Sisters', 'Cute');
insert into acnh_headwear values(74, 0, 'Bunny Day crown', 'unorderable', '2400', 'Crafting', 'Elegant');
insert into acnh_headwear values(75, 0, 'bunny ears (Pink)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(76, 0, 'bunny ears (Red)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(77, 0, 'bunny ears (Light blue)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(78, 0, 'bunny ears (Black)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(79, 0, 'bunny hood (Yellow)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(80, 0, 'bunny hood (White)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(81, 0, 'bunny hood (Pink)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(82, 0, 'captain''s hat (White)', 'orderable', '1680', 'Able Sisters', 'Cool');
insert into acnh_headwear values(83, 0, 'cat cap (Brown)', 'orderable', '980', 'Able Sisters', 'Cute');
insert into acnh_headwear values(84, 0, 'cat cap (White)', 'orderable', '980', 'Able Sisters', 'Cute');
insert into acnh_headwear values(85, 0, 'cat cap (Navy blue)', 'orderable', '980', 'Able Sisters', 'Cute');
insert into acnh_headwear values(86, 0, 'catcher''s mask (Navy blue)', 'orderable', '1560', 'Able Sisters', 'Active');
insert into acnh_headwear values(87, 0, 'catcher''s mask (Green)', 'orderable', '1560', 'Able Sisters', 'Active');
insert into acnh_headwear values(88, 0, 'catcher''s mask (Orange)', 'orderable', '1560', 'Able Sisters', 'Active');
insert into acnh_headwear values(89, 0, 'catcher''s mask (Yellow)', 'orderable', '1560', 'Able Sisters', 'Active');
insert into acnh_headwear values(90, 0, 'catcher''s mask (Red)', 'orderable', '1560', 'Able Sisters', 'Active');
insert into acnh_headwear values(91, 0, 'cavalier hat (Red)', 'orderable', '1600', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(92, 0, 'cavalier hat (Green)', 'orderable', '1600', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(93, 0, 'cavalier hat (Blue)', 'orderable', '1600', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(94, 0, 'chef''s hat (White)', 'orderable', '840', 'Able Sisters', 'Simple');
insert into acnh_headwear values(95, 0, 'cherry hat', 'unorderable', '1000', 'Crafting', 'Cute');
insert into acnh_headwear values(96, 0, 'chic mum crown', 'unorderable', '960', 'Crafting', 'Cute');
insert into acnh_headwear values(97, 0, 'chic rose crown', 'unorderable', '2880', 'Crafting', 'Cute');
insert into acnh_headwear values(98, 0, 'chic tulip crown', 'unorderable', '1440', 'Crafting', 'Cute');
insert into acnh_headwear values(99, 0, 'coin headpiece (Gold)', 'unorderable', '1350', 'Gulliver', 'Gorgeous');
insert into acnh_headwear values(100, 0, 'colorful striped knit cap (Blue)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(101, 0, 'colorful striped knit cap (Green)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(102, 0, 'colorful striped knit cap (Yellow)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(103, 0, 'colorful striped knit cap (Red)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(104, 0, 'colorful striped knit cap (Purple)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(105, 0, 'colorful striped knit cap (Light blue)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(106, 0, 'combat helmet (Avocado)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(107, 0, 'combat helmet (Brown)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(108, 0, 'composer''s wig (Hair Color)', 'orderable', '1680', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(109, 0, 'cool hyacinth crown', 'unorderable', '1280', 'Crafting', 'Cute');
insert into acnh_headwear values(110, 0, 'cool pansy crown', 'unorderable', '960', 'Crafting', 'Cute');
insert into acnh_headwear values(111, 0, 'cool windflower crown', 'unorderable', '960', 'Crafting', 'Cute');
insert into acnh_headwear values(112, 0, 'cosmos crown', 'unorderable', '480', 'Crafting', 'Cute');
insert into acnh_headwear values(113, 0, 'crown (Gold)', 'orderable', '1000000', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(114, 0, 'cute lily crown', 'unorderable', '800', 'Crafting', 'Cute');
insert into acnh_headwear values(115, 0, 'cute rose crown', 'unorderable', '960', 'Crafting', 'Cute');
insert into acnh_headwear values(116, 0, 'cycling cap (Blue)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(117, 0, 'cycling cap (Yellow & avocado)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(118, 0, 'cycling cap (Red & green)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(119, 0, 'cycling cap (Red)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(120, 0, 'cycling cap (Lime & purple)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(121, 0, 'cycling cap (Blue & purple)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(122, 0, 'cycling cap (Black & blue)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(123, 0, 'cycling cap (Black & red)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(124, 0, 'DAL cap (Blue)', 'unorderable', '1010', 'Dodo Airlines', 'Simple');
insert into acnh_headwear values(125, 0, 'dandy hat (Blue)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(126, 0, 'dandy hat (Green)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(127, 0, 'dandy hat (Purple)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(128, 0, 'dandy hat (Gray)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(129, 0, 'dandy hat (White)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(130, 0, 'dandy hat (Camel)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(131, 0, 'dark cosmos crown', 'unorderable', '3360', 'Crafting', 'Cute');
insert into acnh_headwear values(132, 0, 'dark lily crown', 'unorderable', '960', 'Crafting', 'Cute');
insert into acnh_headwear values(133, 0, 'dark tulip crown', 'unorderable', '800', 'Crafting', 'Cute');
insert into acnh_headwear values(134, 0, 'denim cap (Blue)', 'orderable', '770', 'Able Sisters', 'Simple');
insert into acnh_headwear values(135, 0, 'denim cap (Light blue)', 'orderable', '770', 'Able Sisters', 'Simple');
insert into acnh_headwear values(136, 0, 'denim cap (Black)', 'orderable', '770', 'Able Sisters', 'Simple');
insert into acnh_headwear values(137, 0, 'denim cap (White)', 'orderable', '770', 'Able Sisters', 'Simple');
insert into acnh_headwear values(138, 0, 'detective hat (Brown)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(139, 0, 'detective hat (Gray)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(140, 0, 'detective hat (Beige)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(141, 0, 'DJ cap (Blue)', 'orderable', '770', 'Able Sisters', 'Simple');
insert into acnh_headwear values(142, 0, 'DJ cap (Pink)', 'orderable', '770', 'Able Sisters', 'Simple');
insert into acnh_headwear values(143, 0, 'DJ cap (Orange)', 'orderable', '770', 'Able Sisters', 'Simple');
insert into acnh_headwear values(144, 0, 'DJ cap (Black)', 'orderable', '770', 'Able Sisters', 'Simple');
insert into acnh_headwear values(145, 0, 'do-rag (Blue)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(146, 0, 'do-rag (Red)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(147, 0, 'do-rag (Pink)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(148, 0, 'do-rag (Black)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(149, 0, 'do-rag (Purple)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(150, 0, 'do-rag (Green)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(151, 0, 'do-rag (Yellow)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(152, 0, 'do-rag (Beige)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(153, 0, 'dotted shower cap (Pink)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(154, 0, 'dotted shower cap (Blue)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(155, 0, 'earth-egg shell', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_headwear values(156, 0, 'egg party hat', 'unorderable', '4800', 'Crafting', 'Gorgeous');
insert into acnh_headwear values(157, 0, 'eggshell (White)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(158, 0, 'elder mask (White)', 'unorderable', '1500', 'Gulliver', 'Elegant');
insert into acnh_headwear values(159, 0, 'elegant hat (Purple)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(160, 0, 'elegant hat (White)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(161, 0, 'elegant hat (Black)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(162, 0, 'elegant hat (Green)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(163, 0, 'elegant hat (Red)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(164, 0, 'explorer''s hat (Beige)', 'orderable', '1040', 'Able Sisters', 'Active');
insert into acnh_headwear values(165, 0, 'explorer''s hat (Blue)', 'orderable', '1040', 'Able Sisters', 'Active');
insert into acnh_headwear values(166, 0, 'explorer''s hat (Avocado)', 'orderable', '1040', 'Able Sisters', 'Active');
insert into acnh_headwear values(167, 0, 'explorer''s hat (Camel)', 'orderable', '1040', 'Able Sisters', 'Active');
insert into acnh_headwear values(168, 0, 'fairy-tale hood (Pink)', 'orderable', '1560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(169, 0, 'fairy-tale hood (Yellow)', 'orderable', '1560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(170, 0, 'fairy-tale hood (Green)', 'orderable', '1560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(171, 0, 'fairy-tale hood (Blue)', 'orderable', '1560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(172, 0, 'fairy-tale hood (Red)', 'orderable', '1560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(173, 0, 'fairy-tale hood (Light blue)', 'orderable', '1560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(174, 0, 'fairy-tale hood (Light green)', 'orderable', '1560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(175, 0, 'fairy-tale hood (Orange)', 'orderable', '1560', 'Able Sisters', 'Cute');
insert into acnh_headwear values(176, 0, 'faux-fur hat (Beige)', 'orderable', '1300', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(177, 0, 'faux-fur hat (Brown)', 'orderable', '1300', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(178, 0, 'faux-fur hat (Gray)', 'orderable', '1300', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(179, 0, 'faux-fur hat (Black)', 'orderable', '1300', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(180, 0, 'faux-fur hat (Pink)', 'orderable', '1300', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(181, 0, 'faux-fur hat (White)', 'orderable', '1300', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(182, 0, 'faux-fur hat (Red)', 'orderable', '1300', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(183, 0, 'fedora (Beige)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_headwear values(184, 0, 'fedora (Black)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_headwear values(185, 0, 'fedora (Green)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_headwear values(186, 0, 'fedora (Gray)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_headwear values(187, 0, 'fedora (White)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_headwear values(188, 0, 'fedora (Red)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_headwear values(189, 0, 'firefighter''s hat (Flame orange)', 'orderable', '1680', 'Able Sisters', 'Active');
insert into acnh_headwear values(190, 0, 'firefighter''s hat (Brown)', 'orderable', '1680', 'Able Sisters', 'Active');
insert into acnh_headwear values(191, 0, 'firefighter''s hat (Lime yellow)', 'orderable', '1680', 'Able Sisters', 'Active');
insert into acnh_headwear values(192, 0, 'firefighter''s hat (Black)', 'orderable', '1680', 'Able Sisters', 'Active');
insert into acnh_headwear values(193, 0, 'firefighter''s hat (Avocado)', 'orderable', '1680', 'Able Sisters', 'Active');
insert into acnh_headwear values(194, 0, 'flashy hairpin (Blue)', 'orderable', '2340', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(195, 0, 'flashy hairpin (Black)', 'orderable', '2340', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(196, 0, 'flashy hairpin (Purple)', 'orderable', '2340', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(197, 0, 'flashy hairpin (Orange)', 'orderable', '2340', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(198, 0, 'flashy hairpin (Green)', 'orderable', '2340', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(199, 0, 'flashy hairpin (White)', 'orderable', '2340', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(200, 0, 'flashy hairpin (Pink)', 'orderable', '2340', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(201, 0, 'floral hairpin (Green)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(202, 0, 'floral hairpin (Yellow)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(203, 0, 'floral hairpin (Purple)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(204, 0, 'floral hairpin (Pink)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(205, 0, 'floral hairpin (Blue)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(206, 0, 'football helmet (White)', 'orderable', '1440', 'Able Sisters', 'Active');
insert into acnh_headwear values(207, 0, 'football helmet (Yellow)', 'orderable', '1440', 'Able Sisters', 'Active');
insert into acnh_headwear values(208, 0, 'football helmet (Berry red)', 'orderable', '1440', 'Able Sisters', 'Active');
insert into acnh_headwear values(209, 0, 'football helmet (Blue)', 'orderable', '1440', 'Able Sisters', 'Active');
insert into acnh_headwear values(210, 0, 'football helmet (Turquoise)', 'orderable', '1440', 'Able Sisters', 'Active');
insert into acnh_headwear values(211, 0, 'football helmet (Red)', 'orderable', '1440', 'Able Sisters', 'Active');
insert into acnh_headwear values(212, 0, 'football helmet (Green)', 'orderable', '1440', 'Able Sisters', 'Active');
insert into acnh_headwear values(213, 0, 'football helmet (Black)', 'orderable', '1440', 'Able Sisters', 'Active');
insert into acnh_headwear values(214, 0, 'fox mask (White)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(215, 0, 'fox mask (Black)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(216, 0, 'frog cap (Green)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(217, 0, 'frog cap (Blue)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(218, 0, 'frog cap (Red)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(219, 0, 'frog cap (Yellow)', 'orderable', '1120', 'Able Sisters', 'Cute');
insert into acnh_headwear values(220, 0, 'frugal hat (Brown)', 'orderable', '350', 'Able Sisters', 'Simple');
insert into acnh_headwear values(221, 0, 'frugal hat (Green)', 'orderable', '350', 'Able Sisters', 'Simple');
insert into acnh_headwear values(222, 0, 'frugal hat (Blue-gray)', 'orderable', '350', 'Able Sisters', 'Simple');
insert into acnh_headwear values(223, 0, 'geisha wig (Pink)', 'unorderable', '1350', 'Gulliver', 'Cute');
insert into acnh_headwear values(224, 0, 'geisha wig (Golden yellow)', 'unorderable', '1350', 'Gulliver', 'Cute');
insert into acnh_headwear values(225, 0, 'geisha wig (Green)', 'unorderable', '1350', 'Gulliver', 'Cute');
insert into acnh_headwear values(226, 0, 'geisha wig (Blue)', 'unorderable', '1350', 'Gulliver', 'Cute');
insert into acnh_headwear values(227, 0, 'geisha wig (Purple)', 'unorderable', '1350', 'Gulliver', 'Cute');
insert into acnh_headwear values(228, 0, 'geisha wig (Black)', 'unorderable', '1350', 'Gulliver', 'Cute');
insert into acnh_headwear values(229, 0, 'geisha wig (Red)', 'unorderable', '1350', 'Gulliver', 'Cute');
insert into acnh_headwear values(230, 0, 'giant ribbon (Green)', 'orderable', '1470', 'Able Sisters', 'Cute');
insert into acnh_headwear values(231, 0, 'giant ribbon (Blue)', 'orderable', '1470', 'Able Sisters', 'Cute');
insert into acnh_headwear values(232, 0, 'giant ribbon (Yellow)', 'orderable', '1470', 'Able Sisters', 'Cute');
insert into acnh_headwear values(233, 0, 'giant ribbon (Orange)', 'orderable', '1470', 'Able Sisters', 'Cute');
insert into acnh_headwear values(234, 0, 'giant ribbon (Pink)', 'orderable', '1470', 'Able Sisters', 'Cute');
insert into acnh_headwear values(235, 0, 'giant ribbon (White)', 'orderable', '1470', 'Able Sisters', 'Cute');
insert into acnh_headwear values(236, 0, 'giant ribbon (Black)', 'orderable', '1470', 'Able Sisters', 'Cute');
insert into acnh_headwear values(237, 0, 'giant ribbon (Red)', 'orderable', '1470', 'Able Sisters', 'Cute');
insert into acnh_headwear values(238, 0, 'glengarry (Black)', 'orderable', '1320', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(239, 0, 'gold helmet', 'unorderable', '50000', 'Crafting', 'Gorgeous');
insert into acnh_headwear values(240, 0, 'gold rose crown', 'unorderable', '12000', 'Crafting', 'Cute');
insert into acnh_headwear values(241, 0, 'gothic headdress (Black)', 'orderable', '1120', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(242, 0, 'gothic headdress (Red)', 'orderable', '1120', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(243, 0, 'gothic headdress (Pink)', 'orderable', '1120', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(244, 0, 'gothic headdress (Blue)', 'orderable', '1120', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(245, 0, 'gothic headdress (Light purple)', 'orderable', '1120', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(246, 0, 'gothic headdress (Purple)', 'orderable', '1120', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(247, 0, 'grape hat (Purple)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(248, 0, 'halo (Gold)', 'orderable', '2220', 'Able Sisters', 'Cute');
insert into acnh_headwear values(249, 0, 'headband (Blue)', 'orderable', '1400', 'Able Sisters', 'Cute');
insert into acnh_headwear values(250, 0, 'headband (Purple)', 'orderable', '1400', 'Able Sisters', 'Cute');
insert into acnh_headwear values(251, 0, 'headband (Green)', 'orderable', '1400', 'Able Sisters', 'Cute');
insert into acnh_headwear values(252, 0, 'headband (Pink)', 'orderable', '1400', 'Able Sisters', 'Cute');
insert into acnh_headwear values(253, 0, 'headgear (Red)', 'orderable', '910', 'Able Sisters', 'Active');
insert into acnh_headwear values(254, 0, 'headgear (Blue)', 'orderable', '910', 'Able Sisters', 'Active');
insert into acnh_headwear values(255, 0, 'headgear (Green)', 'orderable', '910', 'Able Sisters', 'Active');
insert into acnh_headwear values(256, 0, 'headkerchief (Green)', 'orderable', '490', 'Able Sisters', 'Cool');
insert into acnh_headwear values(257, 0, 'heart hairpin (Red)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(258, 0, 'heart hairpin (Green)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(259, 0, 'heart hairpin (Blue)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(260, 0, 'heart hairpin (Black)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(261, 0, 'heart hairpin (Pink)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(262, 0, 'helmet with goggles (Pink)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(263, 0, 'helmet with goggles (Green)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(264, 0, 'helmet with goggles (Purple)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(265, 0, 'helmet with goggles (Blue)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(266, 0, 'helmet with goggles (Red)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(267, 0, 'helmet with goggles (Light blue)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(268, 0, 'helmet with goggles (Black)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(269, 0, 'helmet with goggles (Yellow)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(270, 0, 'hibiscus hairpin (Yellow)', 'orderable', '560', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(271, 0, 'hibiscus hairpin (White)', 'orderable', '560', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(272, 0, 'hibiscus hairpin (Red)', 'orderable', '560', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(273, 0, 'hibiscus hairpin (Pink)', 'orderable', '560', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(274, 0, 'hockey mask (White)', 'orderable', '1440', 'Able Sisters', 'Cool');
insert into acnh_headwear values(275, 0, 'hot-dog hood (Red)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(276, 0, 'hyacinth crown', 'unorderable', '640', 'Crafting', 'Cute');
insert into acnh_headwear values(277, 0, 'imitation cow skull (White)', 'orderable', '1120', 'Able Sisters', 'Cool');
insert into acnh_headwear values(278, 0, 'imp hood (Black)', 'orderable', '1760', 'Able Sisters', 'Cool');
insert into acnh_headwear values(279, 0, 'imp hood (Red)', 'orderable', '1760', 'Able Sisters', 'Cool');
insert into acnh_headwear values(280, 0, 'jester''s cap (Black & white)', 'orderable', '1900', 'Able Sisters', 'Active');
insert into acnh_headwear values(281, 0, 'jester''s cap (Red & blue)', 'orderable', '1900', 'Able Sisters', 'Active');
insert into acnh_headwear values(282, 0, 'jester''s cap (Green & red)', 'orderable', '1900', 'Able Sisters', 'Active');
insert into acnh_headwear values(283, 0, 'jester''s cap (Purple & yellow)', 'orderable', '1900', 'Able Sisters', 'Active');
insert into acnh_headwear values(284, 0, 'jockey''s helmet (Pink)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(285, 0, 'jockey''s helmet (Orange)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(286, 0, 'jockey''s helmet (Green)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(287, 0, 'jockey''s helmet (Yellow)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(288, 0, 'jockey''s helmet (Blue)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(289, 0, 'jockey''s helmet (Red)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(290, 0, 'jockey''s helmet (Black)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(291, 0, 'jockey''s helmet (White)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(292, 0, 'kaffiyeh (White)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(293, 0, 'kaffiyeh (Red)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(294, 0, 'kaffiyeh (Black)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(295, 0, 'kappa cap (Green)', 'orderable', '980', 'Able Sisters', 'Cute');
insert into acnh_headwear values(296, 0, 'kappa cap (Pink)', 'orderable', '980', 'Able Sisters', 'Cute');
insert into acnh_headwear values(297, 0, 'kiwi hat (Green)', 'orderable', '770', 'Able Sisters', 'Cute');
insert into acnh_headwear values(298, 0, 'knight''s helmet', 'unorderable', '3750', 'Crafting', 'Cool');
insert into acnh_headwear values(299, 0, 'knit cap with earflaps (Ruby red)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_headwear values(300, 0, 'knit cap with earflaps (Moss green)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_headwear values(301, 0, 'knit cap with earflaps (Gray)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_headwear values(302, 0, 'knit cap with earflaps (Beige)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_headwear values(303, 0, 'knit cap with earflaps (Blue)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_headwear values(304, 0, 'knit cap with earflaps (Pink)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_headwear values(305, 0, 'knit cap with earflaps (Green)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_headwear values(306, 0, 'knit hat (White)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(307, 0, 'knit hat (Gray)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(308, 0, 'knit hat (Ochre)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(309, 0, 'knit hat (Red)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(310, 0, 'knit hat (Blue)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(311, 0, 'knit hat (Green)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(312, 0, 'knit hat (Pink)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(313, 0, 'knit hat (Black)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(314, 0, 'Labelle cap (Passion)', 'orderable', '2400', 'Labelle', 'Cool');
insert into acnh_headwear values(315, 0, 'Labelle cap (Ocean)', 'orderable', '2400', 'Labelle', 'Cool');
insert into acnh_headwear values(316, 0, 'Labelle cap (Sunset)', 'orderable', '2400', 'Labelle', 'Cool');
insert into acnh_headwear values(317, 0, 'Labelle cap (Twilight)', 'orderable', '2400', 'Labelle', 'Cool');
insert into acnh_headwear values(318, 0, 'Labelle cap (Love)', 'orderable', '2400', 'Labelle', 'Cool');
insert into acnh_headwear values(319, 0, 'Labelle cap (Midnight)', 'orderable', '2400', 'Labelle', 'Cool');
insert into acnh_headwear values(320, 0, 'Labelle hat (Twilight)', 'orderable', '2500', 'Labelle', 'Gorgeous');
insert into acnh_headwear values(321, 0, 'Labelle hat (Midnight)', 'orderable', '2500', 'Labelle', 'Gorgeous');
insert into acnh_headwear values(322, 0, 'Labelle hat (Passion)', 'orderable', '2500', 'Labelle', 'Gorgeous');
insert into acnh_headwear values(323, 0, 'Labelle hat (Ocean)', 'orderable', '2500', 'Labelle', 'Gorgeous');
insert into acnh_headwear values(324, 0, 'Labelle hat (Sunset)', 'orderable', '2500', 'Labelle', 'Gorgeous');
insert into acnh_headwear values(325, 0, 'Labelle hat (Love)', 'orderable', '2500', 'Labelle', 'Gorgeous');
insert into acnh_headwear values(326, 0, 'leaf mask', 'unorderable', '200', 'Crafting', 'Cute');
insert into acnh_headwear values(327, 0, 'leaf-egg shell', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_headwear values(328, 0, 'lettered cap (Beige)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(329, 0, 'lettered cap (Olive)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(330, 0, 'lettered cap (Red)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(331, 0, 'lily crown', 'unorderable', '480', 'Crafting', 'Cute');
insert into acnh_headwear values(332, 0, 'lovely cosmos crown', 'unorderable', '1120', 'Crafting', 'Cute');
insert into acnh_headwear values(333, 0, 'mage''s hat (Blue)', 'orderable', '3440', 'Able Sisters', 'Cool');
insert into acnh_headwear values(334, 0, 'mage''s hat (White)', 'orderable', '3440', 'Able Sisters', 'Cool');
insert into acnh_headwear values(335, 0, 'mage''s hat (Red)', 'orderable', '3440', 'Able Sisters', 'Cool');
insert into acnh_headwear values(336, 0, 'mage''s hat (Black)', 'orderable', '3440', 'Able Sisters', 'Cool');
insert into acnh_headwear values(337, 0, 'matanpushi (Brown)', 'orderable', '880', 'Able Sisters', 'Cool');
insert into acnh_headwear values(338, 0, 'matanpushi (Red)', 'orderable', '880', 'Able Sisters', 'Cool');
insert into acnh_headwear values(339, 0, 'matanpushi (Blue)', 'orderable', '880', 'Able Sisters', 'Cool');
insert into acnh_headwear values(340, 0, 'matronly bun (Hair Color)', 'orderable', '1280', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(341, 0, 'mesh cap (Red)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(342, 0, 'mesh cap (Pink)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(343, 0, 'mesh cap (Green)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(344, 0, 'mesh cap (Orange)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(345, 0, 'mesh cap (Purple)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(346, 0, 'mesh cap (Yellow)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(347, 0, 'mesh cap (Black)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(348, 0, 'milkmaid hat (White)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(349, 0, 'mohawk wig (Hair Color)', 'orderable', '1280', 'Able Sisters', 'Cool');
insert into acnh_headwear values(350, 0, 'mum crown', 'unorderable', '480', 'Crafting', 'Cute');
insert into acnh_headwear values(351, 0, 'mummy mask (White)', 'orderable', '980', 'Able Sisters', 'Cool');
insert into acnh_headwear values(352, 0, 'New Year''s hat (Purple)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(353, 0, 'New Year''s hat (Pink)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(354, 0, 'New Year''s hat (Light blue)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(355, 0, 'New Year''s hat (Red)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(356, 0, 'New Year''s hat (Blue)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(357, 0, 'New Year''s hat (Yellow)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(358, 0, 'New Year''s hat (Green)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(359, 0, 'New Year''s hat (Orange)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(360, 0, 'New Year''s silk hat (Orange)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(361, 0, 'New Year''s silk hat (Purple)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(362, 0, 'New Year''s silk hat (Pink)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(363, 0, 'New Year''s silk hat (Light blue)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(364, 0, 'New Year''s silk hat (Red)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(365, 0, 'New Year''s silk hat (Blue)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(366, 0, 'New Year''s silk hat (Yellow)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(367, 0, 'New Year''s silk hat (Green)', 'unorderable', '125', 'Countdown event', 'Gorgeous');
insert into acnh_headwear values(368, 0, 'ninja hood (Dark blue)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(369, 0, 'ninja hood (Gray)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(370, 0, 'ninja hood (Red)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(371, 0, 'ninja hood (Purple)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(372, 0, 'ninja hood (Aqua)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(373, 0, 'ninja hood (Green)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(374, 0, 'ninja hood (Yellow)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(375, 0, 'ninja hood (Orange)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(376, 0, 'Noh mask (White)', 'orderable', '2400', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(377, 0, 'Nook Inc. bandanna (Yellow)', 'unorderable', '2500', 'Nook Miles Shop', 'Simple');
insert into acnh_headwear values(378, 0, 'Nook Inc. cap (Green)', 'unorderable', '2500', 'Nook Miles Shop', 'Simple');
insert into acnh_headwear values(379, 0, 'nurse''s cap (Pink)', 'orderable', '1680', 'Able Sisters', 'Simple');
insert into acnh_headwear values(380, 0, 'nurse''s cap (White)', 'orderable', '1680', 'Able Sisters', 'Simple');
insert into acnh_headwear values(381, 0, 'nurse''s cap (Blue)', 'orderable', '1680', 'Able Sisters', 'Simple');
insert into acnh_headwear values(382, 0, 'OK Motors cap', 'unorderable', '192', 'Nook Shopping Promotion', 'Simple');
insert into acnh_headwear values(383, 0, 'orange hat', 'unorderable', '1000', 'Crafting', 'Cute');
insert into acnh_headwear values(384, 0, 'outback hat (Brown)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(385, 0, 'outback hat (Beige)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(386, 0, 'outback hat (Red)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(387, 0, 'outback hat (Pink)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(388, 0, 'outback hat (White)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(389, 0, 'outdoor hat (Red)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(390, 0, 'outdoor hat (Yellow)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(391, 0, 'outdoor hat (Light blue)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(392, 0, 'outdoor hat (Green)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(393, 0, 'outdoor hat (Beige)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(394, 0, 'outdoor hat (Orange)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(395, 0, 'outdoor hat (Blue)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(396, 0, 'outdoor hat (Purple)', 'orderable', '1100', 'Able Sisters', 'Active');
insert into acnh_headwear values(397, 0, 'paintball mask (Black)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(398, 0, 'paintball mask (White)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(399, 0, 'paintball mask (Olive)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(400, 0, 'paintball mask (Yellow)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(401, 0, 'paisley bandanna (Blue)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(402, 0, 'paisley bandanna (Yellow)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(403, 0, 'paisley bandanna (Black)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(404, 0, 'paisley bandanna (Green)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(405, 0, 'paisley bandanna (Orange)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(406, 0, 'paisley bandanna (Pink)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(407, 0, 'paisley bandanna (Purple)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(408, 0, 'paisley bandanna (Red)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(409, 0, 'pansy crown', 'unorderable', '480', 'Crafting', 'Cute');
insert into acnh_headwear values(410, 0, 'paper bag (Beige)', 'orderable', '140', 'Able Sisters', 'Cool');
insert into acnh_headwear values(411, 0, 'paperboy cap (Brown)', 'orderable', '1470', 'Able Sisters', 'Simple');
insert into acnh_headwear values(412, 0, 'paperboy cap (Gray)', 'orderable', '1470', 'Able Sisters', 'Simple');
insert into acnh_headwear values(413, 0, 'paperboy cap (Green)', 'orderable', '1470', 'Able Sisters', 'Simple');
insert into acnh_headwear values(414, 0, 'paperboy cap (Blue)', 'orderable', '1470', 'Able Sisters', 'Simple');
insert into acnh_headwear values(415, 0, 'paperboy cap (Red)', 'orderable', '1470', 'Able Sisters', 'Simple');
insert into acnh_headwear values(416, 0, 'patchwork tulip hat (Pink)', 'orderable', '1680', 'Able Sisters', 'Cute');
insert into acnh_headwear values(417, 0, 'patchwork tulip hat (Blue)', 'orderable', '1680', 'Able Sisters', 'Cute');
insert into acnh_headwear values(418, 0, 'patchwork tulip hat (Yellow)', 'orderable', '1680', 'Able Sisters', 'Cute');
insert into acnh_headwear values(419, 0, 'peach hat', 'unorderable', '1000', 'Crafting', 'Cute');
insert into acnh_headwear values(420, 0, 'pear hat', 'unorderable', '1000', 'Crafting', 'Cute');
insert into acnh_headwear values(421, 0, 'pigtail (Hair Color)', 'unorderable', '800', 'Gulliver', 'Cool');
insert into acnh_headwear values(422, 0, 'pilot''s cap (Black)', 'orderable', '1120', 'Able Sisters', 'Cool');
insert into acnh_headwear values(423, 0, 'pilot''s cap (Avocado)', 'orderable', '1120', 'Able Sisters', 'Cool');
insert into acnh_headwear values(424, 0, 'pilot''s cap (Brown)', 'orderable', '1120', 'Able Sisters', 'Cool');
insert into acnh_headwear values(425, 0, 'pilot''s hat (Navy blue)', 'orderable', '1680', 'Able Sisters', 'Active');
insert into acnh_headwear values(426, 0, 'pilot''s hat (Black)', 'orderable', '1680', 'Able Sisters', 'Active');
insert into acnh_headwear values(427, 0, 'pilot''s hat (Light blue)', 'orderable', '1680', 'Able Sisters', 'Active');
insert into acnh_headwear values(428, 0, 'pineapple cap (Yellow)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(429, 0, 'plain cap (Gray)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(430, 0, 'plain cap (Beige)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(431, 0, 'plain cap (Red)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(432, 0, 'plain cap (Blue)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(433, 0, 'plain cap (Green)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(434, 0, 'police cap (Navy blue)', 'orderable', '1680', 'Able Sisters', 'Active');
insert into acnh_headwear values(435, 0, 'pom casquette (White)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(436, 0, 'pom casquette (Brown)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(437, 0, 'pom casquette (Red)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(438, 0, 'pom casquette (Green)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(439, 0, 'pom casquette (Blue)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(440, 0, 'pom casquette (Gray)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_headwear values(441, 0, 'pompadour wig (Hair Color)', 'orderable', '1280', 'Able Sisters', 'Cool');
insert into acnh_headwear values(442, 0, 'power helmet (Red)', 'orderable', '3220', 'Able Sisters', 'Active');
insert into acnh_headwear values(443, 0, 'power helmet (Blue)', 'orderable', '3220', 'Able Sisters', 'Active');
insert into acnh_headwear values(444, 0, 'power helmet (Green)', 'orderable', '3220', 'Able Sisters', 'Active');
insert into acnh_headwear values(445, 0, 'power helmet (Black)', 'orderable', '3220', 'Able Sisters', 'Active');
insert into acnh_headwear values(446, 0, 'purple hyacinth crown', 'unorderable', '2880', 'Crafting', 'Cute');
insert into acnh_headwear values(447, 0, 'purple pansy crown', 'unorderable', '2880', 'Crafting', 'Cute');
insert into acnh_headwear values(448, 0, 'purple windflower crown', 'unorderable', '2880', 'Crafting', 'Cute');
insert into acnh_headwear values(449, 0, 'racing helmet (Red)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(450, 0, 'racing helmet (White)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(451, 0, 'racing helmet (Black)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(452, 0, 'racing helmet (Blue)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(453, 0, 'racing helmet (Pink)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(454, 0, 'racing helmet (Green)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(455, 0, 'racing helmet (Purple)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(456, 0, 'racing helmet (Light blue)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_headwear values(457, 0, 'rain hat (Green)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(458, 0, 'rain hat (Pink)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(459, 0, 'rain hat (Blue)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(460, 0, 'rain hat (Red)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(461, 0, 'rain hat (Black)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(462, 0, 'rain hat (Purple)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(463, 0, 'rain hat (Beige)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(464, 0, 'rain hat (Yellow)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(465, 0, 'ribbon (Blue)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(466, 0, 'ribbon (Yellow)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(467, 0, 'ribbon (Orange)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(468, 0, 'ribbon (Pink)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(469, 0, 'ribbon (White)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(470, 0, 'ribbon (Black)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(471, 0, 'ribbon (Green)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(472, 0, 'ribbon (Red)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(473, 0, 'ribboned garden hat (Blue)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(474, 0, 'ribboned garden hat (Pink)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(475, 0, 'ribboned garden hat (Black)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(476, 0, 'ribboned garden hat (Brown)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(477, 0, 'ribboned straw hat (Light blue)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(478, 0, 'ribboned straw hat (Pink)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(479, 0, 'ribboned straw hat (Black)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_headwear values(480, 0, 'rose crown', 'unorderable', '480', 'Crafting', 'Cute');
insert into acnh_headwear values(481, 0, 'royal crown (Red)', 'orderable', '1200000', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(482, 0, 'safety helmet (Orange)', 'orderable', '770', 'Able Sisters', 'Active');
insert into acnh_headwear values(483, 0, 'safety helmet (Yellow)', 'orderable', '770', 'Able Sisters', 'Active');
insert into acnh_headwear values(484, 0, 'safety helmet (Green)', 'orderable', '770', 'Able Sisters', 'Active');
insert into acnh_headwear values(485, 0, 'safety helmet (Black)', 'orderable', '770', 'Able Sisters', 'Active');
insert into acnh_headwear values(486, 0, 'safety helmet (Blue)', 'orderable', '770', 'Able Sisters', 'Active');
insert into acnh_headwear values(487, 0, 'sailor''s hat (White)', 'orderable', '1680', 'Able Sisters', 'Simple');
insert into acnh_headwear values(488, 0, 'sailor''s hat (Navy blue)', 'orderable', '1680', 'Able Sisters', 'Simple');
insert into acnh_headwear values(489, 0, 'sailor''s hat (Blue)', 'orderable', '1680', 'Able Sisters', 'Simple');
insert into acnh_headwear values(490, 0, 'samurai helmet (Golden yellow)', 'orderable', '5880', 'Able Sisters', 'Active');
insert into acnh_headwear values(491, 0, 'samurai helmet (Black)', 'orderable', '5880', 'Able Sisters', 'Active');
insert into acnh_headwear values(492, 0, 'samurai helmet (Blue)', 'orderable', '5880', 'Able Sisters', 'Active');
insert into acnh_headwear values(493, 0, 'samurai helmet (White)', 'orderable', '5880', 'Able Sisters', 'Active');
insert into acnh_headwear values(494, 0, 'samurai helmet (Red)', 'orderable', '5880', 'Able Sisters', 'Active');
insert into acnh_headwear values(495, 0, 'samurai wig (Hair Color)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(496, 0, 'scholar''s hat (Red)', 'orderable', '3010', 'Able Sisters', 'Simple');
insert into acnh_headwear values(497, 0, 'scholar''s hat (Green)', 'orderable', '3010', 'Able Sisters', 'Simple');
insert into acnh_headwear values(498, 0, 'scholar''s hat (Blue)', 'orderable', '3010', 'Able Sisters', 'Simple');
insert into acnh_headwear values(499, 0, 'scholar''s hat (Yellow)', 'orderable', '3010', 'Able Sisters', 'Simple');
insert into acnh_headwear values(500, 0, 'school hat (Navy blue)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(501, 0, 'school hat (Yellow)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(502, 0, 'shallow knit cap (Green)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(503, 0, 'shallow knit cap (Beige)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(504, 0, 'shallow knit cap (Navy blue)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(505, 0, 'shallow knit cap (Red)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(506, 0, 'shallow knit cap (Purple)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(507, 0, 'shallow knit cap (Gray)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(508, 0, 'shallow knit cap (Brown)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(509, 0, 'sheep hood (White)', 'orderable', '980', 'Able Sisters', 'Cute');
insert into acnh_headwear values(510, 0, 'sheep hood (Pink)', 'orderable', '980', 'Able Sisters', 'Cute');
insert into acnh_headwear values(511, 0, 'sheep hood (Light blue)', 'orderable', '980', 'Able Sisters', 'Cute');
insert into acnh_headwear values(512, 0, 'sheep hood (Brown)', 'orderable', '980', 'Able Sisters', 'Cute');
insert into acnh_headwear values(513, 0, 'silk hat (Green)', 'unorderable', '500', 'Gulliver', 'Elegant');
insert into acnh_headwear values(514, 0, 'silk hat (Yellow)', 'unorderable', '500', 'Gulliver', 'Elegant');
insert into acnh_headwear values(515, 0, 'silk hat (Black)', 'unorderable', '500', 'Gulliver', 'Elegant');
insert into acnh_headwear values(516, 0, 'silk hat (Blue)', 'unorderable', '500', 'Gulliver', 'Elegant');
insert into acnh_headwear values(517, 0, 'simple mum crown', 'unorderable', '2880', 'Crafting', 'Cute');
insert into acnh_headwear values(518, 0, 'skateboarding helmet (Orange)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_headwear values(519, 0, 'skateboarding helmet (White)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_headwear values(520, 0, 'skateboarding helmet (Light blue)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_headwear values(521, 0, 'skateboarding helmet (Olive)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_headwear values(522, 0, 'skateboarding helmet (Gray)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_headwear values(523, 0, 'skeleton hood (White)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(524, 0, 'ski mask (Green)', 'orderable', '560', 'Able Sisters', 'Cool');
insert into acnh_headwear values(525, 0, 'ski mask (Black)', 'orderable', '560', 'Able Sisters', 'Cool');
insert into acnh_headwear values(526, 0, 'ski mask (Lime)', 'orderable', '560', 'Able Sisters', 'Cool');
insert into acnh_headwear values(527, 0, 'ski mask (Red)', 'orderable', '560', 'Able Sisters', 'Cool');
insert into acnh_headwear values(528, 0, 'ski mask (Blue)', 'orderable', '560', 'Able Sisters', 'Cool');
insert into acnh_headwear values(529, 0, 'sky-egg shell', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_headwear values(530, 0, 'small silk hat (Purple)', 'orderable', '1820', 'Able Sisters', 'Cute');
insert into acnh_headwear values(531, 0, 'small silk hat (Black)', 'orderable', '1820', 'Able Sisters', 'Cute');
insert into acnh_headwear values(532, 0, 'small silk hat (Red)', 'orderable', '1820', 'Able Sisters', 'Cute');
insert into acnh_headwear values(533, 0, 'snowperson head', 'unorderable', '7000', 'Crafting', 'Cute');
insert into acnh_headwear values(534, 0, 'snowy knit cap (Brown)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(535, 0, 'snowy knit cap (Pink)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(536, 0, 'snowy knit cap (Green)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(537, 0, 'snowy knit cap (Orange)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(538, 0, 'snowy knit cap (Red)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(539, 0, 'snowy knit cap (White)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(540, 0, 'snowy knit cap (Blue)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(541, 0, 'snowy knit cap (Black)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(542, 0, 'soft-serve hat (Chocolate)', 'orderable', '630', 'Able Sisters', 'Cute');
insert into acnh_headwear values(543, 0, 'soft-serve hat (Gold leaf)', 'orderable', '630', 'Able Sisters', 'Cute');
insert into acnh_headwear values(544, 0, 'soft-serve hat (Strawberry)', 'orderable', '630', 'Able Sisters', 'Cute');
insert into acnh_headwear values(545, 0, 'soft-serve hat (Green tea)', 'orderable', '630', 'Able Sisters', 'Cute');
insert into acnh_headwear values(546, 0, 'soft-serve hat (Pale sky)', 'orderable', '630', 'Able Sisters', 'Cute');
insert into acnh_headwear values(547, 0, 'soft-serve hat (Vanilla)', 'orderable', '630', 'Able Sisters', 'Cute');
insert into acnh_headwear values(548, 0, 'soft-serve hat (Purple sweet potato)', 'orderable', '630', 'Able Sisters', 'Cute');
insert into acnh_headwear values(549, 0, 'soft-serve hat (Black sesame)', 'orderable', '630', 'Able Sisters', 'Cute');
insert into acnh_headwear values(550, 0, 'sombrero (Natural & red)', 'unorderable', '500', 'Gulliver', 'Active');
insert into acnh_headwear values(551, 0, 'sombrero (Green)', 'unorderable', '500', 'Gulliver', 'Active');
insert into acnh_headwear values(552, 0, 'sombrero (White)', 'unorderable', '500', 'Gulliver', 'Active');
insert into acnh_headwear values(553, 0, 'sombrero (Red)', 'unorderable', '500', 'Gulliver', 'Active');
insert into acnh_headwear values(554, 0, 'sombrero (Blue)', 'unorderable', '500', 'Gulliver', 'Active');
insert into acnh_headwear values(555, 0, 'sombrero (Orange)', 'unorderable', '500', 'Gulliver', 'Active');
insert into acnh_headwear values(556, 0, 'sombrero (Natural & green)', 'unorderable', '500', 'Gulliver', 'Active');
insert into acnh_headwear values(557, 0, 'sombrero (Navy blue)', 'unorderable', '500', 'Gulliver', 'Active');
insert into acnh_headwear values(558, 0, 'space helmet (White)', 'orderable', '4300', 'Able Sisters', 'Active');
insert into acnh_headwear values(559, 0, 'sports cap (White & blue)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(560, 0, 'sports cap (Red)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(561, 0, 'sports cap (White & red)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(562, 0, 'sports cap (Blue)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_headwear values(563, 0, 'stagehand hat (Black)', 'orderable', '980', 'Able Sisters', 'Cool');
insert into acnh_headwear values(564, 0, 'star hairpin (Purple)', 'orderable', '350', 'Able Sisters', 'Cute');
insert into acnh_headwear values(565, 0, 'star hairpin (Mint)', 'orderable', '350', 'Able Sisters', 'Cute');
insert into acnh_headwear values(566, 0, 'star hairpin (Black)', 'orderable', '350', 'Able Sisters', 'Cute');
insert into acnh_headwear values(567, 0, 'star hairpin (Pink)', 'orderable', '350', 'Able Sisters', 'Cute');
insert into acnh_headwear values(568, 0, 'star hairpin (Yellow)', 'orderable', '350', 'Able Sisters', 'Cute');
insert into acnh_headwear values(569, 0, 'star head', 'unorderable', '2500', 'Crafting', 'Cute');
insert into acnh_headwear values(570, 0, 'stone-egg shell', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_headwear values(571, 0, 'straw boater (Beige)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(572, 0, 'straw boater (Light brown)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(573, 0, 'straw boater (Brown)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(574, 0, 'straw boater (Dark brown)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(575, 0, 'straw boater (Monotone)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(576, 0, 'straw boater (Cream)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(577, 0, 'straw boater (Light blue)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(578, 0, 'straw boater (Pink)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_headwear values(579, 0, 'straw hat (Blue)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_headwear values(580, 0, 'straw hat (Red)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_headwear values(581, 0, 'straw hat (Brown)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_headwear values(582, 0, 'straw umbrella hat', 'unorderable', '200', 'Crafting', 'Cool');
insert into acnh_headwear values(583, 0, 'strawberry hat (Red)', 'orderable', '700', 'Able Sisters', 'Cute');
insert into acnh_headwear values(584, 0, 'student cap (Berry red)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_headwear values(585, 0, 'student cap (Green)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_headwear values(586, 0, 'student cap (Black)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_headwear values(587, 0, 'student cap (White)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_headwear values(588, 0, 'student cap (Purple)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_headwear values(589, 0, 'student cap (Gray)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_headwear values(590, 0, 'student cap (Blue)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_headwear values(591, 0, 'sushi chef hat (Dark blue)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(592, 0, 'sushi chef hat (White)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_headwear values(593, 0, 'swimming cap (Light blue)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(594, 0, 'swimming cap (Red)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(595, 0, 'swimming cap (White)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(596, 0, 'swimming cap (Black)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(597, 0, 'swimming cap (Blue)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(598, 0, 'swimming cap (Pink)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(599, 0, 'swimming cap (Green)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(600, 0, 'swimming cap (Yellow)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(601, 0, 'tam-o''-shanter (Gray)', 'unorderable', '500', 'Gulliver', 'Elegant');
insert into acnh_headwear values(602, 0, 'tam-o''-shanter (Blue)', 'unorderable', '500', 'Gulliver', 'Elegant');
insert into acnh_headwear values(603, 0, 'tam-o''-shanter (Green)', 'unorderable', '500', 'Gulliver', 'Elegant');
insert into acnh_headwear values(604, 0, 'tam-o''-shanter (Red)', 'unorderable', '500', 'Gulliver', 'Elegant');
insert into acnh_headwear values(605, 0, 'terry-cloth do-rag (White)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_headwear values(606, 0, 'terry-cloth do-rag (Black)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_headwear values(607, 0, 'terry-cloth do-rag (Blue)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_headwear values(608, 0, 'terry-cloth do-rag (Brown)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_headwear values(609, 0, 'terry-cloth do-rag (Yellow)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_headwear values(610, 0, 'terry-cloth do-rag (Berry red)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_headwear values(611, 0, 'terry-cloth nightcap (Blue)', 'orderable', '840', 'Able Sisters', 'Cute');
insert into acnh_headwear values(612, 0, 'terry-cloth nightcap (Green)', 'orderable', '840', 'Able Sisters', 'Cute');
insert into acnh_headwear values(613, 0, 'terry-cloth nightcap (Orange)', 'orderable', '840', 'Able Sisters', 'Cute');
insert into acnh_headwear values(614, 0, 'terry-cloth nightcap (Pink)', 'orderable', '840', 'Able Sisters', 'Cute');
insert into acnh_headwear values(615, 0, 'terry-cloth nightcap (Cream)', 'orderable', '840', 'Able Sisters', 'Cute');
insert into acnh_headwear values(616, 0, 'terry-cloth nightcap (Purple)', 'orderable', '840', 'Able Sisters', 'Cute');
insert into acnh_headwear values(617, 0, 'terry-cloth nightcap (Lime)', 'orderable', '840', 'Able Sisters', 'Cute');
insert into acnh_headwear values(618, 0, 'terry-cloth nightcap (Light blue)', 'orderable', '840', 'Able Sisters', 'Cute');
insert into acnh_headwear values(619, 0, 'tiara (Rose gold)', 'orderable', '4300', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(620, 0, 'tiara (Gold)', 'orderable', '4300', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(621, 0, 'tiara (Silver)', 'orderable', '4300', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(622, 0, 'tiara hair (Rose gold)', 'orderable', '2940', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(623, 0, 'tiara hair (Silver)', 'orderable', '2940', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(624, 0, 'tiara hair (Gold)', 'orderable', '2940', 'Able Sisters', 'Gorgeous');
insert into acnh_headwear values(625, 0, 'top hat (Black)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(626, 0, 'top hat (White)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(627, 0, 'top hat (Brown)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(628, 0, 'top hat (Purple)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(629, 0, 'top hat (Red)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(630, 0, 'top hat (Blue)', 'orderable', '2100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(631, 0, 'tropical hat (Yellow)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(632, 0, 'tropical hat (Mint)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(633, 0, 'tropical hat (Pink)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(634, 0, 'tropical hat (White)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(635, 0, 'tropical hat (Blue)', 'orderable', '700', 'Able Sisters', 'Active');
insert into acnh_headwear values(636, 0, 'tubeteika (Red)', 'unorderable', '500', 'Gulliver', 'Gorgeous');
insert into acnh_headwear values(637, 0, 'tubeteika (Blue)', 'unorderable', '500', 'Gulliver', 'Gorgeous');
insert into acnh_headwear values(638, 0, 'tubeteika (Camel)', 'unorderable', '500', 'Gulliver', 'Gorgeous');
insert into acnh_headwear values(639, 0, 'tubeteika (Purple)', 'unorderable', '500', 'Gulliver', 'Gorgeous');
insert into acnh_headwear values(640, 0, 'tulip crown', 'unorderable', '400', 'Crafting', 'Cute');
insert into acnh_headwear values(641, 0, 'tulip hat (Orange)', 'orderable', '630', 'Able Sisters', 'Simple');
insert into acnh_headwear values(642, 0, 'tulip hat (Brown)', 'orderable', '630', 'Able Sisters', 'Simple');
insert into acnh_headwear values(643, 0, 'tulip hat (Camel)', 'orderable', '630', 'Able Sisters', 'Simple');
insert into acnh_headwear values(644, 0, 'turban (Blue)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(645, 0, 'turban (Pink)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(646, 0, 'turban (Yellow)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(647, 0, 'turban (Purple)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(648, 0, 'tweed cap (Brown)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(649, 0, 'tweed cap (Blue)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(650, 0, 'tweed cap (Green)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(651, 0, 'veil (Blue)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(652, 0, 'veil (Purple)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(653, 0, 'veil (Pink)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(654, 0, 'veil (Yellow)', 'unorderable', '800', 'Gulliver', 'Elegant');
insert into acnh_headwear values(655, 0, 'veiled gardening hat (Pink)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(656, 0, 'veiled gardening hat (Blue)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(657, 0, 'veiled gardening hat (Orange)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(658, 0, 'veiled gardening hat (Green)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(659, 0, 'veiled gardening hat (Purple)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_headwear values(660, 0, 'viking helmet (Blue)', 'orderable', '2100', 'Able Sisters', 'Active');
insert into acnh_headwear values(661, 0, 'viking helmet (Brown)', 'orderable', '2100', 'Able Sisters', 'Active');
insert into acnh_headwear values(662, 0, 'viking helmet (Gray)', 'orderable', '2100', 'Able Sisters', 'Active');
insert into acnh_headwear values(663, 0, 'visual-punk wig (Hair Color)', 'orderable', '1400', 'Able Sisters', 'Cool');
insert into acnh_headwear values(664, 0, 'water-egg shell', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_headwear values(665, 0, 'watermelon hat (Red)', 'orderable', '980', 'Able Sisters', 'Cute');
insert into acnh_headwear values(666, 0, 'welding mask (Red)', 'orderable', '1040', 'Able Sisters', 'Active');
insert into acnh_headwear values(667, 0, 'wide-brim straw hat (Beige)', 'orderable', '1320', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(668, 0, 'wide-brim straw hat (White)', 'orderable', '1320', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(669, 0, 'wide-brim straw hat (Black)', 'orderable', '1320', 'Able Sisters', 'Elegant');
insert into acnh_headwear values(670, 0, 'windflower crown', 'unorderable', '480', 'Crafting', 'Cute');
insert into acnh_headwear values(671, 0, 'wizard''s cap (Purple)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_headwear values(672, 0, 'wizard''s cap (Blue)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_headwear values(673, 0, 'wood-egg shell', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_headwear values(674, 0, 'wrestling mask (Blue)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(675, 0, 'wrestling mask (Red)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(676, 0, 'wrestling mask (Green)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(677, 0, 'wrestling mask (Pink)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(678, 0, 'wrestling mask (Black)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(679, 0, 'wrestling mask (Yellow)', 'orderable', '1120', 'Able Sisters', 'Active');
insert into acnh_headwear values(680, 0, 'zap helmet (White)', 'orderable', '1600', 'Able Sisters', 'Active');
insert into acnh_headwear values(681, 0, 'zap helmet (Pink)', 'orderable', '1600', 'Able Sisters', 'Active');
insert into acnh_headwear values(682, 0, 'zap helmet (Blue)', 'orderable', '1600', 'Able Sisters', 'Active');
insert into acnh_headwear values(683, 0, 'zap helmet (Green)', 'orderable', '1600', 'Able Sisters', 'Active');
insert into acnh_headwear values(684, 0, 'zap helmet (Red)', 'orderable', '1600', 'Able Sisters', 'Active');
insert into acnh_headwear values(685, 0, 'zap helmet (Yellow)', 'orderable', '1600', 'Able Sisters', 'Active');
insert into acnh_headwear values(686, 0, 'zap helmet (Black)', 'orderable', '1600', 'Able Sisters', 'Active');
insert into acnh_headwear values(687, 0, 'zap helmet (Silver)', 'orderable', '1600', 'Able Sisters', 'Active');
insert into acnh_headwear values(688, 0, 'zen hair clip (Aqua)', 'orderable', '4300', 'Able Sisters', 'Cute');
insert into acnh_headwear values(689, 0, 'zen hair clip (Dark blue)', 'orderable', '4300', 'Able Sisters', 'Cute');
insert into acnh_headwear values(690, 0, 'zen hair clip (Golden yellow)', 'orderable', '4300', 'Able Sisters', 'Cute');
insert into acnh_headwear values(691, 0, 'zen hair clip (Purple)', 'orderable', '4300', 'Able Sisters', 'Cute');
insert into acnh_headwear values(692, 0, 'zen hair clip (Pink)', 'orderable', '4300', 'Able Sisters', 'Cute');
insert into acnh_headwear values(693, 0, 'zen hair clip (Green)', 'orderable', '4300', 'Able Sisters', 'Cute');
insert into acnh_headwear values(694, 0, 'zen hair clip (Sky blue)', 'orderable', '4300', 'Able Sisters', 'Cute');
insert into acnh_headwear values(695, 0, 'zen hair clip (Red)', 'orderable', '4300', 'Able Sisters', 'Cute');
