drop table if exists acnh_wall_mounted;
create table acnh_wall_mounted ("Index" int primary key, Selected int, Name varchar(63), Status varchar(31), Price varchar(15), "From" varchar(31), Concept1 varchar(31), Concept2 varchar(31), Series varchar(31));
insert into acnh_wall_mounted values(1, 0, 'air conditioner (White)', 'orderable', '63000', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wall_mounted values(2, 0, 'air conditioner (Gray)', 'orderable', '63000', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wall_mounted values(3, 0, 'air conditioner (Black)', 'orderable', '63000', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wall_mounted values(4, 0, 'air conditioner (Pink)', 'orderable', '63000', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wall_mounted values(5, 0, 'air conditioner (Blue)', 'orderable', '63000', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wall_mounted values(6, 0, 'air conditioner (Brown)', 'orderable', '63000', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wall_mounted values(7, 0, 'antique phone (Brown)', 'orderable', '16000', 'Nook''s Cranny', 'living room', 'expensive', 'antique');
insert into acnh_wall_mounted values(8, 0, 'antique phone (Natural)', 'orderable', '16000', 'Nook''s Cranny', 'living room', 'expensive', 'antique');
insert into acnh_wall_mounted values(9, 0, 'antique phone (Black)', 'orderable', '16000', 'Nook''s Cranny', 'living room', 'expensive', 'antique');
insert into acnh_wall_mounted values(10, 0, 'autograph cards (Signature)', 'orderable', '1400', 'Nook''s Cranny', 'school', 'den', 'None');
insert into acnh_wall_mounted values(11, 0, 'autograph cards (Handprints)', 'orderable', '1400', 'Nook''s Cranny', 'school', 'den', 'None');
insert into acnh_wall_mounted values(12, 0, 'autograph cards (Illustration)', 'orderable', '1400', 'Nook''s Cranny', 'school', 'den', 'None');
insert into acnh_wall_mounted values(13, 0, 'autograph cards (Words of wisdom)', 'orderable', '1400', 'Nook''s Cranny', 'school', 'den', 'None');
insert into acnh_wall_mounted values(14, 0, 'bamboo wall decoration', 'unorderable', '160', 'Crafting', 'zen-style', 'None', 'bamboo');
insert into acnh_wall_mounted values(15, 0, 'bathroom towel rack (Silver)', 'orderable', '1400', 'Nook''s Cranny', 'bathroom', 'None', 'None');
insert into acnh_wall_mounted values(16, 0, 'bathroom towel rack (Gold)', 'orderable', '1400', 'Nook''s Cranny', 'bathroom', 'None', 'None');
insert into acnh_wall_mounted values(17, 0, 'bathroom towel rack (Copper)', 'orderable', '1400', 'Nook''s Cranny', 'bathroom', 'None', 'None');
insert into acnh_wall_mounted values(18, 0, 'bathroom towel rack (Black)', 'orderable', '1400', 'Nook''s Cranny', 'bathroom', 'None', 'None');
insert into acnh_wall_mounted values(19, 0, 'blue rose wreath', 'unorderable', '20000', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(20, 0, 'bone doorplate', 'unorderable', '360', 'Crafting', 'child''s room', 'living room', 'None');
insert into acnh_wall_mounted values(21, 0, 'boomerang', 'unorderable', '360', 'Crafting', 'child''s room', 'None', 'None');
insert into acnh_wall_mounted values(22, 0, 'breaker', 'orderable', '820', 'Nook''s Cranny', 'garage', 'facility', 'None');
insert into acnh_wall_mounted values(23, 0, 'bronze HHA plaque', 'unorderable', '400', 'HHA', 'living room', 'expensive', 'None');
insert into acnh_wall_mounted values(24, 0, 'broom and dustpan (Natural)', 'orderable', '910', 'Nook''s Cranny', 'school', 'None', 'None');
insert into acnh_wall_mounted values(25, 0, 'broom and dustpan (White)', 'orderable', '910', 'Nook''s Cranny', 'school', 'None', 'None');
insert into acnh_wall_mounted values(26, 0, 'broom and dustpan (Dark brown)', 'orderable', '910', 'Nook''s Cranny', 'school', 'None', 'None');
insert into acnh_wall_mounted values(27, 0, 'broom and dustpan (Colorful)', 'orderable', '910', 'Nook''s Cranny', 'school', 'None', 'None');
insert into acnh_wall_mounted values(28, 0, 'Bunny Day glowy garland', 'unorderable', '2400', 'Crafting', 'fancy', 'party', 'Bunny Day');
insert into acnh_wall_mounted values(29, 0, 'Bunny Day wall clock', 'unorderable', '1200', 'Crafting', 'fancy', 'None', 'Bunny Day');
insert into acnh_wall_mounted values(30, 0, 'Bunny Day wreath', 'unorderable', '2400', 'Crafting', 'fancy', 'party', 'Bunny Day');
insert into acnh_wall_mounted values(31, 0, 'butterfly-fish model', 'orderable', '1300', 'Nook''s Cranny', 'ocean', 'facility', 'None');
insert into acnh_wall_mounted values(32, 0, 'cherry lamp', 'unorderable', '2400', 'Crafting', 'fancy', 'None', 'fruits');
insert into acnh_wall_mounted values(33, 0, 'cherry-blossom clock', 'unorderable', '2750', 'Crafting', 'fancy', 'None', 'cherry blossoms');
insert into acnh_wall_mounted values(34, 0, 'chic cosmos wreath', 'unorderable', '4800', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(35, 0, 'chic windflower wreath', 'unorderable', '4800', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(36, 0, 'coconut wall planter', 'unorderable', '600', 'Crafting', 'ocean', 'living room', 'None');
insert into acnh_wall_mounted values(37, 0, 'cool hyacinth wreath', 'unorderable', '1440', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(38, 0, 'cool pansy wreath', 'unorderable', '4800', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(39, 0, 'cool windflower wreath', 'unorderable', '1200', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(40, 0, 'corkboard (Natural)', 'orderable', '1400', 'Nook''s Cranny', 'school', 'office', 'None');
insert into acnh_wall_mounted values(41, 0, 'corkboard (White)', 'orderable', '1400', 'Nook''s Cranny', 'school', 'office', 'None');
insert into acnh_wall_mounted values(42, 0, 'corkboard (Blue)', 'orderable', '1400', 'Nook''s Cranny', 'school', 'office', 'None');
insert into acnh_wall_mounted values(43, 0, 'cosmos wreath', 'unorderable', '720', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(44, 0, 'crest doorplate', 'unorderable', '3000', 'Crafting', 'expensive', 'None', 'None');
insert into acnh_wall_mounted values(45, 0, 'cuckoo clock (Natural)', 'orderable', '3200', 'Nook''s Cranny', 'living room', 'child''s room', 'None');
insert into acnh_wall_mounted values(46, 0, 'cuckoo clock (Green)', 'orderable', '3200', 'Nook''s Cranny', 'living room', 'child''s room', 'None');
insert into acnh_wall_mounted values(47, 0, 'cuckoo clock (Blue)', 'orderable', '3200', 'Nook''s Cranny', 'living room', 'child''s room', 'None');
insert into acnh_wall_mounted values(48, 0, 'cuckoo clock (Yellow)', 'orderable', '3200', 'Nook''s Cranny', 'living room', 'child''s room', 'None');
insert into acnh_wall_mounted values(49, 0, 'cuckoo clock (Red)', 'orderable', '3200', 'Nook''s Cranny', 'living room', 'child''s room', 'None');
insert into acnh_wall_mounted values(50, 0, 'cuckoo clock (White)', 'orderable', '3200', 'Nook''s Cranny', 'living room', 'child''s room', 'None');
insert into acnh_wall_mounted values(51, 0, 'cuckoo clock (Black)', 'orderable', '3200', 'Nook''s Cranny', 'living room', 'child''s room', 'None');
insert into acnh_wall_mounted values(52, 0, 'cute wall-mounted clock (White)', 'orderable', '1200', 'Nook''s Cranny', 'fancy', 'None', 'cute');
insert into acnh_wall_mounted values(53, 0, 'cute wall-mounted clock (Sky blue)', 'orderable', '1200', 'Nook''s Cranny', 'fancy', 'None', 'cute');
insert into acnh_wall_mounted values(54, 0, 'cute wall-mounted clock (Yellow)', 'orderable', '1200', 'Nook''s Cranny', 'fancy', 'None', 'cute');
insert into acnh_wall_mounted values(55, 0, 'cute wall-mounted clock (Red)', 'orderable', '1200', 'Nook''s Cranny', 'fancy', 'None', 'cute');
insert into acnh_wall_mounted values(56, 0, 'cute wall-mounted clock (Blue)', 'orderable', '1200', 'Nook''s Cranny', 'fancy', 'None', 'cute');
insert into acnh_wall_mounted values(57, 0, 'dark lily wreath', 'unorderable', '1600', 'Crafting', 'fancy', 'horror', 'flowers');
insert into acnh_wall_mounted values(58, 0, 'dark rose wreath', 'unorderable', '4320', 'Crafting', 'fancy', 'horror', 'flowers');
insert into acnh_wall_mounted values(59, 0, 'dark tulip wreath', 'unorderable', '1600', 'Crafting', 'fancy', 'horror', 'flowers');
insert into acnh_wall_mounted values(60, 0, 'deer decoration', 'unorderable', '960', 'Crafting', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(61, 0, 'diner neon clock (Red)', 'orderable', '1500', 'Nook''s Cranny', 'shop', 'None', 'diner');
insert into acnh_wall_mounted values(62, 0, 'diner neon clock (Blue)', 'orderable', '1500', 'Nook''s Cranny', 'shop', 'None', 'diner');
insert into acnh_wall_mounted values(63, 0, 'diner neon clock (Yellow)', 'orderable', '1500', 'Nook''s Cranny', 'shop', 'None', 'diner');
insert into acnh_wall_mounted values(64, 0, 'diner neon clock (Aquamarine)', 'orderable', '1500', 'Nook''s Cranny', 'shop', 'None', 'diner');
insert into acnh_wall_mounted values(65, 0, 'diner neon clock (Pink)', 'orderable', '1500', 'Nook''s Cranny', 'shop', 'None', 'diner');
insert into acnh_wall_mounted values(66, 0, 'diner neon clock (Cream)', 'orderable', '1500', 'Nook''s Cranny', 'shop', 'None', 'diner');
insert into acnh_wall_mounted values(67, 0, 'diner neon clock (Purple)', 'orderable', '1500', 'Nook''s Cranny', 'shop', 'None', 'diner');
insert into acnh_wall_mounted values(68, 0, 'double-sided wall clock (Black)', 'orderable', '1100', 'Nook''s Cranny', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(69, 0, 'double-sided wall clock (White)', 'orderable', '1100', 'Nook''s Cranny', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(70, 0, 'double-sided wall clock (Silver)', 'orderable', '1100', 'Nook''s Cranny', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(71, 0, 'double-sided wall clock (Green)', 'orderable', '1100', 'Nook''s Cranny', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(72, 0, 'double-sided wall clock (Red)', 'orderable', '1100', 'Nook''s Cranny', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(73, 0, 'double-sided wall clock (Yellow)', 'orderable', '1100', 'Nook''s Cranny', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(74, 0, 'exit sign (←)', 'orderable', '810', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wall_mounted values(75, 0, 'exit sign (→)', 'orderable', '810', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wall_mounted values(76, 0, 'exit sign (Red exit)', 'orderable', '810', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wall_mounted values(77, 0, 'exit sign (← →)', 'orderable', '810', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wall_mounted values(78, 0, 'fancy lily wreath', 'unorderable', '1200', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(79, 0, 'fancy mum wreath', 'unorderable', '1200', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(80, 0, 'fancy rose wreath', 'unorderable', '1200', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(81, 0, 'fish doorplate (Light blue)', 'unorderable', '90', 'Fishing Tourney', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(82, 0, 'fish doorplate (Red)', 'unorderable', '90', 'Fishing Tourney', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(83, 0, 'fish doorplate (Orange)', 'unorderable', '90', 'Fishing Tourney', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(84, 0, 'fish doorplate (Yellow)', 'unorderable', '90', 'Fishing Tourney', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(85, 0, 'fish doorplate (Green)', 'unorderable', '90', 'Fishing Tourney', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(86, 0, 'fish doorplate (Blue)', 'unorderable', '90', 'Fishing Tourney', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(87, 0, 'fish doorplate (Black)', 'unorderable', '90', 'Fishing Tourney', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(88, 0, 'fish doorplate (Gray)', 'unorderable', '90', 'Fishing Tourney', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(89, 0, 'fish print (Giant trevally)', 'unorderable', '700', 'Fishing Tourney', 'ocean', 'living room', 'None');
insert into acnh_wall_mounted values(90, 0, 'fish print (Red snapper)', 'unorderable', '700', 'Fishing Tourney', 'ocean', 'living room', 'None');
insert into acnh_wall_mounted values(91, 0, 'fish print (Blue marlin)', 'unorderable', '700', 'Fishing Tourney', 'ocean', 'living room', 'None');
insert into acnh_wall_mounted values(92, 0, 'fish print (Squid)', 'unorderable', '700', 'Fishing Tourney', 'ocean', 'living room', 'None');
insert into acnh_wall_mounted values(93, 0, 'fish print (Black bass)', 'unorderable', '700', 'Fishing Tourney', 'ocean', 'living room', 'None');
insert into acnh_wall_mounted values(94, 0, 'fish print (Carp)', 'unorderable', '700', 'Fishing Tourney', 'ocean', 'living room', 'None');
insert into acnh_wall_mounted values(95, 0, 'fish print (Giant snakehead)', 'unorderable', '700', 'Fishing Tourney', 'ocean', 'living room', 'None');
insert into acnh_wall_mounted values(96, 0, 'fishing-boat flag', 'unorderable', '2200', '2x1.5 ', '1.0.0', 'ocean', 'None');
insert into acnh_wall_mounted values(97, 0, 'fishing-boat flag', 'unorderable', '2200', '2x1.5 ', '1.0.0', 'ocean', 'None');
insert into acnh_wall_mounted values(98, 0, 'fishing-boat flag', 'unorderable', '2200', '2x1.5 ', '1.0.0', 'ocean', 'None');
insert into acnh_wall_mounted values(99, 0, 'fishing-boat flag', 'unorderable', '2200', '2x1.5 ', '1.0.0', 'ocean', 'None');
insert into acnh_wall_mounted values(100, 0, 'floral swag', 'unorderable', '200', 'Crafting', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(101, 0, 'formal paper (Brown)', 'orderable', '620', 'Nook''s Cranny', 'school', 'den', 'None');
insert into acnh_wall_mounted values(102, 0, 'formal paper (Light brown)', 'orderable', '620', 'Nook''s Cranny', 'school', 'den', 'None');
insert into acnh_wall_mounted values(103, 0, 'formal paper (Dark brown)', 'orderable', '620', 'Nook''s Cranny', 'school', 'den', 'None');
insert into acnh_wall_mounted values(104, 0, 'fossil doorplate', 'unorderable', '500', 'Crafting', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(105, 0, 'fruit wreath', 'unorderable', '2000', 'Crafting', 'fancy', 'None', 'fruits');
insert into acnh_wall_mounted values(106, 0, 'gears (Silver)', 'orderable', '1500', 'Nook''s Cranny', 'facility', 'garage', 'None');
insert into acnh_wall_mounted values(107, 0, 'gears (Copper)', 'orderable', '1500', 'Nook''s Cranny', 'facility', 'garage', 'None');
insert into acnh_wall_mounted values(108, 0, 'gears (Black)', 'orderable', '1500', 'Nook''s Cranny', 'facility', 'garage', 'None');
insert into acnh_wall_mounted values(109, 0, 'gears (Colorful)', 'orderable', '1500', 'Nook''s Cranny', 'facility', 'garage', 'None');
insert into acnh_wall_mounted values(110, 0, 'gears (Wooden)', 'orderable', '1500', 'Nook''s Cranny', 'facility', 'garage', 'None');
insert into acnh_wall_mounted values(111, 0, 'gold HHA plaque', 'unorderable', '450', 'HHA', 'living room', 'expensive', 'None');
insert into acnh_wall_mounted values(112, 0, 'gold rose wreath', 'unorderable', '20000', 'Crafting', 'expensive', 'None', 'flowers');
insert into acnh_wall_mounted values(113, 0, 'golden gears', 'unorderable', '11125', 'Crafting', 'expensive', 'None', 'golden');
insert into acnh_wall_mounted values(114, 0, 'grasshopper-head model', 'orderable', '1400', 'Nook''s Cranny', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(115, 0, 'hanging scroll (Green)', 'orderable', '140000', 'Nook''s Cranny', 'zen-style', 'expensive', 'None');
insert into acnh_wall_mounted values(116, 0, 'hanging scroll (Brown)', 'orderable', '140000', 'Nook''s Cranny', 'zen-style', 'expensive', 'None');
insert into acnh_wall_mounted values(117, 0, 'hanging scroll (Pink)', 'orderable', '140000', 'Nook''s Cranny', 'zen-style', 'expensive', 'None');
insert into acnh_wall_mounted values(118, 0, 'hanging scroll (Blue)', 'orderable', '140000', 'Nook''s Cranny', 'zen-style', 'expensive', 'None');
insert into acnh_wall_mounted values(119, 0, 'hanging scroll (Purple)', 'orderable', '140000', 'Nook''s Cranny', 'zen-style', 'expensive', 'None');
insert into acnh_wall_mounted values(120, 0, 'hanging terrarium', 'unorderable', '3240', 'Crafting', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(121, 0, 'heart doorplate (Pink)', 'orderable', '600', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wall_mounted values(122, 0, 'heart doorplate (Blue)', 'orderable', '600', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wall_mounted values(123, 0, 'heart doorplate (Monotone)', 'orderable', '600', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wall_mounted values(124, 0, 'heart doorplate (Light blue)', 'orderable', '600', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wall_mounted values(125, 0, 'heart doorplate (Green)', 'orderable', '600', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wall_mounted values(126, 0, 'heart doorplate (Orange)', 'orderable', '600', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wall_mounted values(127, 0, 'heart doorplate (Red)', 'orderable', '600', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wall_mounted values(128, 0, 'heart doorplate (Purple)', 'orderable', '600', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wall_mounted values(129, 0, 'HHA pennant', 'unorderable', '375', 'HHA', 'living room', 'expensive', 'None');
insert into acnh_wall_mounted values(130, 0, 'hyacinth wreath', 'unorderable', '720', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(131, 0, 'imperial decorative shelves (Red)', 'orderable', '8500', 'Nook''s Cranny', 'zen-style', 'None', 'zen');
insert into acnh_wall_mounted values(132, 0, 'imperial decorative shelves (Blue)', 'orderable', '8500', 'Nook''s Cranny', 'zen-style', 'None', 'zen');
insert into acnh_wall_mounted values(133, 0, 'imperial decorative shelves (Brown)', 'orderable', '8500', 'Nook''s Cranny', 'zen-style', 'None', 'zen');
insert into acnh_wall_mounted values(134, 0, 'imperial decorative shelves (Black)', 'orderable', '8500', 'Nook''s Cranny', 'zen-style', 'None', 'zen');
insert into acnh_wall_mounted values(135, 0, 'imperial dining lantern (Gold)', 'orderable', '19000', 'Nook''s Cranny', 'shop', 'zen-style', 'None');
insert into acnh_wall_mounted values(136, 0, 'imperial dining lantern (Black)', 'orderable', '19000', 'Nook''s Cranny', 'shop', 'zen-style', 'None');
insert into acnh_wall_mounted values(137, 0, 'imperial dining lantern (Blue)', 'orderable', '19000', 'Nook''s Cranny', 'shop', 'zen-style', 'None');
insert into acnh_wall_mounted values(138, 0, 'imperial dining lantern (Red)', 'orderable', '19000', 'Nook''s Cranny', 'shop', 'zen-style', 'None');
insert into acnh_wall_mounted values(139, 0, 'intercom monitor', 'orderable', '860', 'Nook''s Cranny', 'living room', 'facility', 'None');
insert into acnh_wall_mounted values(140, 0, 'iron doorplate', 'unorderable', '1500', 'Crafting', 'living room', 'None', 'iron');
insert into acnh_wall_mounted values(141, 0, 'iron wall lamp', 'unorderable', '3400', 'Crafting', 'living room', 'garage', 'iron');
insert into acnh_wall_mounted values(142, 0, 'iron wall rack', 'unorderable', '2450', 'Crafting', 'living room', 'garage', 'iron');
insert into acnh_wall_mounted values(143, 0, 'ironwood clock', 'unorderable', '1740', 'Crafting', 'living room', 'None', 'ironwood');
insert into acnh_wall_mounted values(144, 0, 'key holder', 'unorderable', '1110', 'Crafting', 'garage', 'living room', 'None');
insert into acnh_wall_mounted values(145, 0, 'Leo sculpture', 'unorderable', '21975', 'Crafting', 'expensive', 'None', 'stars');
insert into acnh_wall_mounted values(146, 0, 'lily wreath', 'unorderable', '720', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(147, 0, 'log wall-mounted clock', 'unorderable', '990', 'Crafting', 'garden', 'living room', 'log');
insert into acnh_wall_mounted values(148, 0, 'macrame tapestry (White)', 'orderable', '840', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(149, 0, 'macrame tapestry (Green)', 'orderable', '840', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(150, 0, 'macrame tapestry (Pink)', 'orderable', '840', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(151, 0, 'macrame tapestry (Blue)', 'orderable', '840', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(152, 0, 'magnetic knife rack (Stainless steel)', 'orderable', '1400', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(153, 0, 'magnetic knife rack (Wooden)', 'orderable', '1400', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(154, 0, 'magnetic knife rack (Pop)', 'orderable', '1400', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(155, 0, 'mantis-head model', 'orderable', '1500', 'Nook''s Cranny', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(156, 0, 'mobile (Hot air balloons)', 'orderable', '780', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(157, 0, 'mobile (Sheep)', 'orderable', '780', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(158, 0, 'mobile (Ocean creatures)', 'orderable', '780', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(159, 0, 'mobile (Space)', 'orderable', '780', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(160, 0, 'mobile (Gorgeous)', 'orderable', '780', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_wall_mounted values(161, 0, 'Mom''s art (Still Life)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(162, 0, 'Mom''s art (Street with Trees)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(163, 0, 'Mom''s art (Nostalgia)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(164, 0, 'Mom''s art (Angel)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(165, 0, 'Mom''s art (Sweet Roses)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(166, 0, 'Mom''s art (Field of Flowers)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(167, 0, 'Mom''s art (Dog)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(168, 0, 'Mom''s art (Blooming)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(169, 0, 'Mom''s embroidery (Flowers)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(170, 0, 'Mom''s embroidery (Bird)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(171, 0, 'Mom''s embroidery (Bouquet)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(172, 0, 'Mom''s embroidery (Girl)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(173, 0, 'Mom''s embroidery (Fairy tale)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(174, 0, 'Mom''s embroidery (Trees)', 'unorderable', '88', 'Mom', 'living room', 'fancy', 'motherly');
insert into acnh_wall_mounted values(175, 0, 'mounted black bass', 'orderable', '1300', 'Nook''s Cranny', 'ocean', 'facility', 'None');
insert into acnh_wall_mounted values(176, 0, 'mounted blue marlin', 'orderable', '5000', 'Nook''s Cranny', 'ocean', 'facility', 'None');
insert into acnh_wall_mounted values(177, 0, 'mum wreath', 'unorderable', '720', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(178, 0, 'mushroom wreath', 'unorderable', '1500', 'Crafting', 'garden', 'None', 'mush');
insert into acnh_wall_mounted values(179, 0, 'natural mum wreath', 'unorderable', '4800', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(180, 0, 'orange wall-mounted clock', 'unorderable', '2240', 'Crafting', 'fancy', 'None', 'fruits');
insert into acnh_wall_mounted values(181, 0, 'ornament mobile', 'unorderable', '340', 'Crafting', 'party', 'fancy', 'festive');
insert into acnh_wall_mounted values(182, 0, 'ornament wreath', 'unorderable', '800', 'Crafting', 'fancy', 'None', 'festive');
insert into acnh_wall_mounted values(183, 0, 'pansy wreath', 'unorderable', '720', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(184, 0, 'party garland (Colorful)', 'orderable', '650', 'Nook''s Cranny', 'party', 'fancy', 'None');
insert into acnh_wall_mounted values(185, 0, 'party garland (Pastel)', 'orderable', '650', 'Nook''s Cranny', 'party', 'fancy', 'None');
insert into acnh_wall_mounted values(186, 0, 'party garland (Boating stripes)', 'orderable', '650', 'Nook''s Cranny', 'party', 'fancy', 'None');
insert into acnh_wall_mounted values(187, 0, 'party garland (Orange & black)', 'orderable', '650', 'Nook''s Cranny', 'party', 'fancy', 'None');
insert into acnh_wall_mounted values(188, 0, 'party garland (Pop)', 'orderable', '650', 'Nook''s Cranny', 'party', 'fancy', 'None');
insert into acnh_wall_mounted values(189, 0, 'party garland (Gorgeous)', 'orderable', '650', 'Nook''s Cranny', 'party', 'fancy', 'None');
insert into acnh_wall_mounted values(190, 0, 'paw-print doorplate', 'unorderable', '360', 'Crafting', 'living room', 'fancy', 'None');
insert into acnh_wall_mounted values(191, 0, 'pendulum clock', 'orderable', '1900', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(192, 0, 'pennant (Sports)', 'orderable', '1300', 'Nook''s Cranny', 'shop', 'child''s room', 'None');
insert into acnh_wall_mounted values(193, 0, 'pennant (University)', 'orderable', '1300', 'Nook''s Cranny', 'shop', 'child''s room', 'None');
insert into acnh_wall_mounted values(194, 0, 'pennant (Classic)', 'orderable', '1300', 'Nook''s Cranny', 'shop', 'child''s room', 'None');
insert into acnh_wall_mounted values(195, 0, 'pennant (Sponsor)', 'orderable', '1300', 'Nook''s Cranny', 'shop', 'child''s room', 'None');
insert into acnh_wall_mounted values(196, 0, 'pennant (Souvenir)', 'orderable', '1300', 'Nook''s Cranny', 'shop', 'child''s room', 'None');
insert into acnh_wall_mounted values(197, 0, 'pot rack (Wooden)', 'orderable', '3000', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(198, 0, 'pot rack (Stainless steel)', 'orderable', '3000', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(199, 0, 'pot rack (Pop)', 'orderable', '3000', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(200, 0, 'potted ivy', 'unorderable', '1100', 'Crafting', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(201, 0, 'pretty cosmos wreath', 'unorderable', '1200', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(202, 0, 'pretty tulip wreath', 'unorderable', '2400', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(203, 0, 'purple hyacinth wreath', 'unorderable', '4800', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(204, 0, 'retro radiator', 'orderable', '1300', 'Nook''s Cranny', 'living room', 'school', 'None');
insert into acnh_wall_mounted values(205, 0, 'rose wreath', 'unorderable', '720', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(206, 0, 'Sagittarius arrow', 'unorderable', '21750', 'Crafting', 'expensive', 'None', 'stars');
insert into acnh_wall_mounted values(207, 0, 'shell wreath', 'unorderable', '4720', 'Crafting', 'ocean', 'None', 'shell');
insert into acnh_wall_mounted values(208, 0, 'shower set (Silver)', 'orderable', '1800', 'Nook''s Cranny', 'bathroom', 'None', 'None');
insert into acnh_wall_mounted values(209, 0, 'shower set (Gold)', 'orderable', '1800', 'Nook''s Cranny', 'bathroom', 'None', 'None');
insert into acnh_wall_mounted values(210, 0, 'shower set (Copper)', 'orderable', '1800', 'Nook''s Cranny', 'bathroom', 'None', 'None');
insert into acnh_wall_mounted values(211, 0, 'shower set (Black)', 'orderable', '1800', 'Nook''s Cranny', 'bathroom', 'None', 'None');
insert into acnh_wall_mounted values(212, 0, 'silver HHA plaque', 'unorderable', '425', 'HHA', 'living room', 'expensive', 'None');
insert into acnh_wall_mounted values(213, 0, 'skull doorplate (Brown)', 'orderable', '540', 'Nook''s Cranny', 'horror', 'None', 'None');
insert into acnh_wall_mounted values(214, 0, 'skull doorplate (White)', 'orderable', '540', 'Nook''s Cranny', 'horror', 'None', 'None');
insert into acnh_wall_mounted values(215, 0, 'snazzy pansy wreath', 'unorderable', '1200', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(216, 0, 'snowflake wreath', 'unorderable', '1600', 'Crafting', 'freezing cold', 'fancy', 'None');
insert into acnh_wall_mounted values(217, 0, 'spider doorplate (Black)', 'unorderable', '90', 'Bug-Off', 'child''s room', 'horror', 'None');
insert into acnh_wall_mounted values(218, 0, 'spider doorplate (Yellow)', 'unorderable', '90', 'Bug-Off', 'child''s room', 'horror', 'None');
insert into acnh_wall_mounted values(219, 0, 'spider doorplate (Green)', 'unorderable', '90', 'Bug-Off', 'child''s room', 'horror', 'None');
insert into acnh_wall_mounted values(220, 0, 'spider doorplate (Pink)', 'unorderable', '90', 'Bug-Off', 'child''s room', 'horror', 'None');
insert into acnh_wall_mounted values(221, 0, 'spider doorplate (Purple)', 'unorderable', '90', 'Bug-Off', 'child''s room', 'horror', 'None');
insert into acnh_wall_mounted values(222, 0, 'spider doorplate (Red)', 'unorderable', '90', 'Bug-Off', 'child''s room', 'horror', 'None');
insert into acnh_wall_mounted values(223, 0, 'spider doorplate (Gray)', 'unorderable', '90', 'Bug-Off', 'child''s room', 'horror', 'None');
insert into acnh_wall_mounted values(224, 0, 'spider doorplate (Blue)', 'unorderable', '90', 'Bug-Off', 'child''s room', 'horror', 'None');
insert into acnh_wall_mounted values(225, 0, 'spider web', 'unorderable', '25', 'Bug-Off', 'facility', 'horror', 'None');
insert into acnh_wall_mounted values(226, 0, 'starry garland', 'unorderable', '5000', 'Crafting', 'space', 'fancy', 'stars');
insert into acnh_wall_mounted values(227, 0, 'studio wall spotlight (White)', 'orderable', '2300', 'Nook''s Cranny', 'facility', 'concert', 'None');
insert into acnh_wall_mounted values(228, 0, 'studio wall spotlight (Yellow)', 'orderable', '2300', 'Nook''s Cranny', 'facility', 'concert', 'None');
insert into acnh_wall_mounted values(229, 0, 'studio wall spotlight (Orange)', 'orderable', '2300', 'Nook''s Cranny', 'facility', 'concert', 'None');
insert into acnh_wall_mounted values(230, 0, 'studio wall spotlight (Red)', 'orderable', '2300', 'Nook''s Cranny', 'facility', 'concert', 'None');
insert into acnh_wall_mounted values(231, 0, 'studio wall spotlight (Pink)', 'orderable', '2300', 'Nook''s Cranny', 'facility', 'concert', 'None');
insert into acnh_wall_mounted values(232, 0, 'studio wall spotlight (Purple)', 'orderable', '2300', 'Nook''s Cranny', 'facility', 'concert', 'None');
insert into acnh_wall_mounted values(233, 0, 'studio wall spotlight (Blue)', 'orderable', '2300', 'Nook''s Cranny', 'facility', 'concert', 'None');
insert into acnh_wall_mounted values(234, 0, 'studio wall spotlight (Green)', 'orderable', '2300', 'Nook''s Cranny', 'facility', 'concert', 'None');
insert into acnh_wall_mounted values(235, 0, 'surveillance camera', 'orderable', '1000', 'Nook''s Cranny', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(236, 0, 'switch (Gray)', 'orderable', '340', 'Nook''s Cranny', 'living room', 'facility', 'None');
insert into acnh_wall_mounted values(237, 0, 'switch (Brown)', 'orderable', '340', 'Nook''s Cranny', 'living room', 'facility', 'None');
insert into acnh_wall_mounted values(238, 0, 'switch (White)', 'orderable', '340', 'Nook''s Cranny', 'living room', 'facility', 'None');
insert into acnh_wall_mounted values(239, 0, 'switch (Wood grain)', 'orderable', '340', 'Nook''s Cranny', 'living room', 'facility', 'None');
insert into acnh_wall_mounted values(240, 0, 'tapestry (Geometric pattern)', 'orderable', '880', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(241, 0, 'tapestry (Animal)', 'orderable', '880', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(242, 0, 'tapestry (Floral)', 'orderable', '880', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(243, 0, 'tapestry (Fairy tale)', 'orderable', '880', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(244, 0, 'tapestry (Bird)', 'orderable', '880', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(245, 0, 'tapestry (Snow)', 'orderable', '880', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(246, 0, 'throwback wall clock (Yellow)', 'orderable', '4200', 'Nook''s Cranny', 'child''s room', 'None', 'throwback');
insert into acnh_wall_mounted values(247, 0, 'throwback wall clock (Red)', 'orderable', '4200', 'Nook''s Cranny', 'child''s room', 'None', 'throwback');
insert into acnh_wall_mounted values(248, 0, 'throwback wall clock (Green)', 'orderable', '4200', 'Nook''s Cranny', 'child''s room', 'None', 'throwback');
insert into acnh_wall_mounted values(249, 0, 'throwback wall clock (Blue)', 'orderable', '4200', 'Nook''s Cranny', 'child''s room', 'None', 'throwback');
insert into acnh_wall_mounted values(250, 0, 'throwback wall clock (White)', 'orderable', '4200', 'Nook''s Cranny', 'child''s room', 'None', 'throwback');
insert into acnh_wall_mounted values(251, 0, 'throwback wall clock (Gray)', 'orderable', '4200', 'Nook''s Cranny', 'child''s room', 'None', 'throwback');
insert into acnh_wall_mounted values(252, 0, 'throwback wall clock (Purple)', 'orderable', '4200', 'Nook''s Cranny', 'child''s room', 'None', 'throwback');
insert into acnh_wall_mounted values(253, 0, 'timber doorplate', 'unorderable', '400', 'Crafting', 'living room', 'child''s room', 'None');
insert into acnh_wall_mounted values(254, 0, 'tree branch wreath', 'unorderable', '100', 'Crafting', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(255, 0, 'tree''s bounty mobile', 'unorderable', '2030', 'Crafting', 'fancy', 'None', 'tree''s bounty or leaves ');
insert into acnh_wall_mounted values(256, 0, 'tulip wreath', 'unorderable', '720', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(257, 0, 'ventilation fan (White)', 'orderable', '1200', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(258, 0, 'ventilation fan (Pink)', 'orderable', '1200', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(259, 0, 'ventilation fan (Blue)', 'orderable', '1200', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(260, 0, 'ventilation fan (Green)', 'orderable', '1200', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(261, 0, 'ventilation fan (Orange)', 'orderable', '1200', 'Nook''s Cranny', 'kitchen', 'shop', 'None');
insert into acnh_wall_mounted values(262, 0, 'wall clock (Silver)', 'orderable', '690', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(263, 0, 'wall clock (White)', 'orderable', '690', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(264, 0, 'wall clock (Black)', 'orderable', '690', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(265, 0, 'wall clock (Red)', 'orderable', '690', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(266, 0, 'wall clock (Blue)', 'orderable', '690', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(267, 0, 'wall fan (Green)', 'orderable', '1400', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(268, 0, 'wall fan (Blue)', 'orderable', '1400', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(269, 0, 'wall fan (Red)', 'orderable', '1400', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(270, 0, 'wall fan (Yellow)', 'orderable', '1400', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(271, 0, 'wall fan (White)', 'orderable', '1400', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(272, 0, 'wall fan (Black)', 'orderable', '1400', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(273, 0, 'wall fan (Silver)', 'orderable', '1400', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(274, 0, 'wall fan (Brown)', 'orderable', '1400', 'Nook''s Cranny', 'office', 'school', 'None');
insert into acnh_wall_mounted values(275, 0, 'wall-mounted candle (Gold)', 'orderable', '800', 'Nook''s Cranny', 'horror', 'None', 'None');
insert into acnh_wall_mounted values(276, 0, 'wall-mounted candle (Silver)', 'orderable', '800', 'Nook''s Cranny', 'horror', 'None', 'None');
insert into acnh_wall_mounted values(277, 0, 'wall-mounted candle (Copper)', 'orderable', '800', 'Nook''s Cranny', 'horror', 'None', 'None');
insert into acnh_wall_mounted values(278, 0, 'wall-mounted candle (Black)', 'orderable', '800', 'Nook''s Cranny', 'horror', 'None', 'None');
insert into acnh_wall_mounted values(279, 0, 'wall-mounted candle (White)', 'orderable', '800', 'Nook''s Cranny', 'horror', 'None', 'None');
insert into acnh_wall_mounted values(280, 0, 'wall-mounted phone (White)', 'orderable', '1300', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(281, 0, 'wall-mounted phone (Black)', 'orderable', '1300', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(282, 0, 'wall-mounted phone (Silver)', 'orderable', '1300', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(283, 0, 'wall-mounted phone (Gray)', 'orderable', '1300', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(284, 0, 'wall-mounted phone (Red)', 'orderable', '1300', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(285, 0, 'wall-mounted phone (Blue)', 'orderable', '1300', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(286, 0, 'wall-mounted tool board (White)', 'orderable', '1500', 'Nook''s Cranny', 'garage', 'None', 'None');
insert into acnh_wall_mounted values(287, 0, 'wall-mounted tool board (Camel)', 'orderable', '1500', 'Nook''s Cranny', 'garage', 'None', 'None');
insert into acnh_wall_mounted values(288, 0, 'wall-mounted tool board (Yellow)', 'orderable', '1500', 'Nook''s Cranny', 'garage', 'None', 'None');
insert into acnh_wall_mounted values(289, 0, 'wall-mounted tool board (Red)', 'orderable', '1500', 'Nook''s Cranny', 'garage', 'None', 'None');
insert into acnh_wall_mounted values(290, 0, 'wall-mounted tool board (Blue)', 'orderable', '1500', 'Nook''s Cranny', 'garage', 'None', 'None');
insert into acnh_wall_mounted values(291, 0, 'wall-mounted tool board (Black)', 'orderable', '1500', 'Nook''s Cranny', 'garage', 'None', 'None');
insert into acnh_wall_mounted values(292, 0, 'wall-mounted TV (20 in.) (Black)', 'orderable', '8900', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(293, 0, 'wall-mounted TV (20 in.) (White)', 'orderable', '8900', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(294, 0, 'wall-mounted TV (20 in.) (Silver)', 'orderable', '8900', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(295, 0, 'wall-mounted TV (20 in.) (Red)', 'orderable', '8900', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(296, 0, 'wall-mounted TV (20 in.) (Yellow)', 'orderable', '8900', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(297, 0, 'wall-mounted TV (20 in.) (Blue)', 'orderable', '8900', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(298, 0, 'wall-mounted TV (20 in.) (Pink)', 'orderable', '8900', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(299, 0, 'wall-mounted TV (20 in.) (Light blue)', 'orderable', '8900', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(300, 0, 'wall-mounted TV (50 in.) (Black)', 'orderable', '22000', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(301, 0, 'wall-mounted TV (50 in.) (White)', 'orderable', '22000', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(302, 0, 'wall-mounted TV (50 in.) (Silver)', 'orderable', '22000', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(303, 0, 'wall-mounted TV (50 in.) (Red)', 'orderable', '22000', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(304, 0, 'wall-mounted TV (50 in.) (Blue)', 'orderable', '22000', 'Nook''s Cranny', 'living room', 'None', 'None');
insert into acnh_wall_mounted values(305, 0, 'wasp-head model', 'orderable', '2500', 'Nook''s Cranny', 'facility', 'None', 'None');
insert into acnh_wall_mounted values(306, 0, 'windflower wreath', 'unorderable', '720', 'Crafting', 'fancy', 'None', 'flowers');
insert into acnh_wall_mounted values(307, 0, 'wooden-block wall clock', 'unorderable', '1350', 'Crafting', 'child''s room', 'None', 'wooden block');
insert into acnh_wall_mounted values(308, 0, 'wooden-plank sign', 'unorderable', '600', 'Crafting', 'zen-style', 'None', 'None');
insert into acnh_wall_mounted values(309, 0, 'writing poster (Alphabet)', 'orderable', '400', 'Nook''s Cranny', 'child''s room', 'school', 'None');
insert into acnh_wall_mounted values(310, 0, 'writing poster (Multiplication tables)', 'orderable', '400', 'Nook''s Cranny', 'child''s room', 'school', 'None');
insert into acnh_wall_mounted values(311, 0, 'writing poster (Periodic table)', 'orderable', '400', 'Nook''s Cranny', 'child''s room', 'school', 'None');
insert into acnh_wall_mounted values(312, 0, 'writing poster (Constellations)', 'orderable', '400', 'Nook''s Cranny', 'child''s room', 'school', 'None');
