drop table if exists acnh_wallpaper;
create table acnh_wallpaper ("Index" int primary key, Selected int, Name varchar(63), Status varchar(31), Price varchar(15), "From" varchar(31), Concept1 varchar(31), Concept2 varchar(31), Series varchar(31));
insert into acnh_wallpaper values(1, 0, 'abstract wall', 'orderable', '3000', 'Nook''s Cranny', 'shop', 'facility', 'None');
insert into acnh_wallpaper values(2, 0, 'ancient wall', 'unorderable', '750', 'Saharah', 'folk art', 'horror', 'None');
insert into acnh_wallpaper values(3, 0, 'apple wall', 'unorderable', '4000', 'Crafting', 'fancy', 'child''s room', 'fruits');
insert into acnh_wallpaper values(4, 0, 'aqua tile wall', 'orderable', '1420', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(5, 0, 'arched-window wall', 'orderable', '2150', 'Nook''s Cranny', 'shop', 'expensive', 'None');
insert into acnh_wallpaper values(6, 0, 'autumn wall', 'unorderable', '4700', 'Crafting', 'garden', 'None', 'tree''s bounty or leaves ');
insert into acnh_wallpaper values(7, 0, 'backyard-fence wall', 'unorderable', '750', 'Saharah', 'garden', 'None', 'None');
insert into acnh_wallpaper values(8, 0, 'bamboo wall', 'unorderable', '2400', 'Crafting', 'zen-style', 'None', 'bamboo');
insert into acnh_wallpaper values(9, 0, 'bamboo-grove wall', 'unorderable', '4300', 'Crafting', 'zen-style', 'None', 'bamboo');
insert into acnh_wallpaper values(10, 0, 'bamboo-screen wall', 'orderable', '1770', 'Nook''s Cranny', 'zen-style', 'None', 'None');
insert into acnh_wallpaper values(11, 0, 'bank-vault wall', 'unorderable', '750', 'Saharah', 'facility', 'expensive', 'None');
insert into acnh_wallpaper values(12, 0, 'basic wall', 'orderable', '600', 'Nook''s Cranny', 'office', 'facility', 'None');
insert into acnh_wallpaper values(13, 0, 'beaded-curtain wall', 'orderable', '1720', 'Nook''s Cranny', 'shop', 'kitchen', 'None');
insert into acnh_wallpaper values(14, 0, 'beige art-deco wall', 'orderable', '2780', 'Nook''s Cranny', 'child''s room', 'living room', 'None');
insert into acnh_wallpaper values(15, 0, 'beige blossoming wall', 'orderable', '1760', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(16, 0, 'beige desert-tile wall', 'orderable', '2440', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(17, 0, 'black botanical-tile wall', 'orderable', '1240', 'Nook''s Cranny', 'facility', 'expensive', 'None');
insert into acnh_wallpaper values(18, 0, 'black hallway wall', 'orderable', '2000', 'Nook''s Cranny', 'facility', 'music', 'None');
insert into acnh_wallpaper values(19, 0, 'black perforated-board wall', 'orderable', '1180', 'Nook''s Cranny', 'music', 'facility', 'None');
insert into acnh_wallpaper values(20, 0, 'black two-toned tile wall', 'orderable', '1850', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(21, 0, 'black-brick wall', 'orderable', '1000', 'Nook''s Cranny', 'facility', 'shop', 'None');
insert into acnh_wallpaper values(22, 0, 'black-crown wall', 'orderable', '2350', 'Nook''s Cranny', 'expensive', 'None', 'None');
insert into acnh_wallpaper values(23, 0, 'blackboard wall', 'unorderable', '750', 'Saharah', 'shop', 'school', 'None');
insert into acnh_wallpaper values(24, 0, 'blue blossoming wall', 'orderable', '1760', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(25, 0, 'blue camo wall', 'orderable', '1150', 'Nook''s Cranny', 'party', 'child''s room', 'None');
insert into acnh_wallpaper values(26, 0, 'blue delicate-blooms wall', 'orderable', '1900', 'Nook''s Cranny', 'expensive', 'living room', 'None');
insert into acnh_wallpaper values(27, 0, 'blue desert-tile wall', 'orderable', '2440', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(28, 0, 'blue diner wall', 'orderable', '2420', 'Nook''s Cranny', 'fancy', 'shop', 'None');
insert into acnh_wallpaper values(29, 0, 'blue flower-print wall', 'orderable', '1780', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(30, 0, 'blue heart-pattern wall', 'orderable', '1280', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(31, 0, 'blue honeycomb-tile wall', 'orderable', '1680', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(32, 0, 'blue intricate wall', 'orderable', '1570', 'Nook''s Cranny', 'living room', 'shop', 'None');
insert into acnh_wallpaper values(33, 0, 'blue molded-panel wall', 'orderable', '1980', 'Nook''s Cranny', 'expensive', 'shop', 'None');
insert into acnh_wallpaper values(34, 0, 'blue painted-wood wall', 'orderable', '1650', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(35, 0, 'blue playroom wall', 'orderable', '2540', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_wallpaper values(36, 0, 'blue quilt wall', 'orderable', '2150', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(37, 0, 'blue shanty wall', 'orderable', '620', 'Nook''s Cranny', 'garage', 'None', 'None');
insert into acnh_wallpaper values(38, 0, 'blue simple-cloth wall', 'orderable', '750', 'Nook''s Cranny', 'child''s room', 'living room', 'None');
insert into acnh_wallpaper values(39, 0, 'blue subway-tile wall', 'orderable', '1340', 'Nook''s Cranny', 'facility', 'shop', 'None');
insert into acnh_wallpaper values(40, 0, 'blue tile wall', 'orderable', '1420', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(41, 0, 'blue two-toned tile wall', 'orderable', '1850', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(42, 0, 'blue-crown wall', 'orderable', '2350', 'Nook''s Cranny', 'expensive', 'None', 'None');
insert into acnh_wallpaper values(43, 0, 'blue-paint wall', 'orderable', '1600', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(44, 0, 'blue-rose wall', 'orderable', '1720', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(45, 0, 'blue-striped wall', 'orderable', '1520', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(46, 0, 'botanical-tile wall', 'orderable', '1240', 'Nook''s Cranny', 'facility', 'expensive', 'None');
insert into acnh_wallpaper values(47, 0, 'brown botanical-tile wall', 'orderable', '1240', 'Nook''s Cranny', 'facility', 'expensive', 'None');
insert into acnh_wallpaper values(48, 0, 'brown diner wall', 'orderable', '2420', 'Nook''s Cranny', 'fancy', 'shop', 'None');
insert into acnh_wallpaper values(49, 0, 'brown hallway wall', 'orderable', '2000', 'Nook''s Cranny', 'facility', 'music', 'None');
insert into acnh_wallpaper values(50, 0, 'brown herringbone wall', 'unorderable', '1800', 'Crafting', 'living room', 'shop', 'None');
insert into acnh_wallpaper values(51, 0, 'brown shanty wall', 'orderable', '620', 'Nook''s Cranny', 'garage', 'None', 'None');
insert into acnh_wallpaper values(52, 0, 'brown-brick wall', 'orderable', '1000', 'Nook''s Cranny', 'facility', 'shop', 'None');
insert into acnh_wallpaper values(53, 0, 'brown-crown wall', 'orderable', '2350', 'Nook''s Cranny', 'expensive', 'None', 'None');
insert into acnh_wallpaper values(54, 0, 'Bunny Day wall', 'unorderable', '4800', 'Crafting', 'fancy', 'child''s room', 'Bunny Day');
insert into acnh_wallpaper values(55, 0, 'butterflies wall', 'unorderable', '840', 'Bug-Off', 'fancy', 'facility', 'None');
insert into acnh_wallpaper values(56, 0, 'cabin wall', 'unorderable', '1800', 'Crafting', 'living room', 'facility', 'None');
insert into acnh_wallpaper values(57, 0, 'café-curtain wall', 'unorderable', '750', 'Saharah', 'shop', 'expensive', 'None');
insert into acnh_wallpaper values(58, 0, 'camo wall', 'orderable', '1150', 'Nook''s Cranny', 'party', 'child''s room', 'None');
insert into acnh_wallpaper values(59, 0, 'chain-link fence', 'unorderable', '750', 'Saharah', 'garden', 'garage', 'None');
insert into acnh_wallpaper values(60, 0, 'cherry wall', 'unorderable', '4000', 'Crafting', 'child''s room', 'fancy', 'fruits');
insert into acnh_wallpaper values(61, 0, 'cherry-blossom-trees wall', 'unorderable', '4600', 'Crafting', 'garden', 'None', 'cherry blossoms');
insert into acnh_wallpaper values(62, 0, 'chic tearoom wall', 'orderable', '1750', 'Nook''s Cranny', 'zen-style', 'shop', 'None');
insert into acnh_wallpaper values(63, 0, 'chic wall', 'orderable', '1960', 'Nook''s Cranny', 'expensive', 'living room', 'None');
insert into acnh_wallpaper values(64, 0, 'chocolate hallway wall', 'orderable', '2000', 'Nook''s Cranny', 'facility', 'music', 'None');
insert into acnh_wallpaper values(65, 0, 'chocolate herringbone wall', 'unorderable', '1800', 'Crafting', 'living room', 'shop', 'None');
insert into acnh_wallpaper values(66, 0, 'circuit-board wall', 'unorderable', '750', 'Saharah', 'facility', 'None', 'None');
insert into acnh_wallpaper values(67, 0, 'cityscape wall', 'unorderable', '750', 'Saharah', 'shop', 'expensive', 'None');
insert into acnh_wallpaper values(68, 0, 'classic-library wall', 'unorderable', '1450', 'Crafting', 'den', 'None', 'None');
insert into acnh_wallpaper values(69, 0, 'colorful puzzle wall', 'orderable', '1540', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(70, 0, 'colorful-tile wall', 'orderable', '1420', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(71, 0, 'common wall', 'orderable', '800', 'Nook''s Cranny', 'living room', 'school', 'None');
insert into acnh_wallpaper values(72, 0, 'concrete wall', 'orderable', '940', 'Nook''s Cranny', 'garage', 'facility', 'None');
insert into acnh_wallpaper values(73, 0, 'construction-site wall', 'unorderable', '750', 'Saharah', 'garage', 'facility', 'None');
insert into acnh_wallpaper values(74, 0, 'crepe-design wall', 'orderable', '1550', 'Nook''s Cranny', 'zen-style', 'None', 'None');
insert into acnh_wallpaper values(75, 0, 'cute blue wall', 'orderable', '1880', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(76, 0, 'cute red wall', 'orderable', '1880', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(77, 0, 'cute white wall', 'orderable', '1880', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(78, 0, 'cute yellow wall', 'orderable', '1880', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(79, 0, 'dark wooden-mosaic wall', 'unorderable', '1800', 'Crafting', 'living room', 'shop', 'None');
insert into acnh_wallpaper values(80, 0, 'dark-chocolate wall', 'unorderable', '750', 'Saharah', 'fancy', 'None', 'None');
insert into acnh_wallpaper values(81, 0, 'desert vista', 'unorderable', '750', 'Saharah', 'folk art', 'None', 'None');
insert into acnh_wallpaper values(82, 0, 'dig-site wall', 'unorderable', '750', 'Saharah', 'garden', 'horror', 'None');
insert into acnh_wallpaper values(83, 0, 'dirt-clod wall', 'orderable', '200', 'Nook''s Cranny', 'horror', 'None', 'None');
insert into acnh_wallpaper values(84, 0, 'dojo wall', 'unorderable', '750', 'Saharah', 'fitness', 'zen-style', 'None');
insert into acnh_wallpaper values(85, 0, 'dungeon wall', 'unorderable', '750', 'Saharah', 'horror', 'None', 'None');
insert into acnh_wallpaper values(86, 0, 'exquisite wall', 'unorderable', '750', 'Saharah', 'zen-style', 'shop', 'None');
insert into acnh_wallpaper values(87, 0, 'forest wall', 'unorderable', '44000', 'Crafting', 'garden', 'None', 'mush');
insert into acnh_wallpaper values(88, 0, 'future-tech wall', 'unorderable', '750', 'Saharah', 'horror', 'folk art', 'None');
insert into acnh_wallpaper values(89, 0, 'garbage-heap wall', 'unorderable', '120', 'Crafting', 'garage', 'horror', 'None');
insert into acnh_wallpaper values(90, 0, 'gold-screen wall', 'unorderable', '20750', 'Crafting', 'zen-style', 'expensive', 'None');
insert into acnh_wallpaper values(91, 0, 'golden wall', 'unorderable', '40000', 'Crafting', 'expensive', 'horror', 'golden');
insert into acnh_wallpaper values(92, 0, 'gray diner wall', 'orderable', '2420', 'Nook''s Cranny', 'fancy', 'shop', 'None');
insert into acnh_wallpaper values(93, 0, 'gray molded-panel wall', 'orderable', '1980', 'Nook''s Cranny', 'expensive', 'shop', 'None');
insert into acnh_wallpaper values(94, 0, 'gray shanty wall', 'orderable', '620', 'Nook''s Cranny', 'garage', 'None', 'None');
insert into acnh_wallpaper values(95, 0, 'gray-striped wall', 'orderable', '1520', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(96, 0, 'green blossoming wall', 'orderable', '1760', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(97, 0, 'green delicate-blooms wall', 'orderable', '1900', 'Nook''s Cranny', 'expensive', 'living room', 'None');
insert into acnh_wallpaper values(98, 0, 'green flower-print wall', 'orderable', '1780', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(99, 0, 'green honeycomb-tile wall', 'orderable', '1680', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(100, 0, 'green intricate wall', 'orderable', '1570', 'Nook''s Cranny', 'living room', 'shop', 'None');
insert into acnh_wallpaper values(101, 0, 'green molded-panel wall', 'orderable', '1980', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(102, 0, 'green painted-wood wall', 'orderable', '1650', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(103, 0, 'green playroom wall', 'orderable', '2540', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_wallpaper values(104, 0, 'green-paint wall', 'orderable', '1600', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(105, 0, 'groovy wall', 'orderable', '1280', 'Nook''s Cranny', 'party', 'None', 'None');
insert into acnh_wallpaper values(106, 0, 'harmonious wall', 'orderable', '1780', 'Nook''s Cranny', 'zen-style', 'shop', 'None');
insert into acnh_wallpaper values(107, 0, 'heavy-curtain wall', 'unorderable', '750', 'Saharah', 'music', 'party', 'None');
insert into acnh_wallpaper values(108, 0, 'honeycomb wall', 'unorderable', '3600', 'Crafting', 'fancy', 'facility', 'None');
insert into acnh_wallpaper values(109, 0, 'honeycomb-tile wall', 'orderable', '1680', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(110, 0, 'ice wall', 'unorderable', '8200', 'Snowman', 'freezing cold', 'facility', 'frozen');
insert into acnh_wallpaper values(111, 0, 'iceberg wall', 'unorderable', '4000', 'Crafting', 'freezing cold', 'None', 'None');
insert into acnh_wallpaper values(112, 0, 'imperial wall', 'unorderable', '750', 'Saharah', 'expensive', 'None', 'None');
insert into acnh_wallpaper values(113, 0, 'industrial wall', 'unorderable', '750', 'Saharah', 'facility', 'None', 'None');
insert into acnh_wallpaper values(114, 0, 'ivy wall', 'unorderable', '750', 'Saharah', 'facility', 'shop', 'None');
insert into acnh_wallpaper values(115, 0, 'Jingle wall', 'unorderable', '2500', 'Crafting', 'fancy', 'party', 'festive');
insert into acnh_wallpaper values(116, 0, 'jungle wall', 'unorderable', '1380', 'Crafting', 'garden', 'facility', 'None');
insert into acnh_wallpaper values(117, 0, 'kisses wall', 'unorderable', '750', 'Saharah', 'party', 'fancy', 'None');
insert into acnh_wallpaper values(118, 0, 'laboratory wall', 'unorderable', '750', 'Saharah', 'facility', 'None', 'None');
insert into acnh_wallpaper values(119, 0, 'lattice wall', 'orderable', '1780', 'Nook''s Cranny', 'zen-style', 'shop', 'None');
insert into acnh_wallpaper values(120, 0, 'magma-cavern wall', 'unorderable', '750', 'Saharah', 'horror', 'None', 'None');
insert into acnh_wallpaper values(121, 0, 'manga-library wall', 'unorderable', '1050', 'Crafting', 'facility', 'den', 'None');
insert into acnh_wallpaper values(122, 0, 'mangrove wall', 'unorderable', '750', 'Saharah', 'garden', 'None', 'None');
insert into acnh_wallpaper values(123, 0, 'marine pop wall', 'unorderable', '805', 'Fishing Tourney', 'ocean', 'child''s room', 'None');
insert into acnh_wallpaper values(124, 0, 'meadow vista', 'unorderable', '750', 'Saharah', 'garden', 'None', 'None');
insert into acnh_wallpaper values(125, 0, 'misty-garden wall', 'unorderable', '585', 'Saharah', 'garden', 'None', 'None');
insert into acnh_wallpaper values(126, 0, 'mod wall', 'orderable', '1220', 'Nook''s Cranny', 'party', 'None', 'None');
insert into acnh_wallpaper values(127, 0, 'modern shoji-screen wall', 'orderable', '1150', 'Nook''s Cranny', 'zen-style', 'shop', 'None');
insert into acnh_wallpaper values(128, 0, 'modern tearoom wall', 'orderable', '1750', 'Nook''s Cranny', 'zen-style', 'shop', 'None');
insert into acnh_wallpaper values(129, 0, 'modern wood wall', 'unorderable', '1800', 'Crafting', 'living room', 'child''s room', 'None');
insert into acnh_wallpaper values(130, 0, 'monochromatic dotted wall', 'orderable', '1100', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(131, 0, 'monochromatic-tile wall', 'orderable', '1420', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(132, 0, 'mortar wall', 'unorderable', '750', 'Saharah', 'zen-style', 'None', 'None');
insert into acnh_wallpaper values(133, 0, 'mosaic-tile wall', 'orderable', '1450', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(134, 0, 'mossy-garden wall', 'unorderable', '750', 'Saharah', 'zen-style', 'None', 'None');
insert into acnh_wallpaper values(135, 0, 'mush wall', 'unorderable', '21400', 'Crafting', 'fancy', 'None', 'mush');
insert into acnh_wallpaper values(136, 0, 'Nook Inc. wall', 'unorderable', '6000', 'Nook Miles Shop', 'fancy', 'shop', 'None');
insert into acnh_wallpaper values(137, 0, 'ocean-horizon wall', 'unorderable', '750', 'Saharah', 'ocean', 'None', 'None');
insert into acnh_wallpaper values(138, 0, 'office wall', 'unorderable', '750', 'Saharah', 'office', 'None', 'None');
insert into acnh_wallpaper values(139, 0, 'old wallpaper', 'orderable', '200', 'Nook''s Cranny', 'horror', 'None', 'None');
insert into acnh_wallpaper values(140, 0, 'olive desert-tile wall', 'orderable', '2440', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(141, 0, 'orange camo wall', 'orderable', '1150', 'Nook''s Cranny', 'party', 'child''s room', 'None');
insert into acnh_wallpaper values(142, 0, 'orange molded-panel wall', 'orderable', '1980', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(143, 0, 'orange wall', 'unorderable', '4000', 'Crafting', 'fancy', 'child''s room', 'fruits');
insert into acnh_wallpaper values(144, 0, 'orange-paint wall', 'orderable', '1600', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(145, 0, 'paintball wall', 'unorderable', '750', 'Saharah', 'garage', 'facility', 'None');
insert into acnh_wallpaper values(146, 0, 'palace wall', 'unorderable', '750', 'Saharah', 'expensive', 'folk art', 'None');
insert into acnh_wallpaper values(147, 0, 'party wall', 'unorderable', '370', 'Birthday', 'party', 'fancy', 'None');
insert into acnh_wallpaper values(148, 0, 'pastel dotted wall', 'orderable', '1100', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(149, 0, 'pastel puzzle wall', 'orderable', '1540', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(150, 0, 'peach two-toned tile wall', 'orderable', '1850', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(151, 0, 'peach wall', 'unorderable', '4000', 'Crafting', 'fancy', 'child''s room', 'fruits');
insert into acnh_wallpaper values(152, 0, 'pear wall', 'unorderable', '4000', 'Crafting', 'fancy', 'child''s room', 'fruits');
insert into acnh_wallpaper values(153, 0, 'perforated-board wall', 'orderable', '1180', 'Nook''s Cranny', 'music', 'facility', 'None');
insert into acnh_wallpaper values(154, 0, 'pink blossoming wall', 'orderable', '1760', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(155, 0, 'pink diner wall', 'orderable', '2420', 'Nook''s Cranny', 'fancy', 'shop', 'None');
insert into acnh_wallpaper values(156, 0, 'pink flower-print wall', 'orderable', '1780', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(157, 0, 'pink heart-pattern wall', 'orderable', '1280', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(158, 0, 'pink painted-wood wall', 'orderable', '1650', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(159, 0, 'pink playroom wall', 'orderable', '2540', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_wallpaper values(160, 0, 'pink quilt wall', 'orderable', '2150', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(161, 0, 'pink shanty wall', 'orderable', '620', 'Nook''s Cranny', 'garage', 'None', 'None');
insert into acnh_wallpaper values(162, 0, 'pink simple-cloth wall', 'orderable', '750', 'Nook''s Cranny', 'child''s room', 'living room', 'None');
insert into acnh_wallpaper values(163, 0, 'pink-crown wall', 'orderable', '2350', 'Nook''s Cranny', 'fancy', 'expensive', 'None');
insert into acnh_wallpaper values(164, 0, 'pink-striped wall', 'orderable', '1520', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(165, 0, 'purple camo wall', 'orderable', '1150', 'Nook''s Cranny', 'party', 'child''s room', 'None');
insert into acnh_wallpaper values(166, 0, 'purple desert-tile wall', 'orderable', '2440', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(167, 0, 'purple dotted wall', 'orderable', '1100', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(168, 0, 'purple puzzle wall', 'orderable', '1540', 'Nook''s Cranny', 'None', 'None', 'None');
insert into acnh_wallpaper values(169, 0, 'purple quilt wall', 'orderable', '2150', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(170, 0, 'purple-rose wall', 'orderable', '1720', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wallpaper values(171, 0, 'rammed-earth wall', 'orderable', '1800', 'Nook''s Cranny', 'folk art', 'None', 'None');
insert into acnh_wallpaper values(172, 0, 'ramshackle wall', 'unorderable', '750', 'Saharah', 'horror', 'None', 'None');
insert into acnh_wallpaper values(173, 0, 'red art-deco wall', 'orderable', '2780', 'Nook''s Cranny', 'child''s room', 'living room', 'None');
insert into acnh_wallpaper values(174, 0, 'red delicate-blooms wall', 'orderable', '1900', 'Nook''s Cranny', 'expensive', 'living room', 'None');
insert into acnh_wallpaper values(175, 0, 'red dotted wall', 'orderable', '1100', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(176, 0, 'red heart-pattern wall', 'orderable', '1280', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(177, 0, 'red intricate wall', 'orderable', '1570', 'Nook''s Cranny', 'living room', 'shop', 'None');
insert into acnh_wallpaper values(178, 0, 'red perforated-board wall', 'orderable', '1180', 'Nook''s Cranny', 'music', 'facility', 'None');
insert into acnh_wallpaper values(179, 0, 'red two-toned tile wall', 'orderable', '1850', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(180, 0, 'red-brick wall', 'orderable', '1000', 'Nook''s Cranny', 'facility', 'shop', 'None');
insert into acnh_wallpaper values(181, 0, 'retro flower-print wall', 'orderable', '1660', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(182, 0, 'rice-paddy wall', 'unorderable', '750', 'Saharah', 'garden', 'None', 'None');
insert into acnh_wallpaper values(183, 0, 'ringside seating', 'unorderable', '750', 'Saharah', 'fitness', 'None', 'None');
insert into acnh_wallpaper values(184, 0, 'rock-climbing wall', 'unorderable', '750', 'Saharah', 'fitness', 'None', 'None');
insert into acnh_wallpaper values(185, 0, 'rose wall', 'orderable', '1720', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wallpaper values(186, 0, 'ruins wall', 'unorderable', '750', 'Saharah', 'horror', 'folk art', 'None');
insert into acnh_wallpaper values(187, 0, 'rustic-stone wall', 'unorderable', '1750', 'Crafting', 'facility', 'shop', 'None');
insert into acnh_wallpaper values(188, 0, 'sakura-wood wall', 'unorderable', '3200', 'Crafting', 'child''s room', 'fancy', 'cherry blossoms');
insert into acnh_wallpaper values(189, 0, 'sci-fi wall', 'unorderable', '7500', 'Crafting', 'space', 'facility', 'None');
insert into acnh_wallpaper values(190, 0, 'screen wall', 'orderable', '3000', 'Nook''s Cranny', 'zen-style', 'facility', 'None');
insert into acnh_wallpaper values(191, 0, 'sea view', 'unorderable', '750', 'Saharah', 'ocean', 'None', 'None');
insert into acnh_wallpaper values(192, 0, 'security-monitors wall', 'unorderable', '750', 'Saharah', 'facility', 'None', 'None');
insert into acnh_wallpaper values(193, 0, 'sepia puzzle wall', 'orderable', '1540', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(194, 0, 'server-room wall', 'unorderable', '750', 'Saharah', 'facility', 'None', 'None');
insert into acnh_wallpaper values(195, 0, 'shoji screen', 'orderable', '1880', 'Nook''s Cranny', 'zen-style', 'None', 'None');
insert into acnh_wallpaper values(196, 0, 'shutter wall', 'unorderable', '750', 'Saharah', 'facility', 'shop', 'None');
insert into acnh_wallpaper values(197, 0, 'ski-slope wall', 'unorderable', '3200', 'Crafting', 'freezing cold', 'None', 'None');
insert into acnh_wallpaper values(198, 0, 'skull wall', 'orderable', '3000', 'Nook''s Cranny', 'horror', 'child''s room', 'None');
insert into acnh_wallpaper values(199, 0, 'sky wall', 'unorderable', '750', 'Saharah', 'fancy', 'None', 'None');
insert into acnh_wallpaper values(200, 0, 'skyscraper wall', 'unorderable', '750', 'Saharah', 'expensive', 'None', 'None');
insert into acnh_wallpaper values(201, 0, 'snowflake wall', 'unorderable', '4800', 'Crafting', 'freezing cold', 'None', 'None');
insert into acnh_wallpaper values(202, 0, 'soothing tearoom wall', 'orderable', '1750', 'Nook''s Cranny', 'zen-style', 'shop', 'None');
insert into acnh_wallpaper values(203, 0, 'stacked-wood wall', 'unorderable', '1800', 'Crafting', 'garage', 'facility', 'None');
insert into acnh_wallpaper values(204, 0, 'stadium wall', 'unorderable', '750', 'Saharah', 'fitness', 'None', 'None');
insert into acnh_wallpaper values(205, 0, 'standard tearoom wall', 'orderable', '1750', 'Nook''s Cranny', 'zen-style', 'None', 'None');
insert into acnh_wallpaper values(206, 0, 'starry wall', 'unorderable', '7500', 'Crafting', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(207, 0, 'starry-sky wall', 'unorderable', '7500', 'Crafting', 'space', 'None', 'stars');
insert into acnh_wallpaper values(208, 0, 'stately wall', 'orderable', '2450', 'Nook''s Cranny', 'expensive', 'None', 'None');
insert into acnh_wallpaper values(209, 0, 'steel-frame wall', 'unorderable', '6000', 'Crafting', 'garage', 'facility', 'None');
insert into acnh_wallpaper values(210, 0, 'stone wall', 'unorderable', '1500', 'Crafting', 'horror', 'facility', 'None');
insert into acnh_wallpaper values(211, 0, 'stormy-night wall', 'unorderable', '750', 'Saharah', 'horror', 'None', 'None');
insert into acnh_wallpaper values(212, 0, 'straw wall', 'unorderable', '750', 'Saharah', 'folk art', 'None', 'None');
insert into acnh_wallpaper values(213, 0, 'strawberry-chocolate wall', 'unorderable', '750', 'Saharah', 'fancy', 'None', 'None');
insert into acnh_wallpaper values(214, 0, 'street-art wall', 'unorderable', '750', 'Saharah', 'garage', 'None', 'None');
insert into acnh_wallpaper values(215, 0, 'summit wall', 'unorderable', '750', 'Saharah', 'garden', 'None', 'None');
insert into acnh_wallpaper values(216, 0, 'tree-lined wall', 'unorderable', '750', 'Saharah', 'garden', 'None', 'None');
insert into acnh_wallpaper values(217, 0, 'tropical vista', 'unorderable', '6000', 'Crafting', 'ocean', 'None', 'None');
insert into acnh_wallpaper values(218, 0, 'underwater wall', 'unorderable', '8600', 'Crafting', 'ocean', 'None', 'None');
insert into acnh_wallpaper values(219, 0, 'wavy-tile wall', 'orderable', '1740', 'Nook''s Cranny', 'shop', 'facility', 'None');
insert into acnh_wallpaper values(220, 0, 'western vista', 'unorderable', '750', 'Saharah', 'folk art', 'horror', 'None');
insert into acnh_wallpaper values(221, 0, 'white botanical-tile wall', 'orderable', '1240', 'Nook''s Cranny', 'facility', 'expensive', 'None');
insert into acnh_wallpaper values(222, 0, 'white delicate-blooms wall', 'orderable', '1900', 'Nook''s Cranny', 'expensive', 'living room', 'None');
insert into acnh_wallpaper values(223, 0, 'white hallway wall', 'orderable', '2000', 'Nook''s Cranny', 'facility', 'music', 'None');
insert into acnh_wallpaper values(224, 0, 'white honeycomb-tile wall', 'orderable', '1680', 'Nook''s Cranny', 'bathroom', 'facility', 'None');
insert into acnh_wallpaper values(225, 0, 'white painted-wood wall', 'orderable', '1650', 'Nook''s Cranny', 'living room', 'child''s room', 'None');
insert into acnh_wallpaper values(226, 0, 'white perforated-board wall', 'orderable', '1180', 'Nook''s Cranny', 'music', 'facility', 'None');
insert into acnh_wallpaper values(227, 0, 'white simple-cloth wall', 'orderable', '750', 'Nook''s Cranny', 'child''s room', 'living room', 'None');
insert into acnh_wallpaper values(228, 0, 'white subway-tile wall', 'orderable', '1340', 'Nook''s Cranny', 'facility', 'shop', 'None');
insert into acnh_wallpaper values(229, 0, 'white-brick wall', 'orderable', '1000', 'Nook''s Cranny', 'facility', 'shop', 'None');
insert into acnh_wallpaper values(230, 0, 'white-chocolate wall', 'unorderable', '750', 'Saharah', 'fancy', 'None', 'None');
insert into acnh_wallpaper values(231, 0, 'white-rose wall', 'orderable', '1720', 'Nook''s Cranny', 'fancy', 'None', 'None');
insert into acnh_wallpaper values(232, 0, 'wild-wood wall', 'unorderable', '1800', 'Crafting', 'living room', 'shop', 'None');
insert into acnh_wallpaper values(233, 0, 'wooden-knot wall', 'unorderable', '1800', 'Crafting', 'living room', 'child''s room', 'None');
insert into acnh_wallpaper values(234, 0, 'wooden-mosaic wall', 'unorderable', '1800', 'Crafting', 'living room', 'shop', 'None');
insert into acnh_wallpaper values(235, 0, 'woodland wall', 'unorderable', '1380', 'Crafting', 'horror', 'facility', 'None');
insert into acnh_wallpaper values(236, 0, 'yellow flower-print wall', 'orderable', '1780', 'Nook''s Cranny', 'fancy', 'living room', 'None');
insert into acnh_wallpaper values(237, 0, 'yellow heart-pattern wall', 'orderable', '1280', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(238, 0, 'yellow intricate wall', 'orderable', '1570', 'Nook''s Cranny', 'living room', 'shop', 'None');
insert into acnh_wallpaper values(239, 0, 'yellow playroom wall', 'orderable', '2540', 'Nook''s Cranny', 'child''s room', 'fancy', 'None');
insert into acnh_wallpaper values(240, 0, 'yellow quilt wall', 'orderable', '2150', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(241, 0, 'yellow simple-cloth wall', 'orderable', '750', 'Nook''s Cranny', 'child''s room', 'living room', 'None');
insert into acnh_wallpaper values(242, 0, 'yellow-paint wall', 'orderable', '1600', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
insert into acnh_wallpaper values(243, 0, 'yellow-striped wall', 'orderable', '1520', 'Nook''s Cranny', 'fancy', 'child''s room', 'None');
