drop table if exists accf_accessory;
create table accf_accessory ("Index" int, Selected int, Name varchar(63), Status varchar(31), "From" varchar(31), Price varchar(31), Color1 varchar(31), Color2 varchar(31), Style varchar(31), Look varchar(31));
insert into accf_accessory values(1, 0, 'White Cap', 'normal', 'Ables', '160', 'white', 'white', 'Cool', 'none');
insert into accf_accessory values(2, 0, 'Red Cap', 'normal', 'Ables', '160', 'red', 'red', 'Cool', 'none');
insert into accf_accessory values(3, 0, 'Yellow Cap', 'normal', 'Ables', '160', 'yellow', 'yellow', 'Cool', 'none');
insert into accf_accessory values(4, 0, 'Light Blue Cap', 'normal', 'Ables', '160', 'aqua', 'aqua', 'Fresh', 'none');
insert into accf_accessory values(5, 0, 'Green Cap', 'normal', 'Ables', '160', 'green', 'green', 'Subtle', 'none');
insert into accf_accessory values(6, 0, 'Star Cap', 'normal', 'Ables', '160', 'pink', 'pink', 'Cute', 'none');
insert into accf_accessory values(7, 0, '1-Up Cap', 'normal', 'Ables', '160', 'black', 'black', 'Funky', 'none');
insert into accf_accessory values(8, 0, 'Purple Cap', 'normal', 'Ables', '160', 'purple', 'purple', 'Gaudy', 'none');
insert into accf_accessory values(9, 0, 'Blue Cap', 'normal', 'Ables', '640', 'blue', 'blue', 'Fresh', 'none');
insert into accf_accessory values(10, 0, 'Blue Pom-Pom Hat', 'normal', 'Ables', '160', 'blue', 'blue', 'Subtle', 'none');
insert into accf_accessory values(11, 0, 'Green Knit Hat', 'normal', 'Ables', '160', 'green', 'green', 'Refined', 'none');
insert into accf_accessory values(12, 0, 'Orange Knit Hat', 'normal', 'Ables', '160', 'orange', 'orange', 'Funky', 'none');
insert into accf_accessory values(13, 0, 'Pink Knit Hat', 'normal', 'Ables', '160', 'pink', 'pink', 'Cute', 'none');
insert into accf_accessory values(14, 0, 'Purple Knit Hat', 'normal', 'Ables', '160', 'purple', 'white', 'Subtle', 'none');
insert into accf_accessory values(15, 0, 'Red Pom-Pom Hat', 'normal', 'Ables', '160', 'red', 'white', 'Gaudy', 'none');
insert into accf_accessory values(16, 0, 'Badge Hat', 'normal', 'Ables', '160', 'colorful', 'white', 'Fresh', 'none');
insert into accf_accessory values(17, 0, 'Straw Hat', 'normal', 'Ables', '160', 'brown', 'brown', 'Fresh', 'none');
insert into accf_accessory values(18, 0, 'Grandpa Hat', 'normal', 'Ables', '240', 'gray', 'gray', 'Refined', 'none');
insert into accf_accessory values(19, 0, 'Paperboy Cap', 'normal', 'Ables', '280', 'aqua', 'aqua', 'Subtle', 'none');
insert into accf_accessory values(20, 0, 'Beret', 'normal', 'Ables', '160', 'brown', 'brown', 'Refined', 'none');
insert into accf_accessory values(21, 0, 'Dandy Hat', 'normal', 'Ables', '160', 'aqua', 'white', 'Striking', 'none');
insert into accf_accessory values(22, 0, 'Hunter''s Cap', 'normal', 'Ables', '300', 'red', 'white', 'Cute', 'none');
insert into accf_accessory values(23, 0, 'Detective Hat', 'normal', 'Ables', '240', 'beige', 'brown', 'Refined', 'Detective Look');
insert into accf_accessory values(24, 0, 'Top Hat', 'normal', 'Ables', '400', 'black', 'black', 'Fancy', 'none');
insert into accf_accessory values(25, 0, 'Puffy Hat', 'normal', 'Ables', '240', 'blue', 'blue', 'Fresh', 'none');
insert into accf_accessory values(26, 0, 'Gracie Hat', 'unorderable', 'GracieGrace', '8,000', 'blue', 'colorful', 'Striking', 'none');
insert into accf_accessory values(27, 0, 'Elegant Hat', 'unorderable', 'GracieGrace', '6,400', 'white', 'white', 'Fresh', 'none');
insert into accf_accessory values(28, 0, 'Bandana', 'normal', 'Ables', '80', 'red', 'red', 'Cool', 'none');
insert into accf_accessory values(29, 0, 'Tulip Hat', 'normal', 'Ables', '640', 'yellow', 'yellow', 'Funky', 'none');
insert into accf_accessory values(30, 0, 'Do-Rag', 'normal', 'Ables', '640', 'yellow', 'orange', 'Fresh', 'none');
insert into accf_accessory values(31, 0, 'Swimming Cap', 'normal', 'Ables', '80', 'yellow', 'yellow', 'Striking', 'none');
insert into accf_accessory values(32, 0, 'Wizard''s Cap', 'normal', 'Ables', '80', 'green', 'green', 'Strange', 'none');
insert into accf_accessory values(33, 0, 'Newsprint Helmet', 'normal', 'Tortimer (Japan)', '80', 'gray', 'gray', 'Cute', 'none');
insert into accf_accessory values(34, 0, 'Festive Hat', 'normal', 'Ables', '640', 'red', 'white', 'Fancy', 'none');
insert into accf_accessory values(35, 0, 'Big Bro''s Hat', 'normal', 'Ables', '320', 'red', 'red', 'Gaudy', 'none');
insert into accf_accessory values(36, 0, 'Li''l Bro''s Hat', 'normal', 'Ables', '320', 'green', 'green', 'Gaudy', 'none');
insert into accf_accessory values(37, 0, 'Wario Hat', 'unorderable', 'Nook Points', 'none', 'yellow', 'yellow', 'Striking', 'none');
insert into accf_accessory values(38, 0, 'Bicycle Helmet', 'normal', 'Ables', '400', 'red', 'red', 'Fresh', 'Cyclist Look');
insert into accf_accessory values(39, 0, 'Chef''s Hat', 'normal', 'Ables', '160', 'white', 'white', 'Subtle', 'Chef Look');
insert into accf_accessory values(40, 0, 'Combat Helmet', 'normal', 'Ables', '960', 'green', 'colorful', 'Cool', 'Combat Look');
insert into accf_accessory values(41, 0, 'Scholar''s Hat', 'normal', 'Ables', '420', 'brown', 'brown', 'Subtle', 'Graduate Look');
insert into accf_accessory values(42, 0, 'Safety Helmet', 'normal', 'Ables', '300', 'yellow', 'yellow', 'Refined', 'Laborer Look');
insert into accf_accessory values(43, 0, 'Police Cap', 'normal', 'Ables', '480', 'black', 'black', 'Cool', 'Police Look');
insert into accf_accessory values(44, 0, 'Explorer''s Hat', 'normal', 'Ables', '160', 'gray', 'gray', 'Cool', 'Explorer Look');
insert into accf_accessory values(45, 0, 'Captain''s Hat', 'normal', 'Ables', '360', 'white', 'white', 'Cool', 'Captain Look');
insert into accf_accessory values(46, 0, 'Sailor''s Hat', 'normal', 'Ables', '300', 'blue', 'white', 'Cute', 'Sailor Look');
insert into accf_accessory values(47, 0, 'Silk Hat', 'normal', 'Ables', '120', 'red', 'green', 'Striking', 'Ornate Look');
insert into accf_accessory values(48, 0, 'Outback Hat', 'normal', 'Ables', '160', 'beige', 'beige', 'Cool', 'Western Look');
insert into accf_accessory values(49, 0, 'Dutch Hat', 'normal', 'Ables', '320', 'white', 'white', 'Cute', 'Nordic Look');
insert into accf_accessory values(50, 0, 'Sombrero', 'normal', 'Ables', '240', 'brown', 'brown', 'Refined', 'Reggae Look');
insert into accf_accessory values(51, 0, 'Tyrolean Hat', 'normal', 'Ables', '160', 'green', 'green', 'Subtle', 'Alpine Look');
insert into accf_accessory values(52, 0, 'Viking Helmet', 'normal', 'Ables', '540', 'gray', 'gray', 'Cool', 'Viking Look');
insert into accf_accessory values(53, 0, 'Cavalier Hat', 'normal', 'Ables', '360', 'black', 'black', 'Cool', 'Cavalier Look');
insert into accf_accessory values(54, 0, 'Pirate''s Hat', 'normal', 'Ables', '240', 'black', 'black', 'Cool', 'Pirate Look');
insert into accf_accessory values(55, 0, 'Jester''s Cap', 'normal', 'Ables', '360', 'yellow', 'purple', 'Striking', 'Jester Look');
insert into accf_accessory values(56, 0, 'Witch''s Hat', 'unorderable', 'GracieGrace', '4,800', 'black', 'black', 'Fancy', 'Witch Look');
insert into accf_accessory values(57, 0, 'Melon Hat', 'normal', 'Ables', '640', 'green', 'green', 'Fresh', 'Melon Look');
insert into accf_accessory values(58, 0, 'Strawberry Hat', 'normal', 'Ables', '640', 'red', 'pink', 'Cute', 'Strawberry Look');
insert into accf_accessory values(59, 0, 'Kiwi Hat', 'normal', 'Ables', '640', 'brown', 'brown', 'Funky', 'Kiwi Look');
insert into accf_accessory values(60, 0, 'Mandarin Hat', 'normal', 'Ables', '640', 'green', 'orange', 'Fresh', 'Tangerine Look');
insert into accf_accessory values(61, 0, 'Watermelon Hat', 'normal', 'Ables', '640', 'green', 'green', 'Funky', 'Watermelon Look');
insert into accf_accessory values(62, 0, 'Grape Hat', 'normal', 'Ables', '640', 'green', 'purple', 'Fancy', 'Grape Look');
insert into accf_accessory values(63, 0, 'Red Ribbon', 'normal', 'Ables', '160', 'red', 'red', 'Cute', 'none');
insert into accf_accessory values(64, 0, 'Blue Ribbon', 'normal', 'Ables', '160', 'blue', 'blue', 'Fresh', 'none');
insert into accf_accessory values(65, 0, 'Yellow Ribbon', 'normal', 'Ables', '160', 'yellow', 'yellow', 'Funky', 'none');
insert into accf_accessory values(66, 0, 'Heart Hairpin', 'normal', 'Ables', '160', 'pink', 'pink', 'Cute', 'none');
insert into accf_accessory values(67, 0, 'Star Hairpin', 'normal', 'Ables', '160', 'yellow', 'yellow', 'Fancy', 'none');
insert into accf_accessory values(68, 0, 'Moon Hairpin', 'normal', 'Ables', '160', 'yellow', 'yellow', 'Funky', 'none');
insert into accf_accessory values(69, 0, 'Green Feather', 'normal', 'Savings', 'none or 200', 'green', 'green', 'Fresh', 'none');
insert into accf_accessory values(70, 0, 'Blue Feather', 'normal', 'Savings', 'none or 240', 'blue', 'blue', 'Fresh', 'none');
insert into accf_accessory values(71, 0, 'Yellow Feather', 'normal', 'Savings', 'none or 280', 'yellow', 'yellow', 'Fresh', 'none');
insert into accf_accessory values(72, 0, 'Red Feather', 'normal', 'Savings', 'none or 320', 'red', 'red', 'Fresh', 'none');
insert into accf_accessory values(73, 0, 'Purple Feather', 'normal', 'Savings', 'none or 360', 'purple', 'purple', 'Fresh', 'none');
insert into accf_accessory values(74, 0, 'White Feather', 'normal', 'Savings', 'none or 400', 'white', 'white', 'Fresh', 'none');
insert into accf_accessory values(75, 0, 'Rainbow Feather', 'normal', 'Savings', 'none or 440', 'colorful', 'colorful', 'Fresh', 'none');
insert into accf_accessory values(76, 0, 'Halo', 'normal', 'Ables', '2,400', 'yellow', 'yellow', 'Striking', 'none');
insert into accf_accessory values(77, 0, 'Royal Crown', 'unorderable', 'Ables', '1,200,000', 'yellow', 'red', 'Fresh', 'Regal Look');
insert into accf_accessory values(78, 0, 'Crown', 'unorderable', 'Ables', '1,000,000', 'yellow', 'yellow', 'Fresh', 'none');
insert into accf_accessory values(79, 0, 'Black Knit Cap', 'normal', 'Ables', '120', 'pink', 'black', 'Cute', 'none');
insert into accf_accessory values(80, 0, 'Pilot''s Cap', 'normal', 'Ables', '720', 'yellow', 'orange', 'Cool', 'none');
insert into accf_accessory values(81, 0, 'Fireman''s Hat', 'normal', 'Ables', '960', 'black', 'black', 'Cool', 'Firefighter Look');
insert into accf_accessory values(82, 0, 'Baby''s Hat', 'normal', 'Ables', '160', 'white', 'white', 'Cute', 'none');
insert into accf_accessory values(83, 0, 'Turban', 'normal', 'Ables', '600', 'white', 'white', 'Fancy', 'Persian Look');
insert into accf_accessory values(84, 0, 'Warbonnet', 'normal', 'Ables', '1,000', 'colorful', 'colorful', 'Cool', 'Native Look');
insert into accf_accessory values(85, 0, 'Kaffiyeh', 'normal', 'Ables', '160', 'white', 'white', 'Fresh', 'none');
insert into accf_accessory values(86, 0, 'Cow Bone', 'normal', 'Ables', '160', 'white', 'white', 'Striking', 'Native Look');
insert into accf_accessory values(87, 0, 'Samurai Wig', 'normal', 'Ables', '1,200', 'none', 'none', 'Subtle', 'none');
insert into accf_accessory values(88, 0, 'Geisha Wig', 'normal', 'Ables', '1,600', 'none', 'none', 'Gaudy', 'Zen Look');
insert into accf_accessory values(89, 0, 'Ninja Hood', 'normal', 'Ables', '240', 'blue', 'blue', 'Cool', 'Ninja Look');
insert into accf_accessory values(90, 0, 'Powdered Wig', 'normal', 'Ables', '160', 'gray', 'gray', 'Refined', 'none');
insert into accf_accessory values(91, 0, 'Afro Wig', 'normal', 'Ables', '160', 'none', 'none', 'Fresh', 'none');
insert into accf_accessory values(92, 0, 'Regent Wig', 'normal', 'Ables', '160', 'none', 'none', 'Fresh', 'none');
insert into accf_accessory values(93, 0, 'Mohawk Wig', 'normal', 'Ables', '160', 'none', 'none', 'Fresh', 'none');
insert into accf_accessory values(94, 0, 'Pigtail', 'normal', 'Ables', '120', 'none', 'none', 'Striking', 'Ornate Look');
insert into accf_accessory values(95, 0, 'Bun Wig', 'normal', 'Ables', '480', 'none', 'none', 'Cute', 'none');
insert into accf_accessory values(96, 0, 'Tiara Hair', 'unorderable', 'GracieGrace', '7,200', 'none', 'none', 'Fancy', 'none');
insert into accf_accessory values(97, 0, 'Bridal Veil', 'unorderable', 'GracieGrace', '7,200', 'white', 'white', 'Cute', 'Bridal Look');
insert into accf_accessory values(98, 0, 'Headband', 'unorderable', 'GracieGrace', '4,800', 'white', 'white', 'Fancy', 'Spa Look');
insert into accf_accessory values(99, 0, 'Bunny Hood', 'normal', 'Ables', '1,600', 'white', 'white', 'Cute', 'Bunny Look');
insert into accf_accessory values(100, 0, 'Cat Cap', 'normal', 'Ables', '120', 'blue', 'blue', 'Cute', 'Cat Look');
insert into accf_accessory values(101, 0, 'Bear Cap', 'normal', 'Ables', '120', 'brown', 'brown', 'Funky', 'Bear Look');
insert into accf_accessory values(102, 0, 'Frog Cap', 'normal', 'Ables', '120', 'green', 'green', 'Strange', 'Frog Look');
insert into accf_accessory values(103, 0, 'Kappa Cap', 'normal', 'Ables', '120', 'green', 'green', 'Striking', 'Kapp''n Look');
insert into accf_accessory values(104, 0, 'Helmet', 'normal', 'Ables', '2,000', 'yellow', 'black', 'Refined', 'Samurai Look');
insert into accf_accessory values(105, 0, 'Hero''s Cap', 'unorderable', 'Nook Points', 'none', 'green', 'green', 'Cool', 'Link Look');
insert into accf_accessory values(106, 0, 'Racing Helmet', 'normal', 'Ables', '1,200', 'red', 'red', 'Cool', 'Racer Look');
insert into accf_accessory values(107, 0, 'Motocross Helmet', 'normal', 'Ables', '1,400', 'blue', 'blue', 'Cool', 'Racer Look');
insert into accf_accessory values(108, 0, 'Football Helmet', 'normal', 'Ables', '1,200', 'yellow', 'yellow', 'Fresh', 'none');
insert into accf_accessory values(109, 0, 'Knight''s Helmet', 'normal', 'Ables', '1,000', 'gray', 'gray', 'Cool', 'Knight Look');
insert into accf_accessory values(110, 0, 'Roman Helmet', 'normal', 'Ables', '1,200', 'yellow', 'yellow', 'Cool', 'Warrior Look');
insert into accf_accessory values(111, 0, 'Diving Mask', 'normal', 'Ables', '2,200', 'yellow', 'yellow', 'Gaudy', 'none');
insert into accf_accessory values(112, 0, 'Space Helmet', 'normal', 'Ables', '2,400', 'aqua', 'aqua', 'Cool', 'Astronaut Look');
insert into accf_accessory values(113, 0, 'Ski Mask', 'normal', 'Ables', '600', 'black', 'black', 'Strange', 'none');
insert into accf_accessory values(114, 0, 'Wrestling Mask', 'normal', 'Ables', '900', 'red', 'red', 'Cool', 'Wrestler Look');
insert into accf_accessory values(115, 0, 'Dressing', 'normal', 'Ables', '120', 'white', 'white', 'Strange', 'Mummy Look');
insert into accf_accessory values(116, 0, 'Retro Helmet', 'unorderable', 'GracieGrace', '5,000', 'green', 'green', 'Refined', 'none');
insert into accf_accessory values(117, 0, 'Red Zap Helmet', 'normal', 'Ables', '120', 'red', 'white', 'Cool', 'Red Hero Look');
insert into accf_accessory values(118, 0, 'Blue Zap Helmet', 'normal', 'Ables', '120', 'blue', 'white', 'Cool', 'Blue Hero Look');
insert into accf_accessory values(119, 0, 'Green Zap Helmet', 'normal', 'Ables', '120', 'green', 'white', 'Cool', 'Green Hero Look');
insert into accf_accessory values(120, 0, 'Pink Zap Helmet', 'normal', 'Ables', '120', 'pink', 'white', 'Cool', 'Heroine Look');
insert into accf_accessory values(121, 0, 'Red Ogre Mask', 'unorderable', 'Tortimer (Japan)', 'none', 'red', 'red', 'Strange', 'none');
insert into accf_accessory values(122, 0, 'Blue Ogre Mask', 'unorderable', 'Tortimer (Japan)', 'none', 'blue', 'blue', 'Strange', 'none');
insert into accf_accessory values(123, 0, 'Majora''s Mask', 'unorderable', 'Nook Points', 'none', 'colorful', 'colorful', 'Strange', 'none');
insert into accf_accessory values(124, 0, 'Samus Mask', 'unorderable', 'Nook Points', 'none', 'orange', 'orange', 'Cool', 'Samus Look');
insert into accf_accessory values(125, 0, 'Midna''s Mask', 'unorderable', 'Nook Points', 'none', 'gray', 'gray', 'Striking', 'none');
insert into accf_accessory values(126, 0, 'Toad Hat', 'unorderable', 'Nook Points', 'none', 'red', 'white', 'Striking', 'none');
insert into accf_accessory values(127, 0, 'Pumpkin Head', 'unorderable', 'Jack', 'none', 'orange', 'orange', 'Fancy', 'none');
insert into accf_accessory values(128, 0, 'King Tut Mask', 'normal', 'Ables', '12,000', 'yellow', 'blue', 'Strange', 'Egyptian Look');
insert into accf_accessory values(129, 0, 'Blue Frames', 'normal', 'Ables', '120', 'blue', 'blue', 'Funky', 'none');
insert into accf_accessory values(130, 0, 'Red Glasses', 'normal', 'Ables', '120', 'red', 'red', 'Fancy', 'none');
insert into accf_accessory values(131, 0, 'Yellow Glasses', 'normal', 'Ables', '120', 'yellow', 'yellow', 'Striking', 'none');
insert into accf_accessory values(132, 0, 'Mint Glasses', 'normal', 'Ables', '120', 'aqua', 'aqua', 'Refined', 'none');
insert into accf_accessory values(133, 0, 'Purple Glasses', 'normal', 'Ables', '120', 'purple', 'purple', 'Gaudy', 'none');
insert into accf_accessory values(134, 0, 'Green Glasses', 'normal', 'Ables', '120', 'green', 'green', 'Subtle', 'none');
insert into accf_accessory values(135, 0, 'Brown Glasses', 'normal', 'Ables', '120', 'brown', 'brown', 'Fresh', 'none');
insert into accf_accessory values(136, 0, 'Pink Glasses', 'normal', 'Ables', '120', 'pink', 'pink', 'Cute', 'none');
insert into accf_accessory values(137, 0, 'Thick Glasses', 'normal', 'Ables', '160', 'black', 'black', 'Cool', 'none');
insert into accf_accessory values(138, 0, 'Silver Frames', 'normal', 'Ables', '120', 'gray', 'gray', 'Fancy', 'none');
insert into accf_accessory values(139, 0, 'Rimmed Glasses', 'normal', 'Ables', '120', 'aqua', 'black', 'Funky', 'none');
insert into accf_accessory values(140, 0, 'Funky Glasses', 'normal', 'Ables', '120', 'purple', 'purple', 'Strange', 'none');
insert into accf_accessory values(141, 0, 'Tortoise Specs', 'unorderable', 'GracieGrace', '5,200', 'brown', 'brown', 'Fancy', 'none');
insert into accf_accessory values(142, 0, 'Gracie Glasses', 'unorderable', 'GracieGrace', '6,200', 'blue', 'colorful', 'Striking', 'none');
insert into accf_accessory values(143, 0, 'Pilot Shades', 'normal', 'Ables', '2,400', 'black', 'black', 'Striking', 'none');
insert into accf_accessory values(144, 0, 'Sporty Shades', 'normal', 'Ables', '160', 'blue', 'blue', 'Refined', 'none');
insert into accf_accessory values(145, 0, 'Huge Shades', 'normal', 'Ables', '160', 'red', 'black', 'Gaudy', 'none');
insert into accf_accessory values(146, 0, 'Triangle Shades', 'normal', 'Ables', '120', 'black', 'black', 'Subtle', 'none');
insert into accf_accessory values(147, 0, 'Tiny Shades', 'normal', 'Ables', '120', 'black', 'black', 'Fresh', 'none');
insert into accf_accessory values(148, 0, 'Heart Shades', 'unorderable', 'GracieGrace', '4,800', 'pink', 'black', 'Funky', 'none');
insert into accf_accessory values(149, 0, 'Star Shades', 'unorderable', 'GracieGrace', '4,800', 'yellow', 'black', 'Funky', 'none');
insert into accf_accessory values(150, 0, '3-D Glasses', 'normal', 'Ables', '120', 'red', 'blue', 'Cute', 'none');
insert into accf_accessory values(151, 0, 'Masquerade Mask', 'unorderable', 'GracieGrace', '4,800', 'white', 'white', 'Cool', 'Masquerade Look');
insert into accf_accessory values(152, 0, 'Superhero Mask', 'normal', 'Ables', '1,200', 'black', 'black', 'Fancy', 'none');
insert into accf_accessory values(153, 0, 'Goggles', 'normal', 'Ables', '280', 'aqua', 'black', 'Funky', 'none');
insert into accf_accessory values(154, 0, 'Snorkel Mask', 'normal', 'Ables', '320', 'aqua', 'black', 'Subtle', 'none');
insert into accf_accessory values(155, 0, 'Eye Mask', 'normal', 'Ables', '160', 'green', 'green', 'Strange', 'none');
insert into accf_accessory values(156, 0, 'HMD', 'normal', 'Ables', '1,800', 'gray', 'gray', 'Striking', 'none');
insert into accf_accessory values(157, 0, 'Monocle', 'normal', 'Ables', '240', 'aqua', 'gray', 'Refined', 'none');
insert into accf_accessory values(158, 0, 'Doctor''s Mirror', 'normal', 'Ables', '160', 'gray', 'gray', 'Subtle', 'Doctor Look');
insert into accf_accessory values(159, 0, 'Eye Patch', 'normal', 'Ables', '120', 'black', 'black', 'Cool', 'none');
insert into accf_accessory values(160, 0, 'Post-Op Patch', 'normal', 'Ables', '120', 'white', 'white', 'Fresh', 'none');
insert into accf_accessory values(161, 0, 'Gas Mask', 'normal', 'Ables', '240', 'gray', 'gray', 'Striking', 'none');
insert into accf_accessory values(162, 0, 'Hockey Mask', 'normal', 'Ables', '200', 'white', 'white', 'Cool', 'none');
insert into accf_accessory values(163, 0, 'Clown Mask', 'normal', 'Ables', '640', 'black', 'white', 'Striking', 'none');
insert into accf_accessory values(164, 0, 'Red Nose', 'normal', 'Ables', '80', 'red', 'red', 'Striking', 'none');
insert into accf_accessory values(165, 0, 'Stache & Glasses', 'normal', 'Ables', '240', 'red', 'black', 'Funky', 'none');
insert into accf_accessory values(166, 0, 'Big Bro Mustache', 'normal', 'Ables', '600', 'black', 'black', 'Strange', 'none');
insert into accf_accessory values(167, 0, 'Bad Bro Stache', 'unorderable', 'Nook Points', 'none', 'black', 'black', 'Striking', 'none');
insert into accf_accessory values(168, 0, 'Curly Mustache', 'normal', 'Ables', '160', 'black', 'black', 'Striking', 'none');
insert into accf_accessory values(169, 0, 'King''s Beard', 'normal', 'Ables', '8,000', 'white', 'white', 'Refined', 'none');
insert into accf_accessory values(170, 0, 'Doctor''s Mask', 'normal', 'Ables', '80', 'white', 'white', 'Fresh', 'none');
insert into accf_accessory values(171, 0, 'Pacifier', 'normal', 'Ables', '120', 'pink', 'pink', 'Cute', 'none');
insert into accf_accessory values(172, 0, 'Beak', 'normal', 'Ables', '640', 'yellow', 'yellow', 'Strange', 'none');
insert into accf_accessory values(173, 0, 'Lemon Pack', 'normal', 'Ables', '360', 'yellow', 'yellow', 'Striking', 'none');
insert into accf_accessory values(174, 0, 'Cucumber Pack', 'normal', 'Ables', '360', 'green', 'green', 'Striking', 'none');
insert into accf_accessory values(175, 0, 'Bandage', 'normal', 'Ables', '80', 'brown', 'brown', 'Cool', 'none');