drop table if exists accf_carpet;
create table accf_carpet ("Index" int, Selected int, Name varchar(63), Status varchar(31), "From" varchar(31), Price varchar(31), Series varchar(31));
insert into accf_carpet values(1, 0, 'Exotic Rug', 'normal', 'Nook''s', '1,820', 'Exotic Series');
insert into accf_carpet values(2, 0, 'Lovely Carpet', 'normal', 'Nook''s', '1,980', 'Lovely Series');
insert into accf_carpet values(3, 0, 'Classic Carpet', 'normal', 'Nook''s', '2,300', 'Classic Series');
insert into accf_carpet values(4, 0, 'Ranch Flooring', 'normal', 'Nook''s', '1,750', 'Ranch Series');
insert into accf_carpet values(5, 0, 'Cabana Flooring', 'normal', 'Nook''s', '1,680', 'Cabana Series');
insert into accf_carpet values(6, 0, 'Blue Flooring', 'normal', 'Nook''s', '1,580', 'Blue Series');
insert into accf_carpet values(7, 0, 'Modern Tile', 'normal', 'Nook''s', '1,540', 'Modern Series');
insert into accf_carpet values(8, 0, 'Regal Carpet', 'normal', 'Nook''s', '2,850', 'Regal Series');
insert into accf_carpet values(9, 0, 'Green Rug', 'normal', 'Nook''s', '1,540', 'Green Series');
insert into accf_carpet values(10, 0, 'Cabin Rug', 'normal', 'Nook''s', '1,540', 'Cabin Series');
insert into accf_carpet values(11, 0, 'Kiddie Carpet', 'normal', 'Nook''s', '1,630', 'Kiddie Series');
insert into accf_carpet values(12, 0, 'Robo-Floor', 'normal', 'Nook''s', '2,400', 'Robo Series');
insert into accf_carpet values(13, 0, 'Snowman Carpet', 'unorderable', 'Snowman', '8,888', 'Snowman Series');
insert into accf_carpet values(14, 0, 'Forest Floor', 'unorderable', 'mushrooms', '420', 'Mushroom Series');
insert into accf_carpet values(15, 0, 'Pave Floor', 'unorderable', 'Pave', '1,800', 'Pave Series');
insert into accf_carpet values(16, 0, 'Egg Floor', 'unorderable', 'Zipper T. Bunny', '8,888', 'Egg Series');
insert into accf_carpet values(17, 0, 'Spooky Carpet', 'unorderable', 'Jack', '10,310', 'Spooky Series');
insert into accf_carpet values(18, 0, 'Harvest Rug', 'unorderable', 'Franklin', '1,200', 'Harvest Series');
insert into accf_carpet values(19, 0, 'Jingle Carpet', 'unorderable', 'Jingle', '12,240', 'Jingle Series');
insert into accf_carpet values(20, 0, 'Princess Carpet', 'unorderable', 'GracieGrace', '124,000', 'Princess Series');
insert into accf_carpet values(21, 0, 'Gracie Carpet', 'unorderable', 'GracieGrace', '124,000', 'Gracie Series');
insert into accf_carpet values(22, 0, 'Sweets Floor', 'unorderable', 'GracieGrace', '124,000', 'Sweets Series');
insert into accf_carpet values(23, 0, 'Gorgeous Floor', 'unorderable', 'GracieGrace', '124,000', 'Gorgeous Series');
insert into accf_carpet values(24, 0, 'Western Desert', 'unorderable', 'Saharah', '1,700', 'Western Theme');
insert into accf_carpet values(25, 0, 'Lunar Surface', 'unorderable', 'Saharah', '2,000', 'Space Theme');
insert into accf_carpet values(26, 0, 'Closed Road', 'unorderable', 'Saharah', '1,625', 'Construction Theme');
insert into accf_carpet values(27, 0, 'Boxing Ring Mat', 'unorderable', 'Saharah', '2,500', 'Boxing Theme');
insert into accf_carpet values(28, 0, 'Backyard Lawn', 'normal', 'Nook''s', '880', 'Backyard Theme');
insert into accf_carpet values(29, 0, 'Playroom Rug', 'normal', 'Nook''s', '1,360', 'Nursery Theme');
insert into accf_carpet values(30, 0, 'Ship Deck', 'unorderable', 'Pascal', '1,000', 'Pirate Theme');
insert into accf_carpet values(31, 0, 'Lab Floor', 'normal', 'Nook''s', '1,280', 'Mad Scientist Theme');
insert into accf_carpet values(32, 0, 'Classroom Floor', 'unorderable', 'Saharah', '1,500', 'none');
insert into accf_carpet values(33, 0, 'Bath Tile', 'unorderable', 'Saharah', '1,700', 'Bath Theme');
insert into accf_carpet values(34, 0, 'Pastel-Dot Rug', 'normal', 'Nook''s', '1,300', 'none');
insert into accf_carpet values(35, 0, 'Checkered Tile', 'normal', 'Nook''s', '1,680', 'none');
insert into accf_carpet values(36, 0, 'Ceramic Tile', 'normal', 'Nook''s', '1,390', 'none');
insert into accf_carpet values(37, 0, 'Diner Tile', 'normal', 'Nook''s', '1,300', 'none');
insert into accf_carpet values(38, 0, 'Kitschy Tile', 'normal', 'Nook''s', '1,280', 'none');
insert into accf_carpet values(39, 0, 'Red Tile', 'normal', 'Nook''s', '1,680', 'none');
insert into accf_carpet values(40, 0, 'Mosaic Tile', 'normal', 'Nook''s', '2,300', 'none');
insert into accf_carpet values(41, 0, 'Chessboard Rug', 'unorderable', 'Saharah', '2,075', 'none');
insert into accf_carpet values(42, 0, 'Plaza Tile', 'normal', 'Nook''s', '2,180', 'none');
insert into accf_carpet values(43, 0, 'Palace Tile', 'normal', 'Nook''s', '3,200', 'none');
insert into accf_carpet values(44, 0, 'Imperial Tile', 'normal', 'Nook''s', '2,980', 'none');
insert into accf_carpet values(45, 0, 'Kitchen Tile', 'normal', 'Nook''s', '1,890', 'none');
insert into accf_carpet values(46, 0, 'Stone Tile', 'normal', 'Nook''s', '2,750', 'none');
insert into accf_carpet values(47, 0, 'Charcoal Tile', 'normal', 'Nook''s', '800', 'none');
insert into accf_carpet values(48, 0, 'Tatami', 'unorderable', 'Saharah', '2,125', 'none');
insert into accf_carpet values(49, 0, 'Planked Tatami', 'normal', 'Nook''s', '1,340', 'none');
insert into accf_carpet values(50, 0, 'Mossy Carpet', 'unorderable', 'Saharah', '2,000', 'none');
insert into accf_carpet values(51, 0, 'Sand Garden', 'unorderable', 'Saharah', '1,750', 'none');
insert into accf_carpet values(52, 0, 'Slate Flooring', 'normal', 'Nook''s', '1,380', 'none');
insert into accf_carpet values(53, 0, 'Concrete Floor', 'unorderable', 'Saharah', '1,800', 'none');
insert into accf_carpet values(54, 0, 'Basement Floor', 'unorderable', 'Saharah, Basements', '2,125', 'none');
insert into accf_carpet values(55, 0, 'Parquet Floor', 'normal', 'Nook''s', '2,350', 'none');
insert into accf_carpet values(56, 0, 'Old Board Floor', 'normal', 'Nook''s', '880', 'none');
insert into accf_carpet values(57, 0, 'Kitchen Flooring', 'normal', 'Nook''s', '1,230', 'none');
insert into accf_carpet values(58, 0, 'Music-Room Floor', 'unorderable', 'Saharah', '1,800', 'none');
insert into accf_carpet values(59, 0, 'Office Flooring', 'unorderable', 'Saharah', '1,700', 'none');
insert into accf_carpet values(60, 0, 'Opulent Rug', 'normal', 'Nook''s', '1,230', 'none');
insert into accf_carpet values(61, 0, 'Plush Carpet', 'normal', 'Nook''s', '2,160', 'none');
insert into accf_carpet values(62, 0, 'Ornate Rug', 'normal', 'Nook''s', '2,100', 'none');
insert into accf_carpet values(63, 0, 'Fancy Carpet', 'normal', 'Nook''s', '2,980', 'none');
insert into accf_carpet values(64, 0, 'Exquisite Rug', 'normal', 'Nook''s', '1,960', 'none');
insert into accf_carpet values(65, 0, 'Persian Rug', 'normal', 'Nook''s', '1,280', 'none');
insert into accf_carpet values(66, 0, 'Tartan Rug', 'normal', 'Nook''s', '1,820', 'none');
insert into accf_carpet values(67, 0, 'Round Carpet', 'normal', 'Nook''s', '1,080', 'none');
insert into accf_carpet values(68, 0, 'Citrus Carpet', 'normal', 'Nook''s', '1,330', 'none');
insert into accf_carpet values(69, 0, 'Cowhide Rug', 'normal', 'Nook''s', '1,540', 'none');
insert into accf_carpet values(70, 0, 'Birch Flooring', 'normal', 'Nook''s', '800', 'none');
insert into accf_carpet values(71, 0, 'Plank Flooring', 'normal', 'Nook''s', '800', 'none');
insert into accf_carpet values(72, 0, 'Bamboo Flooring', 'normal', 'Nook''s', '1,360', 'none');
insert into accf_carpet values(73, 0, 'Steel Flooring', 'normal', 'Nook''s', '1,480', 'none');
insert into accf_carpet values(74, 0, 'Shanty Mat', 'normal', 'Nook''s', '720', 'none');
insert into accf_carpet values(75, 0, 'Ancient Tile', 'unorderable', 'Saharah', '2,400', 'none');
insert into accf_carpet values(76, 0, 'Illusion Floor', 'normal', 'Nook''s', '1,600', 'none');
insert into accf_carpet values(77, 0, 'Daisy Meadow', 'unorderable', 'Saharah', '1,800', 'none');
insert into accf_carpet values(78, 0, 'Tropical Floor', 'unorderable', 'Saharah', '2,050', 'none');
insert into accf_carpet values(79, 0, 'Saharah''s Desert', 'unorderable', 'Saharah', '1,800', 'none');
insert into accf_carpet values(80, 0, 'Sandlot', 'unorderable', 'Saharah', '1,700', 'none');
insert into accf_carpet values(81, 0, 'Sidewalk', 'unorderable', 'Saharah', '1,950', 'none');
insert into accf_carpet values(82, 0, 'Cloud Flooring', 'normal', 'Nook''s', '1,480', 'none');
insert into accf_carpet values(83, 0, 'Common Floor', 'normal', 'Nook''s', '1,280', 'none');
insert into accf_carpet values(84, 0, 'Block Floor', 'unorderable', 'Balloon', '256', 'Mario Theme');
