drop table if exists accf_insect;
create table accf_insect ("Index" int, Selected int, Name varchar(63), Absent varchar(31), Price varchar(31), "Size" varchar(7), "From" varchar(31), Times varchar(255));
insert into accf_insect values(1, 0, 'Common Butterfly', 'raining', '90', '50mm', 'near flowers', 'March through June, 4am to 7pm (best time is 8am to 5pm) September, 8am to 4pm');
insert into accf_insect values(2, 0, 'Yellow Butterfly', 'raining', '90', '50mm', 'near flowers', 'March through June, 4am to 7pm (best time is 8am to 5pm) September, 8am to 4pm');
insert into accf_insect values(3, 0, 'Tiger Butterfly', 'raining', '160', '90mm', 'near red and pink flowers', 'March through June, 4am to 7pm (best time is 8am to 5pm) July through August, 8am to 5pm September, 8am to 4pm');
insert into accf_insect values(4, 0, 'Peacock Butterfly', 'raining', '220', '105mm', 'near blue, purple and black flowers', 'March through June, 4am to 7pm (best time is 8am to 5pm, May through June) July through August, 8am to 5pm September, 8am to 4pm');
insert into accf_insect values(5, 0, 'Monarch Butterfly', 'raining', '140', '85mm', 'near flowers', 'September through October, 4am to 5pm November, 8am to 5pm (best time is 8am to 4pm, October through November)');
insert into accf_insect values(6, 0, 'Emperor Butterfly', 'raining', '2,500', '115mm', 'near flowers', 'June through September, 7pm to 8am');
insert into accf_insect values(7, 0, 'Agrias Butterfly', 'raining', '3,000', '42mm', 'near flowers', 'June through September, 8am to 5pm');
insert into accf_insect values(8, 0, 'Raja Brooke Butterfly', 'raining', '2,500', '140mm', 'near freshwater', 'May through September, 8am to 5pm');
insert into accf_insect values(9, 0, 'Birdwing Butterfly', 'raining', '4,000', '260mm', 'near flowers', 'June through September,8am to 4pm');
insert into accf_insect values(10, 0, 'Moth', 'raining/gate open', '60', '60mm', 'near outdoor lights', 'May through September, 7pm to 4am (best time is June through August)');
insert into accf_insect values(11, 0, 'Oak Silk Moth', 'never', '1,200', '280mm', 'trees', 'June through September, 7pm to 4am');
insert into accf_insect values(12, 0, 'Honeybee', 'raining/gate open', '100', '13mm', 'near flowers', 'March through June, 8am to 5pm; July, 8am to 4pm');
insert into accf_insect values(13, 0, 'Bee', 'gate open', '2,500', '38mm', 'in trees', 'all year, all day');
insert into accf_insect values(14, 0, 'Long Locust', 'raining', '200', '73mm', 'ground', 'May through November, 8am to 7pm (best time is September through November)');
insert into accf_insect values(15, 0, 'Migratory Locust', 'raining', '600', '58mm', 'ground', 'August through November, 8am to 7pm (best time is 8am to 4pm)');
insert into accf_insect values(16, 0, 'Mantis', 'raining', '430', '82mm', 'flowers', 'April through November, 8am to 5pm (best time is 8am to 4pm, September through November)');
insert into accf_insect values(17, 0, 'Orchid Mantis', 'raining', '2,400', '35mm', 'flowers (more commwhite flowers)', 'April through November, 8am to 5pm');
insert into accf_insect values(18, 0, 'Brown Cicada', 'never', '200', '58mm', 'trees', 'July through August, 8am to 5pm (best time is 8am to 4pm)');
insert into accf_insect values(19, 0, 'Robust Cicada', 'never', '300', '60mm', 'trees', 'July through August, 8am to 5pm (best time is 8am to 4pm)');
insert into accf_insect values(20, 0, 'Walker Cicada', 'never', '400', '44mm', 'trees', 'July through September, 8am to 5pm (best time is August)');
insert into accf_insect values(21, 0, 'Evening Cicada', 'never', '550', '45mm', 'trees', 'July through August, 4am to 8am and 4pm to 7pm');
insert into accf_insect values(22, 0, 'Lantern Fly', 'never', '1,800', '70mm', 'trees', 'June and September, 4pm to 7pm and 11pm to 8am July through August, 4pm to 8am');
insert into accf_insect values(23, 0, 'Red Dragonfly', 'raining', '80', '38mm', 'in air', 'September through October, 8am to 7pm (best time is 4pm to 5pm)');
insert into accf_insect values(24, 0, 'Darner Dragonfly', 'raining', '200', '76mm', 'in air', 'June through August, 8am to 5pm (best time is 4pm to 5pm)');
insert into accf_insect values(25, 0, 'Banded Dragonfly', 'raining', '4,500', '90mm', 'in air', 'July through August, 8am to 5pm');
insert into accf_insect values(26, 0, 'Giant Petaltail', 'raining', '8,000', '160mm', 'in air', 'August through October, 5pm to 7pm');
insert into accf_insect values(27, 0, 'Ant', 'gate open', '80', '5mm', 'candy and spoiled turnips', 'all year, all day');
insert into accf_insect values(28, 0, 'Pondskater', 'raining/gate open', '130', '14mm', 'freshwater', 'May through September,8am to 7pm');
insert into accf_insect values(29, 0, 'Diving Beetle', 'never', '800', '38mm', 'in river', 'May through September, 8am to 5pm');
insert into accf_insect values(30, 0, 'Snail', 'never', '250', '45mm', 'flowers, usually during rain', 'April through September, all day (best time is May through June)');
insert into accf_insect values(31, 0, 'Cricket', 'raining', '130', '28mm', 'ground', 'September through November, 5pm to 8am');
insert into accf_insect values(32, 0, 'Bell Cricket', 'raining', '430', '18mm', 'ground', 'September through October, 5pm to 8am');
insert into accf_insect values(33, 0, 'Grasshopper', 'raining', '160', '43mm', 'ground', 'July, 4pm to 5pm August through September, 8am to 5pm (best time is September)');
insert into accf_insect values(34, 0, 'Mole Cricket', 'never', '280', '35mm', 'underground', 'November through May, all day');
insert into accf_insect values(35, 0, 'Walking Leaf', 'gate open', '600', '70mm', 'bottom of tree', 'July through September, 8am to 5pm');
insert into accf_insect values(36, 0, 'Walkingstick', 'never', '600', '85mm', 'trees', 'July through August, 4am to 8am and 5pm to 7pm September through November, 4am to 7pm');
insert into accf_insect values(37, 0, 'Bagworm', 'gate open', '300', '50mm', 'in trees', 'October through February, all day (best time is November through December, 8am to 7pm)');
insert into accf_insect values(38, 0, 'Ladybug', 'raining', '200', '8mm', 'flowers', 'March through June and October, 8am to 5pm (best time is March through May)');
insert into accf_insect values(39, 0, 'Violin Beetle', 'raining', '260', '260mm', 'tree stumps', 'June, 4am to 7pm September through October, 4am to 5pm November, 8am to 5pm');
insert into accf_insect values(40, 0, 'Longhorn Beetle', 'raining', '260', '30mm', 'tree stumps', 'July through August, 11pm to 7pm');
insert into accf_insect values(41, 0, 'Dung Beetle', 'gate open', '800', '35mm', 'near snowballs', 'December through February, 5pm to 8am');
insert into accf_insect values(42, 0, 'Firefly', 'raining', '300', '15mm', 'near freshwater', 'June, 7pm to 4am');
insert into accf_insect values(43, 0, 'Fruit Beetle', 'never', '100', '23mm', 'trees', 'July through August, all day (best time is 5pm to 4am) September, 7pm to 8am');
insert into accf_insect values(44, 0, 'Scarab Beetle', 'never', '6,000', '25mm', 'trees', 'July through August, 11pm to 8am');
insert into accf_insect values(45, 0, 'Jewel Beetle', 'never', '2,400', '35mm', 'trees', 'July through August, 8am to 5pm');
insert into accf_insect values(46, 0, 'Miyama Stag', 'never', '1,000', '60mm', 'trees', 'July through August, all day (best time is August, 7pm to 8am)');
insert into accf_insect values(47, 0, 'Saw Stag Beetle', 'never', '2,000', '65mm', 'trees', 'July through August, all day');
insert into accf_insect values(48, 0, 'Giant Beetle', 'never', '10,000', '60mm', 'trees', 'July through August, 11pm to 8am');
insert into accf_insect values(49, 0, 'Rainbow Stag', 'never', '10,000', '60mm', 'trees', 'June and September, 7pm to 8am July through August, 5pm to 8am');
insert into accf_insect values(50, 0, 'Cyclommatus', 'never', '8,000', '105mm', 'coconut palms', 'July through August, 5pm to 8am');
insert into accf_insect values(51, 0, 'Golden Stag', 'never', '12,000', '80mm', 'coconut palms', 'July through August, 5pm to 8am');
insert into accf_insect values(52, 0, 'Dynastid Beetle', 'never', '1,350', '80mm', 'trees', 'July through August, 5pm to 8am (best time is 11pm to 8am)');
insert into accf_insect values(53, 0, 'Atlas Beetle', 'never', '8,000', '120mm', 'coconut palms', 'July through August,5pm to 8am');
insert into accf_insect values(54, 0, 'Elephant Beetle', 'never', '8,000', '115mm', 'coconut palms', 'July through August, 5pm to 8am');
insert into accf_insect values(55, 0, 'Hercules Beetle', 'never', '12,000', '160mm', 'coconut palms', 'July through August, 5pm to 8am');
insert into accf_insect values(56, 0, 'Goliath Beetle', 'never', '6,000', '90mm', 'coconut palms', 'June and September,7pm to 8am July through August, 5pm to 8am');
insert into accf_insect values(57, 0, 'Flea', 'gate open', '70', '2mm', 'villager', 'March through November, all day');
insert into accf_insect values(58, 0, 'Pillbug', 'never', '250', '10mm', 'under rocks', 'all year, all day (best time is November through March)');
insert into accf_insect values(59, 0, 'Mosquito', 'raining/gate open', '130', '6mm', 'in air', 'June through September, 5pm to 4am (best time is 7pm to 11pm)');
insert into accf_insect values(60, 0, 'Fly', 'gate open', '60', '9mm', 'near garbage, rafflesia or spoiled turnips', 'all year, all day');
insert into accf_insect values(61, 0, 'Centipede', 'never', '300', '120mm', 'under rocks', 'June through February, 4pm to 11pm');
insert into accf_insect values(62, 0, 'Spider', 'gate open', '300', '25mm', 'in trees', 'March through June and September, all day (best times are 4pm to 8am, April through May; 7pm to 8am, September) July through August, 7pm to 8am October, 11pm to 4pm');
insert into accf_insect values(63, 0, 'Tarantula', 'raining/gate open', '8,000', '65mm', 'ground', 'June through August, 7pm to 4am');
insert into accf_insect values(64, 0, 'Scorpion', 'raining/gate open', '8,000', '160mm', 'ground', 'July through September, 7pm to 4am');
