drop table if exists accf_painting;
create table accf_painting ("Index" int, Selected int, Name varchar(63), Status varchar(31), "From" varchar(31), Price varchar(31), Color1 varchar(31), Color2 varchar(31));
insert into accf_painting values(1, 0, 'Dynamic Painting', 'unorderable', 'Crazy Redd', '3,920', 'black', 'brown');
insert into accf_painting values(2, 0, 'Solemn Painting', 'unorderable', 'Crazy Redd', '3,920', 'black', 'brown');
insert into accf_painting values(3, 0, 'Quaint Painting', 'unorderable', 'Crazy Redd', '3,920', 'white', 'brown');
insert into accf_painting values(4, 0, 'Basic Painting', 'unorderable', 'Spotlight', '1,960', 'blue', 'brown');
insert into accf_painting values(5, 0, 'Famous Painting', 'unorderable', 'Crazy Redd', '3,920', 'brown', 'brown');
insert into accf_painting values(6, 0, 'Perfect Painting', 'unorderable', 'Crazy Redd', '3,920', 'white', 'brown');
insert into accf_painting values(7, 0, 'Amazing Painting', 'unorderable', 'Crazy Redd', '3,920', 'black', 'brown');
insert into accf_painting values(8, 0, 'Nice Painting', 'unorderable', 'Crazy Redd', '3,920', 'red', 'brown');
insert into accf_painting values(9, 0, 'Moving Painting', 'unorderable', 'Crazy Redd', '3,920', 'white', 'brown');
insert into accf_painting values(10, 0, 'Common Painting', 'unorderable', 'Spotlight', '1,960', 'yellow', 'brown');
insert into accf_painting values(11, 0, 'Flowery Painting', 'unorderable', 'Crazy Redd', '3,920', 'yellow', 'brown');
insert into accf_painting values(12, 0, 'Warm Painting', 'unorderable', 'Crazy Redd', '3,920', 'black', 'brown');
insert into accf_painting values(13, 0, 'Jolly Painting', 'unorderable', 'Crazy Redd', '3,920', 'yellow', 'brown');
insert into accf_painting values(14, 0, 'Fine Painting', 'unorderable', 'Crazy Redd', '3,920', 'colorful', 'brown');
insert into accf_painting values(15, 0, 'Scary Painting', 'unorderable', 'Crazy Redd', '3,920', 'gray', 'brown');
insert into accf_painting values(16, 0, 'Proper Painting', 'unorderable', 'Crazy Redd', '3,920', 'orange', 'brown');
insert into accf_painting values(17, 0, 'Strange Painting', 'unorderable', 'Crazy Redd', '3,920', 'black', 'brown');
insert into accf_painting values(18, 0, 'Worthy Painting', 'unorderable', 'Crazy Redd', '3,920', 'black', 'brown');
insert into accf_painting values(19, 0, 'Calm Painting', 'unorderable', 'Crazy Redd', '3,920', 'colorful', 'brown');
insert into accf_painting values(20, 0, 'Moody Painting', 'unorderable', 'Crazy Redd', '3,920', 'colorful', 'brown');
insert into accf_painting values(21, 0, 'Wistful Painting', 'unorderable', 'Crazy Redd', '3,920', 'colorful', 'brown');
insert into accf_painting values(22, 0, 'Serene Painting', 'unorderable', 'Crazy Redd', '3,920', 'colorful', 'brown');
insert into accf_painting values(23, 0, 'Scenic Painting', 'unorderable', 'Crazy Redd', '3,920', 'colorful', 'brown');