drop table if exists accf_song
create table accf_song ("Index" int primary key, Selected int, Name varchar(50))
insert into accf_song values(1, 0, 'K.K. Chorale')
insert into accf_song values(2, 0, 'K.K. March')
insert into accf_song values(3, 0, 'K.K. Waltz')
insert into accf_song values(4, 0, 'K.K. Swing')
insert into accf_song values(5, 0, 'K.K. Jazz')
insert into accf_song values(6, 0, 'K.K. Fusion')
insert into accf_song values(7, 0, 'K.K. Etude (the "E" has an accent)')
insert into accf_song values(8, 0, 'K.K. Lullaby')
insert into accf_song values(9, 0, 'K.K. Aria')
insert into accf_song values(10, 0, 'K.K. Samba')
insert into accf_song values(11, 0, 'K.K. Bossa')
insert into accf_song values(12, 0, 'K.K. Calypso')
insert into accf_song values(13, 0, 'K.K. Salsa')
insert into accf_song values(14, 0, 'K.K. Mambo')
insert into accf_song values(15, 0, 'K.K. Reggae')
insert into accf_song values(16, 0, 'K.K. Ska')
insert into accf_song values(17, 0, 'K.K. Tango')
insert into accf_song values(18, 0, 'K.K. Faire')
insert into accf_song values(19, 0, 'Aloha K.K.')
insert into accf_song values(20, 0, 'Lucky K.K.')
insert into accf_song values(21, 0, 'K.K. Condor')
insert into accf_song values(22, 0, 'K.K. Steppe')
insert into accf_song values(23, 0, 'Imperial K.K.')
insert into accf_song values(24, 0, 'K.K. Casbah')
insert into accf_song values(25, 0, 'K.K. Safari')
insert into accf_song values(26, 0, 'K.K. Folk')
insert into accf_song values(27, 0, 'K.K. Rock')
insert into accf_song values(28, 0, 'Rockin'' K.K.')
insert into accf_song values(29, 0, 'K.K. Ragtime')
insert into accf_song values(30, 0, 'K.K. Gumbo')
insert into accf_song values(31, 0, 'The K. Funk')
insert into accf_song values(32, 0, 'K.K. Blues')
insert into accf_song values(33, 0, 'Soulful K.K.')
insert into accf_song values(34, 0, 'K.K. Soul')
insert into accf_song values(35, 0, 'K.K. Cruisin''')
insert into accf_song values(36, 0, 'K.K. Love Song')
insert into accf_song values(37, 0, 'K.K. D & B')
insert into accf_song values(38, 0, 'K.K. Technopop')
insert into accf_song values(39, 0, 'DJ K.K.')
insert into accf_song values(40, 0, 'Only Me')
insert into accf_song values(41, 0, 'K.K. Country')
insert into accf_song values(42, 0, 'Surfin'' K.K.')
insert into accf_song values(43, 0, 'K.K. Ballad')
insert into accf_song values(44, 0, 'Comrade K.K.')
insert into accf_song values(45, 0, 'K.K. Lament')
insert into accf_song values(46, 0, 'Go K.K. Rider!')
insert into accf_song values(47, 0, 'K.K. Dirge')
insert into accf_song values(48, 0, 'K.K. Western')
insert into accf_song values(49, 0, 'Mr. K.K.')
insert into accf_song values(50, 0, 'Cafe K.K. (the "e" has an accent)')
insert into accf_song values(51, 0, 'K.K. Parade')
insert into accf_song values(52, 0, 'Senor K.K. (the "n" has a tilde)')
insert into accf_song values(53, 0, 'K.K. Song')
insert into accf_song values(54, 0, 'I Love You')
insert into accf_song values(55, 0, 'Two Days Ago')
insert into accf_song values(56, 0, 'My Place')
insert into accf_song values(57, 0, 'Forest Life')
insert into accf_song values(58, 0, 'To the Edge')
insert into accf_song values(59, 0, 'Pondering')
insert into accf_song values(60, 0, 'K.K. Dixie')
insert into accf_song values(61, 0, 'K.K. Marathon')
insert into accf_song values(62, 0, 'King K.K.')
insert into accf_song values(63, 0, 'Mountain Song')
insert into accf_song values(64, 0, 'Marine Song 2001')
insert into accf_song values(65, 0, 'Neapolitan')
insert into accf_song values(66, 0, 'Steep Hill')
insert into accf_song values(67, 0, 'K.K. Rockabilly')
insert into accf_song values(68, 0, 'Agent K.K.')
insert into accf_song values(69, 0, 'K.K. Rally')
insert into accf_song values(70, 0, 'K.K. Metal')
insert into accf_song values(71, 0, 'Stale Cupcakes')
insert into accf_song values(72, 0, 'Spring Blossoms')
insert into accf_song values(73, 0, 'Wandering')
insert into accf_song values(74, 0, 'K.K. House')
insert into accf_song values(75, 0, 'K.K. Sonata')