drop table if exists accf_wallpaper;
create table accf_wallpaper ("Index" int, Selected int, Name varchar(63), Status varchar(31), "From" varchar(31), Price varchar(31), Series varchar(31));
insert into accf_wallpaper values(1, 0, 'Exotic Wall', 'normal', 'Nook''s', '1,420', 'Exotic Series');
insert into accf_wallpaper values(2, 0, 'Lovely Wall', 'normal', 'Nook''s', '1,880', 'Lovely Series');
insert into accf_wallpaper values(3, 0, 'Classic Wall', 'normal', 'Nook''s', '2,100', 'Classic Series');
insert into accf_wallpaper values(4, 0, 'Ranch Wall', 'normal', 'Nook''s', '1,450', 'Ranch Series');
insert into accf_wallpaper values(5, 0, 'Cabana Wall', 'normal', 'Nook''s', '1,480', 'Cabana Series');
insert into accf_wallpaper values(6, 0, 'Blue Wall', 'normal', 'Nook''s', '1,260', 'Blue Series');
insert into accf_wallpaper values(7, 0, 'Modern Wall', 'normal', 'Nook''s', '1,450', 'Modern Series');
insert into accf_wallpaper values(8, 0, 'Regal Wall', 'normal', 'Nook''s', '2,240', 'Regal Series');
insert into accf_wallpaper values(9, 0, 'Green Wall', 'normal', 'Nook''s', '1,050', 'Green Series');
insert into accf_wallpaper values(10, 0, 'Cabin Wall', 'normal', 'Nook''s', '1,200', 'Cabin Series');
insert into accf_wallpaper values(11, 0, 'Kiddie Wall', 'normal', 'Nook''s', '1,500', 'Kiddie Series');
insert into accf_wallpaper values(12, 0, 'Robo-Wall', 'normal', 'Nook''s', '1,780', 'Robo Series');
insert into accf_wallpaper values(13, 0, 'Snowman Wall', 'unorderable', 'Snowman', '8,888', 'Snowman Series');
insert into accf_wallpaper values(14, 0, 'Forest Wall', 'unorderable', 'mushrooms', '420', 'Mushroom Series');
insert into accf_wallpaper values(15, 0, 'Pave Wall', 'unorderable', 'Pave', '1,800', 'Pave Series');
insert into accf_wallpaper values(16, 0, 'Egg Wall', 'unorderable', 'Zipper T. Bunny', '8,888', 'Egg Series');
insert into accf_wallpaper values(17, 0, 'Spooky Wall', 'unorderable', 'Jack', '10,310', 'Spooky Series');
insert into accf_wallpaper values(18, 0, 'Harvest Wall', 'unorderable', 'Franklin', '1,200', 'Harvest Series');
insert into accf_wallpaper values(19, 0, 'Jingle Wall', 'unorderable', 'Jingle', '12,240', 'Jingle Series');
insert into accf_wallpaper values(20, 0, 'Princess Wall', 'unorderable', 'GracieGrace', '124,000', 'Princess Series');
insert into accf_wallpaper values(21, 0, 'Gracie Wallpaper', 'unorderable', 'GracieGrace', '124,000', 'Gracie Series');
insert into accf_wallpaper values(22, 0, 'Sweets Wall', 'unorderable', 'GracieGrace', '124,000', 'Sweets Series');
insert into accf_wallpaper values(23, 0, 'Gorgeous Wall', 'unorderable', 'GracieGrace', '124,000', 'Gorgeous Series');
insert into accf_wallpaper values(24, 0, 'Western Vista', 'unorderable', 'Saharah', '1,500', 'Western Theme');
insert into accf_wallpaper values(25, 0, 'Lunar Horizon', 'unorderable', 'Saharah', '1,900', 'Space Theme');
insert into accf_wallpaper values(26, 0, 'Blue Tarp', 'unorderable', 'Saharah', '1,400', 'Construction Theme');
insert into accf_wallpaper values(27, 0, 'Ringside Seating', 'unorderable', 'Saharah', '2,250', 'Boxing Theme');
insert into accf_wallpaper values(28, 0, 'Backyard Fence', 'normal', 'Nook''s', '800', 'Backyard Theme');
insert into accf_wallpaper values(29, 0, 'Playroom Wall', 'normal', 'Nook''s', '1,320', 'Nursery Theme');
insert into accf_wallpaper values(30, 0, 'Sea View', 'unorderable', 'Pascal', '1,000', 'Pirate Theme');
insert into accf_wallpaper values(31, 0, 'Lab Wall', 'normal', 'Nook''s', '1,460', 'Mad Scientist Theme');
insert into accf_wallpaper values(32, 0, 'Classroom Wall', 'unorderable', 'Saharah', '1,500', 'none');
insert into accf_wallpaper values(33, 0, 'Bathhouse Wall', 'unorderable', 'Saharah', '1,500', 'Bath Theme');
insert into accf_wallpaper values(34, 0, 'Pastel-Dot Wall', 'normal', 'Nook''s', '1,480', 'none');
insert into accf_wallpaper values(35, 0, 'Parlor Wall', 'normal', 'Nook''s', '1,120', 'none');
insert into accf_wallpaper values(36, 0, 'Mod Wall', 'normal', 'Nook''s', '1,200', 'none');
insert into accf_wallpaper values(37, 0, 'Kitschy Wall', 'normal', 'Nook''s', '1,240', 'none');
insert into accf_wallpaper values(38, 0, 'Groovy Wall', 'normal', 'Nook''s', '1,280', 'none');
insert into accf_wallpaper values(39, 0, 'Backgammon Wall', 'unorderable', 'Saharah', '1,800', 'none');
insert into accf_wallpaper values(40, 0, 'Mosaic Wall', 'normal', 'Nook''s', '2,100', 'none');
insert into accf_wallpaper values(41, 0, 'Blue-Trim Wall', 'normal', 'Nook''s', '1,420', 'none');
insert into accf_wallpaper values(42, 0, 'Plaster Wall', 'normal', 'Nook''s', '880', 'none');
insert into accf_wallpaper values(43, 0, 'Chic Wall', 'normal', 'Nook''s', '1,960', 'none');
insert into accf_wallpaper values(44, 0, 'Ornate Wall', 'normal', 'Nook''s', '1,580', 'none');
insert into accf_wallpaper values(45, 0, 'Citrus Wall', 'normal', 'Nook''s', '1,120', 'none');
insert into accf_wallpaper values(46, 0, 'Rose Wall', 'normal', 'Nook''s', '2,240', 'none');
insert into accf_wallpaper values(47, 0, 'Old Brick Wall', 'normal', 'Nook''s', '1,200', 'none');
insert into accf_wallpaper values(48, 0, 'Shoji Screen', 'unorderable', 'Saharah', '1,875', 'none');
insert into accf_wallpaper values(49, 0, 'Gold Screen Wall', 'normal', 'Nook''s', '2,180', 'none');
insert into accf_wallpaper values(50, 0, 'Tea-Room Wall', 'normal', 'Nook''s', '1,750', 'none');
insert into accf_wallpaper values(51, 0, 'Modern Screen', 'normal', 'Nook''s', '1,150', 'none');
insert into accf_wallpaper values(52, 0, 'Garden Wall', 'unorderable', 'Saharah', '1,600', 'none');
insert into accf_wallpaper values(53, 0, 'Mortar Wall', 'unorderable', 'Saharah', '1,750', 'none');
insert into accf_wallpaper values(54, 0, 'Stone Wall', 'normal', 'Nook''s', '800', 'none');
insert into accf_wallpaper values(55, 0, 'Concrete Wall', 'normal', 'Nook''s', '800', 'none');
insert into accf_wallpaper values(56, 0, 'Basement Wall', 'unorderable', 'Saharah', '1,875', 'none');
insert into accf_wallpaper values(57, 0, 'Shanty Wall', 'normal', 'Nook''s', '800', 'none');
insert into accf_wallpaper values(58, 0, 'Wood Paneling', 'normal', 'Nook''s', '1,320', 'none');
insert into accf_wallpaper values(59, 0, 'Floral Wall', 'normal', 'Nook''s', '2,250', 'none');
insert into accf_wallpaper values(60, 0, 'Kitchen Wall', 'normal', 'Nook''s', '1,120', 'none');
insert into accf_wallpaper values(61, 0, 'Music-Room Wall', 'unorderable', 'Saharah', '1,600', 'none');
insert into accf_wallpaper values(62, 0, 'Manor Wall', 'normal', 'Nook''s', '1,050', 'none');
insert into accf_wallpaper values(63, 0, 'Office Wall', 'unorderable', 'Saharah', '1,750', 'none');
insert into accf_wallpaper values(64, 0, 'Plaza Wall', 'normal', 'Nook''s', '1,960', 'none');
insert into accf_wallpaper values(65, 0, 'Lattice Wall', 'normal', 'Nook''s', '1,780', 'none');
insert into accf_wallpaper values(66, 0, 'Stately Wall', 'normal', 'Nook''s', '2,450', 'none');
insert into accf_wallpaper values(67, 0, 'Imperial Wall', 'normal', 'Nook''s', '2,660', 'none');
insert into accf_wallpaper values(68, 0, 'Arched Window', 'normal', 'Nook''s', '2,150', 'none');
insert into accf_wallpaper values(69, 0, 'Bamboo Wall', 'normal', 'Nook''s', '1,150', 'none');
insert into accf_wallpaper values(70, 0, 'Ivy Wall', 'normal', 'Nook''s', '1,250', 'none');
insert into accf_wallpaper values(71, 0, 'Ancient Wall', 'unorderable', 'Saharah', '2,300', 'none');
insert into accf_wallpaper values(72, 0, 'Exquisite Wall', 'normal', 'Nook''s', '1,470', 'none');
insert into accf_wallpaper values(73, 0, 'Persian Wall', 'normal', 'Nook''s', '1,480', 'none');
insert into accf_wallpaper values(74, 0, 'Industrial Wall', 'unorderable', 'Saharah', '1,875', 'none');
insert into accf_wallpaper values(75, 0, 'Library Wall', 'normal', 'Nook''s', '1,680', 'none');
insert into accf_wallpaper values(76, 0, 'Illusion Wall', 'normal', 'Nook''s', '1,360', 'none');
insert into accf_wallpaper values(77, 0, 'Meadow Vista', 'unorderable', 'Saharah', '2,000', 'none');
insert into accf_wallpaper values(78, 0, 'Tropical Vista', 'unorderable', 'Saharah', '2,300', 'none');
insert into accf_wallpaper values(79, 0, 'Desert Vista', 'unorderable', 'Saharah', '2,250', 'none');
insert into accf_wallpaper values(80, 0, 'Chainlink Fence', 'normal', 'Nook''s', '2,400', 'none');
insert into accf_wallpaper values(81, 0, 'Tree-Lined Wall', 'unorderable', 'Saharah', '1,850', 'none');
insert into accf_wallpaper values(82, 0, 'Sky Wall', 'normal', 'Nook''s', '1,200', 'none');
insert into accf_wallpaper values(83, 0, 'Cityscape Wall', 'normal', 'Nook''s', '1,600', 'none');
insert into accf_wallpaper values(84, 0, 'Dirt-Clod Wall', 'normal', 'Nook''s', '800', 'none');
insert into accf_wallpaper values(85, 0, 'Common Wall', 'normal', 'Nook''s', '1,240', 'none');
insert into accf_wallpaper values(86, 0, 'Mushroom Mural', 'unorderable', 'Balloon', '256', 'Mario Theme');
