drop table if exists acnh_accessory;
create table acnh_accessory ("Index" int, Selected int, Name varchar(63), Status varchar(31), Price varchar(31), "From" varchar(63), Style varchar(31));
insert into acnh_accessory values(1, 0, '3D glasses (White)', 'orderable', '490', 'Able Sisters', 'Active');
insert into acnh_accessory values(2, 0, '3D glasses (Black)', 'orderable', '490', 'Able Sisters', 'Active');
insert into acnh_accessory values(3, 0, 'bandage (Beige)', 'orderable', '140', 'Able Sisters', 'Active');
insert into acnh_accessory values(4, 0, 'beak (Yellow)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_accessory values(5, 0, 'birthday shades (Yellow)', 'unorderable', '620', 'Birthday', 'Gorgeous');
insert into acnh_accessory values(6, 0, 'birthday shades (Pink)', 'unorderable', '620', 'Birthday', 'Gorgeous');
insert into acnh_accessory values(7, 0, 'birthday shades (Red)', 'unorderable', '620', 'Birthday', 'Gorgeous');
insert into acnh_accessory values(8, 0, 'birthday shades (Blue)', 'unorderable', '620', 'Birthday', 'Gorgeous');
insert into acnh_accessory values(9, 0, 'bottom-rimmed glasses (Red)', 'orderable', '1100', 'Able Sisters', 'Simple');
insert into acnh_accessory values(10, 0, 'bottom-rimmed glasses (Purple)', 'orderable', '1100', 'Able Sisters', 'Simple');
insert into acnh_accessory values(11, 0, 'bottom-rimmed glasses (Green)', 'orderable', '1100', 'Able Sisters', 'Simple');
insert into acnh_accessory values(12, 0, 'bottom-rimmed glasses (Blue)', 'orderable', '1100', 'Able Sisters', 'Simple');
insert into acnh_accessory values(13, 0, 'bottom-rimmed glasses (Yellow)', 'orderable', '1100', 'Able Sisters', 'Simple');
insert into acnh_accessory values(14, 0, 'bottom-rimmed glasses (Pink)', 'orderable', '1100', 'Able Sisters', 'Simple');
insert into acnh_accessory values(15, 0, 'bottom-rimmed glasses (Black)', 'orderable', '1100', 'Able Sisters', 'Simple');
insert into acnh_accessory values(16, 0, 'browline glasses (Black)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_accessory values(17, 0, 'browline glasses (Brown)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_accessory values(18, 0, 'browline glasses (Green)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_accessory values(19, 0, 'browline glasses (Gray)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_accessory values(20, 0, 'bubblegum (Pink)', 'orderable', '140', 'Able Sisters', 'Simple');
insert into acnh_accessory values(21, 0, 'bubblegum (Blue)', 'orderable', '140', 'Able Sisters', 'Simple');
insert into acnh_accessory values(22, 0, 'bubblegum (Yellow)', 'orderable', '140', 'Able Sisters', 'Simple');
insert into acnh_accessory values(23, 0, 'bubblegum (Green)', 'orderable', '140', 'Able Sisters', 'Simple');
insert into acnh_accessory values(24, 0, 'bubblegum (White)', 'orderable', '140', 'Able Sisters', 'Simple');
insert into acnh_accessory values(25, 0, 'bunny nose (Pink)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(26, 0, 'bunny nose (Yellow)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(27, 0, 'bunny nose (White)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(28, 0, 'butterfly shades (Blue)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_accessory values(29, 0, 'butterfly shades (Red)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_accessory values(30, 0, 'butterfly shades (Brown)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_accessory values(31, 0, 'candy-skull mask (Purple)', 'unorderable', '800', 'Gulliver', 'Gorgeous');
insert into acnh_accessory values(32, 0, 'candy-skull mask (Orange)', 'unorderable', '800', 'Gulliver', 'Gorgeous');
insert into acnh_accessory values(33, 0, 'candy-skull mask (Blue)', 'unorderable', '800', 'Gulliver', 'Gorgeous');
insert into acnh_accessory values(34, 0, 'cat nose (White)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(35, 0, 'cat nose (Brown)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(36, 0, 'cat nose (Navy blue)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(37, 0, 'cucumber pack (Green)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_accessory values(38, 0, 'curly mustache (Black)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_accessory values(39, 0, 'cyber shades (Red)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(40, 0, 'cyber shades (Black)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(41, 0, 'cyber shades (Silver)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(42, 0, 'cyber shades (Purple)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(43, 0, 'cyber shades (Green)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(44, 0, 'cyber shades (Yellow)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(45, 0, 'DAL eye mask (Blue)', 'unorderable', '1010', 'Dodo Airlines', 'Simple');
insert into acnh_accessory values(46, 0, 'DAL sunglasses (Yellow)', 'unorderable', '1010', 'Dodo Airlines', 'Gorgeous');
insert into acnh_accessory values(47, 0, 'doctor''s mask (White)', 'orderable', '140', 'Able Sisters', 'Simple');
insert into acnh_accessory values(48, 0, 'dog nose (White)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(49, 0, 'dog nose (Beige)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(50, 0, 'dog nose (Black)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(51, 0, 'double-bridge glasses (Gold)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(52, 0, 'double-bridge glasses (Purple)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(53, 0, 'double-bridge glasses (Silver)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(54, 0, 'double-bridge glasses (Blue)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(55, 0, 'drinking-straw glasses (Green)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_accessory values(56, 0, 'drinking-straw glasses (Blue)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_accessory values(57, 0, 'drinking-straw glasses (Pink)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_accessory values(58, 0, 'drinking-straw glasses (White)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_accessory values(59, 0, 'eye mask (Blue)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_accessory values(60, 0, 'eye mask (Pink)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_accessory values(61, 0, 'eye mask (Gray)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_accessory values(62, 0, 'eye mask (Green)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_accessory values(63, 0, 'eye mask (Orange)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_accessory values(64, 0, 'eye mask (Red)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_accessory values(65, 0, 'eye patch (Black)', 'orderable', '140', 'Able Sisters', 'Cool');
insert into acnh_accessory values(66, 0, 'facial mask (White)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_accessory values(67, 0, 'fake nose (Red)', 'orderable', '490', 'Able Sisters', 'Cute');
insert into acnh_accessory values(68, 0, 'flower sunglasses (Red)', 'orderable', '770', 'Able Sisters', 'Cute');
insert into acnh_accessory values(69, 0, 'flower sunglasses (Orange)', 'orderable', '770', 'Able Sisters', 'Cute');
insert into acnh_accessory values(70, 0, 'flower sunglasses (Blue)', 'orderable', '770', 'Able Sisters', 'Cute');
insert into acnh_accessory values(71, 0, 'flower sunglasses (Purple)', 'orderable', '770', 'Able Sisters', 'Cute');
insert into acnh_accessory values(72, 0, 'flower sunglasses (Green)', 'orderable', '770', 'Able Sisters', 'Cute');
insert into acnh_accessory values(73, 0, 'food mess (Pasta)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_accessory values(74, 0, 'funny glasses (Brown)', 'orderable', '1100', 'Able Sisters', 'Cute');
insert into acnh_accessory values(75, 0, 'funny glasses (Pink)', 'orderable', '1100', 'Able Sisters', 'Cute');
insert into acnh_accessory values(76, 0, 'funny glasses (Blue)', 'orderable', '1100', 'Able Sisters', 'Cute');
insert into acnh_accessory values(77, 0, 'gas mask (Black)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_accessory values(78, 0, 'gas mask (Avocado)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_accessory values(79, 0, 'glass-bottle glasses (Black)', 'orderable', '1100', 'Able Sisters', 'Simple');
insert into acnh_accessory values(80, 0, 'goatee (Black)', 'orderable', '980', 'Able Sisters', 'Cool');
insert into acnh_accessory values(81, 0, 'goggles (Black)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_accessory values(82, 0, 'goggles (Blue)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_accessory values(83, 0, 'goggles (Pink)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_accessory values(84, 0, 'goggles (Green)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_accessory values(85, 0, 'goggles (Purple)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_accessory values(86, 0, 'goggles (Red)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_accessory values(87, 0, 'handlebar mustache (Black)', 'orderable', '1120', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(88, 0, 'heart shades (Pink)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_accessory values(89, 0, 'heart shades (Yellow)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_accessory values(90, 0, 'heart shades (Blue)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_accessory values(91, 0, 'heart shades (Purple)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_accessory values(92, 0, 'heart shades (Green)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_accessory values(93, 0, 'HMD (White)', 'orderable', '2000', 'Able Sisters', 'Cool');
insert into acnh_accessory values(94, 0, 'jester''s mask (Black)', 'orderable', '1760', 'Able Sisters', 'Cool');
insert into acnh_accessory values(95, 0, 'jester''s mask (Red)', 'orderable', '1760', 'Able Sisters', 'Cool');
insert into acnh_accessory values(96, 0, 'jester''s mask (Green)', 'orderable', '1760', 'Able Sisters', 'Cool');
insert into acnh_accessory values(97, 0, 'jester''s mask (Blue)', 'orderable', '1760', 'Able Sisters', 'Cool');
insert into acnh_accessory values(98, 0, 'Labelle sunglasses (Twilight)', 'orderable', '2000', 'Labelle', 'Gorgeous');
insert into acnh_accessory values(99, 0, 'Labelle sunglasses (Midnight)', 'orderable', '2000', 'Labelle', 'Gorgeous');
insert into acnh_accessory values(100, 0, 'Labelle sunglasses (Passion)', 'orderable', '2000', 'Labelle', 'Gorgeous');
insert into acnh_accessory values(101, 0, 'Labelle sunglasses (Ocean)', 'orderable', '2000', 'Labelle', 'Gorgeous');
insert into acnh_accessory values(102, 0, 'Labelle sunglasses (Sunset)', 'orderable', '2000', 'Labelle', 'Gorgeous');
insert into acnh_accessory values(103, 0, 'Labelle sunglasses (Love)', 'orderable', '2000', 'Labelle', 'Gorgeous');
insert into acnh_accessory values(104, 0, 'ladder shades (Red)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_accessory values(105, 0, 'ladder shades (Blue)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_accessory values(106, 0, 'ladder shades (Green)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_accessory values(107, 0, 'ladder shades (Pink)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_accessory values(108, 0, 'ladder shades (Yellow)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_accessory values(109, 0, 'ladder shades (Gold)', 'orderable', '880', 'Able Sisters', 'Active');
insert into acnh_accessory values(110, 0, 'leaf', 'unorderable', '100', 'Crafting', 'Simple');
insert into acnh_accessory values(111, 0, 'masquerade mask (Purple)', 'orderable', '910', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(112, 0, 'masquerade mask (Black)', 'orderable', '910', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(113, 0, 'masquerade mask (Blue)', 'orderable', '910', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(114, 0, 'masquerade mask (Red)', 'orderable', '910', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(115, 0, 'masquerade mask (Green)', 'orderable', '910', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(116, 0, 'masquerade mask (Gold)', 'orderable', '910', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(117, 0, 'monocle (Black)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(118, 0, 'monocle (Gold)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(119, 0, 'monocle (Silver)', 'orderable', '1100', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(120, 0, 'night-vision goggles (Black)', 'orderable', '1560', 'Able Sisters', 'Active');
insert into acnh_accessory values(121, 0, 'Nook Inc. eye mask (Green)', 'unorderable', '2000', 'Nook Miles Shop', 'Simple');
insert into acnh_accessory values(122, 0, 'nose drip (Light blue)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_accessory values(123, 0, 'octagonal glasses (Gray)', 'orderable', '1100', 'Able Sisters', 'Cute');
insert into acnh_accessory values(124, 0, 'octagonal glasses (Green)', 'orderable', '1100', 'Able Sisters', 'Cute');
insert into acnh_accessory values(125, 0, 'octagonal glasses (Purple)', 'orderable', '1100', 'Able Sisters', 'Cute');
insert into acnh_accessory values(126, 0, 'octagonal glasses (Gold)', 'orderable', '1100', 'Able Sisters', 'Cute');
insert into acnh_accessory values(127, 0, 'octagonal glasses (Black)', 'orderable', '1100', 'Able Sisters', 'Cute');
insert into acnh_accessory values(128, 0, 'oval glasses (Green)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(129, 0, 'oval glasses (Orange)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(130, 0, 'oval glasses (Blue)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(131, 0, 'oval glasses (Purple)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(132, 0, 'oval glasses (Magenta)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(133, 0, 'oval glasses (Mustard)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(134, 0, 'oval glasses (Black)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(135, 0, 'pacifier (Baby purple)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(136, 0, 'pacifier (Baby mint)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(137, 0, 'pacifier (Baby yellow)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(138, 0, 'pacifier (Baby green)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(139, 0, 'pacifier (Baby pink)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(140, 0, 'pacifier (Baby gray)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(141, 0, 'pacifier (Baby blue)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(142, 0, 'pacifier (Baby orange)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(143, 0, 'pig nose (Pink)', 'orderable', '560', 'Able Sisters', 'Cute');
insert into acnh_accessory values(144, 0, 'pilot shades (Black)', 'orderable', '1300', 'Able Sisters', 'Cool');
insert into acnh_accessory values(145, 0, 'pilot shades (Gold)', 'orderable', '1300', 'Able Sisters', 'Cool');
insert into acnh_accessory values(146, 0, 'pixel shades (Red)', 'orderable', '1320', 'Able Sisters', 'Cool');
insert into acnh_accessory values(147, 0, 'pixel shades (Green)', 'orderable', '1320', 'Able Sisters', 'Cool');
insert into acnh_accessory values(148, 0, 'pixel shades (Blue)', 'orderable', '1320', 'Able Sisters', 'Cool');
insert into acnh_accessory values(149, 0, 'pixel shades (Black)', 'orderable', '1320', 'Able Sisters', 'Cool');
insert into acnh_accessory values(150, 0, 'pleather mask (Black)', 'orderable', '770', 'Able Sisters', 'Cool');
insert into acnh_accessory values(151, 0, 'post-op patch (White)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_accessory values(152, 0, 'privacy mask (Black)', 'orderable', '560', 'Able Sisters', 'Cool');
insert into acnh_accessory values(153, 0, 'reflector (Gray)', 'orderable', '560', 'Able Sisters', 'Cool');
insert into acnh_accessory values(154, 0, 'retro shades (Yellow)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(155, 0, 'retro shades (Green)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(156, 0, 'retro shades (Red)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(157, 0, 'retro shades (Purple)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(158, 0, 'retro shades (Blue)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(159, 0, 'retro shades (Gray)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(160, 0, 'rhinestone shades (Red)', 'orderable', '1040', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(161, 0, 'rhinestone shades (Ochre)', 'orderable', '1040', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(162, 0, 'rhinestone shades (Purple)', 'orderable', '1040', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(163, 0, 'rimmed glasses (Black)', 'orderable', '630', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(164, 0, 'rimmed glasses (Gold)', 'orderable', '630', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(165, 0, 'rimmed glasses (Gray)', 'orderable', '630', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(166, 0, 'rimmed glasses (Brown)', 'orderable', '630', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(167, 0, 'rimmed glasses (Purple)', 'orderable', '630', 'Able Sisters', 'Elegant');
insert into acnh_accessory values(168, 0, 'round shades (Black)', 'orderable', '1560', 'Able Sisters', 'Cool');
insert into acnh_accessory values(169, 0, 'round shades (Green)', 'orderable', '1560', 'Able Sisters', 'Cool');
insert into acnh_accessory values(170, 0, 'round shades (Blue)', 'orderable', '1560', 'Able Sisters', 'Cool');
insert into acnh_accessory values(171, 0, 'round shades (Yellow)', 'orderable', '1560', 'Able Sisters', 'Cool');
insert into acnh_accessory values(172, 0, 'round shades (Pink)', 'orderable', '1560', 'Able Sisters', 'Cool');
insert into acnh_accessory values(173, 0, 'round shades (Red)', 'orderable', '1560', 'Able Sisters', 'Cool');
insert into acnh_accessory values(174, 0, 'round shades (White)', 'orderable', '1560', 'Able Sisters', 'Cool');
insert into acnh_accessory values(175, 0, 'round shades (Purple)', 'orderable', '1560', 'Able Sisters', 'Cool');
insert into acnh_accessory values(176, 0, 'round tinted shades (Brown)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(177, 0, 'round tinted shades (Light brown)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(178, 0, 'round tinted shades (Dark brown)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(179, 0, 'round tinted shades (Green)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(180, 0, 'rounded beard (Black)', 'orderable', '980', 'Able Sisters', 'Cool');
insert into acnh_accessory values(181, 0, 'shattered glasses (Black)', 'unorderable', '10', 'Recycle bin', 'Simple');
insert into acnh_accessory values(182, 0, 'ski goggles (White)', 'orderable', '980', 'Able Sisters', 'Active');
insert into acnh_accessory values(183, 0, 'ski goggles (Yellow)', 'orderable', '980', 'Able Sisters', 'Active');
insert into acnh_accessory values(184, 0, 'ski goggles (Purple)', 'orderable', '980', 'Able Sisters', 'Active');
insert into acnh_accessory values(185, 0, 'ski goggles (Pink)', 'orderable', '980', 'Able Sisters', 'Active');
insert into acnh_accessory values(186, 0, 'ski goggles (Green)', 'orderable', '980', 'Able Sisters', 'Active');
insert into acnh_accessory values(187, 0, 'ski goggles (Orange)', 'orderable', '980', 'Able Sisters', 'Active');
insert into acnh_accessory values(188, 0, 'sporty shades (Black)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(189, 0, 'sporty shades (White)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(190, 0, 'sporty shades (Pink)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(191, 0, 'sporty shades (Lime)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(192, 0, 'sporty shades (Light blue)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_accessory values(193, 0, 'square glasses (Brown)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(194, 0, 'square glasses (Black)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(195, 0, 'square glasses (Gray)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(196, 0, 'square glasses (Blue)', 'orderable', '880', 'Able Sisters', 'Simple');
insert into acnh_accessory values(197, 0, 'stache & glasses (Black)', 'orderable', '770', 'Able Sisters', 'Cute');
insert into acnh_accessory values(198, 0, 'stache & glasses (Red)', 'orderable', '770', 'Able Sisters', 'Cute');
insert into acnh_accessory values(199, 0, 'star shades (Yellow)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(200, 0, 'star shades (Pink)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(201, 0, 'star shades (Blue)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(202, 0, 'star shades (Purple)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(203, 0, 'star shades (Green)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(204, 0, 'steampunk glasses (Green)', 'orderable', '1300', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(205, 0, 'steampunk glasses (Purple)', 'orderable', '1300', 'Able Sisters', 'Gorgeous');
insert into acnh_accessory values(206, 0, 'sticky rice (White)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_accessory values(207, 0, 'superhero mask (Black)', 'orderable', '1040', 'Able Sisters', 'Cool');
insert into acnh_accessory values(208, 0, 'tiny shades (Gold)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_accessory values(209, 0, 'tiny shades (Black)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_accessory values(210, 0, 'tiny shades (Berry red)', 'orderable', '1100', 'Able Sisters', 'Cool');
insert into acnh_accessory values(211, 0, 'tortoise specs (Brown)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_accessory values(212, 0, 'tortoise specs (Beige)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_accessory values(213, 0, 'tortoise specs (Black)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_accessory values(214, 0, 'triangle shades (Red)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(215, 0, 'triangle shades (Orange)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(216, 0, 'triangle shades (Blue)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(217, 0, 'triangle shades (Purple)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(218, 0, 'triangle shades (Green)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(219, 0, 'triangle shades (White)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(220, 0, 'triangle shades (Black)', 'orderable', '880', 'Able Sisters', 'Cute');
insert into acnh_accessory values(221, 0, 'wooden-frame glasses (Brown)', 'orderable', '1560', 'Able Sisters', 'Simple');
insert into acnh_accessory values(222, 0, 'wooden-frame glasses (Dark brown)', 'orderable', '1560', 'Able Sisters', 'Simple');
