drop table if exists acnh_hybrid;
create table acnh_hybrid ("Index" int primary key, Selected int, Name varchar(255), "From" varchar(63));
insert into acnh_hybrid values(1, 0, 'black-cosmos plant', 'Red/red cosmos');
insert into acnh_hybrid values(2, 0, 'black-lily plant', 'Red/red lilies');
insert into acnh_hybrid values(3, 0, 'black-rose plant', 'Red/red roses');
insert into acnh_hybrid values(4, 0, 'black-tulip plant', 'Red/red tulips');
insert into acnh_hybrid values(5, 0, 'blue-hyacinth plant', 'White/white hyacinths');
insert into acnh_hybrid values(6, 0, 'blue-pansy plant', 'White/white pansies');
insert into acnh_hybrid values(7, 0, 'blue-rose plant', 'Orange/orange roses');
insert into acnh_hybrid values(8, 0, 'blue-windflower plant', 'White/white windflowers or Orange/white windflowers');
insert into acnh_hybrid values(9, 0, 'gold-rose plant', 'Black/black roses Water with gold watering can');
insert into acnh_hybrid values(10, 0, 'green-mum plant', 'Purple/purple mums');
insert into acnh_hybrid values(11, 0, 'lily-of-the-valley plant', '5-star town status');
insert into acnh_hybrid values(12, 0, 'orange-cosmos plant', 'Red/yellow cosmos');
insert into acnh_hybrid values(13, 0, 'orange-hyacinth plant', 'Red/yellow hyacinths');
insert into acnh_hybrid values(14, 0, 'orange-lily plant', 'Red/yellow lilies');
insert into acnh_hybrid values(15, 0, 'orange-pansy plant', 'Red/yellow pansies');
insert into acnh_hybrid values(16, 0, 'orange-rose plant', 'Red/yellow roses');
insert into acnh_hybrid values(17, 0, 'orange-tulip plant', 'Red/yellow tulips');
insert into acnh_hybrid values(18, 0, 'pink-cosmos plant', 'Red/white cosmos');
insert into acnh_hybrid values(19, 0, 'pink-hyacinth plant', 'Red/white hyacinths');
insert into acnh_hybrid values(20, 0, 'pink-lily plant', 'Red/white lilies');
insert into acnh_hybrid values(21, 0, 'pink-mum plant', 'Red/white mums');
insert into acnh_hybrid values(22, 0, 'pink-rose plant', 'Red/white roses');
insert into acnh_hybrid values(23, 0, 'pink-tulip plant', 'Red/white tulips');
insert into acnh_hybrid values(24, 0, 'pink-windflower plant', 'Red/orange windflowers');
insert into acnh_hybrid values(25, 0, 'purple-hyacinth plant', 'Blue/blue hyacinths');
insert into acnh_hybrid values(26, 0, 'purple-mum plant', 'White/white mums');
insert into acnh_hybrid values(27, 0, 'purple-pansy plant', 'Blue/blue pansies');
insert into acnh_hybrid values(28, 0, 'purple-rose plant', 'White/white roses');
insert into acnh_hybrid values(29, 0, 'purple-tulip plant', 'Orange/orange tulips');
insert into acnh_hybrid values(30, 0, 'purple-windflower plant', 'Blue/blue windflowers or Blue/pink windflowers');
