drop table if exists acnh_shoe;
create table acnh_shoe ("Index" int primary key, Selected int, Name varchar(63), Status varchar(31), Price varchar(31), "From" varchar(63), Style varchar(31));
insert into acnh_shoe values(1, 0, 'antique boots (Brown)', 'orderable', '2640', 'Able Sisters', 'Simple');
insert into acnh_shoe values(2, 0, 'antique boots (Black)', 'orderable', '2640', 'Able Sisters', 'Simple');
insert into acnh_shoe values(3, 0, 'antique boots (Greige)', 'orderable', '2640', 'Able Sisters', 'Simple');
insert into acnh_shoe values(4, 0, 'armor shoes', 'unorderable', '3000', 'Crafting', 'Cool');
insert into acnh_shoe values(5, 0, 'babouches (Blue)', 'orderable', '560', 'Kicks', 'Cute');
insert into acnh_shoe values(6, 0, 'babouches (Orange)', 'orderable', '560', 'Kicks', 'Cute');
insert into acnh_shoe values(7, 0, 'babouches (Pink)', 'orderable', '560', 'Kicks', 'Cute');
insert into acnh_shoe values(8, 0, 'babouches (Yellow)', 'orderable', '560', 'Kicks', 'Cute');
insert into acnh_shoe values(9, 0, 'babouches (Gray)', 'orderable', '560', 'Kicks', 'Cute');
insert into acnh_shoe values(10, 0, 'babouches (Purple)', 'orderable', '560', 'Kicks', 'Cute');
insert into acnh_shoe values(11, 0, 'babouches (Mint)', 'orderable', '560', 'Kicks', 'Cute');
insert into acnh_shoe values(12, 0, 'babouches (Red)', 'orderable', '560', 'Kicks', 'Cute');
insert into acnh_shoe values(13, 0, 'ballet slippers (Pink)', 'orderable', '2200', 'Kicks', 'Elegant');
insert into acnh_shoe values(14, 0, 'ballet slippers (Mint)', 'orderable', '2200', 'Kicks', 'Elegant');
insert into acnh_shoe values(15, 0, 'ballet slippers (Blue)', 'orderable', '2200', 'Kicks', 'Elegant');
insert into acnh_shoe values(16, 0, 'ballet slippers (Purple)', 'orderable', '2200', 'Kicks', 'Elegant');
insert into acnh_shoe values(17, 0, 'ballet slippers (Black)', 'orderable', '2200', 'Kicks', 'Elegant');
insert into acnh_shoe values(18, 0, 'ballet slippers (White)', 'orderable', '2200', 'Kicks', 'Elegant');
insert into acnh_shoe values(19, 0, 'ballet slippers (Yellow)', 'orderable', '2200', 'Kicks', 'Elegant');
insert into acnh_shoe values(20, 0, 'ballet slippers (Red)', 'orderable', '2200', 'Kicks', 'Elegant');
insert into acnh_shoe values(21, 0, 'basketball shoes (Red)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(22, 0, 'basketball shoes (Green)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(23, 0, 'basketball shoes (Beige)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(24, 0, 'basketball shoes (Orange)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(25, 0, 'basketball shoes (Blue)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(26, 0, 'basketball shoes (Purple)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(27, 0, 'basketball shoes (Light blue)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(28, 0, 'basketball shoes (Pink)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(29, 0, 'beaded sandals (Orange)', 'orderable', '1800', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(30, 0, 'beaded sandals (Purple)', 'orderable', '1800', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(31, 0, 'beaded sandals (Yellow)', 'orderable', '1800', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(32, 0, 'beaded sandals (Red)', 'orderable', '1800', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(33, 0, 'beaded sandals (Green)', 'orderable', '1800', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(34, 0, 'beaded sandals (Beige)', 'orderable', '1800', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(35, 0, 'boots (Green)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_shoe values(36, 0, 'boots (Black)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_shoe values(37, 0, 'boots (Blue)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_shoe values(38, 0, 'boots (Red)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_shoe values(39, 0, 'boots (Olive)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_shoe values(40, 0, 'business shoes (Black)', 'orderable', '1300', 'Able Sisters', 'Simple');
insert into acnh_shoe values(41, 0, 'business shoes (Brown)', 'orderable', '1300', 'Able Sisters', 'Simple');
insert into acnh_shoe values(42, 0, 'cleats (Blue)', 'orderable', '1200', 'Kicks', 'Active');
insert into acnh_shoe values(43, 0, 'cleats (Light blue)', 'orderable', '1200', 'Kicks', 'Active');
insert into acnh_shoe values(44, 0, 'cleats (Red)', 'orderable', '1200', 'Kicks', 'Active');
insert into acnh_shoe values(45, 0, 'cleats (Yellow)', 'orderable', '1200', 'Kicks', 'Active');
insert into acnh_shoe values(46, 0, 'cleats (Black)', 'orderable', '1200', 'Kicks', 'Active');
insert into acnh_shoe values(47, 0, 'cleats (Orange)', 'orderable', '1200', 'Kicks', 'Active');
insert into acnh_shoe values(48, 0, 'cleats (Green)', 'orderable', '1200', 'Kicks', 'Active');
insert into acnh_shoe values(49, 0, 'cleats (Purple)', 'orderable', '1200', 'Kicks', 'Active');
insert into acnh_shoe values(50, 0, 'comfy sandals (Brown)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_shoe values(51, 0, 'comfy sandals (White)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_shoe values(52, 0, 'comfy sandals (Green)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_shoe values(53, 0, 'comfy sandals (Blue)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_shoe values(54, 0, 'comfy sandals (Red)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_shoe values(55, 0, 'comfy sandals (Orange)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_shoe values(56, 0, 'comfy sandals (Yellow)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_shoe values(57, 0, 'comfy sandals (Purple)', 'orderable', '1040', 'Able Sisters', 'Simple');
insert into acnh_shoe values(58, 0, 'cowboy boots (Brown)', 'orderable', '2380', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(59, 0, 'cowboy boots (Black)', 'orderable', '2380', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(60, 0, 'cowboy boots (Ivory)', 'orderable', '2380', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(61, 0, 'cowboy boots (Pink)', 'orderable', '2380', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(62, 0, 'cowboy boots (Blue)', 'orderable', '2380', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(63, 0, 'cross-belt sandals (Green)', 'orderable', '1040', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(64, 0, 'cross-belt sandals (Pink)', 'orderable', '1040', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(65, 0, 'cross-belt sandals (Gray)', 'orderable', '1040', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(66, 0, 'cross-belt sandals (Brown)', 'orderable', '1040', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(67, 0, 'cross-belt sandals (Black)', 'orderable', '1040', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(68, 0, 'cross-belt sandals (Purple)', 'orderable', '1040', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(69, 0, 'cute sneakers (Light blue)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(70, 0, 'cute sneakers (Green)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(71, 0, 'cute sneakers (Pink)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(72, 0, 'cute sneakers (Yellow)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(73, 0, 'cute sneakers (Purple)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(74, 0, 'cute sneakers (Blue)', 'orderable', '1260', 'Able Sisters', 'Cute');
insert into acnh_shoe values(75, 0, 'DAL slippers (Blue)', 'unorderable', '1010', 'Dodo Airlines', 'Simple');
insert into acnh_shoe values(76, 0, 'earth-egg shoes', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_shoe values(77, 0, 'embroidered shoes (Red)', 'orderable', '2100', 'Kicks', 'Elegant');
insert into acnh_shoe values(78, 0, 'embroidered shoes (White)', 'orderable', '2100', 'Kicks', 'Elegant');
insert into acnh_shoe values(79, 0, 'embroidered shoes (Black)', 'orderable', '2100', 'Kicks', 'Elegant');
insert into acnh_shoe values(80, 0, 'embroidered shoes (Blue)', 'orderable', '2100', 'Kicks', 'Elegant');
insert into acnh_shoe values(81, 0, 'faux-fur ankle booties (Olive)', 'orderable', '1450', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(82, 0, 'faux-fur ankle booties (Beige)', 'orderable', '1450', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(83, 0, 'faux-fur ankle booties (Ruby red)', 'orderable', '1450', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(84, 0, 'faux-fur ankle booties (Navy blue)', 'orderable', '1450', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(85, 0, 'faux-shearling boots (Beige)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(86, 0, 'faux-shearling boots (Pink)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(87, 0, 'faux-shearling boots (Green)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(88, 0, 'faux-shearling boots (Black)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(89, 0, 'faux-shearling boots (Gray)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(90, 0, 'faux-suede sneakers (Green)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(91, 0, 'faux-suede sneakers (Navy blue)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(92, 0, 'faux-suede sneakers (Beige)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(93, 0, 'faux-suede sneakers (Orange)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(94, 0, 'faux-suede sneakers (Pink)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(95, 0, 'faux-suede sneakers (Light blue)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(96, 0, 'faux-suede sneakers (Purple)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(97, 0, 'faux-suede sneakers (Berry red)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(98, 0, 'flip-flops (Blue)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(99, 0, 'flip-flops (Green)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(100, 0, 'flip-flops (Yellow)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(101, 0, 'flip-flops (White)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(102, 0, 'flip-flops (Orange)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(103, 0, 'flip-flops (Light blue)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(104, 0, 'flip-flops (Pink)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(105, 0, 'flip-flops (Red)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(106, 0, 'flower sandals (Yellow)', 'orderable', '1200', 'Able Sisters', 'Cute');
insert into acnh_shoe values(107, 0, 'flower sandals (Pink)', 'orderable', '1200', 'Able Sisters', 'Cute');
insert into acnh_shoe values(108, 0, 'flower sandals (Green)', 'orderable', '1200', 'Able Sisters', 'Cute');
insert into acnh_shoe values(109, 0, 'flower sandals (Purple)', 'orderable', '1200', 'Able Sisters', 'Cute');
insert into acnh_shoe values(110, 0, 'flower sandals (Blue)', 'orderable', '1200', 'Able Sisters', 'Cute');
insert into acnh_shoe values(111, 0, 'flower sandals (Black)', 'orderable', '1200', 'Able Sisters', 'Cute');
insert into acnh_shoe values(112, 0, 'flower sandals (White)', 'orderable', '1200', 'Able Sisters', 'Cute');
insert into acnh_shoe values(113, 0, 'ghillie brogues (Brown)', 'orderable', '2340', 'Kicks', 'Gorgeous');
insert into acnh_shoe values(114, 0, 'ghillie brogues (Black)', 'orderable', '2340', 'Kicks', 'Gorgeous');
insert into acnh_shoe values(115, 0, 'ghillie brogues (White)', 'orderable', '2340', 'Kicks', 'Gorgeous');
insert into acnh_shoe values(116, 0, 'gladiator sandals (Brown)', 'orderable', '1800', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(117, 0, 'gladiator sandals (Black)', 'orderable', '1800', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(118, 0, 'gladiator sandals (Red)', 'orderable', '1800', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(119, 0, 'gold-armor shoes', 'unorderable', '40000', 'Crafting', 'Gorgeous');
insert into acnh_shoe values(120, 0, 'hi-tech sneakers (Orange)', 'orderable', '1260', 'Able Sisters', 'Cool');
insert into acnh_shoe values(121, 0, 'hi-tech sneakers (Pink)', 'orderable', '1260', 'Able Sisters', 'Cool');
insert into acnh_shoe values(122, 0, 'hi-tech sneakers (Green)', 'orderable', '1260', 'Able Sisters', 'Cool');
insert into acnh_shoe values(123, 0, 'hi-tech sneakers (Light blue)', 'orderable', '1260', 'Able Sisters', 'Cool');
insert into acnh_shoe values(124, 0, 'hi-tech sneakers (Blue)', 'orderable', '1260', 'Able Sisters', 'Cool');
insert into acnh_shoe values(125, 0, 'high-tops (Gray)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(126, 0, 'high-tops (Brown)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(127, 0, 'high-tops (Green)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(128, 0, 'high-tops (Blue)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(129, 0, 'high-tops (Purple)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(130, 0, 'high-tops (Red)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(131, 0, 'high-tops (Yellow)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(132, 0, 'high-tops (White)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(133, 0, 'house slippers (Gray)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(134, 0, 'house slippers (Navy blue)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(135, 0, 'house slippers (Pink)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(136, 0, 'house slippers (Yellow)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(137, 0, 'house slippers (Green)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(138, 0, 'house slippers (Blue)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(139, 0, 'house slippers (Red)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(140, 0, 'house slippers (Beige)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(141, 0, 'jester''s shoes (Purple)', 'orderable', '1900', 'Kicks', 'Active');
insert into acnh_shoe values(142, 0, 'jester''s shoes (Black)', 'orderable', '1900', 'Kicks', 'Active');
insert into acnh_shoe values(143, 0, 'jester''s shoes (Red)', 'orderable', '1900', 'Kicks', 'Active');
insert into acnh_shoe values(144, 0, 'jester''s shoes (Green)', 'orderable', '1900', 'Kicks', 'Active');
insert into acnh_shoe values(145, 0, 'kiddie sneakers (Red)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_shoe values(146, 0, 'kiddie sneakers (Blue)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_shoe values(147, 0, 'kiddie sneakers (Green)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_shoe values(148, 0, 'kiddie sneakers (Purple)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_shoe values(149, 0, 'kiddie sneakers (Silver)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_shoe values(150, 0, 'kiddie sneakers (Black)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_shoe values(151, 0, 'kimono sandals (Black)', 'orderable', '1600', 'Kicks', 'Simple');
insert into acnh_shoe values(152, 0, 'kimono sandals (Red)', 'orderable', '1600', 'Kicks', 'Simple');
insert into acnh_shoe values(153, 0, 'kimono sandals (Pink)', 'orderable', '1600', 'Kicks', 'Simple');
insert into acnh_shoe values(154, 0, 'kimono sandals (Dark blue)', 'orderable', '1600', 'Kicks', 'Simple');
insert into acnh_shoe values(155, 0, 'kimono sandals (Gray)', 'orderable', '1600', 'Kicks', 'Simple');
insert into acnh_shoe values(156, 0, 'kimono sandals (Purple)', 'orderable', '1600', 'Kicks', 'Simple');
insert into acnh_shoe values(157, 0, 'kimono sandals (Yellow)', 'orderable', '1600', 'Kicks', 'Simple');
insert into acnh_shoe values(158, 0, 'kimono sandals (Green)', 'orderable', '1600', 'Kicks', 'Simple');
insert into acnh_shoe values(159, 0, 'kung-fu shoes (Black)', 'orderable', '1260', 'Kicks', 'Active');
insert into acnh_shoe values(160, 0, 'Labelle pumps (Twilight)', 'orderable', '3500', 'Labelle', 'Elegant');
insert into acnh_shoe values(161, 0, 'Labelle pumps (Midnight)', 'orderable', '3500', 'Labelle', 'Elegant');
insert into acnh_shoe values(162, 0, 'Labelle pumps (Passion)', 'orderable', '3500', 'Labelle', 'Elegant');
insert into acnh_shoe values(163, 0, 'Labelle pumps (Ocean)', 'orderable', '3500', 'Labelle', 'Elegant');
insert into acnh_shoe values(164, 0, 'Labelle pumps (Sunset)', 'orderable', '3500', 'Labelle', 'Elegant');
insert into acnh_shoe values(165, 0, 'Labelle pumps (Love)', 'orderable', '3500', 'Labelle', 'Elegant');
insert into acnh_shoe values(166, 0, 'Labelle sneakers (Twilight)', 'orderable', '3300', 'Labelle', 'Cool');
insert into acnh_shoe values(167, 0, 'Labelle sneakers (Midnight)', 'orderable', '3300', 'Labelle', 'Cool');
insert into acnh_shoe values(168, 0, 'Labelle sneakers (Passion)', 'orderable', '3300', 'Labelle', 'Cool');
insert into acnh_shoe values(169, 0, 'Labelle sneakers (Ocean)', 'orderable', '3300', 'Labelle', 'Cool');
insert into acnh_shoe values(170, 0, 'Labelle sneakers (Sunset)', 'orderable', '3300', 'Labelle', 'Cool');
insert into acnh_shoe values(171, 0, 'Labelle sneakers (Love)', 'orderable', '3300', 'Labelle', 'Cool');
insert into acnh_shoe values(172, 0, 'lace-up boots (Black)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(173, 0, 'lace-up boots (White)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(174, 0, 'lace-up boots (Brown)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(175, 0, 'lace-up boots (Red)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(176, 0, 'leaf-egg shoes', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_shoe values(177, 0, 'leopard pumps (Beige)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(178, 0, 'leopard pumps (Gray)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(179, 0, 'leopard pumps (Blue)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(180, 0, 'leopard pumps (Green)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(181, 0, 'leopard pumps (Purple)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(182, 0, 'leopard pumps (Pink)', 'orderable', '1560', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(183, 0, 'loafers (Brown)', 'orderable', '1300', 'Able Sisters', 'Simple');
insert into acnh_shoe values(184, 0, 'loafers (Black)', 'orderable', '1300', 'Able Sisters', 'Simple');
insert into acnh_shoe values(185, 0, 'loafers (White)', 'orderable', '1300', 'Able Sisters', 'Simple');
insert into acnh_shoe values(186, 0, 'loafers (Pink)', 'orderable', '1300', 'Able Sisters', 'Simple');
insert into acnh_shoe values(187, 0, 'loafers (Blue)', 'orderable', '1300', 'Able Sisters', 'Simple');
insert into acnh_shoe values(188, 0, 'loafers (Yellow)', 'orderable', '1300', 'Able Sisters', 'Simple');
insert into acnh_shoe values(189, 0, 'loafers (Red)', 'orderable', '1300', 'Able Sisters', 'Simple');
insert into acnh_shoe values(190, 0, 'mage''s booties (Black)', 'orderable', '1550', 'Kicks', 'Cool');
insert into acnh_shoe values(191, 0, 'mage''s booties (Blue)', 'orderable', '1550', 'Kicks', 'Cool');
insert into acnh_shoe values(192, 0, 'mage''s booties (White)', 'orderable', '1550', 'Kicks', 'Cool');
insert into acnh_shoe values(193, 0, 'mage''s booties (Red)', 'orderable', '1550', 'Kicks', 'Cool');
insert into acnh_shoe values(194, 0, 'mary janes (Black)', 'orderable', '1800', 'Able Sisters', 'Cute');
insert into acnh_shoe values(195, 0, 'mary janes (Red)', 'orderable', '1800', 'Able Sisters', 'Cute');
insert into acnh_shoe values(196, 0, 'mary janes (White)', 'orderable', '1800', 'Able Sisters', 'Cute');
insert into acnh_shoe values(197, 0, 'mary janes (Light blue)', 'orderable', '1800', 'Able Sisters', 'Cute');
insert into acnh_shoe values(198, 0, 'mary janes (Yellow)', 'orderable', '1800', 'Able Sisters', 'Cute');
insert into acnh_shoe values(199, 0, 'mary janes (Blue)', 'orderable', '1800', 'Able Sisters', 'Cute');
insert into acnh_shoe values(200, 0, 'mary janes (Green)', 'orderable', '1800', 'Able Sisters', 'Cute');
insert into acnh_shoe values(201, 0, 'mary janes (Pink)', 'orderable', '1800', 'Able Sisters', 'Cute');
insert into acnh_shoe values(202, 0, 'moccasin boots (Camel)', 'orderable', '1120', 'Able Sisters', 'Simple');
insert into acnh_shoe values(203, 0, 'moccasin boots (Olive)', 'orderable', '1120', 'Able Sisters', 'Simple');
insert into acnh_shoe values(204, 0, 'moccasin boots (Beige)', 'orderable', '1120', 'Able Sisters', 'Simple');
insert into acnh_shoe values(205, 0, 'moccasin boots (Pink)', 'orderable', '1120', 'Able Sisters', 'Simple');
insert into acnh_shoe values(206, 0, 'moccasin boots (Black)', 'orderable', '1120', 'Able Sisters', 'Simple');
insert into acnh_shoe values(207, 0, 'moccasin boots (Blue)', 'orderable', '1120', 'Able Sisters', 'Simple');
insert into acnh_shoe values(208, 0, 'moccasin boots (Orange)', 'orderable', '1120', 'Able Sisters', 'Simple');
insert into acnh_shoe values(209, 0, 'moccasins (Camel)', 'orderable', '1080', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(210, 0, 'moccasins (Red)', 'orderable', '1080', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(211, 0, 'moccasins (Light blue)', 'orderable', '1080', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(212, 0, 'moccasins (White)', 'orderable', '1080', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(213, 0, 'moccasins (Pink)', 'orderable', '1080', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(214, 0, 'moccasins (Gray)', 'orderable', '1080', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(215, 0, 'moccasins (Black)', 'orderable', '1080', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(216, 0, 'Nook Inc. slippers (White)', 'unorderable', '2000', 'Nook Miles Shop', 'Simple');
insert into acnh_shoe values(217, 0, 'outdoor sandals (Green)', 'orderable', '630', 'Able Sisters', 'Active');
insert into acnh_shoe values(218, 0, 'outdoor sandals (Red)', 'orderable', '630', 'Able Sisters', 'Active');
insert into acnh_shoe values(219, 0, 'outdoor sandals (Blue)', 'orderable', '630', 'Able Sisters', 'Active');
insert into acnh_shoe values(220, 0, 'outdoor sandals (Purple)', 'orderable', '630', 'Able Sisters', 'Active');
insert into acnh_shoe values(221, 0, 'outdoor sandals (Yellow)', 'orderable', '630', 'Able Sisters', 'Active');
insert into acnh_shoe values(222, 0, 'outdoor sandals (Orange)', 'orderable', '630', 'Able Sisters', 'Active');
insert into acnh_shoe values(223, 0, 'outdoor sandals (White)', 'orderable', '630', 'Able Sisters', 'Active');
insert into acnh_shoe values(224, 0, 'outdoor sandals (Black)', 'orderable', '630', 'Able Sisters', 'Active');
insert into acnh_shoe values(225, 0, 'paw slippers (Pink)', 'orderable', '1260', 'Kicks', 'Cute');
insert into acnh_shoe values(226, 0, 'paw slippers (Brown)', 'orderable', '1260', 'Kicks', 'Cute');
insert into acnh_shoe values(227, 0, 'paw slippers (White)', 'orderable', '1260', 'Kicks', 'Cute');
insert into acnh_shoe values(228, 0, 'paw slippers (Blue)', 'orderable', '1260', 'Kicks', 'Cute');
insert into acnh_shoe values(229, 0, 'paw slippers (Black)', 'orderable', '1260', 'Kicks', 'Cute');
insert into acnh_shoe values(230, 0, 'pleather ankle booties (Brown)', 'orderable', '1280', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(231, 0, 'pleather ankle booties (Black)', 'orderable', '1280', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(232, 0, 'pleather ankle booties (Green)', 'orderable', '1280', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(233, 0, 'pleather ankle booties (Mustard)', 'orderable', '1280', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(234, 0, 'pleather sneakers (White)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_shoe values(235, 0, 'pleather sneakers (Black)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_shoe values(236, 0, 'pleather sneakers (Red)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_shoe values(237, 0, 'pleather sneakers (Green)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_shoe values(238, 0, 'pleather sneakers (Blue)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_shoe values(239, 0, 'pleather sneakers (Yellow)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_shoe values(240, 0, 'pleather sneakers (Light blue)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_shoe values(241, 0, 'pleather sneakers (Orange)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_shoe values(242, 0, 'pom-pom boots (Pink)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(243, 0, 'pom-pom boots (Red)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(244, 0, 'pom-pom boots (Yellow)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(245, 0, 'pom-pom boots (Purple)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(246, 0, 'pom-pom boots (Green)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(247, 0, 'pom-pom boots (Blue)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(248, 0, 'pom-pom boots (Black)', 'orderable', '1600', 'Able Sisters', 'Cute');
insert into acnh_shoe values(249, 0, 'power boots (Red)', 'orderable', '3150', 'Kicks', 'Active');
insert into acnh_shoe values(250, 0, 'power boots (Blue)', 'orderable', '3150', 'Kicks', 'Active');
insert into acnh_shoe values(251, 0, 'power boots (Green)', 'orderable', '3150', 'Kicks', 'Active');
insert into acnh_shoe values(252, 0, 'power boots (Black)', 'orderable', '3150', 'Kicks', 'Active');
insert into acnh_shoe values(253, 0, 'rain boots (Yellow)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(254, 0, 'rain boots (Green)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(255, 0, 'rain boots (Blue)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(256, 0, 'rain boots (Purple)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(257, 0, 'rain boots (Pink)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(258, 0, 'rain boots (Red)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(259, 0, 'rain boots (Beige)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(260, 0, 'rain boots (Black)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(261, 0, 'recycled boots', 'unorderable', '40', 'Crafting', 'Simple');
insert into acnh_shoe values(262, 0, 'restroom slippers (Navy blue)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(263, 0, 'restroom slippers (Red)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(264, 0, 'restroom slippers (Green)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(265, 0, 'restroom slippers (Light blue)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(266, 0, 'restroom slippers (Pink)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(267, 0, 'ribbon sandals (Blue)', 'orderable', '1300', 'Able Sisters', 'Cute');
insert into acnh_shoe values(268, 0, 'ribbon sandals (White)', 'orderable', '1300', 'Able Sisters', 'Cute');
insert into acnh_shoe values(269, 0, 'ribbon sandals (Pink)', 'orderable', '1300', 'Able Sisters', 'Cute');
insert into acnh_shoe values(270, 0, 'ribbon sandals (Yellow)', 'orderable', '1300', 'Able Sisters', 'Cute');
insert into acnh_shoe values(271, 0, 'ribbon sandals (Green)', 'orderable', '1300', 'Able Sisters', 'Cute');
insert into acnh_shoe values(272, 0, 'ribbon sandals (Berry red)', 'orderable', '1300', 'Able Sisters', 'Cute');
insert into acnh_shoe values(273, 0, 'ribbon sandals (Black)', 'orderable', '1300', 'Able Sisters', 'Cute');
insert into acnh_shoe values(274, 0, 'ribbon sandals (Beige)', 'orderable', '1300', 'Able Sisters', 'Cute');
insert into acnh_shoe values(275, 0, 'rubber-toe high tops (Blue)', 'orderable', '1260', 'Able Sisters', 'Simple');
insert into acnh_shoe values(276, 0, 'rubber-toe high tops (Olive)', 'orderable', '1260', 'Able Sisters', 'Simple');
insert into acnh_shoe values(277, 0, 'rubber-toe high tops (Beige)', 'orderable', '1260', 'Able Sisters', 'Simple');
insert into acnh_shoe values(278, 0, 'rubber-toe high tops (Pink)', 'orderable', '1260', 'Able Sisters', 'Simple');
insert into acnh_shoe values(279, 0, 'rubber-toe high tops (Berry red)', 'orderable', '1260', 'Able Sisters', 'Simple');
insert into acnh_shoe values(280, 0, 'rubber-toe high tops (Coral)', 'orderable', '1260', 'Able Sisters', 'Simple');
insert into acnh_shoe values(281, 0, 'rubber-toe high tops (Ivory)', 'orderable', '1260', 'Able Sisters', 'Simple');
insert into acnh_shoe values(282, 0, 'rubber-toe high tops (Black)', 'orderable', '1260', 'Able Sisters', 'Simple');
insert into acnh_shoe values(283, 0, 'rubber-toe sneakers (Purple)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(284, 0, 'rubber-toe sneakers (Green)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(285, 0, 'rubber-toe sneakers (Yellow)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(286, 0, 'rubber-toe sneakers (Light blue)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(287, 0, 'rubber-toe sneakers (Red)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(288, 0, 'rubber-toe sneakers (Pink)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(289, 0, 'rubber-toe sneakers (Blue)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(290, 0, 'rubber-toe sneakers (Black)', 'orderable', '1080', 'Able Sisters', 'Simple');
insert into acnh_shoe values(291, 0, 'samurai greaves (Red)', 'orderable', '4300', 'Kicks', 'Cool');
insert into acnh_shoe values(292, 0, 'samurai greaves (Black)', 'orderable', '4300', 'Kicks', 'Cool');
insert into acnh_shoe values(293, 0, 'samurai greaves (Blue)', 'orderable', '4300', 'Kicks', 'Cool');
insert into acnh_shoe values(294, 0, 'samurai greaves (White)', 'orderable', '4300', 'Kicks', 'Cool');
insert into acnh_shoe values(295, 0, 'samurai greaves (Golden yellow)', 'orderable', '4300', 'Kicks', 'Cool');
insert into acnh_shoe values(296, 0, 'shiny bow platform shoes (Pink)', 'orderable', '2400', 'Kicks', 'Cute');
insert into acnh_shoe values(297, 0, 'shiny bow platform shoes (Black)', 'orderable', '2400', 'Kicks', 'Cute');
insert into acnh_shoe values(298, 0, 'shiny bow platform shoes (Red)', 'orderable', '2400', 'Kicks', 'Cute');
insert into acnh_shoe values(299, 0, 'shiny bow platform shoes (Purple)', 'orderable', '2400', 'Kicks', 'Cute');
insert into acnh_shoe values(300, 0, 'shiny bow platform shoes (Light blue)', 'orderable', '2400', 'Kicks', 'Cute');
insert into acnh_shoe values(301, 0, 'shiny bow platform shoes (White)', 'orderable', '2400', 'Kicks', 'Cute');
insert into acnh_shoe values(302, 0, 'shiny bow platform shoes (Light purple)', 'orderable', '2400', 'Kicks', 'Cute');
insert into acnh_shoe values(303, 0, 'shower sandals (Black)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(304, 0, 'shower sandals (White)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(305, 0, 'shower sandals (Gold)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(306, 0, 'shower sandals (Red)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(307, 0, 'shower sandals (Blue)', 'orderable', '350', 'Able Sisters', 'Active');
insert into acnh_shoe values(308, 0, 'ski boots (White)', 'orderable', '1800', 'Kicks', 'Active');
insert into acnh_shoe values(309, 0, 'ski boots (Orange)', 'orderable', '1800', 'Kicks', 'Active');
insert into acnh_shoe values(310, 0, 'ski boots (Red)', 'orderable', '1800', 'Kicks', 'Active');
insert into acnh_shoe values(311, 0, 'ski boots (Lime)', 'orderable', '1800', 'Kicks', 'Active');
insert into acnh_shoe values(312, 0, 'ski boots (Light blue)', 'orderable', '1800', 'Kicks', 'Active');
insert into acnh_shoe values(313, 0, 'ski boots (Purple)', 'orderable', '1800', 'Kicks', 'Active');
insert into acnh_shoe values(314, 0, 'sky-egg shoes', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_shoe values(315, 0, 'slip-on loafers (Yellow)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(316, 0, 'slip-on loafers (Red)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(317, 0, 'slip-on loafers (Blue)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(318, 0, 'slip-on loafers (Green)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(319, 0, 'slip-on loafers (Black)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(320, 0, 'slip-on loafers (Light blue)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(321, 0, 'slip-on loafers (White)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(322, 0, 'slip-on loafers (Beige)', 'orderable', '490', 'Able Sisters', 'Simple');
insert into acnh_shoe values(323, 0, 'slip-on sandals (Light blue)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_shoe values(324, 0, 'slip-on sandals (Lime)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_shoe values(325, 0, 'slip-on sandals (Black)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_shoe values(326, 0, 'slip-on sandals (Pink)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_shoe values(327, 0, 'slip-on sandals (Navy blue)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_shoe values(328, 0, 'slip-on sandals (Red)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_shoe values(329, 0, 'slip-on sandals (Orange)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_shoe values(330, 0, 'slip-on sandals (Purple)', 'orderable', '560', 'Able Sisters', 'Active');
insert into acnh_shoe values(331, 0, 'slip-on school shoes (Red)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(332, 0, 'slip-on school shoes (Blue)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(333, 0, 'slip-on school shoes (Green)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(334, 0, 'slip-on school shoes (Yellow)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(335, 0, 'slip-on school shoes (Pink)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(336, 0, 'slippers (Gray)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(337, 0, 'slippers (Black)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(338, 0, 'slippers (White)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(339, 0, 'slippers (Pink)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(340, 0, 'slippers (Green)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(341, 0, 'slippers (Blue)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(342, 0, 'slippers (Red)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(343, 0, 'slippers (Yellow)', 'orderable', '350', 'Kicks', 'Simple');
insert into acnh_shoe values(344, 0, 'space boots (White)', 'orderable', '4300', 'Kicks', 'Active');
insert into acnh_shoe values(345, 0, 'sporty sandals (Red)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_shoe values(346, 0, 'sporty sandals (Olive)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_shoe values(347, 0, 'sporty sandals (Blue)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_shoe values(348, 0, 'sporty sandals (Purple)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_shoe values(349, 0, 'sporty sandals (Green)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_shoe values(350, 0, 'sporty sandals (Pink)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_shoe values(351, 0, 'sporty sandals (Beige)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_shoe values(352, 0, 'sporty sandals (Gray)', 'orderable', '1300', 'Able Sisters', 'Active');
insert into acnh_shoe values(353, 0, 'steel-toed boots (Brown)', 'orderable', '2640', 'Able Sisters', 'Cool');
insert into acnh_shoe values(354, 0, 'steel-toed boots (Beige)', 'orderable', '2640', 'Able Sisters', 'Cool');
insert into acnh_shoe values(355, 0, 'steel-toed boots (Green)', 'orderable', '2640', 'Able Sisters', 'Cool');
insert into acnh_shoe values(356, 0, 'steel-toed boots (Black)', 'orderable', '2640', 'Able Sisters', 'Cool');
insert into acnh_shoe values(357, 0, 'steel-toed boots (Red)', 'orderable', '2640', 'Able Sisters', 'Cool');
insert into acnh_shoe values(358, 0, 'steel-toed boots (Gray)', 'orderable', '2640', 'Able Sisters', 'Cool');
insert into acnh_shoe values(359, 0, 'stone-egg shoes', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_shoe values(360, 0, 'strappy heels (Red)', 'orderable', '1560', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(361, 0, 'strappy heels (Blue)', 'orderable', '1560', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(362, 0, 'strappy heels (Gold)', 'orderable', '1560', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(363, 0, 'strappy heels (Silver)', 'orderable', '1560', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(364, 0, 'strappy heels (Black)', 'orderable', '1560', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(365, 0, 'strappy heels (Pink)', 'orderable', '1560', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(366, 0, 'strappy heels (Green)', 'orderable', '1560', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(367, 0, 'strappy heels (Purple)', 'orderable', '1560', 'Able Sisters', 'Gorgeous');
insert into acnh_shoe values(368, 0, 'traditional flower shoes (Red)', 'orderable', '1800', 'Kicks', 'Elegant');
insert into acnh_shoe values(369, 0, 'traditional flower shoes (Pink)', 'orderable', '1800', 'Kicks', 'Elegant');
insert into acnh_shoe values(370, 0, 'traditional flower shoes (Blue)', 'orderable', '1800', 'Kicks', 'Elegant');
insert into acnh_shoe values(371, 0, 'traditional flower shoes (Yellow)', 'orderable', '1800', 'Kicks', 'Elegant');
insert into acnh_shoe values(372, 0, 'traditional flower shoes (Lime)', 'orderable', '1800', 'Kicks', 'Elegant');
insert into acnh_shoe values(373, 0, 'trekking shoes (Orange)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(374, 0, 'trekking shoes (Gray)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(375, 0, 'trekking shoes (Black)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(376, 0, 'trekking shoes (Light blue)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(377, 0, 'trekking shoes (Yellow)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(378, 0, 'trekking shoes (Purple)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(379, 0, 'trekking shoes (White)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(380, 0, 'trekking shoes (Brown)', 'orderable', '1500', 'Able Sisters', 'Active');
insert into acnh_shoe values(381, 0, 'velour boots (Ruby red)', 'orderable', '1920', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(382, 0, 'velour boots (Gray)', 'orderable', '1920', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(383, 0, 'velour boots (Brown)', 'orderable', '1920', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(384, 0, 'velour boots (Blue)', 'orderable', '1920', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(385, 0, 'velour boots (Mustard)', 'orderable', '1920', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(386, 0, 'vinyl round-toed pumps (Beige)', 'orderable', '1500', 'Able Sisters', 'Simple');
insert into acnh_shoe values(387, 0, 'vinyl round-toed pumps (Mint)', 'orderable', '1500', 'Able Sisters', 'Simple');
insert into acnh_shoe values(388, 0, 'vinyl round-toed pumps (Brown)', 'orderable', '1500', 'Able Sisters', 'Simple');
insert into acnh_shoe values(389, 0, 'vinyl round-toed pumps (Pink)', 'orderable', '1500', 'Able Sisters', 'Simple');
insert into acnh_shoe values(390, 0, 'vinyl round-toed pumps (White)', 'orderable', '1500', 'Able Sisters', 'Simple');
insert into acnh_shoe values(391, 0, 'vinyl round-toed pumps (Black)', 'orderable', '1500', 'Able Sisters', 'Simple');
insert into acnh_shoe values(392, 0, 'visual-punk boots (Black)', 'orderable', '2200', 'Kicks', 'Cool');
insert into acnh_shoe values(393, 0, 'walking shoes (Pink)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_shoe values(394, 0, 'walking shoes (Beige)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_shoe values(395, 0, 'walking shoes (Red)', 'orderable', '560', 'Able Sisters', 'Simple');
insert into acnh_shoe values(396, 0, 'water sandals (Pink)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_shoe values(397, 0, 'water sandals (Navy blue)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_shoe values(398, 0, 'water sandals (Red)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_shoe values(399, 0, 'water sandals (Light blue)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_shoe values(400, 0, 'water sandals (Orange)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_shoe values(401, 0, 'water sandals (Purple)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_shoe values(402, 0, 'water sandals (Green)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_shoe values(403, 0, 'water sandals (Yellow)', 'orderable', '1040', 'Able Sisters', 'Cute');
insert into acnh_shoe values(404, 0, 'water shoes (Pink)', 'orderable', '900', 'Able Sisters', 'Active');
insert into acnh_shoe values(405, 0, 'water shoes (Light blue)', 'orderable', '900', 'Able Sisters', 'Active');
insert into acnh_shoe values(406, 0, 'water shoes (Orange)', 'orderable', '900', 'Able Sisters', 'Active');
insert into acnh_shoe values(407, 0, 'water shoes (Green)', 'orderable', '900', 'Able Sisters', 'Active');
insert into acnh_shoe values(408, 0, 'water shoes (Navy blue)', 'orderable', '900', 'Able Sisters', 'Active');
insert into acnh_shoe values(409, 0, 'water shoes (Yellow)', 'orderable', '900', 'Able Sisters', 'Active');
insert into acnh_shoe values(410, 0, 'water shoes (Red)', 'orderable', '900', 'Able Sisters', 'Active');
insert into acnh_shoe values(411, 0, 'water shoes (Black)', 'orderable', '900', 'Able Sisters', 'Active');
insert into acnh_shoe values(412, 0, 'water-egg shoes', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_shoe values(413, 0, 'wingtip shoes (Black & white)', 'orderable', '900', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(414, 0, 'wingtip shoes (Brown)', 'orderable', '900', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(415, 0, 'wingtip shoes (Greige)', 'orderable', '900', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(416, 0, 'wingtip shoes (Green)', 'orderable', '900', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(417, 0, 'wingtip shoes (Gray)', 'orderable', '900', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(418, 0, 'wingtip shoes (Berry red)', 'orderable', '900', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(419, 0, 'wingtip shoes (Black)', 'orderable', '900', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(420, 0, 'winklepickers (Red)', 'orderable', '910', 'Able Sisters', 'Cool');
insert into acnh_shoe values(421, 0, 'winklepickers (White)', 'orderable', '910', 'Able Sisters', 'Cool');
insert into acnh_shoe values(422, 0, 'winklepickers (Black)', 'orderable', '910', 'Able Sisters', 'Cool');
insert into acnh_shoe values(423, 0, 'winklepickers (Blue)', 'orderable', '910', 'Able Sisters', 'Cool');
insert into acnh_shoe values(424, 0, 'wood-egg shoes', 'unorderable', '800', 'Crafting', 'Active');
insert into acnh_shoe values(425, 0, 'wooden clogs (Yellow)', 'orderable', '1300', 'Kicks', 'Elegant');
insert into acnh_shoe values(426, 0, 'wooden clogs (Blue)', 'orderable', '1300', 'Kicks', 'Elegant');
insert into acnh_shoe values(427, 0, 'wooden clogs (Red)', 'orderable', '1300', 'Kicks', 'Elegant');
insert into acnh_shoe values(428, 0, 'wooden clogs (Green)', 'orderable', '1300', 'Kicks', 'Elegant');
insert into acnh_shoe values(429, 0, 'wooden clogs (Brown)', 'orderable', '1300', 'Kicks', 'Elegant');
insert into acnh_shoe values(430, 0, 'work boots (Red)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(431, 0, 'work boots (Purple)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(432, 0, 'work boots (Pink)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(433, 0, 'work boots (Yellow)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(434, 0, 'work boots (White)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(435, 0, 'work boots (Blue)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(436, 0, 'work boots (Green)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(437, 0, 'work boots (Gray)', 'orderable', '1920', 'Able Sisters', 'Cool');
insert into acnh_shoe values(438, 0, 'wrestling shoes (Red)', 'orderable', '1080', 'Kicks', 'Active');
insert into acnh_shoe values(439, 0, 'wrestling shoes (Blue)', 'orderable', '1080', 'Kicks', 'Active');
insert into acnh_shoe values(440, 0, 'wrestling shoes (Green)', 'orderable', '1080', 'Kicks', 'Active');
insert into acnh_shoe values(441, 0, 'wrestling shoes (Pink)', 'orderable', '1080', 'Kicks', 'Active');
insert into acnh_shoe values(442, 0, 'wrestling shoes (Black)', 'orderable', '1080', 'Kicks', 'Active');
insert into acnh_shoe values(443, 0, 'wrestling shoes (Yellow)', 'orderable', '1080', 'Kicks', 'Active');
insert into acnh_shoe values(444, 0, 'zap boots (White)', 'orderable', '2640', 'Kicks', 'Active');
insert into acnh_shoe values(445, 0, 'zori (Black)', 'orderable', '4300', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(446, 0, 'zori (Gold)', 'orderable', '4300', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(447, 0, 'zori (Pink)', 'orderable', '4300', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(448, 0, 'zori (Light pink)', 'orderable', '4300', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(449, 0, 'zori (Green)', 'orderable', '4300', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(450, 0, 'zori (White)', 'orderable', '4300', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(451, 0, 'zori (Aqua)', 'orderable', '4300', 'Able Sisters', 'Elegant');
insert into acnh_shoe values(452, 0, 'zori (Red)', 'orderable', '4300', 'Able Sisters', 'Elegant');
