drop table if exists acnh_sock;
create table acnh_sock ("Index" int primary key, Selected int, Name varchar(63), Status varchar(31), Price varchar(31), "From" varchar(63), Style varchar(31));
insert into acnh_sock values(1, 0, 'aerobics leggings (Emerald & lime)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_sock values(2, 0, 'aerobics leggings (Purple & orange)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_sock values(3, 0, 'aerobics leggings (Light blue & salmon pink)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_sock values(4, 0, 'aerobics leggings (Yellow & blue)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_sock values(5, 0, 'aerobics leggings (Red & pink)', 'orderable', '700', 'Kicks', 'Active');
insert into acnh_sock values(6, 0, 'Aran-knit socks (White)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(7, 0, 'Aran-knit socks (Red)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(8, 0, 'Aran-knit socks (Green)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(9, 0, 'Aran-knit socks (Blue)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(10, 0, 'Aran-knit socks (Black)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(11, 0, 'Aran-knit socks (Beige)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(12, 0, 'argyle crew socks (Red)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(13, 0, 'argyle crew socks (Green)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(14, 0, 'argyle crew socks (Beige)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(15, 0, 'argyle crew socks (Gray)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(16, 0, 'argyle crew socks (White)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(17, 0, 'argyle crew socks (Orange)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(18, 0, 'argyle crew socks (Pink)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(19, 0, 'argyle crew socks (Blue)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(20, 0, 'back-bow socks (Yellow)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(21, 0, 'back-bow socks (Black)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(22, 0, 'back-bow socks (White)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(23, 0, 'back-bow socks (Blue)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(24, 0, 'back-bow socks (Pink)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(25, 0, 'back-bow socks (Peacock blue)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(26, 0, 'bobby socks (White)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(27, 0, 'bobby socks (Gray)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(28, 0, 'bobby socks (Black)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(29, 0, 'bobby socks (Brown)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(30, 0, 'color-blocked socks (Purple)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(31, 0, 'color-blocked socks (Green)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(32, 0, 'color-blocked socks (Brown)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(33, 0, 'color-blocked socks (Blue)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(34, 0, 'color-blocked socks (Beige)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(35, 0, 'color-blocked socks (White)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(36, 0, 'color-blocked socks (Lime)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(37, 0, 'color-blocked socks (Pink)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(38, 0, 'compression tights (Yellow)', 'orderable', '600', 'Kicks', 'Active');
insert into acnh_sock values(39, 0, 'compression tights (Pink)', 'orderable', '600', 'Kicks', 'Active');
insert into acnh_sock values(40, 0, 'compression tights (Mint)', 'orderable', '600', 'Kicks', 'Active');
insert into acnh_sock values(41, 0, 'compression tights (Red)', 'orderable', '600', 'Kicks', 'Active');
insert into acnh_sock values(42, 0, 'compression tights (Blue)', 'orderable', '600', 'Kicks', 'Active');
insert into acnh_sock values(43, 0, 'country socks (Red ribbons)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(44, 0, 'country socks (Green ribbons)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(45, 0, 'country socks (Blue ribbons)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(46, 0, 'country socks (Black ribbons)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(47, 0, 'crocheted socks (Beige)', 'orderable', '600', 'Able Sisters', 'Elegant');
insert into acnh_sock values(48, 0, 'crocheted socks (Purple)', 'orderable', '600', 'Able Sisters', 'Elegant');
insert into acnh_sock values(49, 0, 'crocheted socks (Blue)', 'orderable', '600', 'Able Sisters', 'Elegant');
insert into acnh_sock values(50, 0, 'crocheted socks (Gray)', 'orderable', '600', 'Able Sisters', 'Elegant');
insert into acnh_sock values(51, 0, 'denim leggings (Blue)', 'orderable', '540', 'Able Sisters', 'Simple');
insert into acnh_sock values(52, 0, 'denim leggings (Indigo blue)', 'orderable', '540', 'Able Sisters', 'Simple');
insert into acnh_sock values(53, 0, 'denim leggings (Saxon blue)', 'orderable', '540', 'Able Sisters', 'Simple');
insert into acnh_sock values(54, 0, 'denim leggings (Light blue)', 'orderable', '540', 'Able Sisters', 'Simple');
insert into acnh_sock values(55, 0, 'dotted knee-high socks (Black)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(56, 0, 'dotted knee-high socks (Yellow)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(57, 0, 'dotted knee-high socks (Cyan)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(58, 0, 'dotted knee-high socks (Gray)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(59, 0, 'embroidered-flower tights (Black)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_sock values(60, 0, 'embroidered-flower tights (Green)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_sock values(61, 0, 'embroidered-flower tights (Beige)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_sock values(62, 0, 'embroidered-flower tights (Brown)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_sock values(63, 0, 'embroidered-flower tights (Blue)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_sock values(64, 0, 'embroidered-flower tights (Purple)', 'orderable', '1000', 'Able Sisters', 'Cute');
insert into acnh_sock values(65, 0, 'everyday socks (Black)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(66, 0, 'everyday socks (Navy blue)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(67, 0, 'everyday socks (Gray)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(68, 0, 'everyday socks (Beige)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(69, 0, 'everyday socks (White)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(70, 0, 'everyday socks (Brown)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(71, 0, 'everyday tights (Light gray)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(72, 0, 'everyday tights (Gray)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(73, 0, 'everyday tights (White)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(74, 0, 'everyday tights (Navy blue)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(75, 0, 'everyday tights (Beige)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(76, 0, 'everyday tights (Black)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(77, 0, 'fishnet tights (White)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(78, 0, 'fishnet tights (Red)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(79, 0, 'fishnet tights (Black)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(80, 0, 'flowery-dot tights (White)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(81, 0, 'flowery-dot tights (Pink)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(82, 0, 'flowery-dot tights (Blue)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(83, 0, 'flowery-dot tights (Yellow)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(84, 0, 'flowery-dot tights (Black)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(85, 0, 'frilly knee-high socks (Black)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(86, 0, 'frilly knee-high socks (Red)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(87, 0, 'frilly knee-high socks (Brown)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(88, 0, 'frilly knee-high socks (Mint)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(89, 0, 'frilly knee-high socks (Pink)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(90, 0, 'frilly knee-high socks (Purple)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(91, 0, 'frilly knee-high socks (Yellow)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(92, 0, 'frilly knee-high socks (Green)', 'orderable', '840', 'Kicks', 'Cute');
insert into acnh_sock values(93, 0, 'frilly socks (White)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(94, 0, 'frilly socks (Yellow)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(95, 0, 'frilly socks (Pink)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(96, 0, 'frilly socks (Green)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(97, 0, 'frilly socks (Purple)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(98, 0, 'frilly socks (Blue)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(99, 0, 'funny-face socks (Pink)', 'orderable', '600', 'Kicks', 'Active');
insert into acnh_sock values(100, 0, 'funny-face socks (Blue)', 'orderable', '600', 'Kicks', 'Active');
insert into acnh_sock values(101, 0, 'funny-face socks (Red)', 'orderable', '600', 'Kicks', 'Active');
insert into acnh_sock values(102, 0, 'funny-face socks (Green)', 'orderable', '600', 'Kicks', 'Active');
insert into acnh_sock values(103, 0, 'funny-face socks (Black)', 'orderable', '600', 'Kicks', 'Active');
insert into acnh_sock values(104, 0, 'garter socks (Black)', 'orderable', '980', 'Kicks', 'Cool');
insert into acnh_sock values(105, 0, 'garter socks (White)', 'orderable', '980', 'Kicks', 'Cool');
insert into acnh_sock values(106, 0, 'garter socks (Purple)', 'orderable', '980', 'Kicks', 'Cool');
insert into acnh_sock values(107, 0, 'garter socks (Red)', 'orderable', '980', 'Kicks', 'Cool');
insert into acnh_sock values(108, 0, 'geometric-print socks (Yellow)', 'orderable', '950', 'Able Sisters', 'Active');
insert into acnh_sock values(109, 0, 'geometric-print socks (Peacock blue)', 'orderable', '950', 'Able Sisters', 'Active');
insert into acnh_sock values(110, 0, 'geometric-print socks (Purple)', 'orderable', '950', 'Able Sisters', 'Active');
insert into acnh_sock values(111, 0, 'geometric-print socks (Beige)', 'orderable', '950', 'Able Sisters', 'Active');
insert into acnh_sock values(112, 0, 'geometric-print socks (Pink)', 'orderable', '950', 'Able Sisters', 'Active');
insert into acnh_sock values(113, 0, 'geometric-print socks (Green)', 'orderable', '950', 'Able Sisters', 'Active');
insert into acnh_sock values(114, 0, 'hand-knit socks (Green)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_sock values(115, 0, 'hand-knit socks (Purple)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_sock values(116, 0, 'hand-knit socks (Orange)', 'orderable', '700', 'Able Sisters', 'Simple');
insert into acnh_sock values(117, 0, 'holey socks (Navy blue)', 'unorderable', '10', 'Recycle bin', 'Simple');
insert into acnh_sock values(118, 0, 'holey socks (White)', 'unorderable', '10', 'Recycle bin', 'Simple');
insert into acnh_sock values(119, 0, 'holey socks (Blue)', 'unorderable', '10', 'Recycle bin', 'Simple');
insert into acnh_sock values(120, 0, 'holey tights (Yellow)', 'orderable', '350', 'Able Sisters', 'Cool');
insert into acnh_sock values(121, 0, 'holey tights (Pink)', 'orderable', '350', 'Able Sisters', 'Cool');
insert into acnh_sock values(122, 0, 'holey tights (Light blue)', 'orderable', '350', 'Able Sisters', 'Cool');
insert into acnh_sock values(123, 0, 'holey tights (Red)', 'orderable', '350', 'Able Sisters', 'Cool');
insert into acnh_sock values(124, 0, 'holey tights (Purple)', 'orderable', '350', 'Able Sisters', 'Cool');
insert into acnh_sock values(125, 0, 'holey tights (Green)', 'orderable', '350', 'Able Sisters', 'Cool');
insert into acnh_sock values(126, 0, 'holey tights (Blue)', 'orderable', '350', 'Able Sisters', 'Cool');
insert into acnh_sock values(127, 0, 'holey tights (Black)', 'orderable', '350', 'Able Sisters', 'Cool');
insert into acnh_sock values(128, 0, 'kiddie socks (Red & light blue)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(129, 0, 'kiddie socks (Blue & orange)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(130, 0, 'kiddie socks (Lime & pink)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(131, 0, 'kiddie socks (Yellow & purple)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(132, 0, 'kiddie socks (Light blue & red)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(133, 0, 'kiddie socks (Purple & green)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(134, 0, 'kiddie socks (Pink & yellow)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(135, 0, 'kiddie socks (Black & gray)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(136, 0, 'Labelle socks (Midnight)', 'orderable', '940', 'Labelle', 'Cool');
insert into acnh_sock values(137, 0, 'Labelle socks (Passion)', 'orderable', '940', 'Labelle', 'Cool');
insert into acnh_sock values(138, 0, 'Labelle socks (Ocean)', 'orderable', '940', 'Labelle', 'Cool');
insert into acnh_sock values(139, 0, 'Labelle socks (Sunset)', 'orderable', '940', 'Labelle', 'Cool');
insert into acnh_sock values(140, 0, 'Labelle socks (Love)', 'orderable', '940', 'Labelle', 'Cool');
insert into acnh_sock values(141, 0, 'Labelle socks (Twilight)', 'orderable', '940', 'Labelle', 'Cool');
insert into acnh_sock values(142, 0, 'Labelle tights (Midnight)', 'orderable', '1240', 'Labelle', 'Elegant');
insert into acnh_sock values(143, 0, 'Labelle tights (Passion)', 'orderable', '1240', 'Labelle', 'Elegant');
insert into acnh_sock values(144, 0, 'Labelle tights (Ocean)', 'orderable', '1240', 'Labelle', 'Elegant');
insert into acnh_sock values(145, 0, 'Labelle tights (Sunset)', 'orderable', '1240', 'Labelle', 'Elegant');
insert into acnh_sock values(146, 0, 'Labelle tights (Twilight)', 'orderable', '1240', 'Labelle', 'Elegant');
insert into acnh_sock values(147, 0, 'Labelle tights (Love)', 'orderable', '1240', 'Labelle', 'Elegant');
insert into acnh_sock values(148, 0, 'lace socks (White)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(149, 0, 'lace socks (Pink)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(150, 0, 'lace socks (Green)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(151, 0, 'lace socks (Black)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(152, 0, 'lace socks (Beige)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(153, 0, 'layered socks (Blue)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(154, 0, 'layered socks (Yellow)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(155, 0, 'layered socks (Green)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(156, 0, 'layered socks (Red)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(157, 0, 'layered socks (Orange)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(158, 0, 'layered socks (Purple)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(159, 0, 'leg warmers (Purple)', 'orderable', '440', 'Able Sisters', 'Active');
insert into acnh_sock values(160, 0, 'leg warmers (Black)', 'orderable', '440', 'Able Sisters', 'Active');
insert into acnh_sock values(161, 0, 'leg warmers (Gray)', 'orderable', '440', 'Able Sisters', 'Active');
insert into acnh_sock values(162, 0, 'leg warmers (Pink)', 'orderable', '440', 'Able Sisters', 'Active');
insert into acnh_sock values(163, 0, 'leg warmers (Light purple)', 'orderable', '440', 'Able Sisters', 'Active');
insert into acnh_sock values(164, 0, 'leg warmers (Blue)', 'orderable', '440', 'Able Sisters', 'Active');
insert into acnh_sock values(165, 0, 'mixed-tweed socks (Avocado)', 'orderable', '800', 'Able Sisters', 'Simple');
insert into acnh_sock values(166, 0, 'mixed-tweed socks (Light blue)', 'orderable', '800', 'Able Sisters', 'Simple');
insert into acnh_sock values(167, 0, 'mixed-tweed socks (Purple)', 'orderable', '800', 'Able Sisters', 'Simple');
insert into acnh_sock values(168, 0, 'mixed-tweed socks (Blue)', 'orderable', '800', 'Able Sisters', 'Simple');
insert into acnh_sock values(169, 0, 'mixed-tweed socks (Red)', 'orderable', '800', 'Able Sisters', 'Simple');
insert into acnh_sock values(170, 0, 'mixed-tweed socks (Orange)', 'orderable', '800', 'Able Sisters', 'Simple');
insert into acnh_sock values(171, 0, 'mixed-tweed socks (Lime)', 'orderable', '800', 'Able Sisters', 'Simple');
insert into acnh_sock values(172, 0, 'mixed-tweed socks (Pink)', 'orderable', '800', 'Able Sisters', 'Simple');
insert into acnh_sock values(173, 0, 'neon leggings (Pink)', 'orderable', '540', 'Able Sisters', 'Active');
insert into acnh_sock values(174, 0, 'neon leggings (Orange)', 'orderable', '540', 'Able Sisters', 'Active');
insert into acnh_sock values(175, 0, 'neon leggings (Yellow)', 'orderable', '540', 'Able Sisters', 'Active');
insert into acnh_sock values(176, 0, 'neon leggings (Green)', 'orderable', '540', 'Able Sisters', 'Active');
insert into acnh_sock values(177, 0, 'neon leggings (Purple)', 'orderable', '540', 'Able Sisters', 'Active');
insert into acnh_sock values(178, 0, 'neon tights (Pink)', 'orderable', '720', 'Able Sisters', 'Active');
insert into acnh_sock values(179, 0, 'neon tights (Orange)', 'orderable', '720', 'Able Sisters', 'Active');
insert into acnh_sock values(180, 0, 'neon tights (Green)', 'orderable', '720', 'Able Sisters', 'Active');
insert into acnh_sock values(181, 0, 'neon tights (Purple)', 'orderable', '720', 'Able Sisters', 'Active');
insert into acnh_sock values(182, 0, 'neon tights (Yellow)', 'orderable', '720', 'Able Sisters', 'Active');
insert into acnh_sock values(183, 0, 'no-show socks (White)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(184, 0, 'no-show socks (Berry red)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(185, 0, 'no-show socks (Light blue)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(186, 0, 'no-show socks (Orange)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(187, 0, 'no-show socks (Green)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(188, 0, 'no-show socks (Navy blue)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(189, 0, 'no-show socks (Yellow)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(190, 0, 'no-show socks (Gray)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(191, 0, 'Nook Inc. socks (Yellow)', 'unorderable', '2000', 'Nook Miles Shop', 'Active');
insert into acnh_sock values(192, 0, 'nordic socks (Ivory)', 'orderable', '840', 'Able Sisters', 'Elegant');
insert into acnh_sock values(193, 0, 'nordic socks (Navy blue)', 'orderable', '840', 'Able Sisters', 'Elegant');
insert into acnh_sock values(194, 0, 'nordic socks (Red)', 'orderable', '840', 'Able Sisters', 'Elegant');
insert into acnh_sock values(195, 0, 'nordic socks (Blue)', 'orderable', '840', 'Able Sisters', 'Elegant');
insert into acnh_sock values(196, 0, 'nordic socks (Gray)', 'orderable', '840', 'Able Sisters', 'Elegant');
insert into acnh_sock values(197, 0, 'nordic socks (Green)', 'orderable', '840', 'Able Sisters', 'Elegant');
insert into acnh_sock values(198, 0, 'nordic socks (Light blue)', 'orderable', '840', 'Able Sisters', 'Elegant');
insert into acnh_sock values(199, 0, 'patterned stockings (Black)', 'orderable', '940', 'Able Sisters', 'Elegant');
insert into acnh_sock values(200, 0, 'patterned stockings (White)', 'orderable', '940', 'Able Sisters', 'Elegant');
insert into acnh_sock values(201, 0, 'pom-pom socks (Blue)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(202, 0, 'pom-pom socks (Green)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(203, 0, 'pom-pom socks (Orange)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(204, 0, 'pom-pom socks (Purple)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(205, 0, 'pom-pom socks (Pink)', 'orderable', '720', 'Able Sisters', 'Cute');
insert into acnh_sock values(206, 0, 'puckered socks (Red)', 'orderable', '600', 'Able Sisters', 'Elegant');
insert into acnh_sock values(207, 0, 'puckered socks (Blue)', 'orderable', '600', 'Able Sisters', 'Elegant');
insert into acnh_sock values(208, 0, 'puckered socks (Mustard)', 'orderable', '600', 'Able Sisters', 'Elegant');
insert into acnh_sock values(209, 0, 'puckered socks (Green)', 'orderable', '600', 'Able Sisters', 'Elegant');
insert into acnh_sock values(210, 0, 'puckered socks (Purple)', 'orderable', '600', 'Able Sisters', 'Elegant');
insert into acnh_sock values(211, 0, 'running tights (Pink)', 'orderable', '550', 'Able Sisters', 'Active');
insert into acnh_sock values(212, 0, 'running tights (Yellow)', 'orderable', '550', 'Able Sisters', 'Active');
insert into acnh_sock values(213, 0, 'running tights (Blue)', 'orderable', '550', 'Able Sisters', 'Active');
insert into acnh_sock values(214, 0, 'running tights (Green)', 'orderable', '550', 'Able Sisters', 'Active');
insert into acnh_sock values(215, 0, 'semi-opaque socks (Purple)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(216, 0, 'semi-opaque socks (Camel)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(217, 0, 'semi-opaque socks (Avocado)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(218, 0, 'semi-opaque socks (Brown)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(219, 0, 'semi-opaque socks (Green)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(220, 0, 'semi-opaque socks (Red)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(221, 0, 'semi-opaque socks (Blue)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(222, 0, 'semi-opaque socks (Navy blue)', 'orderable', '480', 'Able Sisters', 'Elegant');
insert into acnh_sock values(223, 0, 'semi-opaque tights (Red)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(224, 0, 'semi-opaque tights (Yellow-green)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(225, 0, 'semi-opaque tights (Yellow)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(226, 0, 'semi-opaque tights (Green)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(227, 0, 'semi-opaque tights (Purple)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(228, 0, 'semi-opaque tights (Blue)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(229, 0, 'semi-opaque tights (Pink)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(230, 0, 'semi-opaque tights (Brown)', 'orderable', '720', 'Able Sisters', 'Elegant');
insert into acnh_sock values(231, 0, 'sequin leggings (Pink)', 'orderable', '940', 'Kicks', 'Gorgeous');
insert into acnh_sock values(232, 0, 'sequin leggings (Red)', 'orderable', '940', 'Kicks', 'Gorgeous');
insert into acnh_sock values(233, 0, 'sequin leggings (Black)', 'orderable', '940', 'Kicks', 'Gorgeous');
insert into acnh_sock values(234, 0, 'sequin leggings (Yellow)', 'orderable', '940', 'Kicks', 'Gorgeous');
insert into acnh_sock values(235, 0, 'sequin leggings (White)', 'orderable', '940', 'Kicks', 'Gorgeous');
insert into acnh_sock values(236, 0, 'sequin leggings (Blue)', 'orderable', '940', 'Kicks', 'Gorgeous');
insert into acnh_sock values(237, 0, 'sequin leggings (Purple)', 'orderable', '940', 'Kicks', 'Gorgeous');
insert into acnh_sock values(238, 0, 'sequin leggings (Green)', 'orderable', '940', 'Kicks', 'Gorgeous');
insert into acnh_sock values(239, 0, 'sheer socks (Green)', 'orderable', '600', 'Kicks', 'Elegant');
insert into acnh_sock values(240, 0, 'sheer socks (Olive)', 'orderable', '600', 'Kicks', 'Elegant');
insert into acnh_sock values(241, 0, 'sheer socks (Gray)', 'orderable', '600', 'Kicks', 'Elegant');
insert into acnh_sock values(242, 0, 'sheer socks (Blue)', 'orderable', '600', 'Kicks', 'Elegant');
insert into acnh_sock values(243, 0, 'sheer socks (Berry red)', 'orderable', '600', 'Kicks', 'Elegant');
insert into acnh_sock values(244, 0, 'sheer socks (Brown)', 'orderable', '600', 'Kicks', 'Elegant');
insert into acnh_sock values(245, 0, 'simple knee-high socks (White)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(246, 0, 'simple knee-high socks (Red)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(247, 0, 'simple knee-high socks (Blue)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(248, 0, 'simple knee-high socks (Pink)', 'orderable', '600', 'Kicks', 'Cute');
insert into acnh_sock values(249, 0, 'simple-accent socks (Black)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(250, 0, 'simple-accent socks (White)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(251, 0, 'simple-accent socks (Gray)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(252, 0, 'simple-accent socks (Blue)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(253, 0, 'simple-accent socks (Orange)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(254, 0, 'simple-accent socks (Red)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(255, 0, 'simple-accent socks (Pink)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(256, 0, 'simple-accent socks (Navy blue)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(257, 0, 'soccer socks (Red)', 'orderable', '800', 'Kicks', 'Active');
insert into acnh_sock values(258, 0, 'soccer socks (Green)', 'orderable', '800', 'Kicks', 'Active');
insert into acnh_sock values(259, 0, 'soccer socks (Light blue)', 'orderable', '800', 'Kicks', 'Active');
insert into acnh_sock values(260, 0, 'soccer socks (Black)', 'orderable', '800', 'Kicks', 'Active');
insert into acnh_sock values(261, 0, 'soccer socks (Orange)', 'orderable', '800', 'Kicks', 'Active');
insert into acnh_sock values(262, 0, 'soccer socks (White)', 'orderable', '800', 'Kicks', 'Active');
insert into acnh_sock values(263, 0, 'soccer socks (Blue)', 'orderable', '800', 'Kicks', 'Active');
insert into acnh_sock values(264, 0, 'spider-web tights (Black)', 'orderable', '720', 'Kicks', 'Cool');
insert into acnh_sock values(265, 0, 'spider-web tights (White)', 'orderable', '720', 'Kicks', 'Cool');
insert into acnh_sock values(266, 0, 'spider-web tights (Orange)', 'orderable', '720', 'Kicks', 'Cool');
insert into acnh_sock values(267, 0, 'spider-web tights (Purple)', 'orderable', '720', 'Kicks', 'Cool');
insert into acnh_sock values(268, 0, 'stockings (Gray)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(269, 0, 'stockings (White)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(270, 0, 'stockings (Brown)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(271, 0, 'stockings (Beige)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(272, 0, 'stockings (Black)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(273, 0, 'stretch leggings (Navy blue)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(274, 0, 'stretch leggings (Brown)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(275, 0, 'stretch leggings (Green)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(276, 0, 'stretch leggings (Gray)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(277, 0, 'stretch leggings (Dark gray)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(278, 0, 'stretch leggings (White)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(279, 0, 'stretch leggings (Black)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(280, 0, 'striped socks (Purple)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(281, 0, 'striped socks (Blue)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(282, 0, 'striped socks (Green)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(283, 0, 'striped socks (Light blue)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(284, 0, 'striped socks (Yellow)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(285, 0, 'striped socks (Orange)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(286, 0, 'striped socks (Red)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(287, 0, 'striped socks (Monotone)', 'orderable', '600', 'Able Sisters', 'Simple');
insert into acnh_sock values(288, 0, 'striped tights (Yellow)', 'orderable', '720', 'Able Sisters', 'Gorgeous');
insert into acnh_sock values(289, 0, 'striped tights (Purple)', 'orderable', '720', 'Able Sisters', 'Gorgeous');
insert into acnh_sock values(290, 0, 'striped tights (Green)', 'orderable', '720', 'Able Sisters', 'Gorgeous');
insert into acnh_sock values(291, 0, 'striped tights (Orange)', 'orderable', '720', 'Able Sisters', 'Gorgeous');
insert into acnh_sock values(292, 0, 'striped tights (Red)', 'orderable', '720', 'Able Sisters', 'Gorgeous');
insert into acnh_sock values(293, 0, 'striped tights (Gray)', 'orderable', '720', 'Able Sisters', 'Gorgeous');
insert into acnh_sock values(294, 0, 'striped tights (Pink)', 'orderable', '720', 'Able Sisters', 'Gorgeous');
insert into acnh_sock values(295, 0, 'striped tights (Light blue)', 'orderable', '720', 'Able Sisters', 'Gorgeous');
insert into acnh_sock values(296, 0, 'tabi (Navy blue)', 'orderable', '1200', 'Able Sisters', 'Simple');
insert into acnh_sock values(297, 0, 'tabi (White)', 'orderable', '1200', 'Able Sisters', 'Simple');
insert into acnh_sock values(298, 0, 'tabi (Black)', 'orderable', '1200', 'Able Sisters', 'Simple');
insert into acnh_sock values(299, 0, 'terry-cloth socks (Purple)', 'orderable', '600', 'Able Sisters', 'Cute');
insert into acnh_sock values(300, 0, 'terry-cloth socks (Pink)', 'orderable', '600', 'Able Sisters', 'Cute');
insert into acnh_sock values(301, 0, 'terry-cloth socks (Blue)', 'orderable', '600', 'Able Sisters', 'Cute');
insert into acnh_sock values(302, 0, 'terry-cloth socks (Green)', 'orderable', '600', 'Able Sisters', 'Cute');
insert into acnh_sock values(303, 0, 'terry-cloth socks (Beige)', 'orderable', '600', 'Able Sisters', 'Cute');
insert into acnh_sock values(304, 0, 'terry-cloth socks (Red)', 'orderable', '600', 'Able Sisters', 'Cute');
insert into acnh_sock values(305, 0, 'terry-cloth socks (Gray)', 'orderable', '600', 'Able Sisters', 'Cute');
insert into acnh_sock values(306, 0, 'tube socks (Blue)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(307, 0, 'tube socks (Orange)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(308, 0, 'tube socks (Green)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(309, 0, 'tube socks (Red)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(310, 0, 'tube socks (Navy blue)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(311, 0, 'tube socks (Berry red)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(312, 0, 'tube socks (Dark green)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(313, 0, 'tube socks (Purple)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(314, 0, 'ultra no-show socks (Pink)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(315, 0, 'ultra no-show socks (Brown)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(316, 0, 'ultra no-show socks (Olive)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(317, 0, 'ultra no-show socks (Green)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(318, 0, 'ultra no-show socks (Purple)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(319, 0, 'ultra no-show socks (Black)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(320, 0, 'ultra no-show socks (Blue)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(321, 0, 'ultra no-show socks (White)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(322, 0, 'vivid leggings (Purple)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(323, 0, 'vivid leggings (Red)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(324, 0, 'vivid leggings (Pink)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(325, 0, 'vivid leggings (Blue)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(326, 0, 'vivid leggings (Yellow)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(327, 0, 'vivid leggings (Green)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(328, 0, 'vivid leggings (Orange)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(329, 0, 'vivid leggings (Light blue)', 'orderable', '450', 'Able Sisters', 'Simple');
insert into acnh_sock values(330, 0, 'vivid socks (Red)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(331, 0, 'vivid socks (Green)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(332, 0, 'vivid socks (Light blue)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(333, 0, 'vivid socks (Blue)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(334, 0, 'vivid socks (Purple)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(335, 0, 'vivid socks (Pink)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(336, 0, 'vivid socks (Orange)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(337, 0, 'vivid socks (Yellow)', 'orderable', '480', 'Able Sisters', 'Simple');
insert into acnh_sock values(338, 0, 'vivid tights (Blue)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(339, 0, 'vivid tights (Yellow)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(340, 0, 'vivid tights (Green)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(341, 0, 'vivid tights (Orange)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(342, 0, 'vivid tights (Purple)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(343, 0, 'vivid tights (Red)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(344, 0, 'vivid tights (Pink)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(345, 0, 'vivid tights (Light blue)', 'orderable', '720', 'Able Sisters', 'Simple');
insert into acnh_sock values(346, 0, 'wave-print socks (Blue)', 'orderable', '600', 'Kicks', 'Cool');
insert into acnh_sock values(347, 0, 'wave-print socks (Brown)', 'orderable', '600', 'Kicks', 'Cool');
insert into acnh_sock values(348, 0, 'wave-print socks (Purple)', 'orderable', '600', 'Kicks', 'Cool');
insert into acnh_sock values(349, 0, 'wave-print socks (Green)', 'orderable', '600', 'Kicks', 'Cool');
insert into acnh_sock values(350, 0, 'wave-print socks (Gray)', 'orderable', '600', 'Kicks', 'Cool');
