drop table if exists acnh_song;
create table acnh_song ("Index" int primary key, Selected int, Name varchar(50), Status varchar (31), "From" varchar(31));
insert into acnh_song values(1, 0, 'Agent K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(2, 0, 'Aloha K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(3, 0, 'Animal City', 'unorderable', 'K.K. concert');
insert into acnh_song values(4, 0, 'Bubblegum K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(5, 0, 'Café K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(6, 0, 'Comrade K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(7, 0, 'DJ K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(8, 0, 'Drivin''', 'unorderable', 'K.K. concert');
insert into acnh_song values(9, 0, 'Farewell', 'unorderable', 'K.K. concert');
insert into acnh_song values(10, 0, 'Forest Life', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(11, 0, 'Go K.K. Rider', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(12, 0, 'Hypno K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(13, 0, 'I Love You', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(14, 0, 'Imperial K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(15, 0, 'K.K. Adventure', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(16, 0, 'K.K. Aria', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(17, 0, 'K.K. Ballad', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(18, 0, 'K.K. Bazaar', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(19, 0, 'K.K. Birthday', 'unorderable', 'K.K. concert');
insert into acnh_song values(20, 0, 'K.K. Blues', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(21, 0, 'K.K. Bossa', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(22, 0, 'K.K. Calypso', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(23, 0, 'K.K. Casbah', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(24, 0, 'K.K. Chorale', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(25, 0, 'K.K. Condor', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(26, 0, 'K.K. Country', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(27, 0, 'K.K. Cruisin''', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(28, 0, 'K.K. D&B', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(29, 0, 'K.K. Dirge', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(30, 0, 'K.K. Disco', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(31, 0, 'K.K. Dixie', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(32, 0, 'K.K. Étude', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(33, 0, 'K.K. Faire', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(34, 0, 'K.K. Flamenco', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(35, 0, 'K.K. Folk', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(36, 0, 'K.K. Fusion', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(37, 0, 'K.K. Groove', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(38, 0, 'K.K. Gumbo', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(39, 0, 'K.K. House', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(40, 0, 'K.K. Island', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(41, 0, 'K.K. Jazz', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(42, 0, 'K.K. Jongara', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(43, 0, 'K.K. Lament', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(44, 0, 'K.K. Love Song', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(45, 0, 'K.K. Lullaby', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(46, 0, 'K.K. Mambo', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(47, 0, 'K.K. Marathon', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(48, 0, 'K.K. March', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(49, 0, 'K.K. Mariachi', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(50, 0, 'K.K. Metal', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(51, 0, 'K.K. Milonga', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(52, 0, 'K.K. Moody', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(53, 0, 'K.K. Oasis', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(54, 0, 'K.K. Parade', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(55, 0, 'K.K. Ragtime', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(56, 0, 'K.K. Rally', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(57, 0, 'K.K. Reggae', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(58, 0, 'K.K. Rock', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(59, 0, 'K.K. Rockabilly', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(60, 0, 'K.K. Safari', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(61, 0, 'K.K. Salsa', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(62, 0, 'K.K. Samba', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(63, 0, 'K.K. Ska', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(64, 0, 'K.K. Sonata', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(65, 0, 'K.K. Song', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(66, 0, 'K.K. Soul', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(67, 0, 'K.K. Steppe', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(68, 0, 'K.K. Stroll', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(69, 0, 'K.K. Swing', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(70, 0, 'K.K. Synth', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(71, 0, 'K.K. Tango', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(72, 0, 'K.K. Technopop', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(73, 0, 'K.K. Waltz', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(74, 0, 'K.K. Western', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(75, 0, 'King K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(76, 0, 'Lucky K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(77, 0, 'Marine Song 2001', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(78, 0, 'Mountain Song', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(79, 0, 'Mr. K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(80, 0, 'My Place', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(81, 0, 'Neapolitan', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(82, 0, 'Only Me', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(83, 0, 'Pondering', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(84, 0, 'Rockin'' K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(85, 0, 'Soulful K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(86, 0, 'Space K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(87, 0, 'Spring Blossoms', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(88, 0, 'Stale Cupcakes', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(89, 0, 'Steep Hill', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(90, 0, 'Surfin'' K.K.', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(91, 0, 'The K. Funk', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(92, 0, 'To the Edge', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(93, 0, 'Two Days Ago', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(94, 0, 'Wandering', 'normal', 'K.K. concert, Nook Shopping Catalog');
insert into acnh_song values(95, 0, 'Welcome Horizons', 'unorderable', 'K.K. concert');