drop table if exists acnh_tool;
create table acnh_tool ("Index" int primary key, Selected int, Name varchar(255), "From" varchar(63));
insert into acnh_tool values(1, 0, 'axe', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(2, 0, 'bamboo wand', 'Crafting');
insert into acnh_tool values(3, 0, 'bug wand', 'Bug-Off');
insert into acnh_tool values(4, 0, 'Bunny Day wand', 'Crafting');
insert into acnh_tool values(5, 0, 'cherry-blossom wand', 'Crafting');
insert into acnh_tool values(6, 0, 'colorful fishing rod', 'Nook''s Cranny');
insert into acnh_tool values(7, 0, 'colorful net', 'Nook''s Cranny');
insert into acnh_tool values(8, 0, 'colorful shovel', 'Nook''s Cranny');
insert into acnh_tool values(9, 0, 'colorful slingshot', 'Nook''s Cranny');
insert into acnh_tool values(10, 0, 'colorful watering can', 'Nook''s Cranny');
insert into acnh_tool values(11, 0, 'cosmos wand', 'Crafting');
insert into acnh_tool values(12, 0, 'elephant watering can', 'Nook''s Cranny');
insert into acnh_tool values(13, 0, 'fish fishing rod', 'Nook''s Cranny');
insert into acnh_tool values(14, 0, 'fish wand', 'Fishing Tourney');
insert into acnh_tool values(15, 0, 'fishing rod', 'Crafting');
insert into acnh_tool values(16, 0, 'flimsy axe', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(17, 0, 'flimsy fishing rod', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(18, 0, 'flimsy net', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(19, 0, 'flimsy shovel', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(20, 0, 'flimsy watering can', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(21, 0, 'golden axe', 'Crafting');
insert into acnh_tool values(22, 0, 'golden net', 'Crafting');
insert into acnh_tool values(23, 0, 'golden rod', 'Crafting');
insert into acnh_tool values(24, 0, 'golden shovel', 'Crafting');
insert into acnh_tool values(25, 0, 'golden slingshot', 'Crafting');
insert into acnh_tool values(26, 0, 'golden wand', 'Crafting');
insert into acnh_tool values(27, 0, 'golden watering can', 'Crafting');
insert into acnh_tool values(28, 0, 'hyacinth wand', 'Crafting');
insert into acnh_tool values(29, 0, 'ice wand', 'Crafting');
insert into acnh_tool values(30, 0, 'iron wand', 'Crafting');
insert into acnh_tool values(31, 0, 'ladder', 'Crafting');
insert into acnh_tool values(32, 0, 'light stick', 'Crafting');
insert into acnh_tool values(33, 0, 'lily wand', 'Crafting');
insert into acnh_tool values(34, 0, 'mums wand', 'Crafting');
insert into acnh_tool values(35, 0, 'mushroom wand', 'Crafting');
insert into acnh_tool values(36, 0, 'net', 'Crafting');
insert into acnh_tool values(37, 0, 'Nook Inc. uchiwa fan', 'Nook Miles Shop');
insert into acnh_tool values(38, 0, 'ocarina', 'Crafting');
insert into acnh_tool values(39, 0, 'outdoorsy fishing rod', 'Nook''s Cranny');
insert into acnh_tool values(40, 0, 'outdoorsy net', 'Nook''s Cranny');
insert into acnh_tool values(41, 0, 'outdoorsy shovel', 'Nook''s Cranny');
insert into acnh_tool values(42, 0, 'outdoorsy slingshot', 'Nook''s Cranny');
insert into acnh_tool values(43, 0, 'outdoorsy watering can', 'Nook''s Cranny');
insert into acnh_tool values(44, 0, 'pan flute', 'Crafting');
insert into acnh_tool values(45, 0, 'pansy wand', 'Crafting');
insert into acnh_tool values(46, 0, 'party popper', 'Nook''s Cranny');
insert into acnh_tool values(47, 0, 'printed-design shovel', 'Nook''s Cranny');
insert into acnh_tool values(48, 0, 'rose wand', 'Crafting');
insert into acnh_tool values(49, 0, 'shell wand', 'Crafting');
insert into acnh_tool values(50, 0, 'shovel', 'Crafting');
insert into acnh_tool values(51, 0, 'slingshot', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(52, 0, 'star net', 'Nook''s Cranny');
insert into acnh_tool values(53, 0, 'star wand', 'Crafting');
insert into acnh_tool values(54, 0, 'stone axe', 'Crafting');
insert into acnh_tool values(55, 0, 'tambourine', 'Nook''s Cranny');
insert into acnh_tool values(56, 0, 'timer', 'Nook''s Cranny');
insert into acnh_tool values(57, 0, 'tree-branch wand', 'Crafting');
insert into acnh_tool values(58, 0, 'tulip wand', 'Crafting');
insert into acnh_tool values(59, 0, 'vaulting pole', 'Crafting');
insert into acnh_tool values(60, 0, 'wand', 'Crafting');
insert into acnh_tool values(61, 0, 'watering can', 'Crafting');
insert into acnh_tool values(62, 0, 'windflower wand', 'Crafting');
insert into acnh_tool values(63, 0, 'axe', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(64, 0, 'bamboo wand', 'Crafting');
insert into acnh_tool values(65, 0, 'bug wand', 'Bug-Off');
insert into acnh_tool values(66, 0, 'Bunny Day wand', 'Crafting');
insert into acnh_tool values(67, 0, 'cherry-blossom wand', 'Crafting');
insert into acnh_tool values(68, 0, 'colorful fishing rod', 'Nook''s Cranny');
insert into acnh_tool values(69, 0, 'colorful net', 'Nook''s Cranny');
insert into acnh_tool values(70, 0, 'colorful shovel', 'Nook''s Cranny');
insert into acnh_tool values(71, 0, 'colorful slingshot', 'Nook''s Cranny');
insert into acnh_tool values(72, 0, 'colorful watering can', 'Nook''s Cranny');
insert into acnh_tool values(73, 0, 'cosmos wand', 'Crafting');
insert into acnh_tool values(74, 0, 'elephant watering can', 'Nook''s Cranny');
insert into acnh_tool values(75, 0, 'fish fishing rod', 'Nook''s Cranny');
insert into acnh_tool values(76, 0, 'fish wand', 'Fishing Tourney');
insert into acnh_tool values(77, 0, 'fishing rod', 'Crafting');
insert into acnh_tool values(78, 0, 'flimsy axe', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(79, 0, 'flimsy fishing rod', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(80, 0, 'flimsy net', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(81, 0, 'flimsy shovel', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(82, 0, 'flimsy watering can', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(83, 0, 'golden axe', 'Crafting');
insert into acnh_tool values(84, 0, 'golden net', 'Crafting');
insert into acnh_tool values(85, 0, 'golden rod', 'Crafting');
insert into acnh_tool values(86, 0, 'golden shovel', 'Crafting');
insert into acnh_tool values(87, 0, 'golden slingshot', 'Crafting');
insert into acnh_tool values(88, 0, 'golden wand', 'Crafting');
insert into acnh_tool values(89, 0, 'golden watering can', 'Crafting');
insert into acnh_tool values(90, 0, 'hyacinth wand', 'Crafting');
insert into acnh_tool values(91, 0, 'ice wand', 'Crafting');
insert into acnh_tool values(92, 0, 'iron wand', 'Crafting');
insert into acnh_tool values(93, 0, 'ladder', 'Crafting');
insert into acnh_tool values(94, 0, 'light stick', 'Crafting');
insert into acnh_tool values(95, 0, 'lily wand', 'Crafting');
insert into acnh_tool values(96, 0, 'mums wand', 'Crafting');
insert into acnh_tool values(97, 0, 'mushroom wand', 'Crafting');
insert into acnh_tool values(98, 0, 'net', 'Crafting');
insert into acnh_tool values(99, 0, 'Nook Inc. uchiwa fan', 'Nook Miles Shop');
insert into acnh_tool values(100, 0, 'ocarina', 'Crafting');
insert into acnh_tool values(101, 0, 'outdoorsy fishing rod', 'Nook''s Cranny');
insert into acnh_tool values(102, 0, 'outdoorsy net', 'Nook''s Cranny');
insert into acnh_tool values(103, 0, 'outdoorsy shovel', 'Nook''s Cranny');
insert into acnh_tool values(104, 0, 'outdoorsy slingshot', 'Nook''s Cranny');
insert into acnh_tool values(105, 0, 'outdoorsy watering can', 'Nook''s Cranny');
insert into acnh_tool values(106, 0, 'pan flute', 'Crafting');
insert into acnh_tool values(107, 0, 'pansy wand', 'Crafting');
insert into acnh_tool values(108, 0, 'party popper', 'Nook''s Cranny');
insert into acnh_tool values(109, 0, 'printed-design shovel', 'Nook''s Cranny');
insert into acnh_tool values(110, 0, 'rose wand', 'Crafting');
insert into acnh_tool values(111, 0, 'shell wand', 'Crafting');
insert into acnh_tool values(112, 0, 'shovel', 'Crafting');
insert into acnh_tool values(113, 0, 'slingshot', 'Nook''s Cranny, Crafting');
insert into acnh_tool values(114, 0, 'star net', 'Nook''s Cranny');
insert into acnh_tool values(115, 0, 'star wand', 'Crafting');
insert into acnh_tool values(116, 0, 'stone axe', 'Crafting');
insert into acnh_tool values(117, 0, 'tambourine', 'Nook''s Cranny');
insert into acnh_tool values(118, 0, 'timer', 'Nook''s Cranny');
insert into acnh_tool values(119, 0, 'tree-branch wand', 'Crafting');
insert into acnh_tool values(120, 0, 'tulip wand', 'Crafting');
insert into acnh_tool values(121, 0, 'vaulting pole', 'Crafting');
insert into acnh_tool values(122, 0, 'wand', 'Crafting');
insert into acnh_tool values(123, 0, 'watering can', 'Crafting');
insert into acnh_tool values(124, 0, 'windflower wand', 'Crafting');