drop table if exists acnh_umbrella;
create table acnh_umbrella ("Index" int primary key, Selected int, Name varchar(255), Status varchar(31), Price varchar(15), "From" varchar(63));
insert into acnh_umbrella values(1, 0, 'apple umbrella', 'unorderable', '1400', 'Crafting');
insert into acnh_umbrella values(2, 0, 'bat umbrella', 'orderable', '840', 'Nook''s Cranny');
insert into acnh_umbrella values(3, 0, 'beach umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(4, 0, 'bear umbrella', 'orderable', '1570', 'Nook''s Cranny');
insert into acnh_umbrella values(5, 0, 'black chic umbrella', 'orderable', '1620', 'Nook''s Cranny');
insert into acnh_umbrella values(6, 0, 'black lace umbrella', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(7, 0, 'blue dot parasol', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(8, 0, 'blue shiny-bows parasol', 'orderable', '1620', 'Nook''s Cranny');
insert into acnh_umbrella values(9, 0, 'blue umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(10, 0, 'busted umbrella', 'orderable', '1570', 'Nook''s Cranny');
insert into acnh_umbrella values(11, 0, 'camo umbrella', 'orderable', '650', 'Nook''s Cranny');
insert into acnh_umbrella values(12, 0, 'candy umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(13, 0, 'cherry umbrella', 'unorderable', '1400', 'Crafting');
insert into acnh_umbrella values(14, 0, 'cherry-blossom umbrella', 'unorderable', '2800', 'Crafting');
insert into acnh_umbrella values(15, 0, 'DAL umbrella', 'unorderable', '1010', 'Dodo Airlines');
insert into acnh_umbrella values(16, 0, 'eggy parasol', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(17, 0, 'exquisite parasol', 'orderable', '1670', 'Nook''s Cranny');
insert into acnh_umbrella values(18, 0, 'fairy-tale umbrella', 'orderable', '820', 'Nook''s Cranny');
insert into acnh_umbrella values(19, 0, 'fish umbrella', 'unorderable', '80', 'Fishing Tourney');
insert into acnh_umbrella values(20, 0, 'frog umbrella', 'orderable', '1570', 'Nook''s Cranny');
insert into acnh_umbrella values(21, 0, 'gelato umbrella', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(22, 0, 'ghost umbrella', 'orderable', '1670', 'Nook''s Cranny');
insert into acnh_umbrella values(23, 0, 'grape umbrella', 'orderable', '1550', 'Nook''s Cranny');
insert into acnh_umbrella values(24, 0, 'green chic umbrella', 'orderable', '1620', 'Nook''s Cranny');
insert into acnh_umbrella values(25, 0, 'green umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(26, 0, 'hydrangea umbrella', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(27, 0, 'kabuki umbrella', 'orderable', '1670', 'Nook''s Cranny');
insert into acnh_umbrella values(28, 0, 'kiwi umbrella', 'orderable', '1550', 'Nook''s Cranny');
insert into acnh_umbrella values(29, 0, 'lacy parasol', 'orderable', '1550', 'Nook''s Cranny');
insert into acnh_umbrella values(30, 0, 'ladybug umbrella', 'unorderable', '80', 'Bug-Off');
insert into acnh_umbrella values(31, 0, 'leaf umbrella', 'unorderable', '300', 'Crafting');
insert into acnh_umbrella values(32, 0, 'lemon umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(33, 0, 'logo umbrella', 'orderable', '650', 'Nook''s Cranny');
insert into acnh_umbrella values(34, 0, 'maple-leaf umbrella', 'unorderable', '2800', 'Crafting');
insert into acnh_umbrella values(35, 0, 'melon umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(36, 0, 'mini-flower-print umbrella', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(37, 0, 'mint umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(38, 0, 'mush umbrella', 'unorderable', '1200', 'Crafting');
insert into acnh_umbrella values(39, 0, 'Nook Inc. umbrella', 'unorderable', '3500', 'Nook Miles Shop');
insert into acnh_umbrella values(40, 0, 'orange umbrella', 'unorderable', '1400', 'Crafting');
insert into acnh_umbrella values(41, 0, 'panda umbrella', 'orderable', '1570', 'Nook''s Cranny');
insert into acnh_umbrella values(42, 0, 'paper parasol', 'orderable', '870', 'Nook''s Cranny');
insert into acnh_umbrella values(43, 0, 'patterned vinyl umbrella', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(44, 0, 'peach umbrella', 'unorderable', '1400', 'Crafting');
insert into acnh_umbrella values(45, 0, 'pear umbrella', 'unorderable', '1400', 'Crafting');
insert into acnh_umbrella values(46, 0, 'petal parasol', 'orderable', '1590', 'Nook''s Cranny');
insert into acnh_umbrella values(47, 0, 'picnic umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(48, 0, 'pineapple umbrella', 'orderable', '1550', 'Nook''s Cranny');
insert into acnh_umbrella values(49, 0, 'pink shiny-bows parasol', 'orderable', '1620', 'Nook''s Cranny');
insert into acnh_umbrella values(50, 0, 'pink umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(51, 0, 'purple chic umbrella', 'orderable', '1620', 'Nook''s Cranny');
insert into acnh_umbrella values(52, 0, 'purple shiny-bows parasol', 'orderable', '1620', 'Nook''s Cranny');
insert into acnh_umbrella values(53, 0, 'rainbow umbrella', 'orderable', '840', 'Nook''s Cranny');
insert into acnh_umbrella values(54, 0, 'raindrop umbrella', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(55, 0, 'red chic umbrella', 'orderable', '1620', 'Nook''s Cranny');
insert into acnh_umbrella values(56, 0, 'red umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(57, 0, 'snowflake umbrella', 'orderable', '1550', 'Nook''s Cranny');
insert into acnh_umbrella values(58, 0, 'spider umbrella', 'orderable', '840', 'Nook''s Cranny');
insert into acnh_umbrella values(59, 0, 'strawberry umbrella', 'orderable', '1550', 'Nook''s Cranny');
insert into acnh_umbrella values(60, 0, 'striped umbrella', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(61, 0, 'sunny parasol', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(62, 0, 'tartan-check umbrella', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(63, 0, 'Toad parasol', 'orderable', '750', 'Nook''s Cranny');
insert into acnh_umbrella values(64, 0, 'two-tone umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(65, 0, 'vinyl umbrella', 'orderable', '770', 'Nook''s Cranny');
insert into acnh_umbrella values(66, 0, 'watermelon umbrella', 'orderable', '1550', 'Nook''s Cranny');
insert into acnh_umbrella values(67, 0, 'white shiny-bows parasol', 'orderable', '1620', 'Nook''s Cranny');
