drop table if exists acww_accessory;
create table acww_accessory ("Index" int primary key, Selected int, Name varchar(50));
insert into acww_accessory values(1, 0, 'White Cap');
insert into acww_accessory values(2, 0, 'Red Cap');
insert into acww_accessory values(3, 0, 'Yellow Cap');
insert into acww_accessory values(4, 0, 'Light Blue Cap');
insert into acww_accessory values(5, 0, 'Green Cap');
insert into acww_accessory values(6, 0, 'Star Cap');
insert into acww_accessory values(7, 0, '1-Up Cap');
insert into acww_accessory values(8, 0, 'Purple Cap');
insert into acww_accessory values(9, 0, 'Blue Knit Hat');
insert into acww_accessory values(10, 0, 'Green Knit Hat');
insert into acww_accessory values(11, 0, 'Orange Knit Hat');
insert into acww_accessory values(12, 0, 'Pink Knit Hat');
insert into acww_accessory values(13, 0, 'Purple Knit Hat');
insert into acww_accessory values(14, 0, 'Red Pom-Pom Hat');
insert into acww_accessory values(15, 0, 'Badge Hat');
insert into acww_accessory values(16, 0, 'Straw Hat');
insert into acww_accessory values(17, 0, 'Grandpa Hat');
insert into acww_accessory values(18, 0, 'Paperboy Cap');
insert into acww_accessory values(19, 0, 'Beret');
insert into acww_accessory values(20, 0, 'Dandy Hat');
insert into acww_accessory values(21, 0, 'Hunter''s Cap');
insert into acww_accessory values(22, 0, 'Detective Hat');
insert into acww_accessory values(23, 0, 'Top Hat');
insert into acww_accessory values(24, 0, 'Puffy Hat');
insert into acww_accessory values(25, 0, 'Bandana');
insert into acww_accessory values(26, 0, 'Swimming Cap');
insert into acww_accessory values(27, 0, 'Wizard''s Cap');
insert into acww_accessory values(28, 0, 'Big Bro''s Hat');
insert into acww_accessory values(29, 0, 'Li''l Bro''s Hat');
insert into acww_accessory values(30, 0, 'Bicycle Helmet');
insert into acww_accessory values(31, 0, 'Chef''s Hat');
insert into acww_accessory values(32, 0, 'Combat Helmet');
insert into acww_accessory values(33, 0, 'Scholar''s Hat');
insert into acww_accessory values(34, 0, 'Safety Helmet');
insert into acww_accessory values(35, 0, 'Police Cap');
insert into acww_accessory values(36, 0, 'Explorer''s Hat');
insert into acww_accessory values(37, 0, 'Captain''s Hat');
insert into acww_accessory values(38, 0, 'Sailor''s Hat');
insert into acww_accessory values(39, 0, 'Silk Hat');
insert into acww_accessory values(40, 0, 'Outback Hat');
insert into acww_accessory values(41, 0, 'Dutch Hat');
insert into acww_accessory values(42, 0, 'Sombrero');
insert into acww_accessory values(43, 0, 'Tyrolean Hat');
insert into acww_accessory values(44, 0, 'Viking Helmet');
insert into acww_accessory values(45, 0, 'Cavalier Hat');
insert into acww_accessory values(46, 0, 'Pirate''s Hat');
insert into acww_accessory values(47, 0, 'Jester''s Cap');
insert into acww_accessory values(48, 0, 'Witch''s Hat');
insert into acww_accessory values(49, 0, 'Red Ribbon');
insert into acww_accessory values(50, 0, 'Blue Ribbon');
insert into acww_accessory values(51, 0, 'Yellow Ribbon');
insert into acww_accessory values(52, 0, 'Heart Hairpin');
insert into acww_accessory values(53, 0, 'Star Hairpin');
insert into acww_accessory values(54, 0, 'Moon Hairpin');
insert into acww_accessory values(55, 0, 'Green Feather');
insert into acww_accessory values(56, 0, 'Blue Feather');
insert into acww_accessory values(57, 0, 'Yellow Feather');
insert into acww_accessory values(58, 0, 'Red Feather');
insert into acww_accessory values(59, 0, 'Purple Feather');
insert into acww_accessory values(60, 0, 'White Feather');
insert into acww_accessory values(61, 0, 'Rainbow Feather');
insert into acww_accessory values(62, 0, 'Halo');
insert into acww_accessory values(63, 0, 'Royal Crown');
insert into acww_accessory values(64, 0, 'Crown');
insert into acww_accessory values(65, 0, 'Pilot''s Cap');
insert into acww_accessory values(66, 0, 'Fireman''s Hat');
insert into acww_accessory values(67, 0, 'Baby''s Hat');
insert into acww_accessory values(68, 0, 'White Veil');
insert into acww_accessory values(69, 0, 'Turban');
insert into acww_accessory values(70, 0, 'Warbonnet');
insert into acww_accessory values(71, 0, 'Kaffiyeh');
insert into acww_accessory values(72, 0, 'Cow Bone');
insert into acww_accessory values(73, 0, 'Samurai Wig');
insert into acww_accessory values(74, 0, 'Geisha Wig');
insert into acww_accessory values(75, 0, 'Ninja Hood');
insert into acww_accessory values(76, 0, 'Powdered Wig');
insert into acww_accessory values(77, 0, 'Afro Wig');
insert into acww_accessory values(78, 0, 'Regent Wig');
insert into acww_accessory values(79, 0, 'Mohawk Wig');
insert into acww_accessory values(80, 0, 'Pigtail');
insert into acww_accessory values(81, 0, 'Bunny Hood');
insert into acww_accessory values(82, 0, 'Racing Helmet');
insert into acww_accessory values(83, 0, 'Motocross Helmet');
insert into acww_accessory values(84, 0, 'Football Helmet');
insert into acww_accessory values(85, 0, 'Knight''s Helmet');
insert into acww_accessory values(86, 0, 'Roman Helmet');
insert into acww_accessory values(87, 0, 'Diving Mask');
insert into acww_accessory values(88, 0, 'Space Helmet');
insert into acww_accessory values(89, 0, 'Ski Mask');
insert into acww_accessory values(90, 0, 'Wrestling Mask');
insert into acww_accessory values(91, 0, 'Dressing');
insert into acww_accessory values(92, 0, 'King Tut Wig');
insert into acww_accessory values(93, 0, 'Blue Frames');
insert into acww_accessory values(94, 0, 'Red Glasses');
insert into acww_accessory values(95, 0, 'Yellow Glasses');
insert into acww_accessory values(96, 0, 'Mint Glasses');
insert into acww_accessory values(97, 0, 'Purple Glasses');
insert into acww_accessory values(98, 0, 'Green Glasses');
insert into acww_accessory values(99, 0, 'Brown Glasses');
insert into acww_accessory values(100, 0, 'Pink Glasses');
insert into acww_accessory values(101, 0, 'Thick Glasses');
insert into acww_accessory values(102, 0, 'Silver Frames');
insert into acww_accessory values(103, 0, 'Rimmed Glasses');
insert into acww_accessory values(104, 0, 'Funky Glasses');
insert into acww_accessory values(105, 0, 'Pilot Shades');
insert into acww_accessory values(106, 0, 'Sporty Shades');
insert into acww_accessory values(107, 0, 'Huge Shades');
insert into acww_accessory values(108, 0, 'Triangle Shades');
insert into acww_accessory values(109, 0, 'Tiny Shades');
insert into acww_accessory values(110, 0, '3-D Glasses');
insert into acww_accessory values(111, 0, 'Masquerade Mask');
insert into acww_accessory values(112, 0, 'Hero''s Mask');
insert into acww_accessory values(113, 0, 'Goggles');
insert into acww_accessory values(114, 0, 'Snorkel Mask');
insert into acww_accessory values(115, 0, 'Eye Mask');
insert into acww_accessory values(116, 0, 'HMD');
insert into acww_accessory values(117, 0, 'Monocle');
insert into acww_accessory values(118, 0, 'Doctor''s Mirror');
insert into acww_accessory values(119, 0, 'Eye Patch');
insert into acww_accessory values(120, 0, 'Post-Op Patch');
insert into acww_accessory values(121, 0, 'Gas Mask');
insert into acww_accessory values(122, 0, 'Hockey Mask');
insert into acww_accessory values(123, 0, 'Red Nose');
insert into acww_accessory values(124, 0, 'Stache & Glasses');
insert into acww_accessory values(125, 0, 'Big Bro Mustache');
insert into acww_accessory values(126, 0, 'Curly Mustache');
insert into acww_accessory values(127, 0, 'Mini-Mustache');
insert into acww_accessory values(128, 0, 'King''s Beard');
insert into acww_accessory values(129, 0, 'Mask');
insert into acww_accessory values(130, 0, 'Pacifier');
