drop table if exists acww_carpet;
create table acww_carpet ("Index" int primary key, Selected int, Name varchar(50));
insert into acww_carpet values(1, 0, 'Exotic Rug');
insert into acww_carpet values(2, 0, 'Lovely Carpet');
insert into acww_carpet values(3, 0, 'Classic Carpet');
insert into acww_carpet values(4, 0, 'Ranch Flooring');
insert into acww_carpet values(5, 0, 'Cabana Flooring');
insert into acww_carpet values(6, 0, 'Blue Flooring');
insert into acww_carpet values(7, 0, 'Modern Tile');
insert into acww_carpet values(8, 0, 'Regal Carpet');
insert into acww_carpet values(9, 0, 'Green Rug');
insert into acww_carpet values(10, 0, 'Cabin Rug');
insert into acww_carpet values(11, 0, 'Kiddie Carpet');
insert into acww_carpet values(12, 0, 'Robo-Floor');
insert into acww_carpet values(13, 0, 'Snowman Carpet');
insert into acww_carpet values(14, 0, 'Forest Floor');
insert into acww_carpet values(15, 0, 'Western Desert');
insert into acww_carpet values(16, 0, 'Lunar Surface');
insert into acww_carpet values(17, 0, 'Closed Road');
insert into acww_carpet values(18, 0, 'Boxing Ring Mat');
insert into acww_carpet values(19, 0, 'Backyard Lawn');
insert into acww_carpet values(20, 0, 'Playroom Rug');
insert into acww_carpet values(21, 0, 'Ship Deck');
insert into acww_carpet values(22, 0, 'Lab Floor');
insert into acww_carpet values(23, 0, 'Pastel Dot Rug');
insert into acww_carpet values(24, 0, 'Checkered Tile');
insert into acww_carpet values(25, 0, 'Ceramic Tile');
insert into acww_carpet values(26, 0, 'Diner Tile');
insert into acww_carpet values(27, 0, 'Red Tile');
insert into acww_carpet values(28, 0, 'Mosaic Tile');
insert into acww_carpet values(29, 0, 'Plaza Tile');
insert into acww_carpet values(30, 0, 'Palace Tile');
insert into acww_carpet values(31, 0, 'Imperial Tile');
insert into acww_carpet values(32, 0, 'Kitchen Tile');
insert into acww_carpet values(33, 0, 'Stone Tile');
insert into acww_carpet values(34, 0, 'Charcoal Tile');
insert into acww_carpet values(35, 0, 'Tatami Floor');
insert into acww_carpet values(36, 0, 'Slate Flooring');
insert into acww_carpet values(37, 0, 'Concrete Floor');
insert into acww_carpet values(38, 0, 'Parquet Floor');
insert into acww_carpet values(39, 0, 'Music Room Floor');
insert into acww_carpet values(40, 0, 'Opulent Rug');
insert into acww_carpet values(41, 0, 'Plush Carpet');
insert into acww_carpet values(42, 0, 'Ornate Rug');
insert into acww_carpet values(43, 0, 'Fancy Carpet');
insert into acww_carpet values(44, 0, 'Exquisite Rug');
insert into acww_carpet values(45, 0, 'Persian Rug');
insert into acww_carpet values(46, 0, 'Tartan Rug');
insert into acww_carpet values(47, 0, 'Round Carpet');
insert into acww_carpet values(48, 0, 'Citrus Carpet');
insert into acww_carpet values(49, 0, 'Cowhide Rug');
insert into acww_carpet values(50, 0, 'Birch Flooring');
insert into acww_carpet values(51, 0, 'Old Flooring');
insert into acww_carpet values(52, 0, 'Bamboo Flooring');
insert into acww_carpet values(53, 0, 'Steel Flooring');
insert into acww_carpet values(54, 0, 'Shanty Mat');
insert into acww_carpet values(55, 0, 'Ancient Tile');
insert into acww_carpet values(56, 0, 'Fairy Tale Floor');
insert into acww_carpet values(57, 0, 'Illusion Floor');
insert into acww_carpet values(58, 0, 'Daisy Meadow');
insert into acww_carpet values(59, 0, 'Tropical Floor');
insert into acww_carpet values(60, 0, 'Saharah''s Desert');
insert into acww_carpet values(61, 0, 'Sandlot');
insert into acww_carpet values(62, 0, 'Cloud Flooring');
insert into acww_carpet values(63, 0, 'Common Floor');
