drop table if exists acww_fish;
create table acww_fish ("Index" int, Selected int, Name varchar(63), Price varchar(31), "Size" varchar(31), Shadow varchar(31), "From" varchar(31), Times varchar(255));
insert into acww_fish values(1, 0, 'Bitterling', '900', '3.9 in.', 'tiny', 'river', 'November through February, all day (best time is 4am to 9pm, December through February)');
insert into acww_fish values(2, 0, 'Pale Chub', '200', '5.9 in.', 'tiny', 'river', 'all year, 9am to 4pm (best time is March through June and August through November)');
insert into acww_fish values(3, 0, 'Crucian Carp', '120', '11.7 in.', 'small', 'river', 'all year, all day (best time is 9am to 4pm and 9pm to 4am, March through June and September through November)');
insert into acww_fish values(4, 0, 'Dace', '200', '13.7 in.', 'small', 'river', 'all year, 4pm to 9am (best time is 9pm to 4am, November through March)');
insert into acww_fish values(5, 0, 'Barbel Steed', '200', '19.5 in.', 'medium', 'river', 'all year, all day (best time is 9pm to 4am, October through March)');
insert into acww_fish values(6, 0, 'Carp', '300', '2.4 ft.', 'medium large', 'river', 'all year, all day (best time is 4pm to 9am, October and November)');
insert into acww_fish values(7, 0, 'Koi', '2,000', '2.4 ft.', 'medium large', 'river', 'all year, 4pm to 9am');
insert into acww_fish values(8, 0, 'Goldfish', '1,300', '5.9 in.', 'tiny', 'river', 'all year, all day');
insert into acww_fish values(9, 0, 'Popeyed Goldfish', '1,300', '5.9 in.', 'tiny', 'river', 'all year, 9am to 4pm');
insert into acww_fish values(10, 0, 'Killifish', '300', '1.6 in.', 'tiny', 'holding pond', 'April through August, all day');
insert into acww_fish values(11, 0, 'Crawfish', '200', '4.7 in.', 'tiny', 'holding pond', 'April through mid-September, all day (best time is 9am to 4pm, April and May)');
insert into acww_fish values(12, 0, 'Frog', '120', '4.7 in.', 'tiny', 'holding pond', 'May through August, all day');
insert into acww_fish values(13, 0, 'Freshwater Goby', '300', '5.9 in.', 'tiny', 'river', 'all year, 4pm to 9am');
insert into acww_fish values(14, 0, 'Loach', '300', '7.8 in.', 'tiny', 'river', 'March through May, all day (best time is 9am to 4pm, March and April)');
insert into acww_fish values(15, 0, 'Catfish', '800', '23.4 in.', 'medium', 'large pond', 'May through October, 4pm to 9am (best time is 9pm to 4am, June through September)');
insert into acww_fish values(16, 0, 'Eel', '2,000', '3.25 ft.', 'thin', 'river', 'June through mid-September, 4pm to 9am (best time is 9pm to 4am, June through August)');
insert into acww_fish values(17, 0, 'Giant Snakehead', '5,500', '2.6 ft.', 'large', 'large pond', 'June through August,9am to 4pm (best time is July and August)');
insert into acww_fish values(18, 0, 'Bluegill', '120', '9.8 in.', 'small', 'river', 'all year, 9am to 4pm (best time is March through November)');
insert into acww_fish values(19, 0, 'Yellow Perch', '240', '13.7 in.', 'small', 'river', 'October through March, all day (best time is November through February)');
insert into acww_fish values(20, 0, 'Black Bass', '300', '19.5 in.', 'medium', 'river', 'all year, all day (best time is 4am to 9am and 4pm to 9pm, May through November)');
insert into acww_fish values(21, 0, 'Pond Smelt', '300', '5.9 in.', 'tiny', 'large pond', 'December through February, all day (best time is 4am to 9pm)');
insert into acww_fish values(22, 0, 'Sweetfish', '900', '9.8 in.', 'small', 'river', 'July through mid-September, all day (best time is 4am to 9pm, July and August)');
insert into acww_fish values(23, 0, 'Cherry Salmon', '1,000', '13.7 in.', 'small', 'river', 'March through June, 4am to 9am and 4pm to 9pm (best time is March and April)');
insert into acww_fish values(24, 0, 'Char', '3,800', '19.5 in.', 'medium', 'under waterfall', 'March through June, 4am to 9am and 4pm to 9pm');
insert into acww_fish values(25, 0, 'Rainbow Trout', '800', '2.3 ft.', 'medium large', 'river', 'March through June, 4am to 9am and 4pm to 9pm (best time is March through May)');
insert into acww_fish values(26, 0, 'Stringfish', '15,000', '4.9 ft.', 'huge', 'river', 'December through February, 4pm to 9am');
insert into acww_fish values(27, 0, 'Salmon', '700', '2.9 ft.', 'large', 'river', 'September, all day');
insert into acww_fish values(28, 0, 'King Salmon', '1,800', '5.2 ft.', 'huge', 'river', 'September, all day (best time is the first half of September)');
insert into acww_fish values(29, 0, 'Guppy', '1,300', '1.6 in.', 'tiny', 'river', 'April through November, 9am to 4pm');
insert into acww_fish values(30, 0, 'Angelfish', '3,000', '4.7 in.', 'tiny', 'river', 'May through October, 4pm to 9am');
insert into acww_fish values(31, 0, 'Piranha', '2,500', '11.7 in.', 'small', 'river', 'June through mid-September, 9am to 4pm and 9pm to 4am');
insert into acww_fish values(32, 0, 'Arowana', '10,000', '2.3 ft.', 'medium large', 'river', 'June through mid-September, 4pm to 9am');
insert into acww_fish values(33, 0, 'Dorado', '15,000', '3.25 ft.', 'very large', 'river', 'June through September, 4am to 9pm');
insert into acww_fish values(34, 0, 'Gar', '6,000', '6.2 ft.', 'huge', 'large pond', 'June through September, 4pm to 9am');
insert into acww_fish values(35, 0, 'Arapaima', '10,000', '9.75 ft.', 'huge', 'river', 'July through September, 4pm to 9am');
insert into acww_fish values(36, 0, 'Sea Butterfly', '1,000', '1.2 in.', 'tiny', 'ocean', 'December through February, all day');
insert into acww_fish values(37, 0, 'Jellyfish', '100', '9.8 in.', 'small', 'ocean', 'the second half of August, all day');
insert into acww_fish values(38, 0, 'Seahorse', '1,100', '3.1 in.', 'tiny', 'ocean', 'April through November, all day (best time is 4am to 9pm, May through October)');
insert into acww_fish values(39, 0, 'Clownfish', '650', '5.9 in.', 'tiny', 'ocean', 'April through September, all day (best time is May through mid-August)');
insert into acww_fish values(40, 0, 'Zebra Turkeyfish', '400', '11.7 in.', 'small', 'ocean', 'April through November, all day (best time is May through October)');
insert into acww_fish values(41, 0, 'Puffer Fish', '240', '13.7 in.', 'small', 'ocean', 'July through September, all day (best time is August and September)');
insert into acww_fish values(42, 0, 'Horse Mackerel', '150', '15.6 in.', 'small', 'ocean', 'all year, all day');
insert into acww_fish values(43, 0, 'Barred Knifejaw', '5,000', '23.4 in.', 'medium', 'ocean', 'March through November,all day');
insert into acww_fish values(44, 0, 'Sea Bass', '160', '3.25 ft.', 'very large', 'ocean', 'all year, all day');
insert into acww_fish values(45, 0, 'Red Snapper', '3,000', '2.9 ft.', 'large', 'ocean', 'all year, all day (best time is March through October)');
insert into acww_fish values(46, 0, 'Dab', '300', '19.5 in.', 'medium', 'ocean', 'October through April, all day');
insert into acww_fish values(47, 0, 'Olive Flounder', '800', '2.6 ft.', 'large', 'ocean', 'all year, all day (best time is November through March)');
insert into acww_fish values(48, 0, 'Squid', '400', '13.7 in.', 'small', 'ocean', 'December through mid-August, all day');
insert into acww_fish values(49, 0, 'Octopus', '500', '23.4 in.', 'medium', 'ocean', 'March through July and mid-September through January, all day');
insert into acww_fish values(50, 0, 'Football Fish', '2,500', '23.4 in.', 'medium', 'ocean', 'November through March, 4pm to 9am (best time is December through February)');
insert into acww_fish values(51, 0, 'Tuna', '7,000', '7.5 ft.', 'huge', 'ocean', 'November through March, all day');
insert into acww_fish values(52, 0, 'Blue Marlin', '10,000', '7.2 ft.', 'huge', 'ocean', 'July through September, all day');
insert into acww_fish values(53, 0, 'Ocean Sunfish', '4,000', '9.75 ft.', 'huge with fin', 'ocean', 'June through September, 4am to 9pm');
insert into acww_fish values(54, 0, 'Hammerhead Shark', '8,000', '8.1 ft.', 'huge with fin', 'ocean', 'June through September, 4pm to 9am');
insert into acww_fish values(55, 0, 'Shark', '15,000', '17.6 ft.', 'huge with fin', 'ocean', 'June through September, 4pm to 9am');
insert into acww_fish values(56, 0, 'Coelacanth', '15,000', '4.9 ft.', 'huge', 'ocean during raor snow', 'all year, 4pm to 9am');
