drop table if exists acww_fossil;
create table acww_fossil ("Index" int primary key, Selected int, Name varchar(255));
insert into acww_fossil values(1, 0, 'Amber');
insert into acww_fossil values(2, 0, 'Ammonite');
insert into acww_fossil values(3, 0, 'Dino Droppings');
insert into acww_fossil values(4, 0, 'Dinosaur Egg');
insert into acww_fossil values(5, 0, 'Fern Fossil');
insert into acww_fossil values(6, 0, 'Dinosaur Track');
insert into acww_fossil values(7, 0, 'Archaeopteryx');
insert into acww_fossil values(8, 0, 'Peking Man');
insert into acww_fossil values(9, 0, 'Shark Tooth');
insert into acww_fossil values(10, 0, 'Trilobite');
insert into acww_fossil values(11, 0, 'T-rex Skull');
insert into acww_fossil values(12, 0, 'T-rex Torso');
insert into acww_fossil values(13, 0, 'T-rex Tail');
insert into acww_fossil values(14, 0, 'Tricera Skull');
insert into acww_fossil values(15, 0, 'Tricera Torso');
insert into acww_fossil values(16, 0, 'Tricera Tail');
insert into acww_fossil values(17, 0, 'Mammoth Skull');
insert into acww_fossil values(18, 0, 'Mammoth Torso');
insert into acww_fossil values(19, 0, 'Ankylo Skull');
insert into acww_fossil values(20, 0, 'Ankylo Torso');
insert into acww_fossil values(21, 0, 'Ankylo Tail');
insert into acww_fossil values(22, 0, 'Apato Skull');
insert into acww_fossil values(23, 0, 'Apato Torso');
insert into acww_fossil values(24, 0, 'Apato Tail');
insert into acww_fossil values(25, 0, 'Dimetrodon Skull');
insert into acww_fossil values(26, 0, 'Dimetrodon Torso');
insert into acww_fossil values(27, 0, 'Dimetrodon Tail');
insert into acww_fossil values(28, 0, 'Iguanodon Skull');
insert into acww_fossil values(29, 0, 'Iguanodon Torso');
insert into acww_fossil values(30, 0, 'Iguanodon Tail');
insert into acww_fossil values(31, 0, 'Sabertooth Skull');
insert into acww_fossil values(32, 0, 'Sabertooth Torso');
insert into acww_fossil values(33, 0, 'Pachy Skull');
insert into acww_fossil values(34, 0, 'Pachy Torso');
insert into acww_fossil values(35, 0, 'Pachy Tail');
insert into acww_fossil values(36, 0, 'Parasaur Skull');
insert into acww_fossil values(37, 0, 'Parasaur Torso');
insert into acww_fossil values(38, 0, 'Parasaur Tail');
insert into acww_fossil values(39, 0, 'Seismo Skull');
insert into acww_fossil values(40, 0, 'Seismo Chest');
insert into acww_fossil values(41, 0, 'Seismo Hip');
insert into acww_fossil values(42, 0, 'Seismo Tail');
insert into acww_fossil values(43, 0, 'Plesio Skull');
insert into acww_fossil values(44, 0, 'Plesio Neck');
insert into acww_fossil values(45, 0, 'Plesio Torso');
insert into acww_fossil values(46, 0, 'Stego Skull');
insert into acww_fossil values(47, 0, 'Stego Torso');
insert into acww_fossil values(48, 0, 'Stego Tail');
insert into acww_fossil values(49, 0, 'Ptera Skull');
insert into acww_fossil values(50, 0, 'Ptera Body');
insert into acww_fossil values(51, 0, 'Ptera Left Wing');
insert into acww_fossil values(52, 0, 'Ptera Right Wing');
