drop table if exists acww_furniture;
create table acww_furniture ("Index" int primary key, Selected int, Name varchar(50), "From" varchar(50));
insert into acww_furniture values(1, 0, 'Exotic Bed', 'Crazy Redd');
insert into acww_furniture values(2, 0, 'Exotic Bureau', 'Nook''s');
insert into acww_furniture values(3, 0, 'Exotic Wardrobe', 'Nook''s');
insert into acww_furniture values(4, 0, 'Exotic Bench', 'Nook''s');
insert into acww_furniture values(5, 0, 'Exotic Chair', 'Nook''s');
insert into acww_furniture values(6, 0, 'Exotic Table', 'Crazy Redd');
insert into acww_furniture values(7, 0, 'Exotic End Table', 'Nook''s');
insert into acww_furniture values(8, 0, 'Exotic Lamp', 'Nook''s');
insert into acww_furniture values(9, 0, 'Exotic Screen', 'Nook''s');
insert into acww_furniture values(10, 0, 'Exotic Chest', 'Spotlight');
insert into acww_furniture values(11, 0, 'Ranch Bed', 'Nook''s');
insert into acww_furniture values(12, 0, 'Ranch Dresser', 'Crazy Redd');
insert into acww_furniture values(13, 0, 'Ranch Wardrobe', 'Nook''s');
insert into acww_furniture values(14, 0, 'Ranch Couch', 'Nook''s');
insert into acww_furniture values(15, 0, 'Ranch Armchair', 'Nook''s');
insert into acww_furniture values(16, 0, 'Ranch Chair', 'Crazy Redd');
insert into acww_furniture values(17, 0, 'Ranch Table', 'Nook''s');
insert into acww_furniture values(18, 0, 'Ranch Tea Table', 'Nook''s');
insert into acww_furniture values(19, 0, 'Ranch Bookcase', 'Nook''s');
insert into acww_furniture values(20, 0, 'Ranch Hutch', 'Spotlight');
insert into acww_furniture values(21, 0, 'Classic Bed', 'Nook''s');
insert into acww_furniture values(22, 0, 'Classic Vanity', 'Crazy Redd');
insert into acww_furniture values(23, 0, 'Classic Wardrobe', 'Crazy Redd');
insert into acww_furniture values(24, 0, 'Classic Chair', 'Nook''s');
insert into acww_furniture values(25, 0, 'Classic Sofa', 'Nook''s');
insert into acww_furniture values(26, 0, 'Classic Table', 'Nook''s');
insert into acww_furniture values(27, 0, 'Classic Bookcase', 'Spotlight');
insert into acww_furniture values(28, 0, 'Classic Buffet', 'Nook''s');
insert into acww_furniture values(29, 0, 'Classic Desk', 'Nook''s');
insert into acww_furniture values(30, 0, 'Classic Clock', 'Nook''s');
insert into acww_furniture values(31, 0, 'Regal Bed', 'Crazy Redd');
insert into acww_furniture values(32, 0, 'Regal Dresser', 'Nook''s');
insert into acww_furniture values(33, 0, 'Regal Armoire', 'Nook''s');
insert into acww_furniture values(34, 0, 'Regal Chair', 'Crazy Redd');
insert into acww_furniture values(35, 0, 'Regal Sofa', 'Nook''s');
insert into acww_furniture values(36, 0, 'Regal Table', 'Nook''s');
insert into acww_furniture values(37, 0, 'Regal Lamp', 'Nook''s');
insert into acww_furniture values(38, 0, 'Regal Clock', 'Spotlight');
insert into acww_furniture values(39, 0, 'Regal Bookcase', 'Nook''s');
insert into acww_furniture values(40, 0, 'Regal Vanity', 'Nook''s');
insert into acww_furniture values(41, 0, 'Blue Bed', 'Crazy Redd');
insert into acww_furniture values(42, 0, 'Blue Bureau', 'Nook''s');
insert into acww_furniture values(43, 0, 'Blue Wardrobe', 'Nook''s');
insert into acww_furniture values(44, 0, 'Blue Chair', 'Nook''s');
insert into acww_furniture values(45, 0, 'Blue Bench', 'Nook''s');
insert into acww_furniture values(46, 0, 'Blue Table', 'Crazy Redd');
insert into acww_furniture values(47, 0, 'Blue Bookcase', 'Nook''s');
insert into acww_furniture values(48, 0, 'Blue Cabinet', 'Nook''s');
insert into acww_furniture values(49, 0, 'Blue Clock', 'Nook''s');
insert into acww_furniture values(50, 0, 'Blue Dresser', 'Spotlight');
insert into acww_furniture values(51, 0, 'Cabana Bed', 'Crazy Redd');
insert into acww_furniture values(52, 0, 'Cabana Dresser', 'Nook''s');
insert into acww_furniture values(53, 0, 'Cabana Wardrobe', 'Nook''s');
insert into acww_furniture values(54, 0, 'Cabana Chair', 'Crazy Redd');
insert into acww_furniture values(55, 0, 'Cabana Armchair', 'Spotlight');
insert into acww_furniture values(56, 0, 'Cabana Table', 'Nook''s');
insert into acww_furniture values(57, 0, 'Cabana Lamp', 'Nook''s');
insert into acww_furniture values(58, 0, 'Cabana Bookcase', 'Nook''s');
insert into acww_furniture values(59, 0, 'Cabana Vanity', 'Nook''s');
insert into acww_furniture values(60, 0, 'Cabana Screen', 'Nook''s');
insert into acww_furniture values(61, 0, 'Green Bed', 'Nook''s');
insert into acww_furniture values(62, 0, 'Green Dresser', 'Crazy Redd');
insert into acww_furniture values(63, 0, 'Green Wardrobe', 'Crazy Redd');
insert into acww_furniture values(64, 0, 'Green Chair', 'Nook''s');
insert into acww_furniture values(65, 0, 'Green Bench', 'Nook''s');
insert into acww_furniture values(66, 0, 'Green Table', 'Nook''s');
insert into acww_furniture values(67, 0, 'Green Desk', 'Nook''s');
insert into acww_furniture values(68, 0, 'Green Lamp', 'Nook''s');
insert into acww_furniture values(69, 0, 'Green Counter', 'Nook''s');
insert into acww_furniture values(70, 0, 'Green Pantry', 'Spotlight');
insert into acww_furniture values(71, 0, 'Cabin Bed', 'Nook''s');
insert into acww_furniture values(72, 0, 'Cabin Dresser', 'Crazy Redd');
insert into acww_furniture values(73, 0, 'Cabin Wardrobe', 'Nook''s');
insert into acww_furniture values(74, 0, 'Cabin Chair', 'Crazy Redd');
insert into acww_furniture values(75, 0, 'Cabin Armchair', 'Nook''s');
insert into acww_furniture values(76, 0, 'Cabin Couch', 'Nook''s');
insert into acww_furniture values(77, 0, 'Cabin Table', 'Nook''s');
insert into acww_furniture values(78, 0, 'Cabin Low Table', 'Nook''s');
insert into acww_furniture values(79, 0, 'Cabin Bookcase', 'Spotlight');
insert into acww_furniture values(80, 0, 'Cabin Clock', 'Nook''s');
insert into acww_furniture values(81, 0, 'Modern Bed', 'Nook''s');
insert into acww_furniture values(82, 0, 'Modern Dresser', 'Nook''s');
insert into acww_furniture values(83, 0, 'Modern Wardrobe', 'Crazy Redd');
insert into acww_furniture values(84, 0, 'Modern Chair', 'Nook''s');
insert into acww_furniture values(85, 0, 'Modern Sofa', 'Nook''s');
insert into acww_furniture values(86, 0, 'Modern End Table', 'Crazy Redd');
insert into acww_furniture values(87, 0, 'Modern Desk', 'Nook''s');
insert into acww_furniture values(88, 0, 'Modern Table', 'Nook''s');
insert into acww_furniture values(89, 0, 'Modern Cabinet', 'Spotlight');
insert into acww_furniture values(90, 0, 'Modern Lamp', 'Nook''s');
insert into acww_furniture values(91, 0, 'Kiddie Bed', 'Crazy Redd');
insert into acww_furniture values(92, 0, 'Kiddie Dresser', 'Nook''s');
insert into acww_furniture values(93, 0, 'Kiddie Wardrobe', 'Nook''s');
insert into acww_furniture values(94, 0, 'Kiddie Couch', 'Nook''s');
insert into acww_furniture values(95, 0, 'Kiddie Chair', 'Nook''s');
insert into acww_furniture values(96, 0, 'Kiddie Table', 'Nook''s');
insert into acww_furniture values(97, 0, 'Kiddie Bureau', 'Nook''s');
insert into acww_furniture values(98, 0, 'Kiddie Bookcase', 'Nook''s');
insert into acww_furniture values(99, 0, 'Kiddie Clock', 'Crazy Redd');
insert into acww_furniture values(100, 0, 'Kiddie Stereo', 'Spotlight');
insert into acww_furniture values(101, 0, 'Lovely Bed', 'Nook''s');
insert into acww_furniture values(102, 0, 'Lovely Dresser', 'Nook''s');
insert into acww_furniture values(103, 0, 'Lovely Armoire', 'Crazy Redd');
insert into acww_furniture values(104, 0, 'Lovely Chair', 'Nook''s');
insert into acww_furniture values(105, 0, 'Lovely Loveseat', 'Nook''s');
insert into acww_furniture values(106, 0, 'Lovely End Table', 'Crazy Redd');
insert into acww_furniture values(107, 0, 'Lovely Table', 'Nook''s');
insert into acww_furniture values(108, 0, 'Lovely Vanity', 'Nook''s');
insert into acww_furniture values(109, 0, 'Lovely Kitchen', 'Spotlight');
insert into acww_furniture values(110, 0, 'Lovely Lamp', 'Nook''s');
insert into acww_furniture values(111, 0, 'Robo-Bed', 'Nook''s');
insert into acww_furniture values(112, 0, 'Robo-Dresser', 'Nook''s');
insert into acww_furniture values(113, 0, 'Robo-Closet', 'Crazy Redd');
insert into acww_furniture values(114, 0, 'Robo-Sofa', 'Nook''s');
insert into acww_furniture values(115, 0, 'Robo-Chair', 'Nook''s');
insert into acww_furniture values(116, 0, 'Robo-Table', 'Nook''s');
insert into acww_furniture values(117, 0, 'Robo-Stereo', 'Spotlight');
insert into acww_furniture values(118, 0, 'Robo-TV', 'Nook''s');
insert into acww_furniture values(119, 0, 'Robo-Clock', 'Nook''s');
insert into acww_furniture values(120, 0, 'Robo-Lamp', 'Crazy Redd');
insert into acww_furniture values(121, 0, 'Snowman Bed', 'Unorderable');
insert into acww_furniture values(122, 0, 'Snowman Dresser', 'Unorderable');
insert into acww_furniture values(123, 0, 'Snowman Wardrobe', 'Unorderable');
insert into acww_furniture values(124, 0, 'Snowman Chair', 'Unorderable');
insert into acww_furniture values(125, 0, 'Snowman Sofa', 'Unorderable');
insert into acww_furniture values(126, 0, 'Snowman Table', 'Unorderable');
insert into acww_furniture values(127, 0, 'Snowman Fridge', 'Unorderable');
insert into acww_furniture values(128, 0, 'Snowman TV', 'Unorderable');
insert into acww_furniture values(129, 0, 'Snowman Clock', 'Unorderable');
insert into acww_furniture values(130, 0, 'Snowman Lamp', 'Unorderable');
insert into acww_furniture values(131, 0, 'Mushroom Bed', 'Unorderable');
insert into acww_furniture values(132, 0, 'Mushroom Dresser', 'Unorderable');
insert into acww_furniture values(133, 0, 'Mushroom Closet', 'Unorderable');
insert into acww_furniture values(134, 0, 'Mushroom Chair', 'Unorderable');
insert into acww_furniture values(135, 0, 'Mushroom Stool', 'Unorderable');
insert into acww_furniture values(136, 0, 'Mushroom Table', 'Unorderable');
insert into acww_furniture values(137, 0, 'Mushroom End Table', 'Unorderable');
insert into acww_furniture values(138, 0, 'Mushroom Lamp', 'Unorderable');
insert into acww_furniture values(139, 0, 'Mushroom Stand', 'Unorderable');
insert into acww_furniture values(140, 0, 'Mushroom TV', 'Unorderable');
insert into acww_furniture values(141, 0, 'Cow Skull', 'Nook''s');
insert into acww_furniture values(142, 0, 'Desert Cactus', 'Nook''s');
insert into acww_furniture values(143, 0, 'Western Fence', 'Nook''s');
insert into acww_furniture values(144, 0, 'Saddle Fence', 'Crazy Redd');
insert into acww_furniture values(145, 0, 'Storefront', 'Nook''s');
insert into acww_furniture values(146, 0, 'Covered Wagon', 'Spotlight');
insert into acww_furniture values(147, 0, 'Watering Trough', 'Nook''s');
insert into acww_furniture values(148, 0, 'Tumbleweed', 'Nook''s');
insert into acww_furniture values(149, 0, 'Well', 'Crazy Redd');
insert into acww_furniture values(150, 0, 'Wagon Wheel', 'Nook''s');
insert into acww_furniture values(151, 0, 'Asteroid', 'Nook''s');
insert into acww_furniture values(152, 0, 'Moon', 'Spotlight');
insert into acww_furniture values(153, 0, 'Lunar Lander', 'Nook''s');
insert into acww_furniture values(154, 0, 'Rocket', 'Crazy Redd');
insert into acww_furniture values(155, 0, 'Lunar Rover', 'Nook''s');
insert into acww_furniture values(156, 0, 'Satellite', 'Nook''s');
insert into acww_furniture values(157, 0, 'Space Shuttle', 'Crazy Redd');
insert into acww_furniture values(158, 0, 'Spaceman Sam', 'Nook''s');
insert into acww_furniture values(159, 0, 'Space Station', 'Nook''s');
insert into acww_furniture values(160, 0, 'Flying Saucer', 'Nook''s');
insert into acww_furniture values(161, 0, 'Detour Arrow', 'Nook''s');
insert into acww_furniture values(162, 0, 'Handcart', 'Nook''s');
insert into acww_furniture values(163, 0, 'Iron Frame', 'Nook''s');
insert into acww_furniture values(164, 0, 'Manhole Cover', 'Nook''s');
insert into acww_furniture values(165, 0, 'Orange Cone', 'Nook''s');
insert into acww_furniture values(166, 0, 'Traffic Cone', 'Nook''s');
insert into acww_furniture values(167, 0, 'Saw Horse', 'Crazy Redd');
insert into acww_furniture values(168, 0, 'Wet Roadway Sign', 'Nook''s');
insert into acww_furniture values(169, 0, 'Steam Roller', 'Crazy Redd');
insert into acww_furniture values(170, 0, 'Jackhammer', 'Nook''s');
insert into acww_furniture values(171, 0, 'Striped Cone', 'Nook''s');
insert into acww_furniture values(172, 0, 'Cement Mixer', 'Spotlight');
insert into acww_furniture values(173, 0, 'Brown Drum', 'Nook''s');
insert into acww_furniture values(174, 0, 'Green Drum', 'Nook''s');
insert into acww_furniture values(175, 0, 'Red Drum', 'Nook''s');
insert into acww_furniture values(176, 0, 'Haz-Mat Barrel', 'Nook''s');
insert into acww_furniture values(177, 0, 'Oil Drum', 'Nook''s');
insert into acww_furniture values(178, 0, 'Boxing Barricade', 'Nook''s');
insert into acww_furniture values(179, 0, 'Red Corner', 'Crazy Redd');
insert into acww_furniture values(180, 0, 'Blue Corner', 'Spotlight');
insert into acww_furniture values(181, 0, 'Neutral Corner', 'Nook''s');
insert into acww_furniture values(182, 0, 'Judge''s Bell', 'Crazy Redd');
insert into acww_furniture values(183, 0, 'Boxing Mat', 'Nook''s');
insert into acww_furniture values(184, 0, 'Ringside Table', 'Nook''s');
insert into acww_furniture values(185, 0, 'Weight Bench', 'Nook''s');
insert into acww_furniture values(186, 0, 'Sandbag', 'Nook''s');
insert into acww_furniture values(187, 0, 'Speed Bag', 'Nook''s');
insert into acww_furniture values(188, 0, 'Birdhouse', 'Nook''s');
insert into acww_furniture values(189, 0, 'Mr. Flamingo', 'Nook''s');
insert into acww_furniture values(190, 0, 'Mrs. Flamingo', 'Nook''s');
insert into acww_furniture values(191, 0, 'Garden Gnome', 'Spotlight');
insert into acww_furniture values(192, 0, 'Bug Zapper', 'Nook''s');
insert into acww_furniture values(193, 0, 'Hammock', 'Nook''s');
insert into acww_furniture values(194, 0, 'Bird Bath', 'Nook''s');
insert into acww_furniture values(195, 0, 'Picnic Table', 'Nook''s');
insert into acww_furniture values(196, 0, 'Bird Feeder', 'Nook''s');
insert into acww_furniture values(197, 0, 'Lawn Chair', 'Nook''s');
insert into acww_furniture values(198, 0, 'Lawn Mower', 'Crazy Redd');
insert into acww_furniture values(199, 0, 'Barbecue', 'Nook''s');
insert into acww_furniture values(200, 0, 'Backyard Pool', 'Crazy Redd');
insert into acww_furniture values(201, 0, 'Sprinkler', 'Nook''s');
insert into acww_furniture values(202, 0, 'Tiki Torch', 'Nook''s');
insert into acww_furniture values(203, 0, 'Elephant Slide', 'Nook''s');
insert into acww_furniture values(204, 0, 'Stroller', 'Nook''s');
insert into acww_furniture values(205, 0, 'Cradle', 'Nook''s');
insert into acww_furniture values(206, 0, 'Baby Bed', 'Crazy Redd');
insert into acww_furniture values(207, 0, 'Clackercart', 'Nook''s');
insert into acww_furniture values(208, 0, 'Merry-Go-Round', 'Crazy Redd');
insert into acww_furniture values(209, 0, 'Rocking Horse', 'Nook''s');
insert into acww_furniture values(210, 0, 'Train Set', 'Nook''s');
insert into acww_furniture values(211, 0, 'Wobbelina', 'Nook''s');
insert into acww_furniture values(212, 0, 'Dolly', 'Spotlight');
insert into acww_furniture values(213, 0, 'Lab Bench', 'Nook''s');
insert into acww_furniture values(214, 0, 'Lab Chair', 'Nook''s');
insert into acww_furniture values(215, 0, 'Medicine Chest', 'Crazy Redd');
insert into acww_furniture values(216, 0, 'Florence Flask', 'Nook''s');
insert into acww_furniture values(217, 0, 'Amazing Machine', 'Crazy Redd');
insert into acww_furniture values(218, 0, 'Unknown Machine', 'Spotlight');
insert into acww_furniture values(219, 0, 'Complex Machine', 'Nook''s');
insert into acww_furniture values(220, 0, 'Helm', 'Nook''s');
insert into acww_furniture values(221, 0, 'Barrel', 'Nook''s');
insert into acww_furniture values(222, 0, 'Keg', 'Nook''s');
insert into acww_furniture values(223, 0, 'Ship Cannon', 'Nook''s');
insert into acww_furniture values(224, 0, 'Anchor', 'Nook''s');
insert into acww_furniture values(225, 0, 'Ship Compass', 'Nook''s');
insert into acww_furniture values(226, 0, 'Black Pawn', 'Nook''s');
insert into acww_furniture values(227, 0, 'Black Bishop', 'Nook''s');
insert into acww_furniture values(228, 0, 'Black King', 'Spotlight');
insert into acww_furniture values(229, 0, 'Black Knight', 'Crazy Redd');
insert into acww_furniture values(230, 0, 'Black Queen', 'Spotlight');
insert into acww_furniture values(231, 0, 'Black Rook', 'Crazy Redd');
insert into acww_furniture values(232, 0, 'White Pawn', 'Nook''s');
insert into acww_furniture values(233, 0, 'White Bishop', 'Nook''s');
insert into acww_furniture values(234, 0, 'White King', 'Spotlight');
insert into acww_furniture values(235, 0, 'White Knight', 'Crazy Redd');
insert into acww_furniture values(236, 0, 'White Queen', 'Spotlight');
insert into acww_furniture values(237, 0, 'White Rook', 'Crazy Redd');
insert into acww_furniture values(238, 0, 'Hamster Cage', 'Spotlight');
insert into acww_furniture values(239, 0, 'Mop', 'Nook''s');
insert into acww_furniture values(240, 0, 'Skeleton', 'Spotlight');
insert into acww_furniture values(241, 0, 'Anatomical Model', 'Nook''s');
insert into acww_furniture values(242, 0, 'Clear Model', 'Crazy Redd');
insert into acww_furniture values(243, 0, 'Vision Tester', 'Nook''s');
insert into acww_furniture values(244, 0, 'Trunk Measure', 'Nook''s');
insert into acww_furniture values(245, 0, 'Stadiometer', 'Nook''s');
insert into acww_furniture values(246, 0, 'Scale', 'Nook''s');
insert into acww_furniture values(247, 0, 'Hospital Bed', 'Crazy Redd');
insert into acww_furniture values(248, 0, 'Writing Desk', 'Nook''s');
insert into acww_furniture values(249, 0, 'Writing Chair', 'Nook''s');
insert into acww_furniture values(250, 0, 'Globe', 'Nook''s');
insert into acww_furniture values(251, 0, 'Office Desk', 'Nook''s');
insert into acww_furniture values(252, 0, 'Office Chair', 'Nook''s');
insert into acww_furniture values(253, 0, 'Office Locker', 'Nook''s');
insert into acww_furniture values(254, 0, 'Coffee Maker', 'Nook''s');
insert into acww_furniture values(255, 0, 'Checkout Counter', 'Nook''s');
insert into acww_furniture values(256, 0, 'Cash Register', 'Nook''s');
insert into acww_furniture values(257, 0, 'Jukebox', 'Spotlight');
insert into acww_furniture values(258, 0, 'Siphon', 'Nook''s');
insert into acww_furniture values(259, 0, 'Giant Dharma', 'Nook''s');
insert into acww_furniture values(260, 0, 'Dharma', 'Nook''s');
insert into acww_furniture values(261, 0, 'Mini-Dharma', 'Nook''s');
insert into acww_furniture values(262, 0, 'Papa Bear', 'Nook''s');
insert into acww_furniture values(263, 0, 'Mama Bear', 'Nook''s');
insert into acww_furniture values(264, 0, 'Baby Bear', 'Nook''s');
insert into acww_furniture values(265, 0, 'Papa Panda', 'Nook''s');
insert into acww_furniture values(266, 0, 'Mama Panda', 'Crazy Redd');
insert into acww_furniture values(267, 0, 'Baby Panda', 'Spotlight');
insert into acww_furniture values(268, 0, 'Tall Cactus', 'Nook''s');
insert into acww_furniture values(269, 0, 'Cactus', 'Nook''s');
insert into acww_furniture values(270, 0, 'Round Cactus', 'Nook''s');
insert into acww_furniture values(271, 0, 'Blue Golf Bag', 'Nook''s');
insert into acww_furniture values(272, 0, 'White Golf Bag', 'Nook''s');
insert into acww_furniture values(273, 0, 'Green Golf Bag', 'Nook''s');
insert into acww_furniture values(274, 0, 'Red Armchair', 'Nook''s');
insert into acww_furniture values(275, 0, 'Red Sofa', 'Nook''s');
insert into acww_furniture values(276, 0, 'Bear Pole', 'Nook''s');
insert into acww_furniture values(277, 0, 'Eagle Pole', 'Nook''s');
insert into acww_furniture values(278, 0, 'Frog Woman Pole', 'Crazy Redd');
insert into acww_furniture values(279, 0, 'Raven Pole', 'Nook''s');
insert into acww_furniture values(280, 0, 'Blue Lava Lamp', 'Nook''s');
insert into acww_furniture values(281, 0, 'Purple Lava Lamp', 'Nook''s');
insert into acww_furniture values(282, 0, 'Green Lava Lamp', 'Nook''s');
insert into acww_furniture values(283, 0, 'Samurai Suit', 'Spotlight');
insert into acww_furniture values(284, 0, 'Black Katana', 'Crazy Redd');
insert into acww_furniture values(285, 0, 'White Katana', 'Crazy Redd');
insert into acww_furniture values(286, 0, 'Ninja Sword', 'Spotlight');
insert into acww_furniture values(287, 0, 'Sword', 'Nook''s');
insert into acww_furniture values(288, 0, 'Bow', 'Nook''s');
insert into acww_furniture values(289, 0, 'Tea Table', 'Nook''s');
insert into acww_furniture values(290, 0, 'Hearth', 'Nook''s');
insert into acww_furniture values(291, 0, 'Deer Scare', 'Crazy Redd');
insert into acww_furniture values(292, 0, 'Tall Lantern', 'Nook''s');
insert into acww_furniture values(293, 0, 'Master Sword', 'Spotlight');
insert into acww_furniture values(294, 0, 'Arwing', 'Spotlight');
insert into acww_furniture values(295, 0, 'Triforce', 'Crazy Redd');
insert into acww_furniture values(296, 0, 'Metroid', 'Unorderable');
insert into acww_furniture values(297, 0, 'Tea Vase', 'Nook''s');
insert into acww_furniture values(298, 0, 'Red Vase', 'Nook''s');
insert into acww_furniture values(299, 0, 'Blue Vase', 'Nook''s');
insert into acww_furniture values(300, 0, 'Lucky Cat', 'Nook''s');
insert into acww_furniture values(301, 0, 'Lefty Lucky Cat', 'Crazy Redd');
insert into acww_furniture values(302, 0, 'Lucky Black Cat', 'Crazy Redd');
insert into acww_furniture values(303, 0, 'Lucky Gold Cat', 'Spotlight');
insert into acww_furniture values(304, 0, 'Grapefruit Table', 'Nook''s');
insert into acww_furniture values(305, 0, 'Lemon Table', 'Nook''s');
insert into acww_furniture values(306, 0, 'Orange Chair', 'Nook''s');
insert into acww_furniture values(307, 0, 'Lime Chair', 'Nook''s');
insert into acww_furniture values(308, 0, 'Pear Wardrobe', 'Nook''s');
insert into acww_furniture values(309, 0, 'Pear Dresser', 'Nook''s');
insert into acww_furniture values(310, 0, 'Watermelon Chair', 'Nook''s');
insert into acww_furniture values(311, 0, 'Melon Chair', 'Nook''s');
insert into acww_furniture values(312, 0, 'Watermelon Table', 'Nook''s');
insert into acww_furniture values(313, 0, 'Apple TV', 'Nook''s');
insert into acww_furniture values(314, 0, 'Apple Clock', 'Nook''s');
insert into acww_furniture values(315, 0, 'Lily-Pad Table', 'Nook''s');
insert into acww_furniture values(316, 0, 'Froggy Chair', 'Nook''s');
insert into acww_furniture values(317, 0, 'Pine Chair', 'Nook''s');
insert into acww_furniture values(318, 0, 'Pine Table', 'Nook''s');
insert into acww_furniture values(319, 0, 'Tulip Chair', 'Nook''s');
insert into acww_furniture values(320, 0, 'Tulip Table', 'Nook''s');
insert into acww_furniture values(321, 0, 'Iris Chair', 'Nook''s');
insert into acww_furniture values(322, 0, 'Iris Table', 'Nook''s');
insert into acww_furniture values(323, 0, 'Daffodil Chair', 'Nook''s');
insert into acww_furniture values(324, 0, 'Daffodil Table', 'Nook''s');
insert into acww_furniture values(325, 0, 'Conga Drum', 'Nook''s');
insert into acww_furniture values(326, 0, 'Djimbe Drum', 'Nook''s');
insert into acww_furniture values(327, 0, 'Timpano Drum', 'Crazy Redd');
insert into acww_furniture values(328, 0, 'Violin', 'Nook''s');
insert into acww_furniture values(329, 0, 'Cello', 'Nook''s');
insert into acww_furniture values(330, 0, 'Bass', 'Nook''s');
insert into acww_furniture values(331, 0, 'Folk Guitar', 'Nook''s');
insert into acww_furniture values(332, 0, 'Country Guitar', 'Nook''s');
insert into acww_furniture values(333, 0, 'Rock Guitar', 'Nook''s');
insert into acww_furniture values(334, 0, 'Metal Guitar', 'Nook''s');
insert into acww_furniture values(335, 0, 'Ukulele', 'Nook''s');
insert into acww_furniture values(336, 0, 'Ebony Piano', 'Nook''s');
insert into acww_furniture values(337, 0, 'Ivory Piano', 'Spotlight');
insert into acww_furniture values(338, 0, 'Japanese Drum', 'Nook''s');
insert into acww_furniture values(339, 0, 'Vibraphone', 'Nook''s');
insert into acww_furniture values(340, 0, 'Biwa Lute', 'Nook''s');
insert into acww_furniture values(341, 0, 'Harp', 'Nook''s');
insert into acww_furniture values(342, 0, 'Metronome', 'Nook''s');
insert into acww_furniture values(343, 0, 'Trash Can', 'Nook''s');
insert into acww_furniture values(344, 0, 'Garbage Pail', 'Nook''s');
insert into acww_furniture values(345, 0, 'Garbage Can', 'Nook''s');
insert into acww_furniture values(346, 0, 'Trash Bin', 'Nook''s');
insert into acww_furniture values(347, 0, 'Pantheon Post', 'Crazy Redd');
insert into acww_furniture values(348, 0, 'Ionian Post', 'Nook''s');
insert into acww_furniture values(349, 0, 'Corinthian Post', 'Nook''s');
insert into acww_furniture values(350, 0, 'Broken Post', 'Nook''s');
insert into acww_furniture values(351, 0, 'Pyramid', 'Nook''s');
insert into acww_furniture values(352, 0, 'Sphinx', 'Nook''s');
insert into acww_furniture values(353, 0, 'Mummy''s Casket', 'Spotlight');
insert into acww_furniture values(354, 0, 'Spaceman', 'Crazy Redd');
insert into acww_furniture values(355, 0, 'Tennis Table', 'Nook''s');
insert into acww_furniture values(356, 0, 'Bowling Pins', 'Nook''s');
insert into acww_furniture values(357, 0, 'Basketball Hoop', 'Crazy Redd');
insert into acww_furniture values(358, 0, 'Ball Return', 'Nook''s');
insert into acww_furniture values(359, 0, 'Billiard Table', 'Nook''s');
insert into acww_furniture values(360, 0, 'Mahjong Table', 'Nook''s');
insert into acww_furniture values(361, 0, 'Dart Board', 'Nook''s');
insert into acww_furniture values(362, 0, 'Pinball Machine', 'Nook''s');
insert into acww_furniture values(363, 0, 'Arcade Machine', 'Nook''s');
insert into acww_furniture values(364, 0, 'Tabletop Game', 'Crazy Redd');
insert into acww_furniture values(365, 0, 'Stool', 'Nook''s');
insert into acww_furniture values(366, 0, 'Moai Statue', 'Unorderable');
insert into acww_furniture values(367, 0, 'Tribal Mask', 'Unorderable');
insert into acww_furniture values(368, 0, 'Arc de Triomphe', 'Unorderable');
insert into acww_furniture values(369, 0, 'Merlion', 'Unorderable');
insert into acww_furniture values(370, 0, 'Pagoda', 'Unorderable');
insert into acww_furniture values(371, 0, 'Plate Armor', 'Unorderable');
insert into acww_furniture values(372, 0, 'Mermaid Statue', 'Unorderable');
insert into acww_furniture values(373, 0, 'Mouth of Truth', 'Unorderable');
insert into acww_furniture values(374, 0, 'Manekin Pis', 'Unorderable');
insert into acww_furniture values(375, 0, 'Tower of Pisa', 'Unorderable');
insert into acww_furniture values(376, 0, 'Compass', 'Unorderable');
insert into acww_furniture values(377, 0, 'Matryoshka', 'Unorderable');
insert into acww_furniture values(378, 0, 'Backpack', 'Nook''s');
insert into acww_furniture values(379, 0, 'Mountain Bike', 'Nook''s');
insert into acww_furniture values(380, 0, 'Propane Stove', 'Nook''s');
insert into acww_furniture values(381, 0, 'Cooler', 'Nook''s');
insert into acww_furniture values(382, 0, 'Kayak', 'Nook''s');
insert into acww_furniture values(383, 0, 'Lantern', 'Nook''s');
insert into acww_furniture values(384, 0, 'Sleeping Bag', 'Spotlight');
insert into acww_furniture values(385, 0, 'Campfire', 'Nook''s');
insert into acww_furniture values(386, 0, 'Bonfire', 'Nook''s');
insert into acww_furniture values(387, 0, 'Ponderosa Bonsai', 'Nook''s');
insert into acww_furniture values(388, 0, 'Pine Bonsai', 'Nook''s');
insert into acww_furniture values(389, 0, 'Mugho Bonsai', 'Nook''s');
insert into acww_furniture values(390, 0, 'Plum Bonsai', 'Spotlight');
insert into acww_furniture values(391, 0, 'Holly Bonsai', 'Nook''s');
insert into acww_furniture values(392, 0, 'Azalea Bonsai', 'Nook''s');
insert into acww_furniture values(393, 0, 'Maple Bonsai', 'Nook''s');
insert into acww_furniture values(394, 0, 'Hawthorn Bonsai', 'Nook''s');
insert into acww_furniture values(395, 0, 'Quince Bonsai', 'Nook''s');
insert into acww_furniture values(396, 0, 'Jasmine Bonsai', 'Nook''s');
insert into acww_furniture values(397, 0, 'Pothos', 'Crazy Redd');
insert into acww_furniture values(398, 0, 'Coconut Palm', 'Nook''s');
insert into acww_furniture values(399, 0, 'Pachira', 'Nook''s');
insert into acww_furniture values(400, 0, 'Caladium', 'Nook''s');
insert into acww_furniture values(401, 0, 'Croton', 'Nook''s');
insert into acww_furniture values(402, 0, 'Dracaena', 'Spotlight');
insert into acww_furniture values(403, 0, 'Lady Palm', 'Nook''s');
insert into acww_furniture values(404, 0, 'Aloe', 'Nook''s');
insert into acww_furniture values(405, 0, 'Rubber Tree', 'Nook''s');
insert into acww_furniture values(406, 0, 'Snake Plant', 'Crazy Redd');
insert into acww_furniture values(407, 0, 'Fan Palm', 'Nook''s');
insert into acww_furniture values(408, 0, 'Corn Plant', 'Nook''s');
insert into acww_furniture values(409, 0, 'Bromeliaceae', 'Nook''s');
insert into acww_furniture values(410, 0, 'Weeping Fig', 'Nook''s');
insert into acww_furniture values(411, 0, 'TV with a VCR', 'Nook''s');
insert into acww_furniture values(412, 0, 'Wide-Screen TV', 'Crazy Redd');
insert into acww_furniture values(413, 0, 'Retro TV', 'Nook''s');
insert into acww_furniture values(414, 0, 'Kitchen Sink', 'Nook''s');
insert into acww_furniture values(415, 0, 'Kitchen Corner', 'Nook''s');
insert into acww_furniture values(416, 0, 'Deluxe Range', 'Nook''s');
insert into acww_furniture values(417, 0, 'Range', 'Nook''s');
insert into acww_furniture values(418, 0, 'Stove', 'Nook''s');
insert into acww_furniture values(419, 0, 'Tea Set', 'Nook''s');
insert into acww_furniture values(420, 0, 'Refrigerator', 'Nook''s');
insert into acww_furniture values(421, 0, 'Retro Fridge', 'Nook''s');
insert into acww_furniture values(422, 0, 'Microwave', 'Nook''s');
insert into acww_furniture values(423, 0, 'Toaster', 'Nook''s');
insert into acww_furniture values(424, 0, 'Sink', 'Nook''s');
insert into acww_furniture values(425, 0, 'Mixer', 'Nook''s');
insert into acww_furniture values(426, 0, 'Clothesline Pole', 'Nook''s');
insert into acww_furniture values(427, 0, 'Doghouse', 'Nook''s');
insert into acww_furniture values(428, 0, 'Beach Chair', 'Nook''s');
insert into acww_furniture values(429, 0, 'Wave Breaker', 'Nook''s');
insert into acww_furniture values(430, 0, 'Surfboard', 'Nook''s');
insert into acww_furniture values(431, 0, 'Diver Dan', 'Nook''s');
insert into acww_furniture values(432, 0, 'Beach Table', 'Nook''s');
insert into acww_furniture values(433, 0, 'Treasure Chest', 'Spotlight');
insert into acww_furniture values(434, 0, 'Life Ring', 'Nook''s');
insert into acww_furniture values(435, 0, 'Snowboard', 'Nook''s');
insert into acww_furniture values(436, 0, 'Sleigh', 'Nook''s');
insert into acww_furniture values(437, 0, 'Snowman', 'Unorderable');
insert into acww_furniture values(438, 0, 'Sunflower', 'Nook''s');
insert into acww_furniture values(439, 0, 'Daffodil', 'Nook''s');
insert into acww_furniture values(440, 0, 'Gerbera', 'Nook''s');
insert into acww_furniture values(441, 0, 'Toilet', 'Nook''s');
insert into acww_furniture values(442, 0, 'Super Toilet', 'Crazy Redd');
insert into acww_furniture values(443, 0, 'Men''s Toilet', 'Nook''s');
insert into acww_furniture values(444, 0, 'Pink Box', 'Nook''s');
insert into acww_furniture values(445, 0, 'Blue Box', 'Nook''s');
insert into acww_furniture values(446, 0, 'Beige Box', 'Nook''s');
insert into acww_furniture values(447, 0, 'Safe', 'Crazy Redd');
insert into acww_furniture values(448, 0, 'Piggy Bank', 'Unorderable');
insert into acww_furniture values(449, 0, 'Deluxe Washer', 'Spotlight');
insert into acww_furniture values(450, 0, 'Automatic Washer', 'Nook''s');
insert into acww_furniture values(451, 0, 'Washer/Dryer', 'Nook''s');
insert into acww_furniture values(452, 0, 'Potbelly Stove', 'Nook''s');
insert into acww_furniture values(453, 0, 'Space Heater', 'Nook''s');
insert into acww_furniture values(454, 0, 'Fireplace', 'Nook''s');
insert into acww_furniture values(455, 0, 'Radiator', 'Nook''s');
insert into acww_furniture values(456, 0, 'CD Player', 'Nook''s');
insert into acww_furniture values(457, 0, 'Gold Stereo', 'Nook''s');
insert into acww_furniture values(458, 0, 'Hi-Fi Stereo', 'Spotlight');
insert into acww_furniture values(459, 0, 'Turntable', 'Crazy Redd');
insert into acww_furniture values(460, 0, 'Dice Stereo', 'Crazy Redd');
insert into acww_furniture values(461, 0, 'White Boom Box', 'Nook''s');
insert into acww_furniture values(462, 0, 'Red Boom Box', 'Nook''s');
insert into acww_furniture values(463, 0, 'Phonograph', 'Nook''s');
insert into acww_furniture values(464, 0, 'Reel-to-Reel', 'Nook''s');
insert into acww_furniture values(465, 0, 'Retro Stereo', 'Nook''s');
insert into acww_furniture values(466, 0, 'High-End Stereo', 'Crazy Redd');
insert into acww_furniture values(467, 0, 'Tape Deck', 'Nook''s');
insert into acww_furniture values(468, 0, 'Red Clock', 'Nook''s');
insert into acww_furniture values(469, 0, 'Kitschy Clock', 'Nook''s');
insert into acww_furniture values(470, 0, 'Antique Clock', 'Nook''s');
insert into acww_furniture values(471, 0, 'Cube Clock', 'Nook''s');
insert into acww_furniture values(472, 0, 'Odd Clock', 'Nook''s');
insert into acww_furniture values(473, 0, 'Glow Clock', 'Nook''s');
insert into acww_furniture values(474, 0, 'Owl Clock', 'Nook''s');
insert into acww_furniture values(475, 0, 'Alarm Clock', 'Nook''s');
insert into acww_furniture values(476, 0, 'Jade Econo-Chair', 'Nook''s');
insert into acww_furniture values(477, 0, 'Ruby Econo-Chair', 'Nook''s');
insert into acww_furniture values(478, 0, 'Gold Econo-Chair', 'Nook''s');
insert into acww_furniture values(479, 0, 'Rocking Chair', 'Nook''s');
insert into acww_furniture values(480, 0, 'Gas Pump', 'Nook''s');
insert into acww_furniture values(481, 0, 'Extinguisher', 'Nook''s');
insert into acww_furniture values(482, 0, 'Fire Hydrant', 'Nook''s');
insert into acww_furniture values(483, 0, 'Raccoon Figurine', 'Crazy Redd');
insert into acww_furniture values(484, 0, 'Barber''s Pole', 'Nook''s');
insert into acww_furniture values(485, 0, 'Candy Machine', 'Nook''s');
insert into acww_furniture values(486, 0, 'Big Festive Tree', 'Nook''s');
insert into acww_furniture values(487, 0, 'Festive Tree', 'Nook''s');
insert into acww_furniture values(488, 0, 'Scarecrow', 'Nook''s');
insert into acww_furniture values(489, 0, 'Birdcage', 'Nook''s');
insert into acww_furniture values(490, 0, 'Chocolates', 'Unorderable');
insert into acww_furniture values(491, 0, 'Nintendo Bench', 'Nook''s');
insert into acww_furniture values(492, 0, 'Outdoor Bath', 'Nook''s');
insert into acww_furniture values(493, 0, 'Screen', 'Nook''s');
insert into acww_furniture values(494, 0, 'Computer', 'Nook''s');
insert into acww_furniture values(495, 0, 'Pineapple Bed', 'Nook''s');
insert into acww_furniture values(496, 0, 'Glass-Top Table', 'Nook''s');
insert into acww_furniture values(497, 0, 'Cream Sofa', 'Nook''s');
insert into acww_furniture values(498, 0, 'Storage Case', 'Nook''s');
insert into acww_furniture values(499, 0, 'Clothes Closet', 'Nook''s');
insert into acww_furniture values(500, 0, 'Claw-foot Tub', 'Nook''s');
insert into acww_furniture values(501, 0, 'Shower', 'Nook''s');
insert into acww_furniture values(502, 0, 'Box of Tissues', 'Unorderable');
insert into acww_furniture values(503, 0, 'Massage Chair', 'Nook''s');
insert into acww_furniture values(504, 0, 'Vacuum Cleaner', 'Nook''s');
insert into acww_furniture values(505, 0, 'Bottled Ship', 'Nook''s');
insert into acww_furniture values(506, 0, 'Water Bird', 'Nook''s');
insert into acww_furniture values(507, 0, 'Executive Toy', 'Nook''s');
insert into acww_furniture values(508, 0, 'Telescope', 'Nook''s');
insert into acww_furniture values(509, 0, 'Mochi Pestle', 'Nook''s');
insert into acww_furniture values(510, 0, 'Lovely Phone', 'Nook''s');
insert into acww_furniture values(511, 0, 'Sewing Machine', 'Nook''s');
insert into acww_furniture values(512, 0, 'Cardboard Box', 'Nook''s');
insert into acww_furniture values(513, 0, 'Wooden Box', 'Nook''s');
insert into acww_furniture values(514, 0, 'Miniature Car', 'Nook''s');
insert into acww_furniture values(515, 0, 'Fan', 'Nook''s');
insert into acww_furniture values(516, 0, 'Birthday Cake', 'Unorderable');
insert into acww_furniture values(517, 0, 'Jack-in-the-Box', 'Nook''s');
insert into acww_furniture values(518, 0, 'Throne*', 'Spotlight');
insert into acww_furniture values(519, 0, 'Table Lamp', 'Nook''s');
insert into acww_furniture values(520, 0, 'Desk Light', 'Nook''s');
insert into acww_furniture values(521, 0, 'Candle', 'Nook''s');
insert into acww_furniture values(522, 0, 'Mini-Lamp', 'Nook''s');
insert into acww_furniture values(523, 0, 'Festive Flag', 'Nook''s');
insert into acww_furniture values(524, 0, 'Festive Candle', 'Nook''s');
insert into acww_furniture values(525, 0, 'Music Box', 'Unorderable');
insert into acww_furniture values(526, 0, 'Portrait', 'Unorderable');
insert into acww_furniture values(527, 0, 'One-Story Model', 'Unorderable');
insert into acww_furniture values(528, 0, 'Two-Story Model', 'Unorderable');
insert into acww_furniture values(529, 0, 'Mansion Model', 'Unorderable');
insert into acww_furniture values(530, 0, 'Nook''s Cranny', 'Unorderable');
insert into acww_furniture values(531, 0, 'Nook ''n'' Go', 'Unorderable');
insert into acww_furniture values(532, 0, 'Nookway', 'Unorderable');
insert into acww_furniture values(533, 0, 'Nookington''s', 'Unorderable');
insert into acww_furniture values(534, 0, 'Museum Model', 'Unorderable');
insert into acww_furniture values(535, 0, 'Town Hall Model', 'Unorderable');
insert into acww_furniture values(536, 0, 'Fish Trophy', 'Unorderable');
insert into acww_furniture values(537, 0, 'Bug Trophy', 'Unorderable');
insert into acww_furniture values(538, 0, 'Flower Trophy', 'Unorderable');
insert into acww_furniture values(539, 0, 'Basic Red Bed', 'Nook''s');
insert into acww_furniture values(540, 0, 'Basic Blue Bed', 'Nook''s');
insert into acww_furniture values(541, 0, 'Basic Yellow Bed', 'Nook''s');
insert into acww_furniture values(542, 0, 'Basic Green Bed', 'Nook''s');
insert into acww_furniture values(543, 0, 'Dainty Painting', 'Crazy Redd');
insert into acww_furniture values(544, 0, 'Solemn Painting', 'Crazy Redd');
insert into acww_furniture values(545, 0, 'Quaint Painting', 'Crazy Redd');
insert into acww_furniture values(546, 0, 'Basic Painting', 'Crazy Redd');
insert into acww_furniture values(547, 0, 'Famous Painting', 'Spotlight');
insert into acww_furniture values(548, 0, 'Perfect Painting', 'Crazy Redd');
insert into acww_furniture values(549, 0, 'Amazing Painting', 'Crazy Redd');
insert into acww_furniture values(550, 0, 'Nice Painting', 'Crazy Redd');
insert into acww_furniture values(551, 0, 'Moving Painting', 'Crazy Redd');
insert into acww_furniture values(552, 0, 'Common Painting', 'Crazy Redd');
insert into acww_furniture values(553, 0, 'Flowery Painting', 'Crazy Redd');
insert into acww_furniture values(554, 0, 'Warm Painting', 'Crazy Redd');
insert into acww_furniture values(555, 0, 'Rare Painting', 'Crazy Redd');
insert into acww_furniture values(556, 0, 'Fine Painting', 'Spotlight');
insert into acww_furniture values(557, 0, 'Scary Painting', 'Crazy Redd');
insert into acww_furniture values(558, 0, 'Lovely Painting', 'Crazy Redd');
insert into acww_furniture values(559, 0, 'Strange Painting', 'Crazy Redd');
insert into acww_furniture values(560, 0, 'Worthy Painting', 'Crazy Redd');
insert into acww_furniture values(561, 0, 'Calm Painting', 'Crazy Redd');
insert into acww_furniture values(562, 0, 'Opulent Painting', 'Crazy Redd')