drop table if exists acww_insect;
create table acww_insect ("Index" int primary key, Selected int, Name varchar(50), Absent varchar(50), Size varchar(5), "From" varchar(50), Times varchar(200));
insert into acww_insect values(1, 0, 'Common Butterfly', 'When Raining', '50 mm', 'near flowers', 'March through June, 4am to 7pm (best time is 8am to 5pm); July through August, 8am to 5pm; September, 8am to 4pm');
insert into acww_insect values(2, 0, 'Yellow Butterfly', 'When Raining', '50 mm', 'near flowers', 'March through June, 4am to 7pm (best time is 8am to 5pm); July through August, 8am to 5pm; September, 8am to 4pm');
insert into acww_insect values(3, 0, 'Tiger Butterfly', 'When Raining', '90 mm', 'near Red and Pink flowers', 'March through June, 4am to 7pm (best time is 8am to 5pm); July through August, 8am to 5pm; September, 8am to 4pm');
insert into acww_insect values(4, 0, 'Peacock Butterfly', 'When Raining', '105 mm', 'near Blue, purple and Black flowers', 'March through June, 4am to 7pm (best time is 8am to 5pm, May through June); July through August, 8am to 5pm; September, 8am to 4pm');
insert into acww_insect values(5, 0, 'Monarch Butterfly', 'When Raining', '85 mm', 'near flowers', 'September through October, 4am to 5pm; November, 8am to 5pm (best time is 8am to 5pm, October through November)');
insert into acww_insect values(6, 0, 'Emperor Butterfly', 'When Raining', '115 mm', 'near flowers', 'June through September, 8am to 5pm');
insert into acww_insect values(7, 0, 'Agrias Butterfly', 'When Raining', '42 mm', 'near flowers', 'June through September, 8am to 5pm');
insert into acww_insect values(8, 0, 'Birdwing Butterfly', 'When Raining', '260 mm', 'near flowers', 'June through September, 8am to 5pm');
insert into acww_insect values(9, 0, 'Moth', 'When Raining', '60 mm', 'near outdoor lights', 'May through September, 7pm to 4am (best time is 11pm to 4am, June through August)');
insert into acww_insect values(10, 0, 'Oak Silk Moth', 'Never', '280 mm', 'on trees', 'June through September, 7pm to 4am');
insert into acww_insect values(11, 0, 'Honeybee', 'When Gate is Open or Raining', '13 mm', 'near flowers', 'March through August, 8am to 5pm (best time is March through June)');
insert into acww_insect values(12, 0, 'Bee', 'When Gate is Open', '38 mm', 'in trees', 'all year, all day');
insert into acww_insect values(13, 0, 'Long Locust', 'When Raining', '73 mm', 'on ground', 'August through November, 8am to 7pm (best time is September through November)');
insert into acww_insect values(14, 0, 'Migratory Locust', 'Never', '58 mm', 'on ground', 'September through November, 8am to 7pm (best time is 8am to 4pm)');
insert into acww_insect values(15, 0, 'Mantis', 'When Raining', '82 mm', 'on flowers', 'August through November, 8am to 5pm (best time is 8am to 4pm, September through November)');
insert into acww_insect values(16, 0, 'Orchid Mantis', 'When Raining', '35 mm', 'on flowers (more common on white flowers)', 'August through November, 8am to 5pm (best time is 8am to 4pm, September through November)');
insert into acww_insect values(17, 0, 'Brown Cicada', 'Never', '58 mm', 'on trees', 'July through August, 8am to 5pm (best time is 8am to 4pm)');
insert into acww_insect values(18, 0, 'Robust Cicada', 'Never', '60 mm', 'on trees', 'July through August, 8am to 5pm (best time is 8am to 4pm)');
insert into acww_insect values(19, 0, 'Walker Cicada', 'Never', '44 mm', 'on trees', 'July through September, 8am to 5pm (best time is August)');
insert into acww_insect values(20, 0, 'Evening Cicada', 'Never', '45 mm', 'on trees', 'July through August, 4am to 8am and 4pm to 7pm');
insert into acww_insect values(21, 0, 'Lantern Fly', 'Never', '70 mm', 'on trees', 'June through September, 4pm to 7pm and 11pm to 8am');
insert into acww_insect values(22, 0, 'Red Dragonfly', 'When Raining', '38 mm', 'in air', 'September through October, 8am to 7pm (best time is 4pm to 5pm)');
insert into acww_insect values(23, 0, 'Darner Dragonfly', 'When Raining', '76 mm', 'in air', 'June through August, 8am to 5pm (best time is 4pm to 5pm)');
insert into acww_insect values(24, 0, 'Banded Dragonfly', 'When Raining', '90 mm', 'in air', 'July through August, 8am to 5pm');
insert into acww_insect values(25, 0, 'Ant', 'When Gate is Open', '5 mm', 'on rotten turnips', 'all year, all day');
insert into acww_insect values(26, 0, 'Pondskater', 'When Gate is Open', '14 mm', 'on large and holding ponds', 'June through September, 8am to 7pm');
insert into acww_insect values(27, 0, 'Snail', 'Never', '45 mm', 'on flowers, usually during rain', 'April through September,all day (best times are 4pm to 8am, May; 4am to 7pm, June; and 7pm to 11pm, July through August)');
insert into acww_insect values(28, 0, 'Cricket', 'Never', '28 mm', 'on ground', 'September through November, 5pm to 8am');
insert into acww_insect values(29, 0, 'Bell Cricket', 'Never', '18 mm', 'on ground', 'September through October, 5pm to 8am');
insert into acww_insect values(30, 0, 'Grasshopper', 'When Raining', '43 mm', 'on ground', 'July, 4pm to 5pm');
insert into acww_insect values(31, 0, 'Mole Cricket', 'Never', '35 mm', 'underground', 'November through May, all day (best time is December through February)');
insert into acww_insect values(32, 0, 'Walkingstick', 'Never', '85 mm', 'on trees', 'July through November, 4am to 7pm');
insert into acww_insect values(33, 0, 'Ladybug', 'When Raining', '8 mm', 'on flowers', 'March through June and October, 8am to 5pm (best time is March through May)');
insert into acww_insect values(34, 0, 'Fruit Beetle', 'Never', '23 mm', 'on trees', 'July through August, all day (best time is 7pm to 4am); September, 7pm to 8am');
insert into acww_insect values(35, 0, 'Scarab Beetle', 'Never', '25 mm', 'on trees', 'July through August, 11pm to 8am');
insert into acww_insect values(36, 0, 'Dung Beetle', 'When Gate is Open', '35 mm', 'near snowballs', 'December through February, 5pm to 8am');
insert into acww_insect values(37, 0, 'Goliath Beetle', 'Never', '90 mm', 'on coconut palms', 'June through August, 7pm to 8am');
insert into acww_insect values(38, 0, 'Firefly', 'When Raining', '15 mm', 'near freshwater', 'June, 7pm to 4am');
insert into acww_insect values(39, 0, 'Jewel Beetle', 'Never', '35 mm', 'on trees', 'July through August, 8am to 5pm');
insert into acww_insect values(40, 0, 'Longhorn Beetle', 'Never', '30 mm', 'on trees', 'June, 8am to 7pm; July through August, 8am to 5pm');
insert into acww_insect values(41, 0, 'Saw Stag Beetle', 'Never', '65 mm', 'on trees', 'July through August, all day (best time is 11pm to 8am)');
insert into acww_insect values(42, 0, 'Stag Beetle', 'Never', '66 mm', 'on trees', 'June through August, 7pm to 8am (best time is 11pm to 8am, July through August)');
insert into acww_insect values(43, 0, 'Giant Beetle', 'Never', '68 mm', 'on trees', 'July through August, 11pm to 8am');
insert into acww_insect values(44, 0, 'Rainbow Stag', 'Never', '68 mm', 'on trees', 'June through September, 7pm to 8am');
insert into acww_insect values(45, 0, 'Dynastid Beetle', 'Never', '80 mm', 'on trees', 'July through August, 7pm to 8am (best time is 11pm to 8am)');
insert into acww_insect values(46, 0, 'Atlas Beetle', 'Never', '120 mm', 'on coconut palms', 'July through August, 7pm to 8am');
insert into acww_insect values(47, 0, 'Elephant Beetle', 'Never', '115 mm', 'on coconut palms', 'July through August, 7pm to 8am');
insert into acww_insect values(48, 0, 'Hercules Beetle', 'Never', '160 mm', 'on coconut palms', 'July through August, 11pm to 8am');
insert into acww_insect values(49, 0, 'Flea', 'When Gate is Open', '2 mm', 'on villager', 'March through November, all day');
insert into acww_insect values(50, 0, 'Pillbug', 'Never', '10 mm', 'under rocks', 'all year, all day (best time is November through March)');
insert into acww_insect values(51, 0, 'Mosquito', 'When Gate is Open or Raining', '6 mm', 'in air', 'June through September, 5pm to 4am (best time is 5pm to 7pm)');
insert into acww_insect values(52, 0, 'Fly', 'When Gate is Open', '9 mm', 'near garbage, Rafflesia or rotten turnips', 'all year, all day');
insert into acww_insect values(53, 0, 'Cockroach', 'Never', '28 mm', 'on trees or rotten turnips', 'all year, all day');
insert into acww_insect values(54, 0, 'Spider', 'When Gate is Open or Raining', '28 mm', 'in trees', 'March through November, all day (best times are 4pm to 8am, April through May; 4am to 8am and 5pm to 7pm, June; 7pm to 8am, July; 5pm to 8am, August; 4am to 8am and 7pm to 11pm, September; and 5pm to 8am, October)');
insert into acww_insect values(55, 0, 'Tarantula', 'When Gate is Open or Raining', '65 mm', 'on ground', 'June through August, 7pm to 4am');
insert into acww_insect values(56, 0, 'Scorpion', 'When Gate is Open or Raining', '160 mm', 'on ground', 'July through September, 7pm to 4am');
