drop table if exists acww_shirt;
create table acww_shirt ("Index" int primary key, Selected int, Name varchar(50));
insert into acww_shirt values(1, 0, 'Work Uniform');
insert into acww_shirt values(2, 0, 'One-Ball Shirt');
insert into acww_shirt values(3, 0, 'Two-Ball Shirt');
insert into acww_shirt values(4, 0, 'Three-Ball Shirt');
insert into acww_shirt values(5, 0, 'Four-Ball Shirt');
insert into acww_shirt values(6, 0, 'Five-Ball Shirt');
insert into acww_shirt values(7, 0, 'Six-Ball Shirt');
insert into acww_shirt values(8, 0, 'Seven-Ball Shirt');
insert into acww_shirt values(9, 0, 'Eight-Ball Shirt');
insert into acww_shirt values(10, 0, 'Nine-Ball Shirt');
insert into acww_shirt values(11, 0, 'Paw Shirt');
insert into acww_shirt values(12, 0, 'Daisy Shirt');
insert into acww_shirt values(13, 0, 'Tulip Shirt');
insert into acww_shirt values(14, 0, 'Cherry Shirt');
insert into acww_shirt values(15, 0, 'Skull Shirt');
insert into acww_shirt values(16, 0, 'U R Here Shirt');
insert into acww_shirt values(17, 0, 'Lightning Shirt');
insert into acww_shirt values(18, 0, 'MVP Shirt');
insert into acww_shirt values(19, 0, 'BB Shirt');
insert into acww_shirt values(20, 0, 'Frog Shirt');
insert into acww_shirt values(21, 0, 'Bear Shirt');
insert into acww_shirt values(22, 0, 'Bunny Shirt');
insert into acww_shirt values(23, 0, 'Elephant Shirt');
insert into acww_shirt values(24, 0, 'Spade Shirt');
insert into acww_shirt values(25, 0, 'Diamond Shirt');
insert into acww_shirt values(26, 0, 'Club Shirt');
insert into acww_shirt values(27, 0, 'Heart Shirt');
insert into acww_shirt values(28, 0, 'Big Star Shirt');
insert into acww_shirt values(29, 0, 'Bright Shirt');
insert into acww_shirt values(30, 0, 'A Shirt');
insert into acww_shirt values(31, 0, 'No. 1 Shirt');
insert into acww_shirt values(32, 0, 'No. 2 Shirt');
insert into acww_shirt values(33, 0, 'No. 3 Shirt');
insert into acww_shirt values(34, 0, 'No. 4 Shirt');
insert into acww_shirt values(35, 0, 'No. 5 Shirt');
insert into acww_shirt values(36, 0, 'No. 23 Shirt');
insert into acww_shirt values(37, 0, 'No. 67 Shirt');
insert into acww_shirt values(38, 0, 'Big Bro''s Shirt');
insert into acww_shirt values(39, 0, 'Li''l Bro''s Shirt');
insert into acww_shirt values(40, 0, 'Cloudy Shirt');
insert into acww_shirt values(41, 0, 'Fresh Shirt');
insert into acww_shirt values(42, 0, 'Dawn Shirt');
insert into acww_shirt values(43, 0, 'Misty Shirt');
insert into acww_shirt values(44, 0, 'Sunset Top');
insert into acww_shirt values(45, 0, 'Deep Blue Tee');
insert into acww_shirt values(46, 0, 'Peachy Shirt');
insert into acww_shirt values(47, 0, 'Rainbow Shirt');
insert into acww_shirt values(48, 0, 'Snowcone Shirt');
insert into acww_shirt values(49, 0, 'Orange Tie-Dye');
insert into acww_shirt values(50, 0, 'Purple Tie-Dye');
insert into acww_shirt values(51, 0, 'Green Tie-Dye');
insert into acww_shirt values(52, 0, 'Blue Tie-Dye');
insert into acww_shirt values(53, 0, 'Red Tie-Dye');
insert into acww_shirt values(54, 0, 'Bold Check Shirt');
insert into acww_shirt values(55, 0, 'Cafe Shirt');
insert into acww_shirt values(56, 0, 'Checkered Shirt');
insert into acww_shirt values(57, 0, 'Blue Check Shirt');
insert into acww_shirt values(58, 0, 'Red Check Shirt');
insert into acww_shirt values(59, 0, 'Rugby Shirt');
insert into acww_shirt values(60, 0, 'Green Bar Shirt');
insert into acww_shirt values(61, 0, 'Yellow Bar Shirt');
insert into acww_shirt values(62, 0, 'Grape Stripe Tee');
insert into acww_shirt values(63, 0, 'Beatnik Shirt');
insert into acww_shirt values(64, 0, 'Red Bar Shirt');
insert into acww_shirt values(65, 0, 'Blue Stripe Knit');
insert into acww_shirt values(66, 0, 'Gelato Shirt');
insert into acww_shirt values(67, 0, 'Chain-gang Shirt');
insert into acww_shirt values(68, 0, 'Yellow Tartan');
insert into acww_shirt values(69, 0, 'Fall Plaid Shirt');
insert into acww_shirt values(70, 0, 'Blue Tartan');
insert into acww_shirt values(71, 0, 'Dapper Shirt');
insert into acww_shirt values(72, 0, 'Natty Shirt');
insert into acww_shirt values(73, 0, 'Blue Grid Shirt');
insert into acww_shirt values(74, 0, 'Red Grid Shirt');
insert into acww_shirt values(75, 0, 'Dazed Shirt');
insert into acww_shirt values(76, 0, 'Checkerboard Tee');
insert into acww_shirt values(77, 0, 'Toad Shirt');
insert into acww_shirt values(78, 0, 'Dark Polka Shirt');
insert into acww_shirt values(79, 0, 'Lite Polka Shirt');
insert into acww_shirt values(80, 0, 'Bubble Gum Shirt');
insert into acww_shirt values(81, 0, 'Funky Dot Shirt');
insert into acww_shirt values(82, 0, 'Gumdrop Shirt');
insert into acww_shirt values(83, 0, 'Big Dot Shirt');
insert into acww_shirt values(84, 0, 'Aqua Polka Shirt');
insert into acww_shirt values(85, 0, 'Blue Pinstripe');
insert into acww_shirt values(86, 0, 'Yellow Pinstripe');
insert into acww_shirt values(87, 0, 'Orange Pinstripe');
insert into acww_shirt values(88, 0, 'Vegetarian Shirt');
insert into acww_shirt values(89, 0, 'Racer Shirt');
insert into acww_shirt values(90, 0, 'Vertigo Shirt');
insert into acww_shirt values(91, 0, 'Barber Shirt');
insert into acww_shirt values(92, 0, 'Jade Check Print');
insert into acww_shirt values(93, 0, 'Blue Check Print');
insert into acww_shirt values(94, 0, 'Mint Gingham Top');
insert into acww_shirt values(95, 0, 'Picnic Shirt');
insert into acww_shirt values(96, 0, 'Candy Gingham');
insert into acww_shirt values(97, 0, 'Lemon Gingham');
insert into acww_shirt values(98, 0, 'Melon Gingham');
insert into acww_shirt values(99, 0, 'Bad Plaid Shirt');
insert into acww_shirt values(100, 0, 'Pink Tartan');
insert into acww_shirt values(101, 0, 'Waffle Shirt');
insert into acww_shirt values(102, 0, 'Gray Tartan');
insert into acww_shirt values(103, 0, 'Chevron Shirt');
insert into acww_shirt values(104, 0, 'Icy Shirt');
insert into acww_shirt values(105, 0, 'Aurora Knit');
insert into acww_shirt values(106, 0, 'Winter Sweater');
insert into acww_shirt values(107, 0, 'Folk Shirt');
insert into acww_shirt values(108, 0, 'Argyle Knit');
insert into acww_shirt values(109, 0, 'Uncommon Shirt');
insert into acww_shirt values(110, 0, 'Comfy Sweater');
insert into acww_shirt values(111, 0, 'Beige Knit');
insert into acww_shirt values(112, 0, 'Earthy Knit');
insert into acww_shirt values(113, 0, 'Spring Shirt');
insert into acww_shirt values(114, 0, 'Vogue Top');
insert into acww_shirt values(115, 0, 'Citrus Gingham');
insert into acww_shirt values(116, 0, 'Floral Knit');
insert into acww_shirt values(117, 0, 'Dreamy Shirt');
insert into acww_shirt values(118, 0, 'Flowery Shirt');
insert into acww_shirt values(119, 0, 'Silk Bloom Shirt');
insert into acww_shirt values(120, 0, 'Pop Bloom Shirt');
insert into acww_shirt values(121, 0, 'Blossom Shirt');
insert into acww_shirt values(122, 0, 'Loud Bloom Shirt');
insert into acww_shirt values(123, 0, 'Rose Shirt');
insert into acww_shirt values(124, 0, 'Rose Sky Shirt');
insert into acww_shirt values(125, 0, 'Lotus Shirt');
insert into acww_shirt values(126, 0, 'Chocomint Shirt');
insert into acww_shirt values(127, 0, 'Fern Shirt');
insert into acww_shirt values(128, 0, 'Blue Retro Shirt');
insert into acww_shirt values(129, 0, 'Orange Check Tee');
insert into acww_shirt values(130, 0, 'Leaf Shirt');
insert into acww_shirt values(131, 0, 'Fall Leaf Shirt');
insert into acww_shirt values(132, 0, 'Grass Shirt');
insert into acww_shirt values(133, 0, 'Snow Shirt');
insert into acww_shirt values(134, 0, 'Lovely Shirt');
insert into acww_shirt values(135, 0, 'Bubble Shirt');
insert into acww_shirt values(136, 0, 'Chichi Print');
insert into acww_shirt values(137, 0, 'Coral Shirt');
insert into acww_shirt values(138, 0, 'Groovy Shirt');
insert into acww_shirt values(139, 0, 'Cool Shirt');
insert into acww_shirt values(140, 0, 'Swell Shirt');
insert into acww_shirt values(141, 0, 'Blue Diamond Top');
insert into acww_shirt values(142, 0, 'Prism Shirt');
insert into acww_shirt values(143, 0, 'Go-Go Shirt');
insert into acww_shirt values(144, 0, 'Flame Shirt');
insert into acww_shirt values(145, 0, 'Danger Shirt');
insert into acww_shirt values(146, 0, 'Gracie''s Top');
insert into acww_shirt values(147, 0, 'Future Shirt');
insert into acww_shirt values(148, 0, 'Optical Shirt');
insert into acww_shirt values(149, 0, 'Twinkle Shirt');
insert into acww_shirt values(150, 0, 'Star Shirt');
insert into acww_shirt values(151, 0, 'Night Sky Tee');
insert into acww_shirt values(152, 0, 'Amethyst Shirt');
insert into acww_shirt values(153, 0, 'Nebula Shirt');
insert into acww_shirt values(154, 0, 'Dice Shirt');
insert into acww_shirt values(155, 0, 'Kiddie Shirt');
insert into acww_shirt values(156, 0, 'Airy Shirt');
insert into acww_shirt values(157, 0, 'Polar Fleece');
insert into acww_shirt values(158, 0, 'Crossing Shirt');
insert into acww_shirt values(159, 0, 'Splendid Shirt');
insert into acww_shirt values(160, 0, 'Jagged Shirt');
insert into acww_shirt values(161, 0, 'Subdued Print');
insert into acww_shirt values(162, 0, 'Sharp Outfit');
insert into acww_shirt values(163, 0, 'Jungle Camo');
insert into acww_shirt values(164, 0, 'Arctic Camo');
insert into acww_shirt values(165, 0, 'Desert Camo');
insert into acww_shirt values(166, 0, 'Zebra Shirt');
insert into acww_shirt values(167, 0, 'Tiger Shirt');
insert into acww_shirt values(168, 0, 'Cow Shirt');
insert into acww_shirt values(169, 0, 'Leopard Shirt');
insert into acww_shirt values(170, 0, 'Giraffe Shirt');
insert into acww_shirt values(171, 0, 'Ladybug Shirt');
insert into acww_shirt values(172, 0, 'Butterfly Shirt');
insert into acww_shirt values(173, 0, 'Spiderweb Shirt');
insert into acww_shirt values(174, 0, 'Caterpillar Tee');
insert into acww_shirt values(175, 0, 'Fiendish Shirt');
insert into acww_shirt values(176, 0, 'Citrus Shirt');
insert into acww_shirt values(177, 0, 'Kiwi Shirt');
insert into acww_shirt values(178, 0, 'Watermelon Shirt');
insert into acww_shirt values(179, 0, 'Strawberry Shirt');
insert into acww_shirt values(180, 0, 'Grape Shirt');
insert into acww_shirt values(181, 0, 'Melon Shirt');
insert into acww_shirt values(182, 0, 'Pink Wave Shirt');
insert into acww_shirt values(183, 0, 'Flan Shirt');
insert into acww_shirt values(184, 0, 'Hot Dog Shirt');
insert into acww_shirt values(185, 0, 'Sandwich Shirt');
insert into acww_shirt values(186, 0, 'Dragon Suit');
insert into acww_shirt values(187, 0, 'Asian Shirt');
insert into acww_shirt values(188, 0, 'Hot Spring Shirt');
insert into acww_shirt values(189, 0, 'New Spring Shirt');
insert into acww_shirt values(190, 0, 'Crewel Shirt');
insert into acww_shirt values(191, 0, 'Tropical Shirt');
insert into acww_shirt values(192, 0, 'Ribbon Shirt');
insert into acww_shirt values(193, 0, 'Bodice');
insert into acww_shirt values(194, 0, 'Laced Shirt');
insert into acww_shirt values(195, 0, 'Circus Shirt');
insert into acww_shirt values(196, 0, 'Green Vest');
insert into acww_shirt values(197, 0, 'Yellow Bolero');
insert into acww_shirt values(198, 0, 'Noble Shirt');
insert into acww_shirt values(199, 0, 'Turnip Top');
insert into acww_shirt values(200, 0, 'Yodel Shirt');
insert into acww_shirt values(201, 0, 'Gaudy Sweater');
insert into acww_shirt values(202, 0, 'Western Shirt');
insert into acww_shirt values(203, 0, 'Red Riding Hoody');
insert into acww_shirt values(204, 0, 'Royal Shirt');
insert into acww_shirt values(205, 0, 'Witch Shirt');
insert into acww_shirt values(206, 0, 'Firefighter Tee');
insert into acww_shirt values(207, 0, 'Graduation Gown');
insert into acww_shirt values(208, 0, 'Sky Shirt');
insert into acww_shirt values(209, 0, 'Captain''s Shirt');
insert into acww_shirt values(210, 0, 'Burglar''s Shirt');
insert into acww_shirt values(211, 0, 'Jester Shirt');
insert into acww_shirt values(212, 0, 'Nurse''s Uniform');
insert into acww_shirt values(213, 0, 'Bone Shirt');
insert into acww_shirt values(214, 0, 'Zipper Shirt');
insert into acww_shirt values(215, 0, 'Mummy Shirt');
insert into acww_shirt values(216, 0, 'Military Uniform');
insert into acww_shirt values(217, 0, 'Sailor''s Uniform');
insert into acww_shirt values(218, 0, 'Reggae Shirt');
insert into acww_shirt values(219, 0, 'Camel Shirt');
insert into acww_shirt values(220, 0, 'Molecule Tee');
insert into acww_shirt values(221, 0, 'Concierge Shirt');
insert into acww_shirt values(222, 0, 'Kimono');
insert into acww_shirt values(223, 0, 'Tuxedo');
insert into acww_shirt values(224, 0, 'Explorer Shirt');
insert into acww_shirt values(225, 0, 'Dutch Shirt');
insert into acww_shirt values(226, 0, 'Toga');
insert into acww_shirt values(227, 0, 'Cake Shirt');
insert into acww_shirt values(228, 0, 'Waitress Shirt');
insert into acww_shirt values(229, 0, 'Princess Shirt');
insert into acww_shirt values(230, 0, 'Fairy Tale Shirt');
insert into acww_shirt values(231, 0, 'Spanish Shirt');
insert into acww_shirt values(232, 0, 'Latin Uniform');
insert into acww_shirt values(233, 0, 'Red Down Vest');
insert into acww_shirt values(234, 0, 'One-Way Tee');
insert into acww_shirt values(235, 0, 'Beaded Shirt');
insert into acww_shirt values(236, 0, 'Nile Shirt');
insert into acww_shirt values(237, 0, 'Wrap Shirt');
insert into acww_shirt values(238, 0, 'Wrestler Shirt');
insert into acww_shirt values(239, 0, 'Security Shirt');
insert into acww_shirt values(240, 0, 'Poncho');
insert into acww_shirt values(241, 0, 'Fluffy Shirt');
insert into acww_shirt values(242, 0, 'Chinese Shirt');
insert into acww_shirt values(243, 0, 'Pep Squad Shirt');
insert into acww_shirt values(244, 0, 'Racing Shirt');
insert into acww_shirt values(245, 0, 'Orange Jumpsuit');
insert into acww_shirt values(246, 0, 'Tin Shirt');
insert into acww_shirt values(247, 0, 'Scale Armor Suit');
insert into acww_shirt values(248, 0, 'Armor Suit');
insert into acww_shirt values(249, 0, 'Gold Armor Suit');
insert into acww_shirt values(250, 0, 'Red Warmup Suit');
insert into acww_shirt values(251, 0, 'Baseball Shirt');
insert into acww_shirt values(252, 0, 'Leather Jerkin');
insert into acww_shirt values(253, 0, 'Frock Coat');
insert into acww_shirt values(254, 0, 'Space Suit');
insert into acww_shirt values(255, 0, 'Caveman Tunic');
insert into acww_shirt values(256, 0, 'Moldy Shirt');