drop table if exists acww_tool;
create table acww_tool ("Index" int, Selected int, Name varchar(63), Status varchar(31), "From" varchar(31), Price varchar(31));
insert into acww_tool values(1, 0, 'Gelato Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(2, 0, 'Bat Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(3, 0, 'Lacy Parasol', 'normal', 'shop', '160');
insert into acww_tool values(4, 0, 'Leaf Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(5, 0, 'Paper Parasol', 'normal', 'shop', '160');
insert into acww_tool values(6, 0, 'Ribbon Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(7, 0, 'Red Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(8, 0, 'Blue Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(9, 0, 'Yellow Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(10, 0, 'Green Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(11, 0, 'Candy Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(12, 0, 'Melon Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(13, 0, 'Mint Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(14, 0, 'Picnic Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(15, 0, 'Lemon Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(16, 0, 'Toad Parasol', 'normal', 'shop', '160');
insert into acww_tool values(17, 0, 'Eggy Parasol', 'normal', 'shop', '160');
insert into acww_tool values(18, 0, 'Blue Dot Parasol', 'normal', 'shop', '160');
insert into acww_tool values(19, 0, 'Daisy Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(20, 0, 'Paw Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(21, 0, 'Petal Parasol', 'normal', 'shop', '160');
insert into acww_tool values(22, 0, 'Busted Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(23, 0, 'Sunny Parasol', 'normal', 'shop', '160');
insert into acww_tool values(24, 0, 'Beach Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(25, 0, 'Elegant Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(26, 0, 'Modern Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(27, 0, 'Leopard Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(28, 0, 'Zebra Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(29, 0, 'Forest Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(30, 0, 'Flame Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(31, 0, 'Camo Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(32, 0, 'Spider Umbrella', 'normal', 'shop', '160');
insert into acww_tool values(33, 0, 'Shovel', 'unorderable', 'Nook''s', '500');
insert into acww_tool values(34, 0, 'Golden Shovel', 'unorderable', 'Buried', '125');
insert into acww_tool values(35, 0, 'Slingshot', 'unorderable', 'Nook''s', '500');
insert into acww_tool values(36, 0, 'Golden Slingshot', 'unorderable', 'Balloon', '125');
insert into acww_tool values(37, 0, 'Fishing Rod', 'unorderable', 'Tortimer/Nook''s', '125');
insert into acww_tool values(38, 0, 'Golden Rod', 'unorderable', 'Tortimer', '125');
insert into acww_tool values(39, 0, 'Net', 'unorderable', 'Tortimer/Nook''s', '125');
insert into acww_tool values(40, 0, 'Golden Net', 'unorderable', 'Tortimer', '125');
insert into acww_tool values(41, 0, 'Watering Can', 'unorderable', 'Nook''s', '500');
insert into acww_tool values(42, 0, 'Golden Can', 'unorderable', 'Pelly/Phyllis', '125');
insert into acww_tool values(43, 0, 'Axe (brand new)', 'unorderable', 'Nook''s', '400');
insert into acww_tool values(44, 0, 'Golden Axe', 'unorderable', 'Pascal', '125');
insert into acww_tool values(45, 0, 'Timer', 'unorderable', 'Nook''s', '500');
insert into acww_tool values(46, 0, 'Party Popper', 'unorderable', 'Tortimer', '30');
insert into acww_tool values(47, 0, 'Sparkler', 'unorderable', 'Tortimer', '30');
insert into acww_tool values(48, 0, 'Roman Candle', 'unorderable', 'Tortimer', '30');
