drop table if exists acww_tool;
create table acww_tool ("Index" int primary key, Selected int, Name varchar(255))
insert into acww_tool values(1, 0, 'Gelato Umbrella');
insert into acww_tool values(2, 0, 'Bat Umbrella');
insert into acww_tool values(3, 0, 'Lacy Parasol');
insert into acww_tool values(4, 0, 'Leaf Umbrella');
insert into acww_tool values(5, 0, 'Paper Parasol');
insert into acww_tool values(6, 0, 'Ribbon Umbrella');
insert into acww_tool values(7, 0, 'Red Umbrella');
insert into acww_tool values(8, 0, 'Blue Umbrella');
insert into acww_tool values(9, 0, 'Yellow Umbrella');
insert into acww_tool values(10, 0, 'Green Umbrella');
insert into acww_tool values(11, 0, 'Candy Umbrella');
insert into acww_tool values(12, 0, 'Melon Umbrella');
insert into acww_tool values(13, 0, 'Mint Umbrella');
insert into acww_tool values(14, 0, 'Picnic Umbrella');
insert into acww_tool values(15, 0, 'Lemon Umbrella');
insert into acww_tool values(16, 0, 'Toad Parasol');
insert into acww_tool values(17, 0, 'Eggy Parasol');
insert into acww_tool values(18, 0, 'Blue Dot Parasol');
insert into acww_tool values(19, 0, 'Daisy Umbrella');
insert into acww_tool values(20, 0, 'Paw Umbrella');
insert into acww_tool values(21, 0, 'Petal Parasol');
insert into acww_tool values(22, 0, 'Busted Umbrella');
insert into acww_tool values(23, 0, 'Sunny Parasol');
insert into acww_tool values(24, 0, 'Beach Umbrella');
insert into acww_tool values(25, 0, 'Elegant Umbrella');
insert into acww_tool values(26, 0, 'Modern Umbrella');
insert into acww_tool values(27, 0, 'Leopard Umbrella');
insert into acww_tool values(28, 0, 'Zebra Umbrella');
insert into acww_tool values(29, 0, 'Forest Umbrella');
insert into acww_tool values(30, 0, 'Flame Umbrella');
insert into acww_tool values(31, 0, 'Camo Umbrella');
insert into acww_tool values(32, 0, 'Spider Umbrella');
