drop table if exists acww_wallpaper;
create table acww_wallpaper ("Index" int, Selected int, Name varchar(63), Status varchar(31), "From" varchar(31), Price varchar(31), Series varchar(31));
insert into acww_wallpaper values(1, 0, 'Exotic Wall', 'normal', 'Grp B', '1,420', 'Exotic Series');
insert into acww_wallpaper values(2, 0, 'Lovely Wall', 'normal', 'Grp A', '1,880', 'Lovely Series');
insert into acww_wallpaper values(3, 0, 'Classic Wall', 'normal', 'Grp B', '2,100', 'Classic Series');
insert into acww_wallpaper values(4, 0, 'Ranch Wall', 'normal', 'Grp A', '1,450', 'Ranch Series');
insert into acww_wallpaper values(5, 0, 'Cabana Wall', 'normal', 'Grp C', '1,480', 'Cabana Series');
insert into acww_wallpaper values(6, 0, 'Blue Wall', 'normal', 'Grp B', '1,260', 'Blue Series');
insert into acww_wallpaper values(7, 0, 'Modern Wall', 'normal', 'Grp B', '1,450', 'Modern Series');
insert into acww_wallpaper values(8, 0, 'Regal Wall', 'normal', 'Grp C', '2,240', 'Regal Series');
insert into acww_wallpaper values(9, 0, 'Green Wall', 'normal', 'Grp A', '1,050', 'Green Series');
insert into acww_wallpaper values(10, 0, 'Cabin Wall', 'normal', 'Grp A', '1,200', 'Cabin Series');
insert into acww_wallpaper values(11, 0, 'Kiddie Wall', 'normal', 'Grp B', '1,500', 'Kiddie Series');
insert into acww_wallpaper values(12, 0, 'Robo-Wall', 'normal', 'Grp B', '1,780', 'Robo Series');
insert into acww_wallpaper values(13, 0, 'Snowman Wall', 'unorderable', 'Snowman', '8,888', 'Snowman Series');
insert into acww_wallpaper values(14, 0, 'Forest Wall', 'unorderable', 'Cornimer', '420', 'Mushroom Series');
insert into acww_wallpaper values(15, 0, 'Western Vista', 'unorderable', 'Saharah', '1,500', 'Western Theme');
insert into acww_wallpaper values(16, 0, 'Lunar Horizon', 'unorderable', 'Saharah', '1,900', 'Space Theme');
insert into acww_wallpaper values(17, 0, 'Blue Tarp', 'unorderable', 'Saharah', '1,400', 'Construction Theme');
insert into acww_wallpaper values(18, 0, 'Ringside Seating', 'unorderable', 'Saharah', '2,250', 'Boxing Theme');
insert into acww_wallpaper values(19, 0, 'Backyard Fence', 'normal', 'Grp B', '800', 'Backyard Theme');
insert into acww_wallpaper values(20, 0, 'Playroom Wall', 'normal', 'Grp C', '1,320', 'Nursery Theme');
insert into acww_wallpaper values(21, 0, 'Sea View', 'unorderable', 'Pascal', '1,000', 'Pirate Theme');
insert into acww_wallpaper values(22, 0, 'Lab Wall', 'normal', 'Grp C', '1,460', 'Mad Scientist Theme');
insert into acww_wallpaper values(23, 0, 'Pastel Dot Wall', 'normal', 'Grp C', '1,480', 'none');
insert into acww_wallpaper values(24, 0, 'Parlor Wall', 'normal', 'Grp C', '1,120', 'none');
insert into acww_wallpaper values(25, 0, 'Mod Wall', 'normal', 'Grp A', '1,200', 'none');
insert into acww_wallpaper values(26, 0, 'Groovy Wall', 'normal', 'Grp B', '1,280', 'none');
insert into acww_wallpaper values(27, 0, 'Mosaic Wall', 'normal', 'Grp B', '2,100', 'none');
insert into acww_wallpaper values(28, 0, 'Blue-Trim Wall', 'normal', 'Grp B', '1,420', 'none');
insert into acww_wallpaper values(29, 0, 'Plaster Wall', 'normal', 'Grp C', '880', 'none');
insert into acww_wallpaper values(30, 0, 'Chic Wall', 'normal', 'Grp A', '1,960', 'none');
insert into acww_wallpaper values(31, 0, 'Ornate Wall', 'normal', 'Grp C', '1,580', 'none');
insert into acww_wallpaper values(32, 0, 'Citrus Wall', 'normal', 'Grp C', '1,120', 'none');
insert into acww_wallpaper values(33, 0, 'Rose Wall', 'normal', 'Grp B', '2,240', 'none');
insert into acww_wallpaper values(34, 0, 'Old Brick Wall', 'normal', 'Grp B', '1,200', 'none');
insert into acww_wallpaper values(35, 0, 'Shoji Screen', 'unorderable', 'Saharah', '1,875', 'none');
insert into acww_wallpaper values(36, 0, 'Stone Wall', 'normal', 'Grp A', '800', 'none');
insert into acww_wallpaper values(37, 0, 'Concrete Wall', 'normal', 'Grp A', '800', 'none');
insert into acww_wallpaper values(38, 0, 'Shanty Wall', 'normal', 'Grp C', '800', 'none');
insert into acww_wallpaper values(39, 0, 'Wood Paneling', 'normal', 'Grp C', '1,320', 'none');
insert into acww_wallpaper values(40, 0, 'Floral Wall', 'normal', 'Grp A', '2,250', 'none');
insert into acww_wallpaper values(41, 0, 'Music Room Wall', 'unorderable', 'Saharah', '1,600', 'none');
insert into acww_wallpaper values(42, 0, 'Manor Wall', 'normal', 'Grp B', '1,050', 'none');
insert into acww_wallpaper values(43, 0, 'Plaza Wall', 'normal', 'Grp A', '1,960', 'none');
insert into acww_wallpaper values(44, 0, 'Lattice Wall', 'normal', 'Grp B', '1,780', 'none');
insert into acww_wallpaper values(45, 0, 'Stately Wall', 'normal', 'Grp C', '2,450', 'none');
insert into acww_wallpaper values(46, 0, 'Imperial Wall', 'normal', 'Grp A', '2,660', 'none');
insert into acww_wallpaper values(47, 0, 'Arched Window', 'normal', 'Grp C', '2,150', 'none');
insert into acww_wallpaper values(48, 0, 'Bamboo Wall', 'normal', 'Grp A', '1,150', 'none');
insert into acww_wallpaper values(49, 0, 'Ivy Wall', 'normal', 'Grp C', '1,250', 'none');
insert into acww_wallpaper values(50, 0, 'Ancient Wall', 'unorderable', 'Saharah', '2,300', 'none');
insert into acww_wallpaper values(51, 0, 'Exquisite Wall', 'normal', 'Grp C', '1,470', 'none');
insert into acww_wallpaper values(52, 0, 'Persian Wall', 'normal', 'Grp B', '1,480', 'none');
insert into acww_wallpaper values(53, 0, 'Industrial Wall', 'unorderable', 'Saharah', '1,875', 'none');
insert into acww_wallpaper values(54, 0, 'Library Wall', 'normal', 'Grp C', '1,680', 'none');
insert into acww_wallpaper values(55, 0, 'Fairy Tale Wall', 'normal', 'Grp C', '2,400', 'none');
insert into acww_wallpaper values(56, 0, 'Illusion Wall', 'normal', 'Grp A', '1,360', 'none');
insert into acww_wallpaper values(57, 0, 'Meadow Vista', 'unorderable', 'Saharah', '2,000', 'none');
insert into acww_wallpaper values(58, 0, 'Tropical Vista', 'unorderable', 'Saharah', '2,300', 'none');
insert into acww_wallpaper values(59, 0, 'Desert Vista', 'unorderable', 'Saharah', '2,250', 'none');
insert into acww_wallpaper values(60, 0, 'Chainlink Fence', 'normal', 'Grp A', '2,400', 'none');
insert into acww_wallpaper values(61, 0, 'Sky Wall', 'normal', 'Grp B', '1,200', 'none');
insert into acww_wallpaper values(62, 0, 'Cityscape Wall', 'normal', 'Grp A', '1,600', 'none');
insert into acww_wallpaper values(63, 0, 'Common Wall', 'normal', 'Grp A', '1,240', 'none');
insert into acww_wallpaper values(64, 0, 'Mushroom Mural', 'unorderable', 'Download', '256', 'Mario Theme');
